import {normalizeQuery} from './router-normalization';
export {normalizeQuery} from './router-normalization';
import type { EntityRoute, EntityParameters, EntityTemplate } from './router-entities';
import { ADDITIONAL_INTENTS } from './router-intents';
/** Shared allowlist. IDs refer to existing palette commands, never provider URLs/tools. */
export type ActionCategory = 'navigate' | 'display' | 'open_existing_flow';
export type SafetyLevel = 'read_only' | 'requires_confirmation' | 'mutation';
export type Intent = { key: string; commandId: string; actionKey: string; category: ActionCategory; safety: SafetyLevel; description: string; permissions: readonly string[]; aliases: readonly string[]; rule?: RegExp; enabled: boolean; entities?: { required: readonly import('./router-entities').EntityType[]; optional: readonly import('./router-entities').EntityType[] } };
const intent = (key: string, commandId: string, description: string, permissions: string[], aliases: string[], rule?: RegExp): Intent => ({ key, commandId, actionKey: `OPEN_${key.toUpperCase()}`, category: ['leave:request','expenses:new','router:submit-grievance'].includes(commandId) ? 'open_existing_flow' : 'navigate', safety: 'read_only', description, permissions, aliases, rule, enabled: true });
// Explicit clock instructions identify the existing manual control, not a presence/history query.
const clockInstructionRule = (direction: 'in' | 'out') => new RegExp(`^(?:(?:(?:help|assist|guide) me(?: (?:to|with))?|i (?:need|want|would like) (?:help|assistance|guidance)(?: (?:to|with))?) clock(?:ing)? ${direction}(?: (?:for|at) work)?|where is (?:the )?clock ${direction} (?:button|control)|clock ${direction} (?:instructions|guidance))$`, 'u');
export const INTENTS: readonly Intent[] = [
  intent('request_leave', 'leave:request', 'Open personal leave request form for user review; never submit.', ['leave.request.self', 'leave.create'], ['request leave', 'apply for leave', 'طلب اجازة', 'عايز اجازة'], /^(?:i (?:want|need|would like) (?:to request |to take )?(?:leave|time off)|(?:عايز|محتاج) (?:اخد )?اجازه)(?:\s.*)?$/u),
  intent('leave_balance', 'roster:leave', 'Open personal leave workspace and balances.', ['leave.view.self', 'leave.create'], ['leave balance', 'pto balance', 'رصيد الاجازات', 'فاضلي كام يوم اجازه']),
  intent('attendance', 'router:attendance', 'Open attendance workspace history controls.', [], ['attendance history', 'my attendance', 'سجل الحضور']),
  intent('clock_in_help', 'attendance:open-clock', 'Open existing clock UI; user must choose and confirm clock action.', ['attendance.clock'], ['clock in', 'clock in help', 'clock in without location', 'start my break', 'end my break', 'request to leave early', 'تسجيل الحضور', 'اسجل حضور ازاي', 'تسجيل الحضور دون موقع', 'بدء استراحتي', 'إنهاء استراحتي', 'طلب انصراف مبكر'], clockInstructionRule('in')),
  intent('payslips', 'router:payslips', 'Open personal payroll statements.', ['payroll.view_self'], ['payslips', 'show payslip', 'قسيمة الراتب', 'مفردات المرتب']),
  intent('my_assets', 'router:my-assets', 'Open personal assigned equipment in profile.', [], ['my assets', 'my equipment', 'معداتى', 'عهدتي', 'العهدة اللي معايا']),
  intent('goals_tasks', 'router:goals', 'Open personal roster goals and tasks.', ['roster.goals.view_self'], ['my goals', 'my tasks', 'مهامي', 'اهدافي']),
  intent('my_grievances', 'navigation:grievances', 'Open personal grievance workspace.', ['grievances.view_own', 'grievances.create'], ['my grievances', 'submit grievance', 'شكاوي', 'تقديم شكوى']),
  {...intent('employee_grievance_lookup','router:grievance-inbox','Read authorized grievance cases for a specified employee. Resolve employee and optional current team location deterministically.',['grievances.view','grievances.review'],['employee grievance lookup','employee complaint case','disciplinary case for an employee','شكوى موظف'], /^(?!.*\b(?:my|own|inbox|history)\b)(?!.*(?:شكاوي|شكاواي|شكوتي)).*(?:\b(?:grievance|grievances|disciplinary case|complaint case)\b.*(?:\b(?:for|employee)\b|بتاع)|\bs (?:disciplinary )?grievance\b|\b(?:show|find|open)\b.+\b(?:grievance|disciplinary case|complaint case)\b|(?:شكوه|شكوي|قضيه).*(?:بتاع|للموظف)|(?:عايز اشوف|وريني|اعرض|افتح).*(?:شكوه|شكوي|قضيه)\s+\S)/u),entities:{required:['employee'] as const,optional:['location'] as const}},
  intent('grievance_inbox', 'router:grievance-inbox', 'Open authorized grievance inbox; case access stays scope-controlled.', ['grievances.view', 'grievances.review'], ['grievance inbox', 'case inbox', 'صندوق الشكاوى']),
  intent('submit_expense', 'expenses:new', 'Open expense form for user review; never submit.', ['expenses.submit.self'], ['submit expense', 'expense claim', 'طلب مصروفات']),
  intent('communications', 'navigation:communications', 'Open communications workspace.', ['communications.view'], ['communications', 'my messages', 'رسائلي']),
  intent('meetings', 'router:meetings', 'Open meetings in existing communications workspace.', ['communications.meetings.view'], ['my meetings', 'meetings', 'اجتماعاتي']),
  intent('company_feed', 'navigation:feed', 'Open company feed.', [], ['company feed', 'company news', 'announcement', 'announcements', 'company announcement', 'company announcements', 'news', 'updates', 'company updates', 'feed', 'اخبار الشركة', 'اعلانات الشركة']),
  intent('workspace_composer', 'navigation:composer', 'Open Workspace Composer.', [], ['workspace composer', 'composer', 'منشئ مساحة العمل']),
  intent('hiring', 'hiring:applicants', 'Open authorized hiring workspace.', ['hiring.view'], ['hiring', 'applicants', 'التوظيف']),
  {...intent('operational_support_onboarding','navigation:support','Read explicit support plus new-hire compositions.',['support.view','hiring.onboarding.view'],[], undefined),entities:{required:[],optional:['employee','asset','location']}},
  {...intent('operational_support','navigation:support','Read allowlisted filtered support queues.',['support.view'],[], undefined),entities:{required:[],optional:['employee','asset','location','job_opening','candidate']}},
  {...intent('operational_hiring','hiring:applicants','Read filtered ATS interviews, feedback, jobs, offers.',['hiring.view'],[], undefined),entities:{required:[],optional:['employee','asset','location','job_opening','candidate']}},
  {...intent('operational_onboarding','hiring:applicants','Read deterministic new-hire checklists and readiness.',['hiring.onboarding.view'],[], undefined),entities:{required:[],optional:['employee','asset','location','job_opening','candidate']}},
  {...intent('operational_composition','hiring:applicants','Read explicit equipment/onboarding or accepted-offer/onboarding compositions.',['hiring.onboarding.view'],[], undefined),entities:{required:[],optional:['employee','asset','location','job_opening','candidate']}},
  {...intent('employee_equipment','navigation:assets','Read an authorized employee’s assigned assets.',['assets.view'],['employee equipment'],/^(?:what (?:laptop|equipment) (?:is .+ using|does .+ have)\??|show (?!(?:my|me|our|us)\b).+ assigned equipment|.+ معاه لابتوب ايه\??)$/u),entities:{required:['employee'],optional:['asset']}},
  {...intent('asset_holder','navigation:assets','Read authorized asset assignment; resolve asset explicitly.',['assets.view'],['asset holder'],/^(?:who has (?:(?:.+ )?(?:asset|equipment|device|laptop|computer|phone)(?: .*)?|[a-z]{2,12} (?:[a-z]{2,12} )?\d{2,12})\??|الجهاز ده مع مين(?: .+)?)$/u),entities:{required:['asset'],optional:[]}},
  {...intent('support_lookup','navigation:support','Read own tickets or authorized support queue and employee/asset/location filters.',[],['show my it tickets','show open it tickets','show unresolved support requests','show tickets assigned to me','طلبات الدعم الخاصة بي'],/^(?:show (?:open |unresolved )?(?:tickets|(?:it |support )tickets|(?:it|support) requests|support issues)(?: .*)?|show .+ support tickets|(?:اعرض|وريني) (?:طلبات|تذاكر) (?:الدعم|دعم).*)$/u),entities:{required:[],optional:['employee','asset','location']}},
  {...intent('support_report','navigation:support','Resolve equipment and prefill the existing support form; never submit.',[],['report equipment damage'],/^(?:report .+ (?:as )?(?:damaged|broken)|open an it ticket for .+|(?:بلغ|ابلغ) .+ (?:تالف|مكسور))$/u),category:'open_existing_flow',safety:'read_only',entities:{required:['asset'],optional:['employee']}},
  {...intent('hiring_jobs_query','hiring:applicants','Read authorized open job summaries.',['hiring.view'],['show open jobs','اعرض الوظائف المفتوحة']),entities:{required:[],optional:['job_opening']}},
  {...intent('hiring_candidates_query','hiring:applicants','Read authorized candidates by job or stage or resolve a named candidate.',['hiring.view'],['show candidates in offer stage','how many candidates are in screening','اعرض المرشحين في مرحلة العرض'],/^(?:show applicants for .+|اعرض المتقدمين لوظيفة .+|open .+ application|show candidates in (?:offer|screening)(?: stage)?|how many candidates are in screening|افتح طلب .+)$/u),entities:{required:[],optional:['job_opening','candidate']}},
  {...intent('hiring_interviews_query','hiring:applicants','Read upcoming hiring interviews.',['hiring.view'],['who is interviewing today','who is interviewing today?','من لديه مقابلة اليوم']),entities:{required:[],optional:[]}},
  ...ADDITIONAL_INTENTS.map(([key,command,description,permissions,aliases])=>intent(key,command,description,[...permissions],aliases.split('|'), key === 'clock_out_help' ? clockInstructionRule('out') : undefined)),
];
// Existing module commands remain the final authority; aliases never grant permissions.
export const ACTIONS = new Map(INTENTS.map(i => [i.actionKey, { commandId: i.commandId, category: i.category, safety: i.safety }]));
export const getIntent = (key: unknown) => typeof key === 'string' ? INTENTS.find(i => i.key === key && i.enabled && i.safety !== 'mutation' && ACTIONS.has(i.actionKey)) : undefined;
/** Unsupported operational verbs must not become equivalent to read/open intents. */
export const unsafeOperation = (text: string) => /(?:\b(?:cancel|delete|close|modify|change salary|change compensation|hire|send (?:(?:an?|the) )?offer|approve|reject|execute|sql|javascript)\b|\bassign .+ (?:laptop|equipment)|\bmove .+ to offer|\bmark .+ (?:complete|completed)|الغاء|الغي|احذف|اغلاق|اقفل|تعديل الراتب|غير المرتب|(?:^| )وظف(?: |$)|(?:^| )عين(?: |$)|ارفض|ارسل عرض)/u.test(text);
export type RouteMethod = 'existing' | 'exact' | 'rule' | 'semantic' | 'llm' | 'none';
export type ProviderFailureReason = 'model_unavailable' | 'authorization_rejected' | 'rate_limited' | 'request_rejected' | 'network_error' | 'incomplete_response' | 'catalog_invalid';
export type ProviderDiagnostics = { upstreamCode?:string; errorType?:string; parameter?:string; detail?:string; requestId?:string; eventType?:string; responseStatus?:string; termination?:string; contentType?:string };
export type RouterDataAnswer = {kind:"shift";timeZone:string;start:string|null;end:string|null}|{kind:"profile";field:string;value:string|null}|{kind:"payday";date:null}|{kind:"presence";total:number;onBreak:number}|{kind:"meetings";timeZone:string;total:number;items:{title:string;start:string;end:string}[]};
export type RouterResult = { outcome: 'matched' | 'ambiguous' | 'no_match' | 'provider_unavailable' | 'unauthorized'; method: RouteMethod; intentKey?: string; actionKey?: string; commandId?: string; choices?: string[]; score?: number; competingScore?: number; margin?: number; fallbackUsed: boolean; semanticStatus?: 'matched'|'ambiguous'|'weak'|'unavailable'; reasoningUnavailable?:boolean; unsupported?:boolean; providerFailure?: { reason: ProviderFailureReason; stage: 'models' | 'responses'; httpStatus?: number; } & ProviderDiagnostics; entityRoute?: EntityRoute; entityParameters?: EntityParameters; entityTemplate?: EntityTemplate; candidateId?: string; latencyMs?: number; answer?:RouterDataAnswer; embeddingLatencyMs?:number; promotedSemanticHit?:boolean; semanticExampleId?:string };
