import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'ar';

const translations = {
  en: {
    'validation.email': 'Enter a valid email address.',
    'validation.passwordRequired': 'Password is required.',
    'validation.passwordChecklist': 'Password must include:',
    'validation.passwordLength': 'At least 8 characters',
    'validation.passwordUppercase': 'One uppercase letter',
    'validation.passwordLowercase': 'One lowercase letter',
    'validation.passwordNumber': 'One number',
    'validation.passwordSpecial': 'One special character',
    'validation.confirmPassword': 'Passwords must match.',
    'validation.required': 'This field is required.',
    'validation.companyLocationRequired': 'Please use your location or enter coordinates for every company location before submitting.',

    'login.title': 'Stanza',
    'login.subtitle': 'Enterprise Authentication',
    'login.corporateId': 'Corporate ID',
    'login.biometricKey': 'Password',
    'login.authenticating': 'Authenticating...',
    'login.accessGranted': 'Access Granted',
    'login.enterSector': 'Log In',
    'login.forgotPassword': 'Forgot Password?',
    'login.registerTenant': 'Register New Company',
    'login.recoveryTitle': 'Recovery',
    'login.recoverySubtitle': 'Choose how this corporate account should recover access.',
    'login.recoveryClose': 'Close',
    'login.recoveryEmailTitle': 'Email reset link',
    'login.recoveryEmailDescription': 'Generate a secure recovery token for the account email.',
    'login.recoveryAdminTitle': 'Tenant admin reset',
    'login.recoveryAdminDescription': 'Route recovery through the company owner or HR administrator.',
    'login.recoverySecurityTitle': 'Security verification',
    'login.recoverySecurityDescription': 'Use internal identity verification before password reset.',
    'login.recoveryGenerating': 'Generating Recovery...',
    'login.recoveryStart': 'Start Recovery',
    'login.passkeyOpening': 'Opening passkey...',
    'login.passkeySignIn': 'Sign in with passkey',
    'login.passkeyDescription': 'Use Face ID, fingerprint, Windows Hello, device PIN, or a security key.',
    'login.passkeyEmailRequired': 'Enter your email, then use passkey sign in.',
    'login.offline': 'You are offline. Some HR actions require connection.',
    'login.offlineSignIn': 'You appear to be offline. Reconnect to sign in.',
    'login.apiUnavailable': 'Unable to reach the HR API. Check the backend connection and try again.',
    'login.recoveryGeneric': 'If an account exists, password reset instructions have been sent.',
    'login.recoveryStartError': 'Unable to start recovery flow.',
    'login.recoveryServerError': 'Server disconnection. Unable to start recovery flow.',
    'login.passkeyUnsupported': 'Passkeys are not supported in this browser.',
    'login.passkeyStartError': 'Unable to start passkey sign in.',
    'login.invalidCredentials': 'Invalid email or password.',
    'login.rateLimited': 'Too many attempts. Please try again later.',
    'login.systemOperational': 'System Operational • V2.4',
    'login.creatorCredit': 'Created by Shady Awad',
    'login.useDemoAccount': 'Use Demo Account',
    'login.hrAdminDemo': 'HR Admin Demo',
    'login.managerDemo': 'Manager Demo',
    'login.employeeDemo': 'Employee Demo',
    'login.demoCredentialsNote': 'Demo credentials are for portfolio testing only.',
    'login.fillDemoCredentials': 'Fill Demo Credentials',
    'login.demoCompany': 'Stanza Demo Company',
    'login.toggleTheme': 'Toggle Light/Dark Mode',
    'login.recoveryEmail': 'Recovery email',

    'dash.elitePortal': 'Workspace',
    'dash.auth': 'Signed in',
    'dash.terminate': 'Log Out',
    'dash.core': 'Core:',
    'dash.geoOp': 'Geo-Operations',
    'dash.roster': 'Weekly Roster',
    'dash.profile': 'Profile',
    'dash.perimeter': 'Perimeter Verification',
    'dash.hqSecure': 'HQ RADIAL STATUS: SECURE',
    'dash.clockIn': 'CLOCK IN',
    'dash.locating': 'LOCATING',
    'dash.verifying': 'VERIFYING',
    'dash.verified': 'VERIFIED',
    'dash.breach': 'BREACH',
    'dash.sysMsg': 'SYS',
    'dash.awaitingInput': 'Ready to clock in.',
    'dash.rosterHub': 'Weekly Roster',
    'dash.weekView': 'Week View',
    'dash.previousWeek': 'Previous week',
    'dash.nextWeek': 'Next week',
    'dash.thisWeek': 'This week',
    'dash.viewRange': 'View range',
    'dash.oneWeek': '1 week',
    'dash.twoWeeks': '2 weeks',
    'dash.fourWeeks': '4 weeks',
    'dash.customRange': 'Custom range',
    'dash.startDate': 'Start date',
    'dash.endDate': 'End date',
    'dash.rosterRangeTooLarge': 'Date range is too large. Choose a range of 31 days or fewer.',
    'dash.noRosterEntries': 'No roster entries in this range.',
    'dash.applyLeave': 'Apply Leave',
    'dash.resignations': 'Resignations',
    'dash.resignationsHelp': 'Submit and track resignation requests.',
    'dash.submitResignation': 'Submit Resignation',
    'dash.lastWorkingDay': 'Last Working Day',
    'dash.lastWorkingDayRequired': 'Last working day is required.',
    'dash.resignationType': 'Resignation Type',
    'dash.voluntary': 'Voluntary',
    'dash.personalReasons': 'Personal Reasons',
    'dash.careerChange': 'Career Change',
    'dash.other': 'Other',
    'dash.reason': 'Reason',
    'dash.withdraw': 'Withdraw',
    'dash.approve': 'Approve',
    'dash.reject': 'Reject',
    'dash.markProcessed': 'Mark Processed',
    'dash.myResignations': 'My Resignation Requests',
    'dash.tenantResignations': 'Resignation Requests',
    'dash.noResignationRequests': 'No resignation requests yet.',
    'dash.resignationSubmitted': 'Resignation request submitted.',
    'dash.resignationApproved': 'Resignation request approved.',
    'dash.resignationRejected': 'Resignation request rejected.',
    'dash.resignationWithdrawn': 'Resignation request withdrawn.',
    'dash.resignationProcessed': 'Resignation request processed.',
    'dash.resignationLoadError': 'Unable to load resignation requests.',
    'dash.resignationSubmitError': 'Unable to submit resignation request.',
    'dash.resignationUpdateError': 'Unable to update resignation request.',
    'dash.dayDate': 'Day / Date',
    'dash.shiftFrame': 'Shift Frame',
    'dash.locationRole': 'Location/Role',
    'dash.status': 'Status',
    'dash.abstained': 'UNSCHEDULED',
    'dash.scheduled': 'SCHEDULED',
    'dash.advParams': 'System Status',
    'dash.adminsOnline': 'Admins Online',
    'dash.companyFeed': 'Company Feed',
    'dash.companyFeedSubtitle': 'Announcements, events, and policy updates for your company.',
    'dash.refresh': 'Refresh',
    'dash.sensitiveFilter': 'Sensitive content filter',
    'dash.sensitiveFilterDescription': 'Blur non-friendly words in company feed content.',
    'dash.filterOn': 'Enabled',
    'dash.filterOff': 'Disabled',
    'dash.requestBreak': 'Request Break',
    'dash.breakStatus': 'Break Status',
    'dash.breakApprovalQueue': 'Break Approval Queue',
    'dash.noBreakRequests': 'No break requests yet.',
    'dash.noPendingBreakRequests': 'No pending break requests.',
    'dash.installStanza': 'Install Stanza',
    'dash.notificationsReady': 'Notifications Ready',
    'dash.enableNotifications': 'Enable Notifications',
    'dash.notifications': 'Notifications',
    'dash.loading': 'Loading...',
    'dash.sending': 'Sending...',
    'dash.saving': 'Saving...',
    'dash.opening': 'Opening...',
    'dash.pending': 'Pending',
    'dash.pendingApproval': 'Pending Approval',
    'dash.cancelRequest': 'Cancel Request',
    'dash.companyLocations': 'Company Locations',
    'dash.clockInValidLocations': 'Clock-in is valid inside any active company location.',
    'dash.active': 'Active',
    'dash.autoSaved': 'Auto Saved',
    'dash.breakTime': 'Break Time',
    'dash.loadingEditor': 'Loading editor...',
    'dash.publishPost': 'Publish Post',
    'dash.saveDraft': 'Save Draft',
    'dash.loadingCompanyFeed': 'Loading company feed...',
    'dash.loadingPosts': 'Loading posts...',
    'dash.payrollSubtitleAdmin': 'Tenant payroll records and run controls.',
    'dash.payrollSubtitleFull': 'Tenant payroll records, compensation, loans, and approvals',
    'dash.payrollSubtitleSelf': 'Your recent payroll records.',
    'dash.runPayroll': 'Run Payroll',
    'dash.generatingPayroll': 'Generating payroll...',
    'dash.loadingPayroll': 'Loading payroll records...',
    'dash.noPayrollRecords': 'No payroll records yet.',
    'dash.noPayrollAccess': 'No payroll access assigned yet.',
    'dash.grievances': 'Grievances',
    'dash.grievancesSubtitleLeave': 'Submit leave dates and details using the existing request workflow.',
    'dash.grievancesSubtitleAdmin': 'File a grievance and manage tenant cases.',
    'dash.grievancesSubtitleSelf': 'File and track your own grievance cases.',
    'dash.submitLeaveRequest': 'Submit Leave Request',
    'dash.submitGrievance': 'Submit Grievance',
    'dash.submitting': 'Submitting...',
    'dash.myGrievances': 'My Grievances',
    'dash.tenantGrievances': 'Tenant Grievances',
    'dash.loadingMyGrievances': 'Loading your grievances...',
    'dash.loadingTenantGrievances': 'Loading tenant grievances...',
    'dash.passkeys': 'Passkeys',
    'dash.addPasskey': 'Add Passkey',
    'dash.loadingPasskeys': 'Loading passkeys...',
    'dash.actions': 'Actions',
    'dash.controlCenterTitle': 'Stanza Control Center',
    'dash.controlCenterSubtitle': 'Quick access to notifications, locations, and workspace status.',
    'dash.close': 'Close',
    'dash.logout': 'Log Out',
    'dash.company': 'Company',
    'dash.tenantId': 'Tenant ID',
    'dash.show': 'Show',
    'dash.hide': 'Hide',
    'dash.copy': 'Copy',
    'dash.copied': 'Copied',
    'dash.hidden': 'Hidden',
    'dash.settings': 'Settings',
    'dash.switchLight': 'Switch to Light Mode',
    'dash.switchDark': 'Switch to Dark Mode',
    'dash.appReadiness': 'App Readiness',
    'dash.appReadinessSubtitle': 'Install, offline, and notification status for this device.',
    'dash.online': 'Online',
    'dash.offline': 'Offline',
    'dash.appMode': 'App mode',
    'dash.installedMode': 'Installed mode',
    'dash.browserMode': 'Browser mode',
    'dash.unsupported': 'Unsupported',
    'dash.permissionGranted': 'Granted',
    'dash.permissionDenied': 'Denied',
    'dash.permissionDefault': 'Default',
    'dash.dismiss': 'Dismiss',
    'dash.iosInstallHint': 'On iOS, open the Share menu, then choose Add to Home Screen to install Stanza.',
    'dash.notificationSettings': 'Notification Settings',
    'dash.emailPushPreferences': 'Email and push preferences',
    'dash.configured': 'Configured',
    'dash.default': 'Default',
    'dash.registered': 'registered',
    'dash.workspaceStatus': 'Workspace Status',
    'dash.passkeyNotConfigured': 'Passkeys are not configured for this environment.',
    'dash.expand': 'Expand',
    'dash.collapse': 'Collapse',
    'dash.notificationSettingsSubtitle': 'Choose which updates Stanza should surface for your account.',
    'dash.notificationDeliveryReady': 'Email and push delivery are preference-ready; delivery providers can be connected later.',
    'dash.category': 'Category',
    'dash.quietHoursStart': 'Quiet hours start',
    'dash.quietHoursEnd': 'Quiet hours end',
    'dash.saveSettings': 'Save Settings',
    'dash.passkeyDescription': 'Add Face ID, fingerprint, Windows Hello, device PIN, or security key sign-in. Stanza never stores biometric data.',
    'dash.noPasskeys': 'No passkeys registered yet.',
    'dash.passkeyDevice': 'Passkey',
    'dash.platform': 'Platform',
    'dash.lastUsed': 'Last used',
    'dash.added': 'Added',
    'dash.never': 'Never',
    'dash.locations': 'Locations',
    'dash.noCompanyLocations': 'No company locations found.',
    'dash.noActiveCompanyLocations': 'No active company locations found.',
    'dash.systemStatus': 'System Status',
    'dash.ready': 'Ready',
    'dash.locationsConfigured': 'Locations configured',
    'dash.currentShift': 'Current shift',
    'dash.open': 'Open',
    'dash.notClockedIn': 'Not clocked in',
    'dash.lastAttendanceEvent': 'Last attendance event',
    'dash.noActiveShiftRecorded': 'No active shift recorded.',
    'dash.breakRequestHelp': 'Send a short break request for manager approval.',
    'dash.custom': 'Custom',
    'dash.breakDurationPlaceholder': '5-180 minutes',
    'dash.optionalReason': 'Optional reason',
    'dash.breakStatusHelp': 'Latest personal requests and manager decisions.',
    'dash.minutes': 'minutes',
    'dash.requested': 'Requested',
    'dash.reviewNote': 'Review note',
    'dash.reviewPendingBreakRequests': 'Review pending employee break requests.',
    'dash.optionalReviewNote': 'Optional review note',
    'dash.employee': 'Employee',
    'dash.primary': 'Primary',
    'dash.noBreak': 'No break',
    'dash.leave': 'Leave',
    'dash.officeHq': 'Office HQ',
    'dash.remote': 'Remote',
    'dash.annualLeave': 'Annual Leave',
    'dash.monday': 'Monday',
    'dash.tuesday': 'Tuesday',
    'dash.wednesday': 'Wednesday',
    'dash.thursday': 'Thursday',
    'dash.friday': 'Friday',
    'dash.saturday': 'Saturday',
    'dash.sunday': 'Sunday',
    'dash.postTitle': 'Post title',
    'dash.writeAnnouncement': 'Write the announcement...',
    'dash.everyone': 'Everyone',
    'dash.roleEmployee': 'Role: Employee',
    'dash.roleManager': 'Role: Manager',
    'dash.roleHrAdmin': 'Role: HR Admin',
    'dash.locationPrefix': 'Location',
    'dash.noCompanyAnnouncements': 'No company announcements yet.',
    'dash.managePosts': 'Manage Posts',
    'dash.noPostsToManage': 'No posts to manage yet.',
    'dash.eventTimeTbd': 'Event time TBD',
    'dash.compensationProfiles': 'Compensation Profiles',
    'dash.compensationProfilesHelp': 'Saved profiles override the fallback salary when payroll runs.',
    'dash.saveCompensation': 'Save Compensation',
    'dash.missingActiveCompensation': 'Missing active compensation profile',
    'dash.noActiveCompensation': 'No active compensation profile',
    'dash.noEmployeesForCompensation': 'No employees found for compensation profiles.',
    'dash.payrollRunHelp': "Payroll uses each employee's active compensation profile. Fallback Base Salary is optional, and active loan repayments are automatically included in deductions for new payroll records.",
    'dash.selectEmployee': 'Select employee',
    'dash.baseAmount': 'Base amount',
    'dash.effective': 'Effective',
    'dash.employeeLoans': 'Employee Loans',
    'dash.employeeLoansAdminHelp': 'Create tenant loans and manage repayment status.',
    'dash.employeeLoansSelfHelp': 'Your active and historical employee loans.',
    'dash.loanName': 'Loan name',
    'dash.principal': 'Principal',
    'dash.outstanding': 'Outstanding',
    'dash.repayment': 'Repayment',
    'dash.due': 'Due',
    'dash.notSet': 'Not set',
    'dash.createLoan': 'Create Loan',
    'dash.creating': 'Creating...',
    'dash.noEmployeeLoans': 'No employee loans yet.',
    'dash.loanDeductionsApplied': 'Loan deductions applied',
    'dash.skippedEmployees': 'Skipped employees',
    'dash.period': 'Period',
    'dash.base': 'Base',
    'dash.bonus': 'Bonus',
    'dash.deductions': 'Deductions',
    'dash.net': 'Net',
    'dash.export': 'Export',
    'dash.exportPdf': 'Export PDF',
    'dash.exporting': 'Exporting...',
    'dash.updating': 'Updating...',
    'dash.final': 'Final',
    'dash.noAccess': 'No access',
    'dash.approvedAt': 'Approved',
    'dash.paidAt': 'Paid',
    'dash.cancelledAt': 'Cancelled',
    'dash.back': 'Back',
    'dash.title': 'Title',
    'dash.categoryLabel': 'Category',
    'dash.description': 'Description',
    'dash.noGrievances': 'No grievances filed yet.',
    'dash.noTenantGrievances': 'No tenant grievances yet.',
    'dash.case': 'Case',
    'dash.priority': 'Priority',
    'dash.created': 'Created',
    'dash.update': 'Update',
    'dash.rolesPermissions': 'Roles & Permissions',
    'dash.rolesPermissionsHelp': 'Foundation controls for tenant roles, permission keys, and employee job titles.',
    'dash.systemRole': 'System role',
    'dash.customRole': 'Custom role',
    'dash.assigned': 'assigned',
    'dash.noPermissions': 'No permissions yet.',
    'dash.employeeAssignments': 'Employee Assignments',
    'dash.noCustomAssignments': 'No custom assignments',
    'dash.assignRole': 'Assign role',
    'dash.saveTitle': 'Save Title',
    'dash.jobTitle': 'Job title',
    'dash.createCustomRole': 'Create Custom Role',
    'dash.roleName': 'Role name',
    'dash.noRolesYet': 'No custom roles yet.',
    'dash.createRole': 'Create Role',
    'dash.roleCreated': 'Custom role created.',
    'dash.roleAssigned': 'Role assigned.',
    'dash.titleUpdated': 'Job title updated.',
    'dash.roleLoadError': 'Unable to load role management.',
    'dash.roleCreateError': 'Unable to create role.',
    'dash.roleAssignError': 'Unable to assign role.',
    'dash.titleUpdateError': 'Unable to update job title.',
    'dash.payPeriodStart': 'Pay period start',
    'dash.payPeriodEnd': 'Pay period end',
    'dash.fallbackBaseSalary': 'Fallback base salary',
    'dash.bonuses': 'Bonuses',
    'dash.profileLoanCleared': 'Cleared',
    'dash.noActiveLiabilities': 'No active liabilities',
    'dash.installedMessage': 'Stanza is installed.',
    'dash.installDismissedMessage': 'Install prompt dismissed. You can still install Stanza from the browser menu.',
    'dash.installStartedMessage': 'Stanza install started.',
    'dash.installPromptError': 'Unable to open the install prompt. Use your browser install menu.',
    'dash.notificationUnsupportedMessage': 'Notifications are not supported in this browser.',
    'dash.notificationSecureContextMessage': 'Notification permissions require HTTPS or localhost.',
    'dash.notificationReadyMessage': 'Notification permissions ready. Push delivery requires server push setup.',
    'dash.notificationNotGrantedMessage': 'Notification permission was not granted.',
    'dash.notificationRequestError': 'Unable to request notification permission.',
    'dash.notificationLoadError': 'Unable to load notification settings.',
    'dash.notificationLoadServerError': 'Server disconnection. Unable to load notification settings.',
    'dash.notificationSaved': 'Notification settings saved.',
    'dash.notificationSaveError': 'Unable to save notification settings.',
    'dash.notificationSaveServerError': 'Server disconnection. Unable to save notification settings.',
    'dash.breakLoadError': 'Unable to load break requests.',
    'dash.breakPendingLoadError': 'Unable to load pending break requests.',
    'dash.breakLoadServerError': 'Server disconnection. Unable to load break requests.',
    'dash.breakDurationError': 'Choose a break duration between 5 and 180 minutes.',
    'dash.breakRequestError': 'Unable to request break.',
    'dash.breakRequestSent': 'Break request sent for approval.',
    'dash.breakRequestServerError': 'Server disconnection. Unable to request break.',
    'dash.breakCancelError': 'Unable to cancel break request.',
    'dash.breakCancelled': 'Break request cancelled.',
    'dash.breakCancelServerError': 'Server disconnection. Unable to cancel break request.',
    'dash.breakReviewError': 'Unable to review break request.',
    'dash.breakReviewServerError': 'Server disconnection. Unable to review break request.',
    'dash.passkeyLoadError': 'Unable to load passkeys.',
    'dash.passkeyLoadServerError': 'Server disconnection. Unable to load passkeys.',
    'dash.passkeyUnsupported': 'Passkeys are not supported in this browser.',
    'dash.passkeyStartError': 'Unable to start passkey registration.',
    'dash.passkeySaveError': 'Unable to save passkey.',
    'dash.passkeyAdded': 'Passkey added. You can now sign in with this device.',
    'dash.passkeyAddError': 'Unable to add passkey.',
    'dash.payrollLoadError': 'Unable to load payroll records.',
    'dash.payrollLoadServerError': 'Server disconnection. Unable to load payroll records.',
    'dash.compensationLoadError': 'Unable to load compensation profiles.',
    'dash.compensationLoadServerError': 'Server disconnection. Unable to load compensation profiles.',
    'dash.loanLoadError': 'Unable to load employee loans.',
    'dash.loanLoadServerError': 'Server disconnection. Unable to load employee loans.',
    'dash.compensationSaved': 'Compensation profile saved.',
    'dash.compensationSaveError': 'Unable to save compensation profile.',
    'dash.compensationSaveServerError': 'Server disconnection. Unable to save compensation profile.',
    'dash.employeeLoanCreated': 'Employee loan created.',
    'dash.employeeLoanCreateError': 'Unable to create employee loan.',
    'dash.employeeLoanCreateServerError': 'Server disconnection. Unable to create employee loan.',
    'dash.loanStatusUpdated': 'Loan status updated.',
    'dash.loanStatusUpdateError': 'Unable to update loan status.',
    'dash.loanStatusUpdateServerError': 'Server disconnection. Unable to update loan status.',
    'dash.payrollStatusUpdateError': 'Unable to update payroll status.',
    'dash.payrollStatusUpdateServerError': 'Server disconnection. Unable to update payroll status.',
    'dash.payrollRunError': 'Unable to run payroll.',
    'dash.payrollRunServerError': 'Server disconnection. Unable to run payroll.',
    'dash.payrollPeriodError': 'Choose a payroll end date after the start date.',
    'dash.payrollStatusUpdated': 'Payroll status updated to',
    'dash.payrollRunComplete': 'Payroll run completed. Records generated:',
    'dash.missingCompensationSkip': 'Missing active compensation profile and no fallback base salary was provided.',
    'dash.offlineActionMessage': 'You are offline. Some HR actions require connection.',
    'dash.payrollExportError': 'Unable to export payroll PDF.',
    'dash.grievanceLoadError': 'Unable to load grievances.',
    'dash.tenantGrievanceLoadError': 'Unable to load tenant grievances.',
    'dash.grievanceLoadServerError': 'Server disconnection. Unable to load grievances.',
    'dash.leaveRequestOpened': 'Leave request form opened. Add your dates and details, then submit.',
    'dash.grievanceFiled': 'Grievance filed successfully.',
    'dash.grievanceFileError': 'Unable to file grievance.',
    'dash.grievanceFileServerError': 'Server disconnection. Unable to file grievance.',
    'dash.grievanceStatusUpdated': 'Grievance status updated.',
    'dash.grievanceStatusUpdateError': 'Unable to update grievance status.',
    'dash.grievanceStatusUpdateServerError': 'Server disconnection. Unable to update grievance status.',
    'dash.feedLoadError': 'Unable to load company feed.',
    'dash.feedLoadServerError': 'Server disconnection. Unable to load company feed.',
    'dash.postPublished': 'Post published.',
    'dash.draftSaved': 'Draft saved.',
    'dash.feedSaveError': 'Unable to save feed post.',
    'dash.feedSaveServerError': 'Server disconnection. Unable to save feed post.',
    'dash.postStatusUpdated': 'Post status updated.',
    'dash.postStatusUpdateError': 'Unable to update post status.',
    'dash.postStatusUpdateServerError': 'Server disconnection. Unable to update post status.',
    'dash.locationsLoadError': 'Unable to load locations.',
    'enum.employee': 'Employee',
    'enum.manager': 'Manager',
    'enum.hrAdmin': 'HR Admin',
    'enum.pending': 'Pending',
    'enum.approved': 'Approved',
    'enum.rejected': 'Rejected',
    'enum.cancelled': 'Cancelled',
    'enum.draft': 'Draft',
    'enum.published': 'Published',
    'enum.archived': 'Archived',
    'enum.paid': 'Paid',
    'enum.open': 'Open',
    'enum.underReview': 'Under Review',
    'enum.resolved': 'Resolved',
    'enum.closed': 'Closed',
    'enum.active': 'Active',
    'enum.inactive': 'Inactive',
    'enum.missing': 'Missing',
    'enum.low': 'Low',
    'enum.normal': 'Normal',
    'enum.high': 'High',
    'enum.urgent': 'Urgent',
    'enum.general': 'General',
    'enum.scheduling': 'Scheduling',
    'enum.leaveRequest': 'Leave Request',
    'enum.announcement': 'Announcement',
    'enum.event': 'Event',
    'enum.policyUpdate': 'Policy Update',
    'enum.monthly': 'Monthly',
    'enum.weekly': 'Weekly',
    'enum.hourly': 'Hourly',
    'enum.annual': 'Annual',
    'enum.oneTime': 'One Time',
    'enum.headquarters': 'Headquarters',
    'enum.branch': 'Branch',
    'enum.warehouse': 'Warehouse',
    'enum.remoteSite': 'Remote Site',
    'enum.other': 'Other',
    'notification.inApp': 'In-app',
    'notification.email': 'Email',
    'notification.push': 'Push',
    'notification.attendanceReminders': 'Attendance reminders',
    'notification.attendanceRemindersDescription': 'Clock-in, clock-out, and attendance perimeter prompts.',
    'notification.breakReminders': 'Break reminders',
    'notification.breakRemindersDescription': 'Scheduled break start and return reminders.',
    'notification.breakRequestPending': 'Break approval queue',
    'notification.breakRequestPendingDescription': 'Manager and HR alerts for pending break requests.',
    'notification.breakRequestReviewed': 'Break request updates',
    'notification.breakRequestReviewedDescription': 'Approval and rejection updates for your break requests.',
    'notification.leaveUpdates': 'Leave request updates',
    'notification.leaveUpdatesDescription': 'Leave approvals, rejections, and workflow changes.',
    'notification.payrollUpdates': 'Payroll updates',
    'notification.payrollUpdatesDescription': 'Payroll runs, approvals, payments, and statement availability.',
    'notification.loanUpdates': 'Loan updates',
    'notification.loanUpdatesDescription': 'Employee loan creation, balance, and status updates.',
    'notification.grievanceUpdates': 'Grievance updates',
    'notification.grievanceUpdatesDescription': 'Case status changes and review activity.',
    'notification.companyFeedPosts': 'Company feed posts',
    'notification.companyFeedPostsDescription': 'Announcements, events, and policy updates.',
    'notification.rolePermissionChanges': 'Role & permission changes',
    'notification.rolePermissionChangesDescription': 'Custom role assignments and permission updates.',
    'notification.systemAlerts': 'System alerts',
    'notification.systemAlertsDescription': 'Important account, workspace, and security notices.',
    'editor.bold': 'Bold',
    'editor.italic': 'Italic',
    'editor.underline': 'Underline',
    'editor.bulletedList': 'Bulleted list',
    'editor.numberedList': 'Numbered list',
    'editor.removeList': 'Remove list',
    'editor.textColor': 'Text color',
    'editor.color': 'Color',
    'editor.fontSize': 'Font size',
    'editor.size': 'Size',
    'editor.insertEmoji': 'Insert emoji',
    'editor.emoji': 'Emoji',
    'editor.undo': 'Undo',
    'editor.redo': 'Redo',
    'editor.reset': 'Reset',
    'editor.defaultColor': 'Default',
    'editor.white': 'White',
    'editor.mutedGray': 'Muted Gray',
    'editor.emerald': 'Emerald',
    'editor.lime': 'Lime',
    'editor.teal': 'Teal',
    'editor.cyan': 'Cyan',
    'editor.blue': 'Blue',
    'editor.purple': 'Purple',
    'editor.pink': 'Pink',
    'editor.red': 'Red',
    'editor.orange': 'Orange',
    'editor.amber': 'Amber',
    'editor.yellow': 'Yellow',
    'editor.announcements': 'Announcements',
    'editor.calendarEvents': 'Calendar/events',
    'editor.workHr': 'Work/HR',
    'editor.positiveTeam': 'Positive/team',
    'editor.status': 'Status',
    'editor.writeUpdate': 'Write an update...',
    'dash.clockOut': 'CLOCK OUT',
    'dash.activeShift': 'Active shift open',
    'dash.offlineAction': 'You are offline. Some HR actions require connection.',
    'dash.noActiveLocation': 'No active company location found for this workspace.',
    'dash.locationUnavailable': 'Location services are not available in this browser.',
    'dash.locationPermission': 'Requesting location permission...',
    'dash.locationDenied': 'Location permission is required to clock in.',
    'dash.clockInSuccess': 'Clocked in successfully.',
    'dash.clockInError': 'Unable to record clock-in.',
    'dash.clockInTryAgain': 'Unable to clock in. Please try again.',
    'dash.outsideGeofence': 'You are outside the allowed worksite geofence.',
    'dash.outsideGeofenceLabel': 'Outside geofence',
    'dash.openShiftConflict': 'You already have an active shift. Clock out before clocking in again.',
    'dash.openShiftConflictLabel': 'Active shift already open',
    'dash.attendanceErrorLabel': 'Attendance error',
    'dash.clockOutSuccess': 'Clocked out successfully.',
    'dash.clockOutError': 'Unable to clock out. Please try again.',
    'dash.noActiveShift': 'No active shift found.',
    'dash.clockingOut': 'Clocking out...',
    'dash.serverDisconnected': 'Server disconnection. Unable to verify location.',
    'dash.secureLocationContext': 'Location permission requires localhost or HTTPS. Plain LAN IP HTTP may not work.',
    'dash.validatingGeofence': 'Validating geofence...',
    'dash.locationAccuracy': 'Location accuracy',
    'dash.approximateLocation': 'Approximate location.',
    'dash.lowAccuracyLocation': 'Your browser returned a low-accuracy location. Clock-in may be inaccurate. Use phone GPS for best results.',

    'profile.title': 'Employee Profile',
    'profile.subtitle': 'Personnel Ledger & Workflows',
    'profile.leaveName': 'Leave Balance',
    'profile.leaveDays': 'Days',
    'profile.loan': 'Active Loan Status',
    'profile.payroll': 'Payroll Details',
    'profile.grievance': 'File Grievance',

    'signup.title': 'Corporate Onboarding',
    'signup.subtitle': 'Register your Stanza workspace',
    'signup.step1': 'Corporate Details',
    'signup.step2': 'Operations & Finance',
    'signup.step3': 'Geo-Perimeter',
    'signup.companyName': 'Company Legal Name',
    'signup.tenantSlug': 'Unique Tenant Slug',
    'signup.adminFullName': 'Admin Full Name',
    'signup.adminEmail': 'Admin Email',
    'signup.emailUnavailable': 'This email cannot be used for a new workspace. Try signing in or recovering your account.',
    'signup.workspaceUnavailable': 'This workspace name is unavailable. Try another name.',
    'signup.rateLimited': 'Too many attempts. Please try again later.',
    'signup.emailAlreadyRegistered': 'An account with this email already exists.',
    'signup.workspaceAlreadyExists': 'A workspace with this name already exists.',
    'signup.registerError': 'Unable to register workspace.',
    'signup.adminPass': 'Admin Password',
    'signup.confirmPass': 'Confirm Password',
    'signup.currency': 'Base Operating Currency',
    'signup.capacity': 'Employee Capacity',
    'signup.loans': 'Enable Corporate Loans Policy',
    'signup.geoLat': 'Headquarters Latitude',
    'signup.geoLng': 'Headquarters Longitude',
    'signup.geoRadius': 'Bounding Radius (meters)',
    'signup.complete': 'Create Workspace',
    'signup.back': 'Back',
    'signup.next': 'Next',
    'signup.login': 'Return to Login',
    'signup.initialRole': 'Initial Account Role',
    'signup.initialRoleHelp': 'Choose the role for the first account created under this tenant.',
    'signup.enableLoansHelp': 'Enable payroll deductions and standard corporate loan requests.',
    'signup.customRoles': 'Custom Roles',
    'signup.customRolesHelp': 'Optional. Defaults are created automatically.',
    'signup.addRole': 'Add Role',
    'signup.roleName': 'Role name',
    'signup.roleDescription': 'Description',
    'signup.remove': 'Remove',
    'signup.noCustomRoles': 'No custom roles defined. Employee, Manager, and HR Admin will be created.',
    'signup.locations': 'Locations',
    'signup.locationsHelp': 'Add each site that should allow clock-in.',
    'signup.addLocation': 'Add Location',
    'signup.unnamedLocation': 'Unnamed Location',
    'signup.coordinatesSet': 'Coordinates set',
    'signup.primaryLocation': 'Primary Location',
    'signup.locationDetails': 'Location details',
    'signup.locationDetailsHelp': 'Name the worksite before placing the pin.',
    'signup.locationName': 'Location Name',
    'signup.locationType': 'Location Type',
    'signup.addressOptional': 'Address Optional',
    'signup.addressPlaceholder': 'Street, city, country',
    'signup.removeLocation': 'Remove Location',
    'signup.worksiteGeofence': 'Worksite Geofence',
    'signup.geofenceInstruction': 'Drag the pin to the exact office entrance or worksite center.',
    'signup.useMyLocation': 'Use My Location',
    'signup.detecting': 'Detecting...',
    'signup.mapKeyMissing': 'Map provider key missing',
    'signup.mapKeyMissingHelp': 'Add VITE_MAPTILER_KEY.',
    'signup.mapLoading': 'Loading MapLibre map...',
    'signup.mapUnavailable': 'Map provider unavailable',
    'signup.mapUnavailableHelp': 'Check VITE_MAPTILER_KEY, then restart the dev server.',
    'signup.locationStatus': 'Location status',
    'signup.locationDetected': 'Location detected',
    'signup.approximateLocation': 'Approximate location',
    'signup.lowAccuracyLocation': 'Low accuracy location',
    'signup.manualAdjustment': 'Manual adjustment',
    'signup.manualCoordinates': 'Manual coordinates',
    'signup.approximateWarning': 'Browser location is only approximate. Manual adjustment is required.',
    'signup.useApproximateAnyway': 'Use Approximate Location Anyway',
    'signup.mapProviderNote': 'Map labels are provided by MapTiler/OpenStreetMap and may differ from local naming. Use satellite view or drag the pin to confirm the exact worksite.',
    'signup.latitude': 'Latitude',
    'signup.longitude': 'Longitude',
    'signup.notSelected': 'Not selected',
    'signup.locationAccuracy': 'Location accuracy',
    'signup.meters': 'meters',
    'signup.accuracyHelp': 'Your browser location may be approximate. Drag the pin to fine-tune the worksite.',
    'signup.geofenceRadius': 'Geofence Radius',
    'signup.geofenceRadiusHelp': 'Controls the allowed clock-in zone around the selected worksite.',
    'signup.enterCoordinatesManually': 'Enter Coordinates Manually',
    'signup.hideManualCoordinates': 'Hide Manual Coordinates',
    'signup.howToGetCoordinates': 'How to get coordinates',
    'signup.coordinateStepGoogleMaps': 'Open Google Maps.',
    'signup.coordinateStepPress': 'Long-press or right-click the exact office/worksite location.',
    'signup.coordinateStepCopy': 'Copy the latitude and longitude numbers.',
    'signup.coordinateStepPaste': 'Paste them into the Latitude and Longitude fields.',
    'signup.coordinateStepConfirm': 'Confirm the marker moves to the correct place.',
    'signup.coordinateOrderHelp': 'Google Maps shows latitude first, longitude second.',
    'signup.radius': 'Radius',
    'signup.radiusValidation': 'Radius must be between 25 and 5000 meters.',
    'signup.latitudeValidation': 'Latitude must be between -90 and 90.',
    'signup.longitudeValidation': 'Longitude must be between -180 and 180.',
    'signup.locationTypeHeadquarters': 'Headquarters',
    'signup.locationTypeBranch': 'Branch Office',
    'signup.locationTypeWarehouse': 'Warehouse',
    'signup.locationTypeRemote': 'Remote Site',
    'signup.locationTypeOther': 'Other',
    'signup.mapStyleStreets': 'Streets',
    'signup.mapStyleSatellite': 'Satellite',
    'privacy.link': 'Privacy Policy',
    'privacy.title': 'Privacy Policy',
    'privacy.close': 'Close privacy policy',
    'privacy.notLegalAdvice': 'This policy explains the Stanza demo experience and is not legal advice.',
    'privacy.overview': 'Overview',
    'privacy.overviewText': 'Stanza is a workforce operations demo and portfolio application created by Shady Awad.',
    'privacy.data': 'Information we handle',
    'privacy.dataText': 'The app may handle account, workforce, attendance, payroll, leave, grievance, and company feed information needed to demonstrate its features.',
    'privacy.location': 'Location data',
    'privacy.locationText': 'Location is used for geofence and attendance features only when you choose an action that needs it. You can deny location permission, though those features may not work.',
    'privacy.passkeys': 'Passkeys',
    'privacy.passkeysText': 'Passkeys use your device authenticator. Stanza does not receive or store biometric data or private keys.',
    'privacy.demoData': 'Demo data',
    'privacy.demoDataText': 'Use fictional or test information in this demo. Do not submit sensitive real-world employee or payroll data.',
    'privacy.recovery': 'Account recovery',
    'privacy.recoveryText': 'Recovery features are demonstrated through the application flow. They are not a guarantee of production email delivery or identity verification.',
    'privacy.thirdParties': 'Third-party services',
    'privacy.thirdPartiesText': 'Map views use MapTiler and OpenStreetMap data. Their labels and coverage may differ from local map providers.',
    'privacy.security': 'Security',
    'privacy.securityText': 'Stanza applies application security controls, but this portfolio demo is not a production HR deployment or a substitute for a company privacy program.',
    'privacy.contact': 'Contact',
    'privacy.createdBy': 'Created by',
    'demo.title': 'Demo context',
    'demo.body': 'You are using a Stanza demo and portfolio application. Use fictional data only. Some features may use sample records or simulated workflows and are not a production HR service.',
    'demo.dismiss': 'I understand',
    'demo.show': 'About this demo',
    'demo.mapNoticeTitle': 'Map data notice',
    'demo.mapNoticeBody': 'Map views use MapTiler and OpenStreetMap data. Labels and coverage may differ from Google Maps or local map providers.',
    'demo.payroll': 'Payroll information in this environment is for demonstration and testing. Use fictional data only.',
    'demo.grievances': 'Avoid entering sensitive real employee grievances in this demo environment.',
    'demo.feed': 'Company feed posts are part of this demo workspace. Do not publish confidential company information.',
    'demo.passkeys': 'Passkeys use your device authenticator. Stanza does not store biometric data or private keys.',
    'demo.notifications': 'Notification settings prepare your preferences; push delivery requires a configured production service.',
    'demo.footer': 'Demo / Portfolio project by Shady Awad. Use fictional data only.',
  },
  ar: {
    'validation.email': 'أدخل عنوان بريد إلكتروني صالح.',
    'validation.passwordRequired': 'كلمة المرور مطلوبة.',
    'validation.passwordChecklist': 'يجب أن تتضمن كلمة المرور:',
    'validation.passwordLength': 'ثمانية أحرف على الأقل',
    'validation.passwordUppercase': 'حرفًا كبيرًا واحدًا',
    'validation.passwordLowercase': 'حرفًا صغيرًا واحدًا',
    'validation.passwordNumber': 'رقمًا واحدًا',
    'validation.passwordSpecial': 'رمزًا خاصًا واحدًا',
    'validation.confirmPassword': 'يجب أن تتطابق كلمتا المرور.',
    'validation.required': 'هذا الحقل مطلوب.',
    'validation.companyLocationRequired': 'يرجى استخدام موقعك أو إدخال الإحداثيات لكل موقع شركة قبل الإرسال.',

    'login.title': 'Stanza',
    'login.subtitle': 'مصادقة المؤسسات',
    'login.corporateId': 'البريد الإلكتروني',
    'login.biometricKey': 'كلمة المرور',
    'login.authenticating': 'جارٍ تسجيل الدخول...',
    'login.accessGranted': 'تم تسجيل الدخول',
    'login.enterSector': 'تسجيل الدخول',
    'login.forgotPassword': 'هل نسيت كلمة المرور؟',
    'login.registerTenant': 'تسجيل شركة جديدة',
    'login.recoveryTitle': 'استعادة الوصول',
    'login.recoverySubtitle': 'اختر طريقة استعادة الوصول لهذا الحساب.',
    'login.recoveryClose': 'إغلاق',
    'login.recoveryEmailTitle': 'رابط إعادة تعيين عبر البريد',
    'login.recoveryEmailDescription': 'إنشاء رمز استعادة آمن لبريد الحساب.',
    'login.recoveryAdminTitle': 'إعادة تعيين بواسطة مسؤول الشركة',
    'login.recoveryAdminDescription': 'توجيه الاستعادة إلى مالك الشركة أو مسؤول الموارد البشرية.',
    'login.recoverySecurityTitle': 'تحقق أمني',
    'login.recoverySecurityDescription': 'استخدم التحقق الداخلي من الهوية قبل إعادة تعيين كلمة المرور.',
    'login.recoveryGenerating': 'جارٍ إنشاء الاستعادة...',
    'login.recoveryStart': 'بدء الاستعادة',
    'login.passkeyOpening': 'جارٍ فتح مفتاح المرور...',
    'login.passkeySignIn': 'تسجيل الدخول بمفتاح مرور',
    'login.passkeyDescription': 'استخدم Face ID أو البصمة أو Windows Hello أو رمز الجهاز أو مفتاح أمان.',
    'login.passkeyEmailRequired': 'أدخل بريدك الإلكتروني ثم استخدم تسجيل الدخول بمفتاح المرور.',
    'login.offline': 'أنت غير متصل. بعض إجراءات الموارد البشرية تتطلب اتصالًا.',
    'login.offlineSignIn': 'يبدو أنك غير متصل. أعد الاتصال لتسجيل الدخول.',
    'login.apiUnavailable': 'تعذر الوصول إلى واجهة الموارد البشرية. تحقق من اتصال الخادم وحاول مرة أخرى.',
    'login.recoveryGeneric': 'إذا كان الحساب موجودًا، فقد تم إرسال تعليمات إعادة تعيين كلمة المرور.',
    'login.systemOperational': 'النظام يعمل • V2.4',
    'login.toggleTheme': 'تبديل الوضع الفاتح/الداكن',
    'login.recoveryEmail': 'بريد الاستعادة',

    'dash.elitePortal': 'مساحة العمل',
    'dash.auth': 'تم تسجيل الدخول',
    'dash.terminate': 'تسجيل الخروج',
    'dash.core': 'الأساسي:',
    'dash.geoOp': 'عمليات الموقع',
    'dash.roster': 'الجدول الأسبوعي',
    'dash.profile': 'الملف الشخصي',
    'dash.perimeter': 'التحقق من النطاق',
    'dash.hqSecure': 'حالة المقر: آمن',
    'dash.clockIn': 'تسجيل الحضور',
    'dash.locating': 'تحديد الموقع',
    'dash.verifying': 'التحقق',
    'dash.verified': 'تم التحقق',
    'dash.breach': 'خارج النطاق',
    'dash.sysMsg': 'النظام',
    'dash.awaitingInput': 'بانتظار الموقع أو الإدخال',
    'dash.rosterHub': 'الجدول الأسبوعي',
    'dash.weekView': 'عرض أسبوعي',
    'dash.applyLeave': 'طلب إجازة',
    'dash.dayDate': 'اليوم / التاريخ',
    'dash.shiftFrame': 'وقت المناوبة',
    'dash.locationRole': 'الموقع/الدور',
    'dash.status': 'الحالة',
    'dash.abstained': 'غير مجدول',
    'dash.scheduled': 'مجدول',
    'dash.advParams': 'حالة النظام',
    'dash.adminsOnline': 'المسؤولون المتصلون',
    'dash.companyFeed': 'منشورات الشركة',
    'dash.companyFeedSubtitle': 'إعلانات وفعاليات وتحديثات سياسات الشركة.',
    'dash.refresh': 'تحديث',
    'dash.sensitiveFilter': 'مرشح المحتوى الحساس',
    'dash.sensitiveFilterDescription': 'إخفاء الكلمات غير المناسبة في منشورات الشركة.',
    'dash.filterOn': 'مفعل',
    'dash.filterOff': 'معطل',
    'dash.requestBreak': 'طلب استراحة',
    'dash.breakStatus': 'حالة الاستراحة',
    'dash.breakApprovalQueue': 'قائمة موافقات الاستراحة',
    'dash.noBreakRequests': 'لا توجد طلبات استراحة بعد.',
    'dash.noPendingBreakRequests': 'لا توجد طلبات استراحة معلقة.',
    'dash.installStanza': 'تثبيت Stanza',
    'dash.notificationsReady': 'الإشعارات جاهزة',

    'profile.title': 'ملف الموظف',
    'profile.subtitle': 'سجل الموظف وسير العمل',
    'profile.leaveName': 'رصيد الإجازات',
    'profile.leaveDays': 'أيام',
    'profile.loan': 'حالة القرض النشط',
    'profile.payroll': 'تفاصيل الرواتب',
    'profile.grievance': 'تقديم شكوى',

    'signup.title': 'إعداد الشركة',
    'signup.subtitle': 'سجل مساحة عمل Stanza',
    'signup.step1': 'تفاصيل الشركة',
    'signup.step2': 'العمليات والمالية',
    'signup.step3': 'النطاق الجغرافي',
    'signup.companyName': 'الاسم القانوني للشركة',
    'signup.tenantSlug': 'معرف الشركة الفريد',
    'signup.adminFullName': 'الاسم الكامل للمسؤول',
    'signup.adminEmail': 'بريد المسؤول الإلكتروني',
    'signup.emailAlreadyRegistered': 'يوجد حساب مسجل بالفعل بهذا البريد الإلكتروني.',
    'signup.workspaceAlreadyExists': 'توجد مساحة عمل مسجلة بالفعل بهذا الاسم.',
    'signup.registerError': 'تعذر تسجيل مساحة العمل.',
    'signup.adminPass': 'كلمة مرور المسؤول',
    'signup.confirmPass': 'تأكيد كلمة المرور',
    'signup.currency': 'عملة التشغيل الأساسية',
    'signup.capacity': 'سعة الموظفين',
    'signup.loans': 'تفعيل سياسة قروض الشركة',
    'signup.geoLat': 'خط عرض المقر',
    'signup.geoLng': 'خط طول المقر',
    'signup.geoRadius': 'نصف قطر النطاق (متر)',
    'signup.complete': 'إنشاء مساحة العمل',
    'signup.back': 'رجوع',
    'signup.next': 'التالي',
    'signup.login': 'العودة إلى تسجيل الدخول',
    'signup.initialRole': 'دور الحساب الأول',
    'signup.initialRoleHelp': 'اختر دور أول حساب يتم إنشاؤه ضمن هذه الشركة.',
    'signup.enableLoansHelp': 'تفعيل الاستقطاعات من الرواتب وطلبات قروض الشركة القياسية.',
    'signup.customRoles': 'الأدوار المخصصة',
    'signup.customRolesHelp': 'اختياري. سيتم إنشاء الأدوار الافتراضية تلقائيًا.',
    'signup.addRole': 'إضافة دور',
    'signup.roleName': 'اسم الدور',
    'signup.roleDescription': 'الوصف',
    'signup.remove': 'إزالة',
    'signup.noCustomRoles': 'لم يتم تعريف أدوار مخصصة. سيتم إنشاء موظف ومدير ومسؤول موارد بشرية.',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

const arabicOverrides: Partial<Record<TranslationKey, string>> = {
  'validation.email': 'أدخل عنوان بريد إلكتروني صالح.',
  'validation.passwordRequired': 'كلمة المرور مطلوبة.',
  'validation.passwordChecklist': 'يجب أن تتضمن كلمة المرور:',
  'validation.passwordLength': 'ثمانية أحرف على الأقل',
  'validation.passwordUppercase': 'حرفا كبيرا واحدا',
  'validation.passwordLowercase': 'حرفا صغيرا واحدا',
  'validation.passwordNumber': 'رقما واحدا',
  'validation.passwordSpecial': 'رمزا خاصا واحدا',
  'validation.confirmPassword': 'يجب أن تتطابق كلمتا المرور.',
  'validation.required': 'هذا الحقل مطلوب.',
  'validation.companyLocationRequired': 'يرجى استخدام موقعك أو إدخال الإحداثيات لكل موقع شركة قبل الإرسال.',
  'login.title': 'Stanza',
  'login.subtitle': 'مصادقة المؤسسات',
  'login.corporateId': 'البريد الإلكتروني',
  'login.biometricKey': 'كلمة المرور',
  'login.authenticating': 'جار تسجيل الدخول...',
  'login.accessGranted': 'تم تسجيل الدخول',
  'login.enterSector': 'تسجيل الدخول',
  'login.forgotPassword': 'هل نسيت كلمة المرور؟',
  'login.registerTenant': 'تسجيل شركة جديدة',
  'login.recoveryTitle': 'استعادة الوصول',
  'login.recoverySubtitle': 'اختر طريقة استعادة الوصول لهذا الحساب.',
  'login.recoveryClose': 'إغلاق',
  'login.recoveryEmailTitle': 'رابط إعادة تعيين عبر البريد',
  'login.recoveryEmailDescription': 'إنشاء رمز استعادة آمن لبريد الحساب.',
  'login.recoveryAdminTitle': 'إعادة تعيين بواسطة مسؤول الشركة',
  'login.recoveryAdminDescription': 'توجيه الاستعادة إلى مالك الشركة أو مسؤول الموارد البشرية.',
  'login.recoverySecurityTitle': 'تحقق أمني',
  'login.recoverySecurityDescription': 'استخدم التحقق الداخلي من الهوية قبل إعادة تعيين كلمة المرور.',
  'login.recoveryGenerating': 'جار إنشاء الاستعادة...',
  'login.recoveryStart': 'بدء الاستعادة',
  'login.passkeyOpening': 'جار فتح مفتاح المرور...',
  'login.passkeySignIn': 'تسجيل الدخول بمفتاح مرور',
  'login.passkeyDescription': 'استخدم Face ID أو البصمة أو Windows Hello أو رمز الجهاز أو مفتاح أمان.',
  'login.passkeyEmailRequired': 'أدخل بريدك الإلكتروني ثم استخدم تسجيل الدخول بمفتاح المرور.',
  'login.offline': 'أنت غير متصل. بعض إجراءات الموارد البشرية تتطلب اتصالا.',
  'login.offlineSignIn': 'يبدو أنك غير متصل. أعد الاتصال لتسجيل الدخول.',
  'login.apiUnavailable': 'تعذر الوصول إلى واجهة الموارد البشرية. تحقق من اتصال الخادم وحاول مرة أخرى.',
  'login.recoveryGeneric': 'إذا كان الحساب موجودا، فقد تم إرسال تعليمات إعادة تعيين كلمة المرور.',
  'login.recoveryStartError': 'تعذر بدء تدفق الاستعادة.',
  'login.recoveryServerError': 'انقطع الاتصال بالخادم. تعذر بدء تدفق الاستعادة.',
  'login.passkeyUnsupported': 'مفاتيح المرور غير مدعومة في هذا المتصفح.',
  'login.systemOperational': 'النظام يعمل • V2.4',
  'login.toggleTheme': 'تبديل الوضع الفاتح/الداكن',
  'login.recoveryEmail': 'بريد الاستعادة',
  'dash.elitePortal': 'مساحة العمل',
  'dash.auth': 'تم تسجيل الدخول',
  'dash.terminate': 'تسجيل الخروج',
  'dash.core': 'الأساسي:',
  'dash.geoOp': 'عمليات الموقع',
  'dash.roster': 'الجدول الأسبوعي',
  'dash.profile': 'الملف الشخصي',
  'dash.perimeter': 'التحقق من النطاق',
  'dash.hqSecure': 'حالة المقر: آمن',
  'dash.clockIn': 'تسجيل الحضور',
  'dash.clockOut': 'تسجيل الانصراف',
  'dash.locating': 'تحديد الموقع',
  'dash.verifying': 'التحقق',
  'dash.verified': 'تم التحقق',
  'dash.breach': 'خارج النطاق',
  'dash.sysMsg': 'النظام',
  'dash.awaitingInput': 'جاهز لتسجيل الحضور.',
  'dash.activeShift': 'المناوبة مفتوحة',
  'dash.offlineAction': 'أنت غير متصل. بعض إجراءات الموارد البشرية تتطلب اتصالا.',
  'dash.noActiveLocation': 'لا يوجد موقع شركة نشط لهذه المساحة.',
  'dash.locationUnavailable': 'خدمات الموقع غير متاحة في هذا المتصفح.',
  'dash.locationPermission': 'جار طلب إذن الموقع...',
  'dash.locationDenied': 'إذن الموقع مطلوب لتسجيل الحضور.',
  'dash.clockInSuccess': 'تم تسجيل الحضور بنجاح.',
  'dash.clockInError': 'تعذر تسجيل الحضور.',
  'dash.clockInTryAgain': 'تعذر تسجيل الحضور. يرجى المحاولة مرة أخرى.',
  'dash.outsideGeofence': 'أنت خارج نطاق موقع العمل المسموح.',
  'dash.outsideGeofenceLabel': 'خارج النطاق',
  'dash.openShiftConflict': 'لديك مناوبة نشطة بالفعل. سجل الانصراف قبل تسجيل الحضور مرة أخرى.',
  'dash.openShiftConflictLabel': 'المناوبة نشطة بالفعل',
  'dash.attendanceErrorLabel': 'خطأ في الحضور',
  'dash.clockOutSuccess': 'تم تسجيل الانصراف بنجاح.',
  'dash.clockOutError': 'تعذر تسجيل الانصراف. يرجى المحاولة مرة أخرى.',
  'dash.noActiveShift': 'لا توجد مناوبة نشطة.',
  'dash.clockingOut': 'جار تسجيل الانصراف...',
  'dash.serverDisconnected': 'انقطع الاتصال بالخادم. تعذر التحقق من الموقع.',
  'dash.secureLocationContext': 'إذن الموقع يتطلب localhost أو HTTPS. قد لا يعمل HTTP عبر عنوان شبكة محلية.',
  'dash.validatingGeofence': 'جار التحقق من النطاق الجغرافي...',
  'dash.locationAccuracy': 'دقة الموقع',
  'dash.approximateLocation': 'الموقع تقريبي.',
  'dash.lowAccuracyLocation': 'أعاد المتصفح موقعا منخفض الدقة. قد يكون تسجيل الحضور غير دقيق. استخدم GPS الهاتف لأفضل نتيجة.',
  'dash.rosterHub': 'الجدول الأسبوعي',
  'dash.weekView': 'عرض أسبوعي',
  'dash.applyLeave': 'طلب إجازة',
  'dash.dayDate': 'اليوم / التاريخ',
  'dash.shiftFrame': 'وقت المناوبة',
  'dash.locationRole': 'الموقع/الدور',
  'dash.status': 'الحالة',
  'dash.abstained': 'غير مجدول',
  'dash.scheduled': 'مجدول',
  'dash.advParams': 'حالة النظام',
  'dash.adminsOnline': 'المسؤولون المتصلون',
  'dash.companyFeed': 'منشورات الشركة',
  'dash.companyFeedSubtitle': 'إعلانات وفعاليات وتحديثات سياسات الشركة.',
  'dash.refresh': 'تحديث',
  'dash.sensitiveFilter': 'مرشح المحتوى الحساس',
  'dash.sensitiveFilterDescription': 'إخفاء الكلمات غير المناسبة في منشورات الشركة.',
  'dash.filterOn': 'مفعل',
  'dash.filterOff': 'معطل',
  'dash.requestBreak': 'طلب استراحة',
  'dash.breakStatus': 'حالة الاستراحة',
  'dash.breakApprovalQueue': 'قائمة موافقات الاستراحة',
  'dash.noBreakRequests': 'لا توجد طلبات استراحة بعد.',
  'dash.noPendingBreakRequests': 'لا توجد طلبات استراحة معلقة.',
  'dash.installStanza': 'تثبيت Stanza',
  'dash.notificationsReady': 'الإشعارات جاهزة',
  'profile.title': 'ملف الموظف',
  'profile.subtitle': 'سجل الموظف وسير العمل',
  'profile.leaveName': 'رصيد الإجازات',
  'profile.leaveDays': 'أيام',
  'profile.loan': 'حالة القرض النشط',
  'profile.payroll': 'تفاصيل الرواتب',
  'profile.grievance': 'تقديم شكوى',
  'signup.title': 'إعداد الشركة',
  'signup.subtitle': 'سجل مساحة عمل Stanza',
  'signup.step1': 'تفاصيل الشركة',
  'signup.step2': 'العمليات والمالية',
  'signup.step3': 'النطاق الجغرافي',
  'signup.companyName': 'الاسم القانوني للشركة',
  'signup.tenantSlug': 'معرف الشركة الفريد',
  'signup.adminFullName': 'الاسم الكامل للمسؤول',
  'signup.adminEmail': 'بريد المسؤول الإلكتروني',
  'signup.emailAlreadyRegistered': 'يوجد حساب مسجل بالفعل بهذا البريد الإلكتروني.',
  'signup.workspaceAlreadyExists': 'توجد مساحة عمل مسجلة بالفعل بهذا الاسم.',
  'signup.registerError': 'تعذر تسجيل مساحة العمل.',
  'signup.adminPass': 'كلمة مرور المسؤول',
  'signup.confirmPass': 'تأكيد كلمة المرور',
  'signup.currency': 'عملة التشغيل الأساسية',
  'signup.capacity': 'سعة الموظفين',
  'signup.loans': 'تفعيل سياسة قروض الشركة',
  'signup.geoLat': 'خط عرض المقر',
  'signup.geoLng': 'خط طول المقر',
  'signup.geoRadius': 'نصف قطر النطاق (متر)',
  'signup.complete': 'إنشاء مساحة العمل',
  'signup.back': 'رجوع',
  'signup.next': 'التالي',
  'signup.login': 'العودة إلى تسجيل الدخول',
  'signup.initialRole': 'دور الحساب الأول',
  'signup.initialRoleHelp': 'اختر دور أول حساب يتم إنشاؤه ضمن هذه الشركة.',
  'signup.enableLoansHelp': 'تفعيل الاستقطاعات من الرواتب وطلبات قروض الشركة القياسية.',
  'signup.customRoles': 'الأدوار المخصصة',
  'signup.customRolesHelp': 'اختياري. سيتم إنشاء الأدوار الافتراضية تلقائيا.',
  'signup.addRole': 'إضافة دور',
  'signup.roleName': 'اسم الدور',
  'signup.roleDescription': 'الوصف',
  'signup.remove': 'إزالة',
  'signup.noCustomRoles': 'لم يتم تعريف أدوار مخصصة. سيتم إنشاء موظف ومدير ومسؤول موارد بشرية.',
  'login.creatorCredit': 'تم الإنشاء بواسطة Shady Awad',
  'signup.locations': 'المواقع',
  'signup.locationsHelp': 'أضف كل موقع يسمح بتسجيل الحضور.',
  'signup.addLocation': 'إضافة موقع',
  'signup.unnamedLocation': 'موقع بدون اسم',
  'signup.coordinatesSet': 'تم تحديد الإحداثيات',
  'signup.primaryLocation': 'الموقع الأساسي',
  'signup.locationDetails': 'تفاصيل الموقع',
  'signup.locationDetailsHelp': 'سم الموقع قبل وضع الدبوس.',
  'signup.locationName': 'اسم الموقع',
  'signup.locationType': 'نوع الموقع',
  'signup.addressOptional': 'العنوان اختياري',
  'signup.addressPlaceholder': 'الشارع، المدينة، الدولة',
  'signup.removeLocation': 'إزالة الموقع',
  'signup.worksiteGeofence': 'نطاق موقع العمل',
  'signup.geofenceInstruction': 'اسحب الدبوس إلى مدخل المكتب أو مركز موقع العمل بدقة.',
  'signup.useMyLocation': 'استخدم موقعي',
  'signup.detecting': 'جار التحديد...',
  'signup.mapKeyMissing': 'مفتاح مزود الخريطة غير موجود',
  'signup.mapKeyMissingHelp': 'أضف VITE_MAPTILER_KEY.',
  'signup.mapLoading': 'جار تحميل خريطة MapLibre...',
  'signup.mapUnavailable': 'مزود الخريطة غير متاح',
  'signup.mapUnavailableHelp': 'تحقق من VITE_MAPTILER_KEY ثم أعد تشغيل خادم التطوير.',
  'signup.locationStatus': 'حالة الموقع',
  'signup.locationDetected': 'تم تحديد الموقع',
  'signup.approximateLocation': 'موقع تقريبي',
  'signup.lowAccuracyLocation': 'دقة الموقع منخفضة',
  'signup.manualAdjustment': 'تعديل يدوي',
  'signup.manualCoordinates': 'إحداثيات يدوية',
  'signup.approximateWarning': 'موقع المتصفح تقريبي فقط. يلزم ضبط يدوي.',
  'signup.useApproximateAnyway': 'استخدم الموقع التقريبي على أي حال',
  'signup.mapProviderNote': 'تسميات الخريطة مقدمة من MapTiler/OpenStreetMap وقد تختلف عن التسميات المحلية. استخدم عرض القمر الصناعي أو اسحب الدبوس لتأكيد موقع العمل بدقة.',
  'signup.latitude': 'خط العرض',
  'signup.longitude': 'خط الطول',
  'signup.notSelected': 'غير محدد',
  'signup.locationAccuracy': 'دقة الموقع',
  'signup.meters': 'متر',
  'signup.accuracyHelp': 'قد يكون موقع المتصفح تقريبيا. اسحب الدبوس لضبط موقع العمل.',
  'signup.geofenceRadius': 'نصف قطر النطاق',
  'signup.geofenceRadiusHelp': 'يتحكم في منطقة تسجيل الحضور المسموحة حول موقع العمل المحدد.',
  'signup.enterCoordinatesManually': 'إدخال الإحداثيات يدويا',
  'signup.hideManualCoordinates': 'إخفاء الإحداثيات اليدوية',
  'signup.howToGetCoordinates': 'كيفية الحصول على الإحداثيات',
  'signup.coordinateStepGoogleMaps': 'افتح Google Maps.',
  'signup.coordinateStepPress': 'اضغط مطولا أو انقر بزر الماوس الأيمن على موقع المكتب أو العمل بدقة.',
  'signup.coordinateStepCopy': 'انسخ رقمي خط العرض وخط الطول.',
  'signup.coordinateStepPaste': 'الصقهما في حقلي خط العرض وخط الطول.',
  'signup.coordinateStepConfirm': 'تأكد أن الدبوس انتقل إلى المكان الصحيح.',
  'signup.coordinateOrderHelp': 'يعرض Google Maps خط العرض أولا ثم خط الطول ثانيا.',
  'signup.radius': 'نصف القطر',
  'signup.radiusValidation': 'يجب أن يكون نصف القطر بين 25 و5000 متر.',
  'signup.latitudeValidation': 'يجب أن يكون خط العرض بين -90 و90.',
  'signup.longitudeValidation': 'يجب أن يكون خط الطول بين -180 و180.',
  'signup.locationTypeHeadquarters': 'المقر الرئيسي',
  'signup.locationTypeBranch': 'فرع',
  'signup.locationTypeWarehouse': 'مستودع',
  'signup.locationTypeRemote': 'موقع عمل بعيد',
  'signup.locationTypeOther': 'أخرى',
  'signup.mapStyleStreets': 'الشوارع',
  'signup.mapStyleSatellite': 'القمر الصناعي',
  'dash.enableNotifications': 'تفعيل الإشعارات',
  'dash.notifications': 'الإشعارات',
  'dash.loading': 'جار التحميل...',
  'dash.sending': 'جار الإرسال...',
  'dash.saving': 'جار الحفظ...',
  'dash.opening': 'جار الفتح...',
  'dash.pending': 'معلق',
  'dash.pendingApproval': 'بانتظار الموافقة',
  'dash.cancelRequest': 'إلغاء الطلب',
  'dash.approve': 'موافقة',
  'dash.reject': 'رفض',
  'dash.companyLocations': 'مواقع الشركة',
  'dash.clockInValidLocations': 'تسجيل الحضور صالح داخل أي موقع شركة نشط.',
  'dash.active': 'نشط',
  'dash.autoSaved': 'تم الحفظ تلقائيا',
  'dash.breakTime': 'وقت الاستراحة',
  'dash.loadingEditor': 'جار تحميل المحرر...',
  'dash.publishPost': 'نشر المنشور',
  'dash.saveDraft': 'حفظ كمسودة',
  'dash.loadingCompanyFeed': 'جار تحميل منشورات الشركة...',
  'dash.loadingPosts': 'جار تحميل المنشورات...',
  'dash.payrollSubtitleAdmin': 'سجلات رواتب الشركة وأدوات التشغيل.',
  'dash.payrollSubtitleFull': 'سجلات الرواتب والتعويضات والقروض والموافقات للشركة',
  'dash.payrollSubtitleSelf': 'سجلات راتبك الأخيرة.',
  'dash.runPayroll': 'تشغيل الرواتب',
  'dash.generatingPayroll': 'جار إنشاء الرواتب...',
  'dash.loadingPayroll': 'جار تحميل سجلات الرواتب...',
  'dash.noPayrollRecords': 'لا توجد سجلات رواتب بعد.',
  'dash.noPayrollAccess': 'لم يتم تعيين صلاحية الرواتب بعد.',
  'dash.grievances': 'الشكاوى',
  'dash.grievancesSubtitleLeave': 'أرسل تواريخ الإجازة وتفاصيلها من خلال سير الطلب الحالي.',
  'dash.grievancesSubtitleAdmin': 'قدم شكوى وأدر حالات الشركة.',
  'dash.grievancesSubtitleSelf': 'قدم شكاواك وتابع حالاتها.',
  'dash.submitLeaveRequest': 'إرسال طلب إجازة',
  'dash.submitGrievance': 'إرسال شكوى',
  'dash.submitting': 'جار الإرسال...',
  'dash.myGrievances': 'شكاواي',
  'dash.tenantGrievances': 'شكاوى الشركة',
  'dash.loadingMyGrievances': 'جار تحميل شكاواك...',
  'dash.loadingTenantGrievances': 'جار تحميل شكاوى الشركة...',
  'dash.passkeys': 'مفاتيح المرور',
  'dash.addPasskey': 'إضافة مفتاح مرور',
  'dash.loadingPasskeys': 'جار تحميل مفاتيح المرور...',
  'dash.actions': 'الإجراءات',
  'dash.controlCenterTitle': 'مركز تحكم Stanza',
  'dash.controlCenterSubtitle': 'وصول سريع إلى الإشعارات والمواقع وحالة مساحة العمل.',
  'dash.close': 'إغلاق',
  'dash.logout': 'تسجيل الخروج',
  'dash.company': 'الشركة',
  'dash.tenantId': 'معرف الشركة',
  'dash.show': 'إظهار',
  'dash.hide': 'إخفاء',
  'dash.copy': 'نسخ',
  'dash.copied': 'تم النسخ',
  'dash.hidden': 'مخفي',
  'dash.settings': 'الإعدادات',
  'dash.switchLight': 'التبديل إلى الوضع الفاتح',
  'dash.switchDark': 'التبديل إلى الوضع الداكن',
  'dash.appReadiness': 'جاهزية التطبيق',
  'dash.appReadinessSubtitle': 'حالة التثبيت والعمل دون اتصال والإشعارات لهذا الجهاز.',
  'dash.online': 'متصل',
  'dash.offline': 'غير متصل',
  'dash.appMode': 'وضع التطبيق',
  'dash.installedMode': 'مثبت',
  'dash.browserMode': 'وضع المتصفح',
  'dash.unsupported': 'غير مدعوم',
  'dash.permissionGranted': 'ممنوح',
  'dash.permissionDenied': 'مرفوض',
  'dash.permissionDefault': 'افتراضي',
  'dash.dismiss': 'إخفاء',
  'dash.iosInstallHint': 'على iOS افتح قائمة المشاركة ثم اختر إضافة إلى الشاشة الرئيسية لتثبيت Stanza.',
  'dash.notificationSettings': 'إعدادات الإشعارات',
  'dash.notificationSettingsSubtitle': 'اختر التحديثات التي يجب أن يعرضها Stanza لحسابك.',
  'dash.notificationDeliveryReady': 'تفضيلات البريد والإشعارات الفورية جاهزة، ويمكن ربط مزودي الإرسال لاحقا.',
  'dash.category': 'الفئة',
  'dash.quietHoursStart': 'بداية ساعات الهدوء',
  'dash.quietHoursEnd': 'نهاية ساعات الهدوء',
  'dash.saveSettings': 'حفظ الإعدادات',
  'dash.passkeyDescription': 'أضف تسجيل الدخول عبر Face ID أو البصمة أو Windows Hello أو رمز الجهاز أو مفتاح أمان. لا يخزن Stanza أي بيانات حيوية.',
  'dash.noPasskeys': 'لا توجد مفاتيح مرور مسجلة بعد.',
  'dash.passkeyDevice': 'مفتاح مرور',
  'dash.platform': 'النظام',
  'dash.lastUsed': 'آخر استخدام',
  'dash.added': 'أضيف',
  'dash.never': 'أبدا',
  'dash.locations': 'المواقع',
  'dash.noCompanyLocations': 'لا توجد مواقع شركة.',
  'dash.noActiveCompanyLocations': 'لا توجد مواقع شركة نشطة.',
  'dash.systemStatus': 'حالة النظام',
  'dash.ready': 'جاهز',
  'dash.locationsConfigured': 'المواقع المهيأة',
  'dash.currentShift': 'المناوبة الحالية',
  'dash.open': 'مفتوحة',
  'dash.notClockedIn': 'لم يتم تسجيل الحضور',
  'dash.lastAttendanceEvent': 'آخر حدث حضور',
  'dash.noActiveShiftRecorded': 'لا توجد مناوبة نشطة مسجلة.',
  'dash.breakRequestHelp': 'أرسل طلب استراحة قصير للموافقة من المدير.',
  'dash.custom': 'مخصص',
  'dash.breakDurationPlaceholder': '5-180 دقيقة',
  'dash.optionalReason': 'سبب اختياري',
  'dash.breakStatusHelp': 'آخر طلباتك الشخصية وقرارات المدير.',
  'dash.minutes': 'دقيقة',
  'dash.requested': 'تم الطلب',
  'dash.reviewNote': 'ملاحظة المراجعة',
  'dash.reviewPendingBreakRequests': 'راجع طلبات الاستراحة المعلقة للموظفين.',
  'dash.optionalReviewNote': 'ملاحظة مراجعة اختيارية',
  'dash.employee': 'الموظف',
  'dash.primary': 'أساسي',
  'dash.noBreak': 'لا توجد استراحة',
  'dash.leave': 'إجازة',
  'dash.officeHq': 'مقر المكتب',
  'dash.remote': 'عن بعد',
  'dash.annualLeave': 'إجازة سنوية',
  'dash.monday': 'الاثنين',
  'dash.tuesday': 'الثلاثاء',
  'dash.wednesday': 'الأربعاء',
  'dash.thursday': 'الخميس',
  'dash.friday': 'الجمعة',
  'dash.saturday': 'السبت',
  'dash.sunday': 'الأحد',
  'dash.postTitle': 'عنوان المنشور',
  'dash.writeAnnouncement': 'اكتب الإعلان...',
  'dash.everyone': 'الجميع',
  'dash.roleEmployee': 'الدور: موظف',
  'dash.roleManager': 'الدور: مدير',
  'dash.roleHrAdmin': 'الدور: مسؤول موارد بشرية',
  'dash.locationPrefix': 'الموقع',
  'dash.noCompanyAnnouncements': 'لا توجد إعلانات شركة بعد.',
  'dash.managePosts': 'إدارة المنشورات',
  'dash.noPostsToManage': 'لا توجد منشورات لإدارتها بعد.',
  'dash.eventTimeTbd': 'وقت الفعالية غير محدد',
  'dash.compensationProfiles': 'ملفات التعويض',
  'dash.compensationProfilesHelp': 'تحل الملفات المحفوظة محل الراتب الاحتياطي عند تشغيل الرواتب.',
  'dash.saveCompensation': 'حفظ التعويض',
  'dash.missingActiveCompensation': 'ملف تعويض نشط مفقود',
  'dash.noActiveCompensation': 'لا يوجد ملف تعويض نشط',
  'dash.noEmployeesForCompensation': 'لا يوجد موظفون لملفات التعويض.',
  'dash.payrollRunHelp': 'تستخدم الرواتب ملف التعويض النشط لكل موظف. الراتب الأساسي الاحتياطي اختياري، ويتم تضمين أقساط القروض النشطة تلقائيا في الاستقطاعات للسجلات الجديدة.',
  'dash.selectEmployee': 'اختر موظفا',
  'dash.baseAmount': 'المبلغ الأساسي',
  'dash.effective': 'ساري من',
  'dash.employeeLoans': 'قروض الموظفين',
  'dash.employeeLoansAdminHelp': 'أنشئ قروض الشركة وأدر حالة السداد.',
  'dash.employeeLoansSelfHelp': 'قروضك الحالية والسابقة.',
  'dash.loanName': 'اسم القرض',
  'dash.principal': 'الأصل',
  'dash.outstanding': 'المتبقي',
  'dash.repayment': 'السداد',
  'dash.due': 'الاستحقاق',
  'dash.notSet': 'غير محدد',
  'dash.createLoan': 'إنشاء قرض',
  'dash.creating': 'جار الإنشاء...',
  'dash.noEmployeeLoans': 'لا توجد قروض موظفين بعد.',
  'dash.loanDeductionsApplied': 'استقطاعات القروض المطبقة',
  'dash.skippedEmployees': 'الموظفون المتجاوزون',
  'dash.period': 'الفترة',
  'dash.base': 'الأساسي',
  'dash.bonus': 'المكافأة',
  'dash.deductions': 'الاستقطاعات',
  'dash.net': 'الصافي',
  'dash.export': 'تصدير',
  'dash.exportPdf': 'تصدير PDF',
  'dash.exporting': 'جار التصدير...',
  'dash.updating': 'جار التحديث...',
  'dash.final': 'نهائي',
  'dash.noAccess': 'لا توجد صلاحية',
  'dash.approvedAt': 'تمت الموافقة',
  'dash.paidAt': 'تم الدفع',
  'dash.cancelledAt': 'تم الإلغاء',
  'dash.back': 'رجوع',
  'dash.title': 'العنوان',
  'dash.categoryLabel': 'الفئة',
  'dash.description': 'الوصف',
  'dash.noGrievances': 'لا توجد شكاوى مقدمة بعد.',
  'dash.noTenantGrievances': 'لا توجد شكاوى للشركة بعد.',
  'dash.case': 'الحالة',
  'dash.priority': 'الأولوية',
  'dash.created': 'تاريخ الإنشاء',
  'dash.update': 'تحديث',
  'dash.rolesPermissions': 'الأدوار والصلاحيات',
  'dash.rolesPermissionsHelp': 'عناصر التحكم الأساسية لأدوار الشركة ومفاتيح الصلاحيات ومسميات الموظفين.',
  'dash.systemRole': 'دور نظام',
  'dash.customRole': 'دور مخصص',
  'dash.assigned': 'معين',
  'dash.noPermissions': 'لا توجد صلاحيات بعد.',
  'dash.employeeAssignments': 'تعيينات الموظفين',
  'dash.noCustomAssignments': 'لا توجد تعيينات مخصصة',
  'dash.assignRole': 'تعيين دور',
  'dash.saveTitle': 'حفظ المسمى',
  'dash.jobTitle': 'المسمى الوظيفي',
  'dash.createCustomRole': 'إنشاء دور مخصص',
  'dash.roleName': 'اسم الدور',
  'dash.noRolesYet': 'لا توجد أدوار مخصصة بعد.',
  'dash.createRole': 'إنشاء الدور',
  'dash.roleCreated': 'تم إنشاء الدور المخصص.',
  'dash.roleAssigned': 'تم تعيين الدور.',
  'dash.titleUpdated': 'تم تحديث المسمى الوظيفي.',
  'dash.roleLoadError': 'تعذر تحميل إدارة الأدوار.',
  'dash.roleCreateError': 'تعذر إنشاء الدور.',
  'dash.roleAssignError': 'تعذر تعيين الدور.',
  'dash.titleUpdateError': 'تعذر تحديث المسمى الوظيفي.',
  'dash.payPeriodStart': 'بداية فترة الراتب',
  'dash.payPeriodEnd': 'نهاية فترة الراتب',
  'dash.fallbackBaseSalary': 'راتب أساسي احتياطي',
  'dash.bonuses': 'المكافآت',
  'dash.profileLoanCleared': 'تمت التسوية',
  'dash.noActiveLiabilities': 'لا توجد التزامات نشطة',
  'dash.installedMessage': 'تم تثبيت Stanza.',
  'dash.installDismissedMessage': 'تم إغلاق مطالبة التثبيت. يمكنك تثبيت Stanza من قائمة المتصفح.',
  'dash.installStartedMessage': 'بدأ تثبيت Stanza.',
  'dash.installPromptError': 'تعذر فتح مطالبة التثبيت. استخدم قائمة التثبيت في المتصفح.',
  'dash.notificationUnsupportedMessage': 'الإشعارات غير مدعومة في هذا المتصفح.',
  'dash.notificationSecureContextMessage': 'أذونات الإشعارات تتطلب HTTPS أو localhost.',
  'dash.notificationReadyMessage': 'أذونات الإشعارات جاهزة. يتطلب إرسال الدفع إعداد الخادم.',
  'dash.notificationNotGrantedMessage': 'لم يتم منح إذن الإشعارات.',
  'dash.notificationRequestError': 'تعذر طلب إذن الإشعارات.',
  'dash.notificationLoadError': 'تعذر تحميل إعدادات الإشعارات.',
  'dash.notificationLoadServerError': 'انقطع الاتصال بالخادم. تعذر تحميل إعدادات الإشعارات.',
  'dash.notificationSaved': 'تم حفظ إعدادات الإشعارات.',
  'dash.notificationSaveError': 'تعذر حفظ إعدادات الإشعارات.',
  'dash.notificationSaveServerError': 'انقطع الاتصال بالخادم. تعذر حفظ إعدادات الإشعارات.',
  'dash.breakLoadError': 'تعذر تحميل طلبات الاستراحة.',
  'dash.breakPendingLoadError': 'تعذر تحميل طلبات الاستراحة المعلقة.',
  'dash.breakLoadServerError': 'انقطع الاتصال بالخادم. تعذر تحميل طلبات الاستراحة.',
  'dash.breakDurationError': 'اختر مدة استراحة بين 5 و180 دقيقة.',
  'dash.breakRequestError': 'تعذر طلب الاستراحة.',
  'dash.breakRequestSent': 'تم إرسال طلب الاستراحة للموافقة.',
  'dash.breakRequestServerError': 'انقطع الاتصال بالخادم. تعذر طلب الاستراحة.',
  'dash.breakCancelError': 'تعذر إلغاء طلب الاستراحة.',
  'dash.breakCancelled': 'تم إلغاء طلب الاستراحة.',
  'dash.breakCancelServerError': 'انقطع الاتصال بالخادم. تعذر إلغاء طلب الاستراحة.',
  'dash.breakReviewError': 'تعذر مراجعة طلب الاستراحة.',
  'dash.breakReviewServerError': 'انقطع الاتصال بالخادم. تعذر مراجعة طلب الاستراحة.',
  'dash.passkeyLoadError': 'تعذر تحميل مفاتيح المرور.',
  'dash.passkeyLoadServerError': 'انقطع الاتصال بالخادم. تعذر تحميل مفاتيح المرور.',
  'dash.passkeyUnsupported': 'مفاتيح المرور غير مدعومة في هذا المتصفح.',
  'dash.passkeyStartError': 'تعذر بدء تسجيل مفتاح المرور.',
  'dash.passkeySaveError': 'تعذر حفظ مفتاح المرور.',
  'dash.passkeyAdded': 'تمت إضافة مفتاح المرور. يمكنك الآن تسجيل الدخول بهذا الجهاز.',
  'dash.passkeyAddError': 'تعذر إضافة مفتاح المرور.',
  'dash.payrollLoadError': 'تعذر تحميل سجلات الرواتب.',
  'dash.payrollLoadServerError': 'انقطع الاتصال بالخادم. تعذر تحميل سجلات الرواتب.',
  'dash.compensationLoadError': 'تعذر تحميل ملفات التعويضات.',
  'dash.compensationLoadServerError': 'انقطع الاتصال بالخادم. تعذر تحميل ملفات التعويضات.',
  'dash.loanLoadError': 'تعذر تحميل قروض الموظفين.',
  'dash.loanLoadServerError': 'انقطع الاتصال بالخادم. تعذر تحميل قروض الموظفين.',
  'dash.compensationSaved': 'تم حفظ ملف التعويض.',
  'dash.compensationSaveError': 'تعذر حفظ ملف التعويض.',
  'dash.compensationSaveServerError': 'انقطع الاتصال بالخادم. تعذر حفظ ملف التعويض.',
  'dash.employeeLoanCreated': 'تم إنشاء قرض الموظف.',
  'dash.employeeLoanCreateError': 'تعذر إنشاء قرض الموظف.',
  'dash.employeeLoanCreateServerError': 'انقطع الاتصال بالخادم. تعذر إنشاء قرض الموظف.',
  'dash.loanStatusUpdated': 'تم تحديث حالة القرض.',
  'dash.loanStatusUpdateError': 'تعذر تحديث حالة القرض.',
  'dash.loanStatusUpdateServerError': 'انقطع الاتصال بالخادم. تعذر تحديث حالة القرض.',
  'dash.payrollStatusUpdateError': 'تعذر تحديث حالة الراتب.',
  'dash.payrollStatusUpdateServerError': 'انقطع الاتصال بالخادم. تعذر تحديث حالة الراتب.',
  'dash.payrollRunError': 'تعذر تشغيل الرواتب.',
  'dash.payrollRunServerError': 'انقطع الاتصال بالخادم. تعذر تشغيل الرواتب.',
  'dash.payrollPeriodError': 'اختر تاريخ نهاية للراتب بعد تاريخ البداية.',
  'dash.payrollStatusUpdated': 'تم تحديث حالة الراتب إلى',
  'dash.payrollRunComplete': 'اكتمل تشغيل الرواتب. السجلات التي تم إنشاؤها:',
  'dash.missingCompensationSkip': 'لا يوجد ملف تعويض نشط ولم يتم إدخال راتب أساسي احتياطي.',
  'dash.offlineActionMessage': 'أنت غير متصل. بعض إجراءات الموارد البشرية تتطلب اتصالا.',
  'dash.payrollExportError': 'تعذر تصدير ملف PDF للراتب.',
  'dash.grievanceLoadError': 'تعذر تحميل الشكاوى.',
  'dash.tenantGrievanceLoadError': 'تعذر تحميل شكاوى الشركة.',
  'dash.grievanceLoadServerError': 'انقطع الاتصال بالخادم. تعذر تحميل الشكاوى.',
  'dash.leaveRequestOpened': 'تم فتح نموذج طلب الإجازة. أضف التواريخ والتفاصيل ثم أرسل الطلب.',
  'dash.grievanceFiled': 'تم تقديم الشكوى بنجاح.',
  'dash.grievanceFileError': 'تعذر تقديم الشكوى.',
  'dash.grievanceFileServerError': 'انقطع الاتصال بالخادم. تعذر تقديم الشكوى.',
  'dash.grievanceStatusUpdated': 'تم تحديث حالة الشكوى.',
  'dash.grievanceStatusUpdateError': 'تعذر تحديث حالة الشكوى.',
  'dash.grievanceStatusUpdateServerError': 'انقطع الاتصال بالخادم. تعذر تحديث حالة الشكوى.',
  'dash.feedLoadError': 'تعذر تحميل موجز الشركة.',
  'dash.feedLoadServerError': 'انقطع الاتصال بالخادم. تعذر تحميل موجز الشركة.',
  'dash.postPublished': 'تم نشر المنشور.',
  'dash.draftSaved': 'تم حفظ المسودة.',
  'dash.feedSaveError': 'تعذر حفظ منشور الموجز.',
  'dash.feedSaveServerError': 'انقطع الاتصال بالخادم. تعذر حفظ منشور الموجز.',
  'dash.postStatusUpdated': 'تم تحديث حالة المنشور.',
  'dash.postStatusUpdateError': 'تعذر تحديث حالة المنشور.',
  'dash.postStatusUpdateServerError': 'انقطع الاتصال بالخادم. تعذر تحديث حالة المنشور.',
  'dash.locationsLoadError': 'تعذر تحميل المواقع.',
  'enum.employee': 'موظف',
  'enum.manager': 'مدير',
  'enum.hrAdmin': 'مسؤول موارد بشرية',
  'enum.pending': 'معلق',
  'enum.approved': 'تمت الموافقة',
  'enum.rejected': 'مرفوض',
  'enum.cancelled': 'ملغى',
  'enum.draft': 'مسودة',
  'enum.published': 'منشور',
  'enum.archived': 'مؤرشف',
  'enum.paid': 'مدفوع',
  'enum.open': 'مفتوح',
  'enum.underReview': 'قيد المراجعة',
  'enum.resolved': 'تم الحل',
  'enum.closed': 'مغلق',
  'enum.active': 'نشط',
  'enum.inactive': 'غير نشط',
  'enum.missing': 'مفقود',
  'enum.low': 'منخفضة',
  'enum.normal': 'عادية',
  'enum.high': 'عالية',
  'enum.urgent': 'عاجلة',
  'enum.general': 'عام',
  'enum.scheduling': 'الجدولة',
  'enum.leaveRequest': 'طلب إجازة',
  'enum.announcement': 'إعلان',
  'enum.event': 'فعالية',
  'enum.policyUpdate': 'تحديث سياسة',
  'enum.monthly': 'شهري',
  'enum.weekly': 'أسبوعي',
  'enum.hourly': 'بالساعة',
  'enum.annual': 'سنوي',
  'enum.oneTime': 'مرة واحدة',
  'enum.headquarters': 'المقر الرئيسي',
  'enum.branch': 'فرع',
  'enum.warehouse': 'مستودع',
  'enum.remoteSite': 'موقع بعيد',
  'enum.other': 'أخرى',
  'notification.inApp': 'داخل التطبيق',
  'notification.email': 'البريد',
  'notification.push': 'دفع',
  'notification.attendanceReminders': 'تذكيرات الحضور',
  'notification.attendanceRemindersDescription': 'تذكيرات تسجيل الحضور والانصراف ونطاق الحضور.',
  'notification.breakReminders': 'تذكيرات الاستراحة',
  'notification.breakRemindersDescription': 'تذكيرات بداية الاستراحة والعودة المجدولة.',
  'notification.breakRequestPending': 'قائمة موافقات الاستراحة',
  'notification.breakRequestPendingDescription': 'تنبيهات المدير والموارد البشرية لطلبات الاستراحة المعلقة.',
  'notification.breakRequestReviewed': 'تحديثات طلب الاستراحة',
  'notification.breakRequestReviewedDescription': 'تحديثات الموافقة والرفض لطلبات الاستراحة الخاصة بك.',
  'notification.leaveUpdates': 'تحديثات طلبات الإجازة',
  'notification.leaveUpdatesDescription': 'موافقات ورفض وتغييرات سير عمل الإجازات.',
  'notification.payrollUpdates': 'تحديثات الرواتب',
  'notification.payrollUpdatesDescription': 'تشغيل الرواتب والموافقات والمدفوعات وتوفر الكشوف.',
  'notification.loanUpdates': 'تحديثات القروض',
  'notification.loanUpdatesDescription': 'إنشاء قروض الموظفين والأرصدة وتحديثات الحالة.',
  'notification.grievanceUpdates': 'تحديثات الشكاوى',
  'notification.grievanceUpdatesDescription': 'تغييرات حالة الشكوى ونشاط المراجعة.',
  'notification.companyFeedPosts': 'منشورات الشركة',
  'notification.companyFeedPostsDescription': 'الإعلانات والفعاليات وتحديثات السياسات.',
  'notification.rolePermissionChanges': 'تغييرات الأدوار والصلاحيات',
  'notification.rolePermissionChangesDescription': 'تعيينات الأدوار المخصصة وتحديثات الصلاحيات.',
  'notification.systemAlerts': 'تنبيهات النظام',
  'notification.systemAlertsDescription': 'إشعارات مهمة للحساب ومساحة العمل والأمان.',
  'editor.bold': 'غامق',
  'editor.italic': 'مائل',
  'editor.underline': 'تحته خط',
  'editor.bulletedList': 'قائمة نقطية',
  'editor.numberedList': 'قائمة مرقمة',
  'editor.removeList': 'إزالة القائمة',
  'editor.textColor': 'لون النص',
  'editor.color': 'اللون',
  'editor.fontSize': 'حجم الخط',
  'editor.size': 'الحجم',
  'editor.insertEmoji': 'إدراج رمز تعبيري',
  'editor.emoji': 'رمز تعبيري',
  'editor.undo': 'تراجع',
  'editor.redo': 'إعادة',
  'editor.reset': 'إعادة ضبط',
  'editor.defaultColor': 'افتراضي',
  'editor.white': 'أبيض',
  'editor.mutedGray': 'رمادي هادئ',
  'editor.emerald': 'زمردي',
  'editor.lime': 'ليموني',
  'editor.teal': 'تركوازي',
  'editor.cyan': 'سماوي',
  'editor.blue': 'أزرق',
  'editor.purple': 'بنفسجي',
  'editor.pink': 'وردي',
  'editor.red': 'أحمر',
  'editor.orange': 'برتقالي',
  'editor.amber': 'كهرماني',
  'editor.yellow': 'أصفر',
  'editor.announcements': 'الإعلانات',
  'editor.calendarEvents': 'التقويم والفعاليات',
  'editor.workHr': 'العمل والموارد البشرية',
  'editor.positiveTeam': 'الإيجابية والفريق',
  'editor.status': 'الحالة',
  'editor.writeUpdate': 'اكتب تحديثا...',
  'dash.emailPushPreferences': 'تفضيلات البريد الإلكتروني والإشعارات الفورية',
  'dash.configured': 'مُعد',
  'dash.default': 'افتراضي',
  'dash.registered': 'مسجل',
  'dash.workspaceStatus': 'حالة مساحة العمل',
  'dash.passkeyNotConfigured': 'مفاتيح المرور غير مهيأة لهذه البيئة.',
  'dash.expand': 'توسيع',
  'dash.collapse': 'طي',
  'login.invalidCredentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
  'login.rateLimited': 'محاولات كثيرة جدا. يرجى المحاولة لاحقا.',
  'login.passkeyStartError': 'تعذر بدء تسجيل الدخول بمفتاح المرور.',
  'signup.emailUnavailable': 'لا يمكن استخدام هذا البريد الإلكتروني لمساحة عمل جديدة. جرّب تسجيل الدخول أو استرداد حسابك.',
  'signup.workspaceUnavailable': 'اسم مساحة العمل هذا غير متاح. جرّب اسما آخر.',
  'signup.rateLimited': 'محاولات كثيرة جدا. يرجى المحاولة لاحقا.',
  'privacy.link': 'سياسة الخصوصية',
  'privacy.title': 'سياسة الخصوصية',
  'privacy.close': 'إغلاق سياسة الخصوصية',
  'privacy.notLegalAdvice': 'توضح هذه السياسة تجربة Stanza التجريبية وليست استشارة قانونية.',
  'privacy.overview': 'نظرة عامة',
  'privacy.overviewText': 'Stanza تطبيق تجريبي ومحفظة أعمال لإدارة عمليات القوى العاملة، من إنشاء Shady Awad.',
  'privacy.data': 'المعلومات التي نتعامل معها',
  'privacy.dataText': 'قد يتعامل التطبيق مع معلومات الحساب والموظفين والحضور والرواتب والإجازات والشكاوى ومنشورات الشركة اللازمة لعرض الميزات.',
  'privacy.location': 'بيانات الموقع',
  'privacy.locationText': 'يُستخدم الموقع لميزات النطاق الجغرافي والحضور فقط عند اختيار إجراء يحتاج إليه. يمكنك رفض الإذن، لكن هذه الميزات قد لا تعمل.',
  'privacy.passkeys': 'مفاتيح المرور',
  'privacy.passkeysText': 'تستخدم مفاتيح المرور موثّق جهازك. لا يتلقى Stanza بيانات حيوية أو مفاتيح خاصة ولا يخزنها.',
  'privacy.demoData': 'بيانات تجريبية',
  'privacy.demoDataText': 'استخدم بيانات خيالية أو للاختبار في هذه التجربة. لا تُدخل بيانات موظفين أو رواتب حقيقية وحساسة.',
  'privacy.recovery': 'استرداد الحساب',
  'privacy.recoveryText': 'تُعرض ميزات الاسترداد عبر تدفق التطبيق وليست ضماناً لإرسال بريد إنتاجي أو للتحقق من الهوية.',
  'privacy.thirdParties': 'خدمات خارجية',
  'privacy.thirdPartiesText': 'تستخدم الخرائط بيانات MapTiler وOpenStreetMap، وقد تختلف تسمياتها وتغطيتها عن مزودي الخرائط المحليين.',
  'privacy.security': 'الأمان',
  'privacy.securityText': 'يطبق Stanza ضوابط أمان للتطبيق، لكن هذا العرض في محفظة الأعمال ليس نظام موارد بشرية إنتاجياً أو بديلاً عن برنامج خصوصية للشركة.',
  'privacy.contact': 'التواصل',
  'privacy.createdBy': 'من إنشاء',
  'demo.title': 'سياق تجريبي',
  'demo.body': 'أنت تستخدم تطبيق Stanza تجريبياً ضمن محفظة أعمال. استخدم بيانات خيالية فقط. قد تستخدم بعض الميزات سجلات نموذجية أو تدفقات محاكاة وليست خدمة موارد بشرية إنتاجية.',
  'demo.dismiss': 'فهمت',
  'demo.show': 'حول هذه التجربة',
  'demo.mapNoticeTitle': 'تنبيه عن بيانات الخريطة',
  'demo.mapNoticeBody': 'تستخدم الخرائط بيانات MapTiler وOpenStreetMap. قد تختلف التسميات والتغطية عن Google Maps أو مزودي الخرائط المحليين.',
  'demo.payroll': 'معلومات الرواتب في هذه البيئة للعرض والاختبار. استخدم بيانات خيالية فقط.',
  'demo.grievances': 'تجنب إدخال شكاوى موظفين حقيقية أو حساسة في هذه البيئة التجريبية.',
  'demo.feed': 'منشورات موجز الشركة جزء من مساحة العمل التجريبية. لا تنشر معلومات سرية عن الشركة.',
  'demo.passkeys': 'تستخدم مفاتيح المرور موثّق جهازك. لا يخزن Stanza بيانات حيوية أو مفاتيح خاصة.',
  'demo.notifications': 'تُعد إعدادات الإشعارات تفضيلاتك؛ ويتطلب التسليم الفوري خدمة إنتاجية مهيأة.',
  'demo.footer': 'مشروع تجريبي ضمن محفظة أعمال من Shady Awad. استخدم بيانات خيالية فقط.',
  'dash.previousWeek': 'الأسبوع السابق',
  'dash.nextWeek': 'الأسبوع التالي',
  'dash.thisWeek': 'هذا الأسبوع',
  'dash.viewRange': 'نطاق العرض',
  'dash.oneWeek': 'أسبوع واحد',
  'dash.twoWeeks': 'أسبوعان',
  'dash.fourWeeks': '4 أسابيع',
  'dash.customRange': 'نطاق مخصص',
  'dash.startDate': 'تاريخ البداية',
  'dash.endDate': 'تاريخ النهاية',
  'dash.rosterRangeTooLarge': 'نطاق التاريخ كبير جداً. اختر نطاقاً لا يتجاوز 31 يوماً.',
  'dash.noRosterEntries': 'لا توجد مناوبات في هذا النطاق.',
  'dash.resignations': 'طلبات الاستقالة',
  'dash.resignationsHelp': 'قدّم طلبات الاستقالة وتابع حالتها.',
  'dash.submitResignation': 'تقديم الاستقالة',
  'dash.lastWorkingDay': 'آخر يوم عمل',
  'dash.lastWorkingDayRequired': 'آخر يوم عمل مطلوب.',
  'dash.resignationType': 'نوع الاستقالة',
  'dash.voluntary': 'طوعية',
  'dash.personalReasons': 'أسباب شخصية',
  'dash.careerChange': 'تغيير مهني',
  'dash.withdraw': 'سحب',
  'dash.markProcessed': 'تحديد كمُعالج',
  'dash.myResignations': 'طلبات استقالتي',
  'dash.tenantResignations': 'طلبات الاستقالة',
  'dash.noResignationRequests': 'لا توجد طلبات استقالة بعد.',
  'dash.resignationSubmitted': 'تم تقديم طلب الاستقالة.',
  'dash.resignationApproved': 'تمت الموافقة على طلب الاستقالة.',
  'dash.resignationRejected': 'تم رفض طلب الاستقالة.',
  'dash.resignationWithdrawn': 'تم سحب طلب الاستقالة.',
  'dash.resignationProcessed': 'تمت معالجة طلب الاستقالة.',
  'dash.resignationLoadError': 'تعذر تحميل طلبات الاستقالة.',
  'dash.resignationSubmitError': 'تعذر تقديم طلب الاستقالة.',
  'dash.resignationUpdateError': 'تعذر تحديث طلب الاستقالة.',
  'login.useDemoAccount': 'استخدام حساب تجريبي',
  'login.hrAdminDemo': 'عرض مسؤول الموارد البشرية',
  'login.managerDemo': 'عرض المدير',
  'login.employeeDemo': 'عرض الموظف',
  'login.demoCredentialsNote': 'بيانات الاعتماد التجريبية مخصصة لاختبار محفظة الأعمال فقط.',
  'login.fillDemoCredentials': 'ملء بيانات الاعتماد التجريبية',
  'login.demoCompany': 'Stanza Demo Company',
};

type LanguageContextType = {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  isRtl: boolean;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function getInitialLanguage(): Language {
  if (typeof window === 'undefined') return 'en';

  const savedLanguage = window.localStorage.getItem('horizon-language');
  return savedLanguage === 'ar' || savedLanguage === 'en' ? savedLanguage : 'en';
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang === 'ar' ? 'ar-AE' : 'en-US';
    document.documentElement.classList.toggle('rtl', lang === 'ar');
    window.localStorage.setItem('horizon-language', lang);
  }, [lang]);

  const t = (key: TranslationKey) => {
    const value = lang === 'ar'
      ? arabicOverrides[key] || (translations.ar as Partial<Record<TranslationKey, string>>)[key] || translations.en[key]
      : translations.en[key];

    if (!value && import.meta.env.DEV) {
      console.warn('[i18n] missing key', key);
    }

    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRtl: lang === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
