import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'ar';

const translations = {
  en: {
    'validation.email': 'Enter a valid email address.',
    'validation.passwordRequired': 'Password is required.',
    'validation.passwordChecklist': 'Password must include:',
    'validation.passwordLength': 'At least 8 characters',
    'validation.passwordUppercase': 'One uppercase letter',
    'validation.passwordLowercase': 'One lowercase letter',
    'validation.passwordNumber': 'One number',
    'validation.passwordSpecial': 'One special character',
    'validation.confirmPassword': 'Passwords must match.',
    'validation.required': 'This field is required.',
    'validation.companyLocationRequired': 'Please use your location or enter coordinates for every company location before submitting.',

    'login.title': 'Stanza',
    'login.subtitle': 'Enterprise Authentication',
    'login.corporateId': 'Corporate ID',
    'login.biometricKey': 'Password',
    'login.authenticating': 'Authenticating...',
    'login.accessGranted': 'Access Granted',
    'login.enterSector': 'Log In',
    'login.forgotPassword': 'Forgot Password?',
    'login.registerTenant': 'Register New Company',
    'login.recoveryTitle': 'Recovery',
    'login.recoverySubtitle': 'Choose how this corporate account should recover access.',
    'login.recoveryClose': 'Close',
    'login.recoveryEmailTitle': 'Email reset link',
    'login.recoveryEmailDescription': 'Generate a secure recovery token for the account email.',
    'login.recoveryAdminTitle': 'Tenant admin reset',
    'login.recoveryAdminDescription': 'Route recovery through the company owner or HR administrator.',
    'login.recoverySecurityTitle': 'Security verification',
    'login.recoverySecurityDescription': 'Use internal identity verification before password reset.',
    'login.recoveryGenerating': 'Generating Recovery...',
    'login.recoveryStart': 'Start Recovery',
    'login.passkeyOpening': 'Opening passkey...',
    'login.passkeySignIn': 'Sign in with passkey',
    'login.passkeyDescription': 'Use Face ID, fingerprint, Windows Hello, device PIN, or a security key.',
    'login.passkeyEmailRequired': 'Enter your email, then use passkey sign in.',
    'login.offline': 'You are offline. Some HR actions require connection.',
    'login.offlineSignIn': 'You appear to be offline. Reconnect to sign in.',
    'login.apiUnavailable': 'Unable to reach the HR API. Check the backend connection and try again.',
    'login.recoveryGeneric': 'If an account exists, password reset instructions have been sent.',
    'login.systemOperational': 'System Operational • V2.4',
    'login.toggleTheme': 'Toggle Light/Dark Mode',
    'login.recoveryEmail': 'Recovery email',

    'dash.elitePortal': 'Workspace',
    'dash.auth': 'Signed in',
    'dash.terminate': 'Log Out',
    'dash.core': 'Core:',
    'dash.geoOp': 'Geo-Operations',
    'dash.roster': 'Weekly Roster',
    'dash.profile': 'Profile',
    'dash.perimeter': 'Perimeter Verification',
    'dash.hqSecure': 'HQ RADIAL STATUS: SECURE',
    'dash.clockIn': 'CLOCK IN',
    'dash.locating': 'LOCATING',
    'dash.verifying': 'VERIFYING',
    'dash.verified': 'VERIFIED',
    'dash.breach': 'BREACH',
    'dash.sysMsg': 'SYS',
    'dash.awaitingInput': 'Awaiting Biometric / Geo Input',
    'dash.rosterHub': 'Weekly Roster',
    'dash.weekView': 'Week View',
    'dash.applyLeave': 'Apply Leave',
    'dash.dayDate': 'Day / Date',
    'dash.shiftFrame': 'Shift Frame',
    'dash.locationRole': 'Location/Role',
    'dash.status': 'Status',
    'dash.abstained': 'UNSCHEDULED',
    'dash.scheduled': 'SCHEDULED',
    'dash.advParams': 'System Status',
    'dash.adminsOnline': 'Admins Online',
    'dash.companyFeed': 'Company Feed',
    'dash.companyFeedSubtitle': 'Announcements, events, and policy updates for your company.',
    'dash.refresh': 'Refresh',
    'dash.sensitiveFilter': 'Sensitive content filter',
    'dash.sensitiveFilterDescription': 'Blur non-friendly words in company feed content.',
    'dash.filterOn': 'Enabled',
    'dash.filterOff': 'Disabled',
    'dash.requestBreak': 'Request Break',
    'dash.breakStatus': 'Break Status',
    'dash.breakApprovalQueue': 'Break Approval Queue',
    'dash.noBreakRequests': 'No break requests yet.',
    'dash.noPendingBreakRequests': 'No pending break requests.',
    'dash.installStanza': 'Install Stanza',
    'dash.notificationsReady': 'Notifications Ready',

    'profile.title': 'Employee Profile',
    'profile.subtitle': 'Personnel Ledger & Workflows',
    'profile.leaveName': 'Leave Balance',
    'profile.leaveDays': 'Days',
    'profile.loan': 'Active Loan Status',
    'profile.payroll': 'Payroll Details',
    'profile.grievance': 'File Grievance',

    'signup.title': 'Corporate Onboarding',
    'signup.subtitle': 'Register your Stanza workspace',
    'signup.step1': 'Corporate Details',
    'signup.step2': 'Operations & Finance',
    'signup.step3': 'Geo-Perimeter',
    'signup.companyName': 'Company Legal Name',
    'signup.tenantSlug': 'Unique Tenant Slug',
    'signup.adminFullName': 'Admin Full Name',
    'signup.adminEmail': 'Admin Email',
    'signup.adminPass': 'Admin Password',
    'signup.confirmPass': 'Confirm Password',
    'signup.currency': 'Base Operating Currency',
    'signup.capacity': 'Employee Capacity',
    'signup.loans': 'Enable Corporate Loans Policy',
    'signup.geoLat': 'Headquarters Latitude',
    'signup.geoLng': 'Headquarters Longitude',
    'signup.geoRadius': 'Bounding Radius (meters)',
    'signup.complete': 'Create Workspace',
    'signup.back': 'Back',
    'signup.next': 'Next',
    'signup.login': 'Return to Login',
    'signup.initialRole': 'Initial Account Role',
    'signup.initialRoleHelp': 'Choose the role for the first account created under this tenant.',
    'signup.enableLoansHelp': 'Enable payroll deductions and standard corporate loan requests.',
    'signup.customRoles': 'Custom Roles',
    'signup.customRolesHelp': 'Optional. Defaults are created automatically.',
    'signup.addRole': 'Add Role',
    'signup.roleName': 'Role name',
    'signup.roleDescription': 'Description',
    'signup.remove': 'Remove',
    'signup.noCustomRoles': 'No custom roles defined. Employee, Manager, and HR Admin will be created.',
  },
  ar: {
    'validation.email': 'أدخل عنوان بريد إلكتروني صالح.',
    'validation.passwordRequired': 'كلمة المرور مطلوبة.',
    'validation.passwordChecklist': 'يجب أن تتضمن كلمة المرور:',
    'validation.passwordLength': 'ثمانية أحرف على الأقل',
    'validation.passwordUppercase': 'حرفًا كبيرًا واحدًا',
    'validation.passwordLowercase': 'حرفًا صغيرًا واحدًا',
    'validation.passwordNumber': 'رقمًا واحدًا',
    'validation.passwordSpecial': 'رمزًا خاصًا واحدًا',
    'validation.confirmPassword': 'يجب أن تتطابق كلمتا المرور.',
    'validation.required': 'هذا الحقل مطلوب.',
    'validation.companyLocationRequired': 'يرجى استخدام موقعك أو إدخال الإحداثيات لكل موقع شركة قبل الإرسال.',

    'login.title': 'Stanza',
    'login.subtitle': 'مصادقة المؤسسات',
    'login.corporateId': 'البريد الإلكتروني',
    'login.biometricKey': 'كلمة المرور',
    'login.authenticating': 'جارٍ تسجيل الدخول...',
    'login.accessGranted': 'تم تسجيل الدخول',
    'login.enterSector': 'تسجيل الدخول',
    'login.forgotPassword': 'هل نسيت كلمة المرور؟',
    'login.registerTenant': 'تسجيل شركة جديدة',
    'login.recoveryTitle': 'استعادة الوصول',
    'login.recoverySubtitle': 'اختر طريقة استعادة الوصول لهذا الحساب.',
    'login.recoveryClose': 'إغلاق',
    'login.recoveryEmailTitle': 'رابط إعادة تعيين عبر البريد',
    'login.recoveryEmailDescription': 'إنشاء رمز استعادة آمن لبريد الحساب.',
    'login.recoveryAdminTitle': 'إعادة تعيين بواسطة مسؤول الشركة',
    'login.recoveryAdminDescription': 'توجيه الاستعادة إلى مالك الشركة أو مسؤول الموارد البشرية.',
    'login.recoverySecurityTitle': 'تحقق أمني',
    'login.recoverySecurityDescription': 'استخدم التحقق الداخلي من الهوية قبل إعادة تعيين كلمة المرور.',
    'login.recoveryGenerating': 'جارٍ إنشاء الاستعادة...',
    'login.recoveryStart': 'بدء الاستعادة',
    'login.passkeyOpening': 'جارٍ فتح مفتاح المرور...',
    'login.passkeySignIn': 'تسجيل الدخول بمفتاح مرور',
    'login.passkeyDescription': 'استخدم Face ID أو البصمة أو Windows Hello أو رمز الجهاز أو مفتاح أمان.',
    'login.passkeyEmailRequired': 'أدخل بريدك الإلكتروني ثم استخدم تسجيل الدخول بمفتاح المرور.',
    'login.offline': 'أنت غير متصل. بعض إجراءات الموارد البشرية تتطلب اتصالًا.',
    'login.offlineSignIn': 'يبدو أنك غير متصل. أعد الاتصال لتسجيل الدخول.',
    'login.apiUnavailable': 'تعذر الوصول إلى واجهة الموارد البشرية. تحقق من اتصال الخادم وحاول مرة أخرى.',
    'login.recoveryGeneric': 'إذا كان الحساب موجودًا، فقد تم إرسال تعليمات إعادة تعيين كلمة المرور.',
    'login.systemOperational': 'النظام يعمل • V2.4',
    'login.toggleTheme': 'تبديل الوضع الفاتح/الداكن',
    'login.recoveryEmail': 'بريد الاستعادة',

    'dash.elitePortal': 'مساحة العمل',
    'dash.auth': 'تم تسجيل الدخول',
    'dash.terminate': 'تسجيل الخروج',
    'dash.core': 'الأساسي:',
    'dash.geoOp': 'عمليات الموقع',
    'dash.roster': 'الجدول الأسبوعي',
    'dash.profile': 'الملف الشخصي',
    'dash.perimeter': 'التحقق من النطاق',
    'dash.hqSecure': 'حالة المقر: آمن',
    'dash.clockIn': 'تسجيل الحضور',
    'dash.locating': 'تحديد الموقع',
    'dash.verifying': 'التحقق',
    'dash.verified': 'تم التحقق',
    'dash.breach': 'خارج النطاق',
    'dash.sysMsg': 'النظام',
    'dash.awaitingInput': 'بانتظار الموقع أو الإدخال',
    'dash.rosterHub': 'الجدول الأسبوعي',
    'dash.weekView': 'عرض أسبوعي',
    'dash.applyLeave': 'طلب إجازة',
    'dash.dayDate': 'اليوم / التاريخ',
    'dash.shiftFrame': 'وقت المناوبة',
    'dash.locationRole': 'الموقع/الدور',
    'dash.status': 'الحالة',
    'dash.abstained': 'غير مجدول',
    'dash.scheduled': 'مجدول',
    'dash.advParams': 'حالة النظام',
    'dash.adminsOnline': 'المسؤولون المتصلون',
    'dash.companyFeed': 'منشورات الشركة',
    'dash.companyFeedSubtitle': 'إعلانات وفعاليات وتحديثات سياسات الشركة.',
    'dash.refresh': 'تحديث',
    'dash.sensitiveFilter': 'مرشح المحتوى الحساس',
    'dash.sensitiveFilterDescription': 'إخفاء الكلمات غير المناسبة في منشورات الشركة.',
    'dash.filterOn': 'مفعل',
    'dash.filterOff': 'معطل',
    'dash.requestBreak': 'طلب استراحة',
    'dash.breakStatus': 'حالة الاستراحة',
    'dash.breakApprovalQueue': 'قائمة موافقات الاستراحة',
    'dash.noBreakRequests': 'لا توجد طلبات استراحة بعد.',
    'dash.noPendingBreakRequests': 'لا توجد طلبات استراحة معلقة.',
    'dash.installStanza': 'تثبيت Stanza',
    'dash.notificationsReady': 'الإشعارات جاهزة',

    'profile.title': 'ملف الموظف',
    'profile.subtitle': 'سجل الموظف وسير العمل',
    'profile.leaveName': 'رصيد الإجازات',
    'profile.leaveDays': 'أيام',
    'profile.loan': 'حالة القرض النشط',
    'profile.payroll': 'تفاصيل الرواتب',
    'profile.grievance': 'تقديم شكوى',

    'signup.title': 'إعداد الشركة',
    'signup.subtitle': 'سجل مساحة عمل Stanza',
    'signup.step1': 'تفاصيل الشركة',
    'signup.step2': 'العمليات والمالية',
    'signup.step3': 'النطاق الجغرافي',
    'signup.companyName': 'الاسم القانوني للشركة',
    'signup.tenantSlug': 'معرف الشركة الفريد',
    'signup.adminFullName': 'الاسم الكامل للمسؤول',
    'signup.adminEmail': 'بريد المسؤول الإلكتروني',
    'signup.adminPass': 'كلمة مرور المسؤول',
    'signup.confirmPass': 'تأكيد كلمة المرور',
    'signup.currency': 'عملة التشغيل الأساسية',
    'signup.capacity': 'سعة الموظفين',
    'signup.loans': 'تفعيل سياسة قروض الشركة',
    'signup.geoLat': 'خط عرض المقر',
    'signup.geoLng': 'خط طول المقر',
    'signup.geoRadius': 'نصف قطر النطاق (متر)',
    'signup.complete': 'إنشاء مساحة العمل',
    'signup.back': 'رجوع',
    'signup.next': 'التالي',
    'signup.login': 'العودة إلى تسجيل الدخول',
    'signup.initialRole': 'دور الحساب الأول',
    'signup.initialRoleHelp': 'اختر دور أول حساب يتم إنشاؤه ضمن هذه الشركة.',
    'signup.enableLoansHelp': 'تفعيل الاستقطاعات من الرواتب وطلبات قروض الشركة القياسية.',
    'signup.customRoles': 'الأدوار المخصصة',
    'signup.customRolesHelp': 'اختياري. سيتم إنشاء الأدوار الافتراضية تلقائيًا.',
    'signup.addRole': 'إضافة دور',
    'signup.roleName': 'اسم الدور',
    'signup.roleDescription': 'الوصف',
    'signup.remove': 'إزالة',
    'signup.noCustomRoles': 'لم يتم تعريف أدوار مخصصة. سيتم إنشاء موظف ومدير ومسؤول موارد بشرية.',
  },
} as const;

type TranslationKey = keyof typeof translations.en;

type LanguageContextType = {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  isRtl: boolean;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function getInitialLanguage(): Language {
  if (typeof window === 'undefined') return 'en';

  const savedLanguage = window.localStorage.getItem('horizon-language');
  return savedLanguage === 'ar' || savedLanguage === 'en' ? savedLanguage : 'en';
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang === 'ar' ? 'ar-AE' : 'en-US';
    window.localStorage.setItem('horizon-language', lang);
  }, [lang]);

  const t = (key: TranslationKey) => translations[lang][key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRtl: lang === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
