// Each destination below already exists in Dashboard's command registry. No action submits a form.
export const ADDITIONAL_INTENTS = [
 ['tomorrow_shift','roster:schedule','Open the existing roster to inspect tomorrow shifts.',[],'tomorrow shift|شيفت بكره'],
 ['next_shift','roster:schedule','Open the roster to inspect the next scheduled shift.',[],'next shift|المناوبه القادمه'],
 ['current_shift','roster:schedule','Open the roster to inspect the current shift.',[],'current shift|شيفتي الحالي'],
 ['shift_end_time','roster:schedule','Open the roster to inspect scheduled shift end time.',[],'shift end time|نهايه الشيفت'],
 ['clock_out_help','router:clock-out','Show the existing clock control; never clock out automatically.',['attendance.clock'],'clock out help|ازاي اسجل انصراف'],
 ['break_status','router:attendance','Open attendance and break records; no break is started.',['attendance.clock'],'break status|حاله الاستراحه'],
 ['pending_leave_requests','roster:leave','Open personal leave requests to inspect pending status.',['leave.view.self','leave.create'],'pending leave requests|اجازات قيد الانتظار'],
 ['approved_leave','roster:leave','Open personal leave to inspect approved requests.',['leave.view.self','leave.create'],'approved leave|اجازات معتمده'],
 ['leave_history','roster:leave','Open the existing personal leave request history.',['leave.view.self','leave.create'],'leave history|تاريخ الاجازات'],
 ['latest_payslip','router:payslips','Open actual payroll statements; latest payment comes from payroll records.',['payroll.view_self'],'latest payslip|اخر قسيمه راتب'],
 ['next_payday','router:payslips','Open payroll; next pay date is not stored authoritatively, never estimate it.',['payroll.view_self'],'next payday|payday|ميعاد المرتب القادم'],
 ['compensation_summary','router:payslips','Open existing payroll and compensation details.',['payroll.view_self'],'compensation summary|ملخص التعويضات'],
 ['active_loans','router:payslips','Open payroll where existing loan details can be inspected.',['payroll.view_self'],'active loans|قروض نشطه'],
 ['pending_expenses','expenses:claims','Open personal expense claims to inspect pending statuses.',['expenses.submit.self'],'pending expenses|مصروفات معلقه'],
 ['expense_history','expenses:claims','Open existing personal expense claim history.',['expenses.submit.self'],'expense history|سجل المصروفات'],
 ['reimbursement_status','expenses:claims','Open personal claims and recorded reimbursement status.',['expenses.submit.self'],'reimbursement status|حاله سداد المصروفات'],
 ['my_tasks','router:goals','Open existing assigned roster tasks.',['roster.goals.view_self'],'assigned tasks|مهام مسنده'],
 ['overdue_tasks','router:goals','Open roster goals to inspect due dates and outstanding tasks.',['roster.goals.view_self'],'overdue tasks|مهام متاخره'],
 ['submit_grievance','router:submit-grievance','Open existing grievance submission form; never submit.',['grievances.create'],'new grievance|شكوي جديده'],
 ['grievance_status','navigation:grievances','Open personal grievance records and status.',['grievances.view_own','grievances.create'],'grievance status|حاله شكواي'],
 ['grievance_history','navigation:grievances','Open personal grievance history.',['grievances.view_own','grievances.create'],'grievance history|تاريخ الشكاوي'],
 ['tomorrow_meetings','router:meetings','Open existing meetings with recorded dates; never fabricate tomorrow appointments.',['communications.meetings.view'],'tomorrow meetings|اجتماعات بكره'],
 ['upcoming_meetings','router:meetings','Open existing upcoming meetings.',['communications.meetings.view'],'upcoming meetings|اجتماعات قادمه'],
 ['candidates_by_stage','hiring:applicants','Open existing authorized applicant pipeline and stage filters.',['hiring.view'],'candidates by stage|متقدمين حسب المرحله'],
 ['my_manager','navigation:profile','Open own profile to inspect stored reporting manager.',[],'my manager|مديري'],
 ['my_department','navigation:profile','Open own profile to inspect stored department.',[],'my department|قسمي'],
 ['my_team','navigation:profile','Open own profile to inspect stored team.',[],'my team|فريقي'],
 ['employee_profile','navigation:profile','Open personal employee profile.',[],'employee profile|ملفي الشخصي'],
 ['organisation','organisation:hierarchy','Open authorized organisation hierarchy.',['organisation.view'],'organisation hierarchy|هيكل المؤسسه'],
 ['digital_id','profile:digital-id','Open own existing digital employee badge.',[],'digital employee id|بطاقه الموظف'],
 ['help_center','router:help','Open existing Help Center.',[],'help center|مركز المساعده'],
 ['appearance_settings','settings:appearance','Open existing Appearance and Theme Studio controls; never change preferences automatically.',[],'appearance|theme|themes|change theme|customise appearance|cursor|change cursor|change my cursor|pointer effects|dark mode|light mode|شكل البرنامج|الثيم|المؤشر|dark mode عايز'],
 ['font_settings','settings:font','Open existing personalisation font-size controls; never change preferences automatically.',[],'font|fonts|change font|text size|make text bigger|غير الخط|كبر الخط|حجم الخط'],
 ['live_employees','navigation:liveEmployees','Open authorized Live Employees and summarize actual clocked-in records.',['attendance.view_live'],'live employees|active employees|الموظفين الموجودين دلوقتي|مين عامل clock in'],
 ['settings','settings:open','Open existing personal settings.',[],'personal settings|language|language settings|اعداداتي|اللغة'],
] as const;
