import {useState,useEffect,useCallback,useRef} from 'react';
import {apiFetch} from '../../lib/api';
import {useLanguage} from '../../lib/LanguageContext';
import {Surface} from '../ui/Surface';
import {Select,Textarea} from '../ui/FormControls';
import {INTENTS} from '../../lib/intelligent-router';
type Caps={tenant:string[];platform:string[]};
type Example={id:string;phrase:string;intent:string;scope?:string;source?:string;classification?:string;analysis?:{nearest?:{example_text:string;intent_key:string;similarity:number}[];coverage?:number};review_state?:string;state?:string;approval_state?:string;created_at?:string;hit_count?:number;last_hit?:string;private_only?:boolean;entity_template?:{placeholders:{type:string}[]};model?:string;revision?:string;dimensions?:number;shared_state?:string;privacyMode?:string;generalization_method?:string};
type Overview={counts:Record<string,string|number>;privacyMode?:string;metrics?:{requests:number;layerPercentages:Record<string,number>;outcomePercentages:Record<string,number>;llmFallbackPercent:number;learnedSemanticHits:number;learnedHitRate:number;promotions:number};timings?:{kind:string;p50_ms:number|null;p95_ms:number|null;sample_count?:number}[];intents?:{intent_key:string;requests:string;fallbacks:string;ambiguities:string;learned_hits:string}[];coverage?:{intent_key:string;examples:number}[];health?:{id:string;intent_key:string;hits:string}[];growth?:{day:string;added:string}[];windowDays?:number;pendingShared?:number;model?:{provider:string;model:string;revision:string;dimensions:number};strategy?:string;thresholds?:{score:number;margin:number}};
export default function SemanticIntelligencePanel({platform=false}:{platform?:boolean}){
 const {lang}=useLanguage(),ar=lang==='ar',tr=(en:string,arabic:string)=>ar?arabic:en;
 const [caps,setCaps]=useState<Caps|null>(null),[section,setSection]=useState(''),[days,setDays]=useState(30),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [overview,setOverview]=useState<Overview|null>(null),[items,setItems]=useState<Example[]>([]),[tenants,setTenants]=useState<{id:string;name:string;lastActivity:string|null;privacyMode:string;counts:Record<string,string>;metrics:Overview['metrics'];timings:Overview['timings'];growth:Overview['growth'];intents:Overview['intents']}[]>([]);
 const [mode,setMode]=useState('PRIVATE'),[confirmMode,setConfirmMode]=useState(false),[confirmation,setConfirmation]=useState<{path:string;body:Record<string,unknown>;label:string}|null>(null),[edit,setEdit]=useState<Example|null>(null),[editText,setEditText]=useState(''),[editIntent,setEditIntent]=useState(''),[history,setHistory]=useState<{action:string;created_at:string}[]>([]);
 const [inspectedTenant,setInspectedTenant]=useState('');
 const generation=useRef(0);
 const root='/api/semantic-intelligence';
 const request=useCallback(async(path:string,body?:Record<string,unknown>)=>{const response=await apiFetch(root+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const result=await response.json();if(!response.ok)throw Error(result.code??'SEMANTIC_UNAVAILABLE');return result;},[]);
 useEffect(()=>{let alive=true;void request('/capabilities').then(c=>{if(alive){setCaps(c);setSection(platform?(c.platform.includes('view_all')?'overview':c.platform.includes('review_global')?'review':'tenants'):(c.tenant.includes('view_analytics')?'overview':c.tenant.includes('review_candidates')?'review':c.tenant.includes('manage_examples')?'examples':'privacy'));}}).catch(()=>{if(alive)setError('SEMANTIC_UNAVAILABLE');});return()=>{alive=false;};},[request,platform]);
 const load=useCallback(async()=>{
  if(!section)return;const version=++generation.current;setBusy(true);setError('');setInspectedTenant('');setOverview(null);setItems([]);setTenants([]);
  try{const prefix=platform?'/platform':'';let path=section==='overview'?'/overview':section==='review'?platform?'/shared-review':'/candidates':section==='examples'?'/examples':section==='privacy'?'/privacy':section==='tenants'?'/tenants':section==='history'?'/history':'/corpus';
   const data=await request(prefix+path+`?days=${days}&page=${page}&scope=${section==='shared'?'SHARED':'SYSTEM'}`);
   if(version!==generation.current)return;
   if(section==='overview')setOverview(data);else if(section==='privacy'){setMode(data.mode);setConfirmMode(false);}else if(section==='tenants')setTenants(data.tenants);else if(section==='history')setHistory(data.history);else setItems(data.candidates??data.examples??[]);
  }catch(e){if(version===generation.current)setError(e instanceof Error?e.message:'SEMANTIC_UNAVAILABLE');}finally{if(version===generation.current)setBusy(false);}
 },[section,platform,days,page,request]);
 useEffect(()=>{void load();return()=>{generation.current++;};},[load]);
 const mutate=async(path:string,body:Record<string,unknown>)=>{setBusy(true);setError('');setNotice('');try{await request(path,body);setNotice(tr('Change saved.','تم حفظ التغيير.'));setEdit(null);setConfirmation(null);await load();}catch(e){setError(e instanceof Error?e.message:'SEMANTIC_UNAVAILABLE');}finally{setBusy(false);}};
 const capability=(key:string)=>Boolean((platform?caps?.platform:caps?.tenant)?.includes(key));
 const sections=platform?[['overview','Global overview','نظرة عامة عالمية','view_all'],['tenants','Tenants & analytics','الشركات والتحليلات','view_tenants'],['review','Shared review','مراجعة التعلم المشترك','review_global'],['system','System corpus','أمثلة النظام','view_all'],['shared','Shared corpus','الأمثلة المشتركة','view_all']]:[['overview','Overview & analytics','نظرة عامة وتحليلات','view_analytics'],['review','Review & conflicts','المراجعة والتعارضات','review_candidates'],['examples','Approved examples','الأمثلة المعتمدة','manage_examples'],['privacy','Privacy settings','إعدادات الخصوصية','manage_privacy'],['history','Review history','سجل المراجعة','view_analytics']];
 const button='stanza-interactive-control rounded-lg border border-[var(--stanza-border-default)] px-3 py-2 text-sm hover:bg-[var(--stanza-hover-surface)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--stanza-focus-ring)] disabled:opacity-50';
 const explanations={SHARED:tr("Use Stanza’s shared semantic library and allow explicitly submitted, reviewed, sanitized language patterns from this company to be considered for shared learning.",'استخدام مكتبة ستانزا المشتركة والسماح بالنظر في مشاركة أنماط لغوية منقحة بعد إرسالها صراحة ومراجعتها.'),PRIVATE:tr("Use Stanza’s shared semantic library, but keep this company’s learned examples private.",'استخدام مكتبة ستانزا المشتركة مع الاحتفاظ بأمثلة الشركة المكتسبة خاصة.'),STRICT_PRIVATE:tr("Use only Stanza’s built-in system corpus plus this company’s private learned examples.",'استخدام أمثلة النظام الأساسية وأمثلة الشركة الخاصة فقط.')};
 const errorText:Record<string,string>={SEMANTIC_FORBIDDEN:tr('You do not have authority for this section.','ليس لديك صلاحية لهذا القسم.'),PRIVATE_ONLY:tr('This example was marked private-only. Review that decision before contribution.','هذا المثال محدد كخاص فقط. راجع القرار قبل المساهمة.'),PRIVATE_MODE:tr('Contribution is disabled by the company privacy mode or the source example is inactive.','المساهمة غير متاحة وفق وضع الخصوصية أو المثال الأصلي غير نشط.'),SENSITIVE:tr('Safe generalization is uncertain. Keep this text private.','التنقيح الآمن غير مؤكد. احتفظ بهذا النص خاصًا.'),DUPLICATE:tr('This example is redundant. Inspect the nearest examples or dismiss it.','هذا المثال مكرر. راجع الأمثلة القريبة أو استبعده.'),CONFLICT_REVIEW_REQUIRED:tr('Another intent matches this phrase. Inspect the conflict and correct the intent before approval.','توجد نية أخرى تطابق العبارة. راجع التعارض وصحح النية قبل الاعتماد.')};
 const classLabel=(v:string)=>({approved:tr('Approved','معتمد'),pending:tr('Pending','معلق'),rejected:tr('Rejected','مرفوض'),disabled:tr('Inactive','غير نشط'),safe_new:tr('New coverage','تغطية جديدة'),exact_duplicate:tr('Exact duplicate','تكرار مطابق'),near_duplicate:tr('Near duplicate','تكرار قريب'),cross_intent_conflict:tr('Intent conflict','تعارض النية'),sensitive:tr('Sensitive — keep private','حساس — يبقى خاصًا'),needs_review:tr('Needs review','بحاجة للمراجعة')}[v]??v);
 const metricLabels:Record<string,string>={pending_shared:tr('Pending shared candidates','مرشحات مشتركة معلقة'),private_examples:tr('Private examples','أمثلة خاصة'),approved_examples:tr('Active approved examples','أمثلة معتمدة نشطة'),pending_candidates:tr('Pending candidates','مرشحات معلقة'),rejected_candidates:tr('Rejected candidates','مرشحات مرفوضة'),duplicate_count:tr('Duplicates','تكرارات'),conflict_count:tr('Conflicts','تعارضات'),shared_promotions:tr('Shared promotions in period','ترقيات مشتركة في الفترة'),SYSTEM:tr('System examples','أمثلة النظام'),SHARED:tr('Shared examples','أمثلة مشتركة')};
 return <div className="min-w-0 space-y-4 text-[var(--text-primary)]" dir={ar?'rtl':'ltr'}>
  <header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">{platform?tr('Platform Semantic Intelligence','الذكاء الدلالي للمنصة'):tr('Semantic Intelligence','الذكاء الدلالي')}</h2><p className="text-sm text-[var(--stanza-text-secondary)]">{platform?tr('Operator-authorized corpus oversight. Private data stays tenant-scoped.','إشراف مصرح به من المشغل. تظل البيانات الخاصة ضمن الشركة.'):tr('Review learned language patterns and control company privacy.','مراجعة الأنماط اللغوية المكتسبة والتحكم في خصوصية الشركة.')}</p></div><button className={button} disabled={busy} onClick={()=>void load()}>{tr('Refresh','تحديث')}</button></header>
  <nav aria-label={tr('Semantic intelligence sections','أقسام الذكاء الدلالي')} className="flex flex-wrap gap-2">{sections.filter(s=>capability(s[3])).map(([key,en,arabic])=><button key={key} aria-current={section===key?'page':undefined} data-selected={section===key} className={button} onClick={()=>{setSection(key);setPage(1);setNotice('');setConfirmation(null);setEdit(null);}}>{tr(en,arabic)}</button>)}</nav>
  <label className="flex flex-wrap items-center gap-2 text-sm">{tr('Analytics window','فترة التحليلات')}<Select value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90].map(d=><option key={d} value={d}>{d} {tr('days','يوم')}</option>)}</Select></label>
  <p aria-live="polite" className="text-sm">{busy?tr('Loading…','جار التحميل…'):notice}</p>{error&&<p role="alert" className="rounded-lg border p-3">{errorText[error]??tr('Unable to complete this request. Refresh and try again.','تعذر إكمال الطلب. حدّث الصفحة وحاول مجددًا.')}</p>}
  {inspectedTenant&&<h3 className="text-lg font-medium">{tr('Tenant overview','نظرة عامة للشركة')}: {inspectedTenant}</h3>}
  {overview&&<>
   <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(Array.isArray(overview.counts)?Object.fromEntries((overview.counts as unknown as {scope:string;count:string}[]).map(r=>[r.scope,r.count])):overview.counts??{}).map(([key,value])=><Surface key={key} className="rounded-xl border p-4"><p className="text-sm text-[var(--stanza-text-secondary)]">{metricLabels[key]??key.replaceAll('_',' ')}</p><p className="text-xl font-semibold">{value}</p></Surface>)}</div>
   {overview.metrics&&<Surface className="rounded-xl border p-4 space-y-3"><h3 className="font-semibold">{tr('Measured routing distribution','توزيع التوجيه المقاس')}</h3><p>{overview.metrics.requests} {tr('requests in selected period','طلب في الفترة المحددة')}</p><div className="grid gap-2 sm:grid-cols-2">{Object.entries({...overview.metrics.layerPercentages,...overview.metrics.outcomePercentages}).map(([k,v])=><p key={k}>{k}: {v.toFixed(1)}%</p>)}</div><p>{tr('LLM fallback','الرجوع للنموذج')}: {overview.metrics.llmFallbackPercent.toFixed(1)}%</p><p>{tr('Learned-example semantic hits','تطابقات أمثلة مكتسبة')}: {overview.metrics.learnedSemanticHits}</p><p className="text-sm text-[var(--stanza-text-muted)]">{tr('A semantic hit avoided escalation on that request; whether an LLM would otherwise succeed is not measured. No financial savings are estimated.','التطابق الدلالي تجنب التصعيد لهذا الطلب؛ لا نقيس نجاح النموذج البديل ولا نقدّر وفورات مالية.')}</p></Surface>}
   <Surface className="rounded-xl border p-4 space-y-2"><h3 className="font-semibold">{tr('Model & performance','النموذج والأداء')}</h3><p>{tr('Exact pgvector search; score .84 / margin .10. ANN remains disabled.','بحث pgvector دقيق؛ درجة .84 وهامش .10. الفهارس التقريبية معطلة.')}</p>{overview.model&&<p className="break-all text-sm">{overview.model.provider} · {overview.model.model} · {overview.model.revision} · {overview.model.dimensions}D</p>}{(overview.timings??[]).map((r,i)=><p key={i}>{r.kind} — p50 {r.p50_ms==null?'—':Number(r.p50_ms).toFixed(1)}ms / p95 {r.p95_ms==null?'—':Number(r.p95_ms).toFixed(1)}ms</p>)}{overview.timings?.some(r=>r.kind==='search'&&Number(r.p95_ms)>100)&&<p>{tr('ANN benchmarking recommended if corpus growth persists; indexes remain unchanged. Advisory threshold: measured search p95 above 100ms.','يُقترح قياس الفهارس التقريبية إذا استمر نمو الأمثلة؛ لا تتغير الفهارس. الحد الإرشادي: p95 للبحث المقاس أعلى من ١٠٠ مللي ثانية.')}</p>}{!overview.timings?.length&&!overview.model&&<p>{tr('No timing samples in this period.','لا توجد عينات زمنية في الفترة.')}</p>}</Surface>
   <Surface className="rounded-xl border p-4 space-y-2"><h3 className="font-semibold">{tr('Corpus health — advisory','صحة الأمثلة — إرشادية')}</h3>{overview.health?.map(r=><p key={r.id} className="break-words">{r.intent_key} · {r.hits} {tr('hits; older than 30 days','تطابق؛ أقدم من ٣٠ يومًا')}</p>)}{!overview.health?.length&&<p>{platform?tr('Inspect tenant health through the audited tenant overview. Nothing is deleted automatically.','افحص صحة أمثلة الشركة عبر النظرة العامة المسجلة. لا تُحذف أمثلة تلقائيًا.'):tr('No low-hit aging examples found in this tenant. Nothing is deleted automatically.','لا توجد أمثلة قديمة قليلة الاستخدام في هذه الشركة. لا تُحذف أمثلة تلقائيًا.')}</p>}{overview.coverage?.filter(r=>Number(r.examples)<3).map(r=><p key={r.intent_key}>{r.intent_key} · {r.examples} {tr('examples — coverage review suggested','أمثلة — يُقترح مراجعة التغطية')}</p>)}{overview.intents?.map(r=><p key={r.intent_key}>{r.intent_key}: {r.requests} {tr('requests','طلبات')} · {r.fallbacks} {tr('fallbacks','تصعيدات')} · {r.ambiguities??0} {tr('ambiguous','غامضة')}</p>)}{overview.growth?.map(r=><p key={r.day}>{new Date(r.day).toLocaleDateString(ar?'ar':'en')} · +{r.added} {tr('examples','أمثلة')}</p>)}</Surface>
  </>}
  {section==='privacy'&&capability('manage_privacy')&&<Surface className="rounded-xl border p-4 space-y-4"><label className="block font-medium">{tr('Company learning mode','وضع تعلم الشركة')}<Select className="mt-2 w-full" value={mode} onChange={e=>{setMode(e.target.value);setConfirmMode(false);}}>{Object.keys(explanations).map(m=><option key={m} value={m}>{m==='SHARED'?tr('Shared Learning','التعلم المشترك'):m==='PRIVATE'?tr('Private Learning','التعلم الخاص'):tr('Strict Private Learning','التعلم الخاص الصارم')}</option>)}</Select></label><p>{explanations[mode as keyof typeof explanations]}</p><p className="text-sm">{tr('Changing to Shared never publishes old examples. Each contribution still requires explicit submission and platform review. Leaving Shared immediately blocks pending contributions from approval.','التحويل إلى المشترك لا ينشر أمثلة قديمة. كل مساهمة تحتاج إرسالًا صريحًا ومراجعة المنصة. مغادرة المشترك تمنع اعتماد المساهمات المعلقة فورًا.')}</p><label className="flex items-start gap-2"><input type="checkbox" checked={confirmMode} onChange={e=>setConfirmMode(e.target.checked)}/>{tr('I understand and confirm this privacy change.','أفهم وأؤكد تغيير الخصوصية.')}</label><button className={button} disabled={busy||!confirmMode} onClick={()=>void mutate('/privacy',{mode,confirm:true})}>{tr('Save privacy mode','حفظ وضع الخصوصية')}</button></Surface>}
  {items.map(item=><Surface key={item.id} className="rounded-xl border p-4 space-y-3 min-w-0"><p className="font-medium break-words">{item.phrase}</p><p className="text-sm break-words">{item.intent} · {item.scope??item.source??item.generalization_method??''} · {item.created_at?new Date(item.created_at).toLocaleDateString(ar?'ar':'en'):''}</p><p className="text-sm">{classLabel(item.review_state??item.state??item.approval_state??'pending')} · {classLabel(item.classification??'needs_review')}</p>{item.privacyMode&&<p>{tr('Source privacy mode','وضع خصوصية المصدر')}: {item.privacyMode} · {tr('Deterministic sanitization passed at submission; rechecked before approval.','اجتاز التنقيح الحتمي عند الإرسال؛ يُعاد التحقق قبل الاعتماد.')}</p>}{item.entity_template&&<p className="text-sm">{tr('Typed placeholders','حقول بديلة ذات نوع')}: {item.entity_template.placeholders.map(p=>p.type).join(', ')}</p>}{item.hit_count!==undefined&&<p>{tr('Hits','تطابقات')}: {item.hit_count} · {tr('Last hit','آخر تطابق')}: {item.last_hit?new Date(item.last_hit).toLocaleString(ar?'ar':'en'):'—'}</p>}{item.model&&<p className="break-all text-xs">{item.model} · {item.revision} · {item.dimensions}D</p>}
   {(item.analysis?.nearest?.length??0)>0&&<details><summary className="cursor-pointer focus-visible:outline-2">{tr('Inspect duplicates & conflicts','فحص التكرارات والتعارضات')}</summary><ul className="space-y-2 pt-2">{item.analysis.nearest.map((n,i)=><li key={i} className="break-words text-sm">{n.example_text} · {n.intent_key} · {Number(n.similarity).toFixed(3)}</li>)}</ul><p>{tr('Coverage novelty','جِدّة التغطية')}: {item.analysis.coverage?.toFixed(3)??'—'}</p></details>}
   <div className="flex flex-wrap gap-2">{section==='review'&&(item.review_state==='pending'||item.state==='pending')&&<>
    {<button className={button} disabled={busy} onClick={async()=>{setBusy(true);try{await request(platform?`/platform/shared-review/${item.id}/analyze`:`/candidates/${item.id}/analyze`,{});await load();}catch(e){setError(e instanceof Error?e.message:'SEMANTIC_UNAVAILABLE');}finally{setBusy(false);}}}>{tr('Analyze','تحليل')}</button>}
    <button className={button} disabled={busy||(platform&&!capability('manage_global'))} onClick={()=>setConfirmation({path:platform?`/platform/shared-review/${item.id}`:`/candidates/${item.id}/review`,body:{decision:'approve',confirm:true},label:tr('Approve this reviewed example?','اعتماد هذا المثال بعد المراجعة؟')})}>{tr('Approve','اعتماد')}</button>
    {['reject',platform?'duplicate':'dismiss_duplicate'].map(decision=><button key={decision} className={button} disabled={busy} onClick={()=>void mutate(platform?`/platform/shared-review/${item.id}`:`/candidates/${item.id}/review`,{decision})}>{decision==='reject'?tr('Reject','رفض'):tr('Dismiss duplicate','استبعاد التكرار')}</button>)}
    <button className={button} disabled={busy} onClick={()=>{setEdit(item);setEditText(item.phrase);setEditIntent(item.intent);}}>{platform?tr('Edit text / intent','تعديل العبارة أو النية'):tr('Change intent','تغيير النية')}</button>
    <button className={button} disabled={busy} onClick={()=>void mutate(platform?`/platform/shared-review/${item.id}`:`/candidates/${item.id}/review`,platform?{decision:'sensitive'}:{decision:'private_only',privateOnly:!item.private_only})}>{platform?tr('Mark sensitive','تحديد كحساس'):item.private_only?tr('Allow reviewed contribution','السماح بالمساهمة بعد المراجعة'):tr('Keep private only','الاحتفاظ خاصًا فقط')}</button>
   </>}{section==='examples'&&<><button className={button} disabled={busy} onClick={()=>setConfirmation({path:`/examples/${item.id}/action`,body:{action:item.approval_state==='approved'?'deactivate':'reactivate',confirm:true},label:tr('Change this private example’s active state?','تغيير حالة هذا المثال الخاص؟')})}>{item.approval_state==='approved'?tr('Deactivate','تعطيل'):tr('Reactivate','إعادة تفعيل')}</button><button className={button} disabled={busy} onClick={()=>setConfirmation({path:`/examples/${item.id}/action`,body:{action:'delete',confirm:true},label:tr('Delete this private example? Review history remains.','حذف المثال الخاص؟ سيبقى سجل المراجعة.')})}>{tr('Delete','حذف')}</button><button className={button} disabled={busy||item.approval_state!=='approved'||Boolean(item.shared_state)} onClick={()=>setConfirmation({path:`/examples/${item.id}/contribute`,body:{confirm:true},label:tr('Submit a sanitized copy for platform review? The original stays private.','إرسال نسخة منقحة لمراجعة المنصة؟ يبقى الأصل خاصًا.')})}>{tr('Submit for shared review','إرسال للمراجعة المشتركة')}</button></>}{['system','shared'].includes(section)&&capability('manage_global')&&<button className={button} disabled={busy} onClick={()=>setConfirmation({path:`/platform/corpus/${item.id}`,body:{action:item.approval_state==='approved'?'deactivate':'reactivate',confirm:true},label:tr('Change this global example’s active state? This affects all consuming tenants.','تغيير حالة المثال العالمي؟ يؤثر ذلك على الشركات المستهلكة.')})}>{item.approval_state==='approved'?tr('Deactivate','تعطيل'):tr('Reactivate','إعادة تفعيل')}</button>}</div>
  </Surface>)}
  {edit&&<Surface className="rounded-xl border p-4 space-y-3"><h3 className="font-medium">{tr('Review proposed change','مراجعة التغيير المقترح')}</h3>{platform&&<label className="block">{tr('Generalized phrase','العبارة المنقحة')}<Textarea className="w-full" value={editText} maxLength={500} onChange={e=>setEditText(e.target.value)}/></label>}<label className="block">{tr('Intent','النية')}<Select className="w-full" value={editIntent} onChange={e=>setEditIntent(e.target.value)}>{INTENTS.map(i=><option key={i.key} value={i.key}>{i.key}</option>)}</Select></label><button className={button} disabled={busy} onClick={()=>void mutate(platform?`/platform/shared-review/${edit.id}`:`/candidates/${edit.id}/review`,platform?{decision:'edit',text:editText,intent:editIntent}:{decision:'change_intent',intent:editIntent})}>{tr('Save proposed change','حفظ التغيير المقترح')}</button><button className={button} onClick={()=>setEdit(null)}>{tr('Cancel','إلغاء')}</button></Surface>}
  {confirmation&&<Surface className="rounded-xl border p-4 space-y-3" role="group" aria-label={tr('Confirm semantic change','تأكيد التغيير الدلالي')}><p>{confirmation.label}</p><button className={button} disabled={busy} onClick={()=>void mutate(confirmation.path,confirmation.body)}>{tr('Confirm','تأكيد')}</button><button className={button} disabled={busy} onClick={()=>setConfirmation(null)}>{tr('Cancel','إلغاء')}</button></Surface>}
  {tenants.map(tenant=><Surface key={tenant.id} className="rounded-xl border p-4 space-y-2"><h3 className="font-semibold break-words">{tenant.name}</h3><p>{tenant.privacyMode} · {tenant.counts.private_examples} {tr('private examples','أمثلة خاصة')} · {tenant.counts.pending_candidates} {tr('pending','معلقة')}</p><p>{tr('Semantic','دلالي')}: {tenant.metrics?.layerPercentages.semantic.toFixed(1)}% · {tr('LLM fallback','تصعيد للنموذج')}: {tenant.metrics?.llmFallbackPercent.toFixed(1)}%</p><p>{tr('Ambiguous','غامض')}: {tenant.metrics?.outcomePercentages.ambiguous.toFixed(1)}% · {tr('No match','بدون تطابق')}: {tenant.metrics?.outcomePercentages.no_match.toFixed(1)}% · {tr('Shared contributions','مساهمات مشتركة')}: {tenant.counts.shared_promotions}</p><p>{tr('Last routing activity','آخر نشاط توجيه')}: {tenant.lastActivity?new Date(tenant.lastActivity).toLocaleDateString(ar?'ar':'en'):'—'}</p><button className={button} disabled={busy} onClick={async()=>{setBusy(true);try{const data=await request(`/platform/tenants/${tenant.id}?days=${days}`);setOverview(data);setItems(data.examples);setTenants([]);setInspectedTenant(tenant.name);}catch(e){setError(e instanceof Error?e.message:'SEMANTIC_UNAVAILABLE');}finally{setBusy(false);}}}>{tr('Inspect tenant (audited)','فحص الشركة (مسجل)')}</button></Surface>)}
  {section==='history'&&history.map((h,i)=><p key={i} className="text-sm">{h.action.replaceAll('_',' ')} · {new Date(h.created_at).toLocaleString(ar?'ar':'en')}</p>)}
  {['review','examples','system','shared','tenants','history'].includes(section)&&<div className="flex flex-wrap gap-3"><button className={button} disabled={busy||page===1} onClick={()=>setPage(p=>p-1)}>{tr('Previous','السابق')}</button><span>{tr('Page','صفحة')} {page}</span><button className={button} disabled={busy||(section==='tenants'?tenants.length:section==='history'?history.length:items.length)<(section==='history'?50:25)} onClick={()=>setPage(p=>p+1)}>{tr('Next','التالي')}</button>{!busy&&!items.length&&!tenants.length&&section!=='history'&&<p>{tr('No records on this page.','لا توجد سجلات في هذه الصفحة.')}</p>}</div>}
 </div>;
}
