import { FormEvent, useCallback, useEffect, useRef, useState } from 'react';
import { Building2, Network, RefreshCw, UsersRound } from 'lucide-react';
import { apiFetch } from '../../lib/api';
import { useLanguage } from '../../lib/LanguageContext';
import { RolesPermissionsPanel } from './RolesPermissionsPanel';

type Overview = { employeeCount: number; departments: number; teams: number; unassignedEmployees: number };
type Department = { id: string; name: string; description: string | null; parentDepartmentId: string | null; departmentHeadId: string | null; departmentHeadName: string | null; isActive: boolean };
type Team = { id: string; name: string; description: string | null; departmentId: string | null; teamLeadId: string | null; locationId: string | null; memberCount: number; isActive: boolean };
type JobTitle = { id: string; name: string; description: string | null; level: number | null; isActive: boolean };
type Employee = { id: string; fullName: string; email: string; isActive: boolean; departmentId?: string | null; department?: string | null; teamId?: string | null; team?: string | null; jobTitleId?: string | null; jobTitle?: string | null; managerId?: string | null; managerName?: string | null };
type Location = { id: string; name: string; is_active: boolean };
type TeamMember = { id: string; employeeId: string; fullName: string; email: string; jobTitle: string | null; department: string | null; departmentId?: string | null; teamName: string | null; isActive: boolean; membershipType: string; startsAt: string };

function PlacementFields({ employee, departments, teams, jobTitles, inputClass, t }: { employee: Employee; departments: Department[]; teams: Team[]; jobTitles: JobTitle[]; inputClass: string; t: (key: string) => string }) {
  const [departmentId, setDepartmentId] = useState(employee.departmentId || '');
  const [teamId, setTeamId] = useState(employee.teamId || '');
  const [teamCleared, setTeamCleared] = useState(false);
  const compatibleTeams = teams.filter(team => team.isActive && (team.departmentId || '') === departmentId);

  return <>
    <label className="mt-3 block text-sm font-medium">{t('organisation.department')}<select name="departmentId" value={departmentId} onChange={event => { const nextDepartmentId = event.target.value; setDepartmentId(nextDepartmentId); const incompatible = Boolean(teamId && !teams.some(team => team.id === teamId && (team.departmentId || '') === nextDepartmentId)); setTeamCleared(incompatible); if (incompatible) setTeamId(''); }} className={inputClass}><option value="">{t('organisation.none')}</option>{departments.filter(department => department.isActive).map(department => <option key={department.id} value={department.id}>{department.name}</option>)}</select></label>
    <label className="mt-3 block text-sm font-medium">{t('organisation.teams')}<select name="teamId" value={teamId} onChange={event => { setTeamId(event.target.value); setTeamCleared(false); }} className={inputClass}><option value="">{t('organisation.none')}</option>{compatibleTeams.map(team => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label>
    {teamCleared && <p className="mt-2 text-xs text-amber-700 dark:text-amber-200">{t('organisation.teamCleared')}</p>}
    <label className="mt-3 block text-sm font-medium">{t('organisation.jobTitle')}<select name="jobTitleId" defaultValue={employee.jobTitleId || ''} className={inputClass}><option value="">{t('organisation.none')}</option>{jobTitles.filter(jobTitle => jobTitle.isActive).map(jobTitle => <option key={jobTitle.id} value={jobTitle.id}>{jobTitle.name}</option>)}</select></label>
  </>;
}

function ReportingLineFields({ employee, managers, inputClass, t }: { employee: Employee; managers: Employee[]; inputClass: string; t: (key: string) => string }) {
  const [managerId, setManagerId] = useState(employee.managerId || '');
  const manager = managers.find(candidate => candidate.id === managerId);

  return <>
    <label className="mt-3 block text-sm font-medium">{t('organisation.manager')}<select name="managerId" value={managerId} onChange={event => setManagerId(event.target.value)} className={inputClass}><option value="">{t('organisation.none')}</option>{managers.filter(candidate => candidate.id !== employee.id).map(candidate => <option key={candidate.id} value={candidate.id}>{candidate.fullName} ({candidate.email})</option>)}</select></label>
    {manager && <div className="mt-3 rounded border border-emerald-500/15 bg-emerald-500/5 p-3 text-xs text-neutral-600 dark:text-emerald-100/65"><p className="font-medium text-neutral-900 dark:text-emerald-50">{manager.fullName}</p><p>{manager.jobTitle || t('organisation.none')}</p><p>{manager.department || t('organisation.none')} · {manager.team || t('organisation.none')}</p></div>}
    <label className="mt-4 flex items-start gap-2 text-sm"><input required name="confirmManagerChange" type="checkbox" className="mt-1 accent-emerald-500" />{t('organisation.confirmManagerChange')}</label>
  </>;
}

function TeamMembershipFields({ team, activePeople, teams, inputClass, t, onChanged }: { team: Team; activePeople: Employee[]; teams: Team[]; inputClass: string; t: (key: string) => string; onChanged: () => Promise<void> }) {
  const [members, setMembers] = useState<TeamMember[]>([]);
  const [memberIds, setMemberIds] = useState<string[]>([]);
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [addEmployeeId, setAddEmployeeId] = useState('');
  const [moveMember, setMoveMember] = useState<TeamMember | null>(null);
  const [moveTargetId, setMoveTargetId] = useState('');
  const [moveConfirmed, setMoveConfirmed] = useState(false);

  const loadMembers = useCallback(async () => {
    setLoading(true); setError('');
    try {
      const [pageResponse, allResponse] = await Promise.all([
        apiFetch(`/api/hr/organisation/teams/${team.id}/members?page=${page}&pageSize=25&search=${encodeURIComponent(search)}`),
        apiFetch(`/api/hr/organisation/teams/${team.id}/members?page=1&pageSize=100`),
      ]);
      const [pageBody, allBody] = await Promise.all([pageResponse.json(), allResponse.json()]);
      if (!pageResponse.ok || !allResponse.ok) throw new Error(pageBody.error || allBody.error || t('organisation.loadError'));
      setMembers(pageBody.members || []); setTotal(pageBody.total || 0); setMemberIds((allBody.members || []).map((member: TeamMember) => member.employeeId));
    } catch (cause) { setError(cause instanceof Error ? cause.message : t('organisation.loadError')); } finally { setLoading(false); }
  }, [page, search, t, team.id]);

  useEffect(() => { void loadMembers(); }, [loadMembers]);
  const mutate = async (path: string, options: RequestInit) => { setPending(true); setError(''); setSuccess(''); try { const response = await apiFetch(path, options); const body = await response.json(); if (!response.ok) throw new Error(body.error || t('organisation.saveError')); setSuccess(t('organisation.membersSaved')); setAddEmployeeId(''); setMoveMember(null); setMoveTargetId(''); setMoveConfirmed(false); await Promise.all([loadMembers(), onChanged()]); } catch (cause) { setError(cause instanceof Error ? cause.message : t('organisation.saveError')); } finally { setPending(false); } };
  const availableEmployees = activePeople.filter(employee => !memberIds.includes(employee.id));
  const moveDepartmentId = activePeople.find(employee => employee.id === moveMember?.employeeId)?.departmentId;
  const moveTargets = teams.filter(candidate => candidate.isActive && candidate.id !== team.id && (!moveDepartmentId || !candidate.departmentId || candidate.departmentId === moveDepartmentId));

  return <div className="mt-3 space-y-3">
    {error && <p role="alert" className="rounded border border-red-400/30 bg-red-500/10 p-2 text-sm text-red-700">{error}</p>}
    {success && <p role="status" className="rounded border border-emerald-500/30 bg-emerald-500/10 p-2 text-sm text-emerald-800 dark:text-emerald-100">{success}</p>}
    <div className="rounded border border-emerald-500/15 p-3"><label className="block text-sm font-medium">{t('organisation.addMember')}<select value={addEmployeeId} onChange={event => setAddEmployeeId(event.target.value)} disabled={pending} className={inputClass}><option value="">{t('organisation.none')}</option>{availableEmployees.map(employee => <option key={employee.id} value={employee.id}>{employee.fullName} ({employee.email})</option>)}</select></label><button type="button" disabled={!addEmployeeId || pending} onClick={() => void mutate(`/api/hr/organisation/teams/${team.id}/members`, { method: 'POST', body: JSON.stringify({ employeeId: addEmployeeId }) })} className="mt-2 rounded bg-emerald-500 px-3 py-2 text-xs font-bold text-black disabled:opacity-50">{t('organisation.addMember')}</button></div>
    <label className="block text-sm font-medium">{t('organisation.searchPeople')}<input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} className={inputClass} /></label>
    {loading ? <p className="text-sm text-neutral-500">{t('organisation.loading')}</p> : members.length ? members.map(member => <article key={member.id} className="rounded border border-emerald-500/15 p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="font-medium text-neutral-900 dark:text-emerald-50">{member.fullName}</p><p className="truncate text-xs text-neutral-500 dark:text-emerald-100/55">{member.jobTitle || t('organisation.none')} · {member.department || t('organisation.none')} · {member.teamName || team.name}</p><p className="mt-1 text-xs text-neutral-500 dark:text-emerald-100/55">{member.membershipType} · {member.isActive ? t('organisation.active') : t('organisation.inactive')}</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={pending} onClick={() => { if (window.confirm(t('organisation.confirmRemoveMember'))) void mutate(`/api/hr/organisation/teams/${team.id}/members/${member.employeeId}`, { method: 'DELETE' }); }} className="rounded border border-red-500/25 px-2 py-1 text-xs text-red-700 dark:text-red-200">{t('organisation.removeMember')}</button><button type="button" disabled={pending} onClick={() => { setMoveMember(member); setMoveTargetId(''); setMoveConfirmed(false); }} className="rounded border border-emerald-500/25 px-2 py-1 text-xs text-emerald-700 dark:text-emerald-200">{t('organisation.moveMember')}</button></div></div>{moveMember?.id === member.id && <div className="mt-3 border-t border-emerald-500/15 pt-3"><label className="block text-sm font-medium">{t('organisation.targetTeam')}<select value={moveTargetId} onChange={event => setMoveTargetId(event.target.value)} className={inputClass}><option value="">{t('organisation.none')}</option>{moveTargets.map(target => <option key={target.id} value={target.id}>{target.name}</option>)}</select></label><label className="mt-3 flex items-start gap-2 text-sm"><input type="checkbox" checked={moveConfirmed} onChange={event => setMoveConfirmed(event.target.checked)} className="mt-1 accent-emerald-500" />{t('organisation.confirmMoveMember')}</label><button type="button" disabled={!moveTargetId || !moveConfirmed || pending} onClick={() => void mutate(`/api/hr/organisation/teams/${moveTargetId}/members/move`, { method: 'POST', body: JSON.stringify({ employeeId: member.employeeId, fromTeamId: team.id }) })} className="mt-3 rounded bg-emerald-500 px-3 py-2 text-xs font-bold text-black disabled:opacity-50">{t('organisation.moveMember')}</button></div>}</article>) : <p className="text-sm text-neutral-500">{t('organisation.emptyMembers')}</p>}
    <div className="flex items-center justify-between gap-3"><button type="button" disabled={page === 1 || loading} onClick={() => setPage(value => Math.max(1, value - 1))} className="rounded border border-emerald-500/20 px-3 py-2 text-xs disabled:opacity-50">{t('organisation.previous')}</button><span className="text-xs text-neutral-500 dark:text-emerald-100/55">{total}</span><button type="button" disabled={page * 25 >= total || loading} onClick={() => setPage(value => value + 1)} className="rounded border border-emerald-500/20 px-3 py-2 text-xs disabled:opacity-50">{t('organisation.next')}</button></div>
  </div>;
}

export function OrganisationPanel() {
  const { t, isRtl } = useLanguage();
  const [overview, setOverview] = useState<Overview | null>(null);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [teams, setTeams] = useState<Team[]>([]);
  const [jobTitles, setJobTitles] = useState<JobTitle[]>([]);
  const [people, setPeople] = useState<Employee[]>([]);
  const [activePeople, setActivePeople] = useState<Employee[]>([]);
  const [peopleSearch, setPeopleSearch] = useState('');
  const [peoplePage, setPeoplePage] = useState(1);
  const [peopleTotal, setPeopleTotal] = useState(0);
  const [locations, setLocations] = useState<Location[]>([]);
  const [tab, setTab] = useState<'overview' | 'people' | 'departments' | 'teams' | 'titles' | 'roles'>('overview');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [selectedDepartment, setSelectedDepartment] = useState<Department | null>(null);
  const [selectedTeam, setSelectedTeam] = useState<Team | null>(null);
  const [selectedJobTitle, setSelectedJobTitle] = useState<JobTitle | null>(null);
  const [selectedEmployee, setSelectedEmployee] = useState<Employee | null>(null);
  const [selectedReportingEmployee, setSelectedReportingEmployee] = useState<Employee | null>(null);
  const [selectedMembershipTeam, setSelectedMembershipTeam] = useState<Team | null>(null);
  const [saving, setSaving] = useState(false);
  const [dialogError, setDialogError] = useState('');
  const [success, setSuccess] = useState('');
  const closeRef = useRef<HTMLButtonElement>(null);

  const load = useCallback(async () => {
    setLoading(true); setError('');
    try {
      const peoplePath = `/api/hr/organisation/people?page=${peoplePage}&pageSize=25&search=${encodeURIComponent(peopleSearch)}`;
      const responses = await Promise.all(['/api/hr/organisation/overview', '/api/hr/organisation/departments', '/api/hr/organisation/teams', '/api/hr/organisation/job-titles', peoplePath, '/api/hr/organisation/people?pageSize=100', '/api/company-locations'].map(path => apiFetch(path)));
      const bodies = await Promise.all(responses.map(response => response.json()));
      if (responses.some(response => !response.ok)) throw new Error(bodies.find(body => body?.error)?.error || t('organisation.loadError'));
      setOverview(bodies[0].overview); setDepartments(bodies[1].departments || []); setTeams(bodies[2].teams || []); setJobTitles(bodies[3].jobTitles || []); setPeople((bodies[4].people || []).filter((person: Employee) => person.isActive)); setPeopleTotal(bodies[4].total || 0); setActivePeople((bodies[5].people || []).filter((person: Employee) => person.isActive)); setLocations(bodies[6].locations || []);
    } catch (cause) { setError(cause instanceof Error ? cause.message : t('organisation.loadError')); } finally { setLoading(false); }
  }, [peoplePage, peopleSearch, t]);

  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (selectedDepartment || selectedTeam || selectedJobTitle || selectedEmployee || selectedReportingEmployee || selectedMembershipTeam) queueMicrotask(() => closeRef.current?.focus()); }, [selectedDepartment, selectedTeam, selectedJobTitle, selectedEmployee, selectedReportingEmployee, selectedMembershipTeam]);

  const save = async (event: FormEvent<HTMLFormElement>, path: string, onSuccess: () => void) => {
    event.preventDefault(); const form = new FormData(event.currentTarget); const value = (key: string) => String(form.get(key) || '');
    setSaving(true); setDialogError('');
    try { const response = await apiFetch(path, { method: 'PATCH', body: JSON.stringify({ name: value('name'), description: value('description'), parentDepartmentId: value('parentDepartmentId') || null, departmentHeadId: value('departmentHeadId') || null, departmentId: value('departmentId') || null, teamLeadId: value('teamLeadId') || null, locationId: value('locationId') || null, level: form.get('level') === null ? undefined : value('level') === '' ? null : Number(value('level')) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || t('organisation.saveError')); onSuccess(); await load(); } catch (cause) { setDialogError(cause instanceof Error ? cause.message : t('organisation.saveError')); } finally { setSaving(false); }
  };
  const archive = async (path: string) => { if (!window.confirm(t('organisation.confirmArchive'))) return; setError(''); try { const response = await apiFetch(path, { method: 'POST', body: JSON.stringify({ confirmArchive: true }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || t('organisation.saveError')); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : t('organisation.saveError')); } };
  const savePlacement = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedEmployee) return; const form = new FormData(event.currentTarget), value = (key: string) => String(form.get(key) || ''); setSaving(true); setDialogError(''); setSuccess(''); try { const response = await apiFetch(`/api/hr/organisation/employees/${selectedEmployee.id}/placement`, { method: 'PATCH', body: JSON.stringify({ departmentId: value('departmentId') || null, teamId: value('teamId') || null, jobTitleId: value('jobTitleId') || null }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || t('organisation.saveError')); setSelectedEmployee(null); setSuccess(t('organisation.placementSaved')); await load(); } catch (cause) { setDialogError(cause instanceof Error ? cause.message : t('organisation.saveError')); } finally { setSaving(false); } };
  const saveReportingLine = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedReportingEmployee) return; const managerId = String(new FormData(event.currentTarget).get('managerId') || ''); setSaving(true); setDialogError(''); setSuccess(''); try { const response = await apiFetch(`/api/hr/organisation/employees/${selectedReportingEmployee.id}/reporting-line`, { method: 'PATCH', body: JSON.stringify({ managerId: managerId || null }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || t('organisation.saveError')); setSelectedReportingEmployee(null); setSuccess(t('organisation.reportingLineSaved')); await load(); } catch (cause) { setDialogError(cause instanceof Error ? cause.message : t('organisation.saveError')); } finally { setSaving(false); } };
  const close = () => { if (!saving) { setSelectedDepartment(null); setSelectedTeam(null); setSelectedJobTitle(null); setSelectedEmployee(null); setSelectedReportingEmployee(null); setSelectedMembershipTeam(null); } };
  const inputClass = 'mt-1 w-full rounded border border-emerald-500/20 bg-transparent p-2';
  const metrics = overview ? [[t('organisation.employees'), overview.employeeCount, UsersRound], [t('organisation.departments'), overview.departments, Building2], [t('organisation.teams'), overview.teams, Network], [t('organisation.unassigned'), overview.unassignedEmployees, UsersRound]] : [];
  const modal = (title: string, onSubmit: (event: FormEvent<HTMLFormElement>) => void, children: React.ReactNode, showSubmit = true) => <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-3" onKeyDown={event => { if (event.key === 'Escape') close(); }}><form onSubmit={onSubmit} aria-labelledby="organisation-edit-title" className="max-h-[calc(100dvh-1.5rem)] w-full max-w-lg overflow-y-auto rounded-xl border border-emerald-500/25 bg-white p-4 shadow-2xl dark:bg-neutral-950"><div className="flex items-start justify-between gap-3"><h3 id="organisation-edit-title" className="text-base font-bold text-neutral-900 dark:text-emerald-50">{title}</h3><button ref={closeRef} type="button" onClick={close} disabled={saving} className="rounded border px-2 py-1 text-xs">{t('organisation.close')}</button></div>{dialogError && <p role="alert" className="mt-3 rounded border border-red-400/30 bg-red-500/10 p-2 text-sm text-red-700">{dialogError}</p>}{children}{showSubmit && <div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" onClick={close} disabled={saving} className="rounded border px-3 py-2 text-sm">{t('organisation.cancel')}</button><button disabled={saving} className="rounded bg-emerald-500 px-3 py-2 text-sm font-bold text-black">{saving ? t('organisation.saving') : t('organisation.save')}</button></div>}</form></div>;

  return <section className="rounded-2xl border border-emerald-500/15 bg-white p-4 shadow-xl dark:bg-black/40" dir={isRtl ? 'rtl' : 'ltr'}>
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-neutral-900 dark:text-emerald-50">{t('organisation.title')}</h2><p className="mt-1 text-sm text-neutral-600 dark:text-emerald-100/60">{t('organisation.subtitle')}</p></div><button type="button" onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded border border-emerald-500/25 px-3 py-2 text-xs font-bold text-emerald-700 dark:text-emerald-200"><RefreshCw className={loading ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} />{t('organisation.refresh')}</button></div>
    {error && <p role="alert" className="mt-3 rounded border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-700 dark:text-red-200">{error}</p>}
    <div className="mt-4 flex flex-wrap gap-2">{(['overview', 'people', 'departments', 'teams', 'titles', 'roles'] as const).map(item => <button key={item} type="button" onClick={() => setTab(item)} className={tab === item ? 'rounded border border-emerald-500/40 bg-emerald-500/10 px-3 py-2 text-xs font-bold' : 'rounded border border-emerald-500/15 px-3 py-2 text-xs'}>{t(`organisation.${item === 'titles' ? 'titles' : item}`)}</button>)}</div>
    {tab === 'overview' && <div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{metrics.map(([label, value, Icon]) => { const Metric = Icon as typeof UsersRound; return <div key={String(label)} className="rounded-lg border border-emerald-500/15 bg-emerald-500/5 p-3"><Metric className="h-4 w-4 text-emerald-500" /><p className="mt-3 text-2xl font-bold text-neutral-900 dark:text-emerald-50">{String(value)}</p><p className="text-xs text-neutral-600 dark:text-emerald-100/55">{String(label)}</p></div>; })}</div>}
    {tab === 'people' && <div className="mt-4 space-y-2"><label className="block text-sm font-medium">{t('organisation.searchPeople')}<input value={peopleSearch} onChange={event => { setPeopleSearch(event.target.value); setPeoplePage(1); }} className={inputClass} /></label>{people.map(employee => <article key={employee.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-emerald-500/15 p-3"><div className="min-w-0"><p className="truncate font-medium text-neutral-900 dark:text-emerald-50">{employee.fullName}</p><p className="truncate text-xs text-neutral-500 dark:text-emerald-100/55">{employee.email}</p><p className="mt-1 text-xs text-neutral-500 dark:text-emerald-100/55">{employee.department || t('organisation.none')} · {employee.team || t('organisation.none')} · {employee.jobTitle || t('organisation.none')}</p></div><div className="flex shrink-0 flex-wrap gap-2"><button type="button" onClick={() => { setDialogError(''); setSuccess(''); setSelectedEmployee(employee); }} className="rounded border border-emerald-500/25 px-3 py-2 text-xs font-bold text-emerald-700 dark:text-emerald-200">{t('organisation.editPlacement')}</button><button type="button" onClick={() => { setDialogError(''); setSuccess(''); setSelectedReportingEmployee(employee); }} className="rounded border border-emerald-500/25 px-3 py-2 text-xs font-bold text-emerald-700 dark:text-emerald-200">{t('organisation.changeManager')}</button></div></article>)}{!loading && !people.length && <p className="text-sm text-neutral-500">{t('organisation.emptyPeople')}</p>}<div className="flex items-center justify-between gap-3 pt-2"><button type="button" disabled={peoplePage === 1 || loading} onClick={() => setPeoplePage(page => Math.max(1, page - 1))} className="rounded border border-emerald-500/20 px-3 py-2 text-xs disabled:opacity-50">{t('organisation.previous')}</button><span className="text-xs text-neutral-500 dark:text-emerald-100/55">{peopleTotal}</span><button type="button" disabled={peoplePage * 25 >= peopleTotal || loading} onClick={() => setPeoplePage(page => page + 1)} className="rounded border border-emerald-500/20 px-3 py-2 text-xs disabled:opacity-50">{t('organisation.next')}</button></div></div>}
    {tab === 'departments' && <div className="mt-4 space-y-2">{departments.filter(item => item.isActive).map(item => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-emerald-500/15 p-3"><div><p className="font-medium text-neutral-900 dark:text-emerald-50">{item.name}</p><p className="text-xs text-neutral-500 dark:text-emerald-100/55">{item.departmentHeadName || t('organisation.noHead')}</p></div><button type="button" onClick={() => { setDialogError(''); setSelectedDepartment(item); }} className="rounded border border-emerald-500/25 px-3 py-2 text-xs font-bold text-emerald-700 dark:text-emerald-200">{t('organisation.edit')}</button></article>)}{!loading && !departments.length && <p className="text-sm text-neutral-500">{t('organisation.emptyDepartments')}</p>}</div>}
    {tab === 'teams' && <div className="mt-4 space-y-2">{teams.filter(item => item.isActive).map(item => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-emerald-500/15 p-3"><div><p className="font-medium text-neutral-900 dark:text-emerald-50">{item.name}</p><p className="text-xs text-neutral-500 dark:text-emerald-100/55">{item.memberCount} {t('organisation.members')}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => { setDialogError(''); setSelectedTeam(item); }} className="rounded border border-emerald-500/25 px-3 py-2 text-xs font-bold text-emerald-700 dark:text-emerald-200">{t('organisation.edit')}</button><button type="button" onClick={() => { setDialogError(''); setSuccess(''); setSelectedMembershipTeam(item); }} className="rounded border border-emerald-500/25 px-3 py-2 text-xs font-bold text-emerald-700 dark:text-emerald-200">{t('organisation.manageMembers')}</button><button type="button" onClick={() => void archive(`/api/hr/organisation/teams/${item.id}/archive`)} className="rounded border border-red-500/25 px-3 py-2 text-xs font-bold text-red-700 dark:text-red-200">{t('organisation.archive')}</button></div></article>)}{!loading && !teams.length && <p className="text-sm text-neutral-500">{t('organisation.emptyTeams')}</p>}</div>}
    {tab === 'titles' && <div className="mt-4 space-y-2">{jobTitles.filter(item => item.isActive).map(item => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-emerald-500/15 p-3"><div><p className="font-medium text-neutral-900 dark:text-emerald-50">{item.name}</p><p className="text-xs text-neutral-500 dark:text-emerald-100/55">{item.level === null ? t('organisation.none') : `${t('organisation.level')}: ${item.level}`}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => { setDialogError(''); setSelectedJobTitle(item); }} className="rounded border border-emerald-500/25 px-3 py-2 text-xs font-bold text-emerald-700 dark:text-emerald-200">{t('organisation.edit')}</button><button type="button" onClick={() => void archive(`/api/hr/organisation/job-titles/${item.id}/archive`)} className="rounded border border-red-500/25 px-3 py-2 text-xs font-bold text-red-700 dark:text-red-200">{t('organisation.archive')}</button></div></article>)}{!loading && !jobTitles.length && <p className="text-sm text-neutral-500">{t('organisation.emptyTeams')}</p>}</div>}
    {tab === 'roles' && <RolesPermissionsPanel people={activePeople} departments={departments} teams={teams} locations={locations} />}
    {selectedDepartment && modal(t('organisation.editDepartment'), event => void save(event, `/api/hr/organisation/departments/${selectedDepartment.id}`, () => setSelectedDepartment(null)), <><label className="mt-3 block text-sm font-medium">{t('organisation.name')}<input required name="name" defaultValue={selectedDepartment.name} className={inputClass} /></label><label className="mt-3 block text-sm font-medium">{t('organisation.description')}<textarea name="description" defaultValue={selectedDepartment.description || ''} className={inputClass} /></label><label className="mt-3 block text-sm font-medium">{t('organisation.parentDepartment')}<select name="parentDepartmentId" defaultValue={selectedDepartment.parentDepartmentId || ''} className={inputClass}><option value="">{t('organisation.none')}</option>{departments.filter(item => item.isActive && item.id !== selectedDepartment.id).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="mt-3 block text-sm font-medium">{t('organisation.departmentHead')}<select name="departmentHeadId" defaultValue={selectedDepartment.departmentHeadId || ''} className={inputClass}><option value="">{t('organisation.none')}</option>{activePeople.map(item => <option key={item.id} value={item.id}>{item.fullName} ({item.email})</option>)}</select></label></>)}
    {selectedTeam && modal(t('organisation.editTeam'), event => void save(event, `/api/hr/organisation/teams/${selectedTeam.id}`, () => setSelectedTeam(null)), <><label className="mt-3 block text-sm font-medium">{t('organisation.name')}<input required name="name" defaultValue={selectedTeam.name} className={inputClass} /></label><label className="mt-3 block text-sm font-medium">{t('organisation.description')}<textarea name="description" defaultValue={selectedTeam.description || ''} className={inputClass} /></label><label className="mt-3 block text-sm font-medium">{t('organisation.departments')}<select name="departmentId" defaultValue={selectedTeam.departmentId || ''} className={inputClass}><option value="">{t('organisation.none')}</option>{departments.filter(item => item.isActive).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="mt-3 block text-sm font-medium">{t('organisation.teamLeader')}<select name="teamLeadId" defaultValue={selectedTeam.teamLeadId || ''} className={inputClass}><option value="">{t('organisation.none')}</option>{activePeople.map(item => <option key={item.id} value={item.id}>{item.fullName} ({item.email})</option>)}</select></label><label className="mt-3 block text-sm font-medium">{t('organisation.location')}<select name="locationId" defaultValue={selectedTeam.locationId || ''} className={inputClass}><option value="">{t('organisation.none')}</option>{locations.filter(item => item.is_active).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></>)}
    {selectedJobTitle && modal(t('organisation.editJobTitle'), event => void save(event, `/api/hr/organisation/job-titles/${selectedJobTitle.id}`, () => setSelectedJobTitle(null)), <><label className="mt-3 block text-sm font-medium">{t('organisation.name')}<input required name="name" defaultValue={selectedJobTitle.name} className={inputClass} /></label><label className="mt-3 block text-sm font-medium">{t('organisation.description')}<textarea name="description" defaultValue={selectedJobTitle.description || ''} className={inputClass} /></label><label className="mt-3 block text-sm font-medium">{t('organisation.level')}<input name="level" type="number" min="0" max="100" step="1" defaultValue={selectedJobTitle.level ?? ''} className={inputClass} /></label></>)}
    {selectedEmployee && modal(t('organisation.editPlacement'), event => void savePlacement(event), <PlacementFields employee={selectedEmployee} departments={departments} teams={teams} jobTitles={jobTitles} inputClass={inputClass} t={t} />)}
    {selectedReportingEmployee && modal(t('organisation.changeManager'), event => void saveReportingLine(event), <ReportingLineFields employee={selectedReportingEmployee} managers={activePeople} inputClass={inputClass} t={t} />)}
    {selectedMembershipTeam && modal(t('organisation.manageMembers'), event => event.preventDefault(), <TeamMembershipFields team={selectedMembershipTeam} activePeople={activePeople} teams={teams} inputClass={inputClass} t={t} onChanged={load} />, false)}
    {success && <p role="status" className="mt-3 rounded border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm text-emerald-800 dark:text-emerald-100">{success}</p>}
  </section>;
}
