import { FormEvent, useCallback, useEffect, useRef, useState } from 'react';
import { Building2, Network, RefreshCw, UsersRound } from 'lucide-react';
import { apiFetch } from '../../lib/api';
import { useLanguage } from '../../lib/LanguageContext';

type Overview = { employeeCount: number; departments: number; teams: number; unassignedEmployees: number };
type Department = { id: string; name: string; description: string | null; parentDepartmentId: string | null; departmentHeadId: string | null; departmentHeadName: string | null; isActive: boolean };
type Team = { id: string; name: string; description: string | null; departmentId: string | null; teamLeadId: string | null; locationId: string | null; memberCount: number; isActive: boolean };
type JobTitle = { id: string; name: string; description: string | null; level: number | null; isActive: boolean };
type Employee = { id: string; fullName: string; email: string; isActive: boolean };
type Location = { id: string; name: string; is_active: boolean };

export function OrganisationPanel() {
  const { t, isRtl } = useLanguage();
  const [overview, setOverview] = useState<Overview | null>(null);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [teams, setTeams] = useState<Team[]>([]);
  const [jobTitles, setJobTitles] = useState<JobTitle[]>([]);
  const [people, setPeople] = useState<Employee[]>([]);
  const [locations, setLocations] = useState<Location[]>([]);
  const [tab, setTab] = useState<'overview' | 'departments' | 'teams' | 'titles'>('overview');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [selectedDepartment, setSelectedDepartment] = useState<Department | null>(null);
  const [selectedTeam, setSelectedTeam] = useState<Team | null>(null);
  const [selectedJobTitle, setSelectedJobTitle] = useState<JobTitle | null>(null);
  const [saving, setSaving] = useState(false);
  const [dialogError, setDialogError] = useState('');
  const closeRef = useRef<HTMLButtonElement>(null);

  const load = useCallback(async () => {
    setLoading(true); setError('');
    try {
      const responses = await Promise.all(['/api/hr/organisation/overview', '/api/hr/organisation/departments', '/api/hr/organisation/teams', '/api/hr/organisation/job-titles', '/api/hr/organisation/people?pageSize=100', '/api/company-locations'].map(path => apiFetch(path)));
      const bodies = await Promise.all(responses.map(response => response.json()));
      if (responses.some(response => !response.ok)) throw new Error(bodies.find(body => body?.error)?.error || t('organisation.loadError'));
      setOverview(bodies[0].overview); setDepartments(bodies[1].departments || []); setTeams(bodies[2].teams || []); setJobTitles(bodies[3].jobTitles || []); setPeople((bodies[4].people || []).filter((person: Employee) => person.isActive)); setLocations(bodies[5].locations || []);
    } catch (cause) { setError(cause instanceof Error ? cause.message : t('organisation.loadError')); } finally { setLoading(false); }
  }, [t]);

  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (selectedDepartment || selectedTeam || selectedJobTitle) queueMicrotask(() => closeRef.current?.focus()); }, [selectedDepartment, selectedTeam, selectedJobTitle]);

  const save = async (event: FormEvent<HTMLFormElement>, path: string, onSuccess: () => void) => {
    event.preventDefault(); const form = new FormData(event.currentTarget); const value = (key: string) => String(form.get(key) || '');
    setSaving(true); setDialogError('');
    try { const response = await apiFetch(path, { method: 'PATCH', body: JSON.stringify({ name: value('name'), description: value('description'), parentDepartmentId: value('parentDepartmentId') || null, departmentHeadId: value('departmentHeadId') || null, departmentId: value('departmentId') || null, teamLeadId: value('teamLeadId') || null, locationId: value('locationId') || null, level: form.get('level') === null ? undefined : value('level') === '' ? null : Number(value('level')) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || t('organisation.saveError')); onSuccess(); await load(); } catch (cause) { setDialogError(cause instanceof Error ? cause.message : t('organisation.saveError')); } finally { setSaving(false); }
  };
  const archive = async (path: string) => { if (!window.confirm(t('organisation.confirmArchive'))) return; setError(''); try { const response = await apiFetch(path, { method: 'POST', body: JSON.stringify({ confirmArchive: true }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || t('organisation.saveError')); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : t('organisation.saveError')); } };
  const close = () => { if (!saving) { setSelectedDepartment(null); setSelectedTeam(null); setSelectedJobTitle(null); } };
  const inputClass = 'mt-1 w-full rounded border border-emerald-500/20 bg-transparent p-2';
  const metrics = overview ? [[t('organisation.employees'), overview.employeeCount, UsersRound], [t('organisation.departments'), overview.departments, Building2], [t('organisation.teams'), overview.teams, Network], [t('organisation.unassigned'), overview.unassignedEmployees, UsersRound]] : [];
  const modal = (title: string, onSubmit: (event: FormEvent<HTMLFormElement>) => void, children: React.ReactNode) => <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-3" onKeyDown={event => { if (event.key === 'Escape') close(); }}><form onSubmit={onSubmit} aria-labelledby="organisation-edit-title" className="max-h-[calc(100dvh-1.5rem)] w-full max-w-lg overflow-y-auto rounded-xl border border-emerald-500/25 bg-white p-4 shadow-2xl dark:bg-neutral-950"><div className="flex items-start justify-between gap-3"><h3 id="organisation-edit-title" className="text-base font-bold text-neutral-900 dark:text-emerald-50">{title}</h3><button ref={closeRef} type="button" onClick={close} disabled={saving} className="rounded border px-2 py-1 text-xs">{t('organisation.close')}</button></div>{dialogError && <p role="alert" className="mt-3 rounded border border-red-400/30 bg-red-500/10 p-2 text-sm text-red-700">{dialogError}</p>}{children}<div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" onClick={close} disabled={saving} className="rounded border px-3 py-2 text-sm">{t('organisation.cancel')}</button><button disabled={saving} className="rounded bg-emerald-500 px-3 py-2 text-sm font-bold text-black">{saving ? t('organisation.saving') : t('organisation.save')}</button></div></form></div>;

  return <section className="rounded-2xl border border-emerald-500/15 bg-white p-4 shadow-xl dark:bg-black/40" dir={isRtl ? 'rtl' : 'ltr'}>
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-neutral-900 dark:text-emerald-50">{t('organisation.title')}</h2><p className="mt-1 text-sm text-neutral-600 dark:text-emerald-100/60">{t('organisation.subtitle')}</p></div><button type="button" onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded border border-emerald-500/25 px-3 py-2 text-xs font-bold text-emerald-700 dark:text-emerald-200"><RefreshCw className={loading ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} />{t('organisation.refresh')}</button></div>
    {error && <p role="alert" className="mt-3 rounded border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-700 dark:text-red-200">{error}</p>}
    <div className="mt-4 flex flex-wrap gap-2">{(['overview', 'departments', 'teams', 'titles'] as const).map(item => <button key={item} type="button" onClick={() => setTab(item)} className={tab === item ? 'rounded border border-emerald-500/40 bg-emerald-500/10 px-3 py-2 text-xs font-bold' : 'rounded border border-emerald-500/15 px-3 py-2 text-xs'}>{t(`organisation.${item === 'titles' ? 'titles' : item}`)}</button>)}</div>
    {tab === 'overview' && <div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{metrics.map(([label, value, Icon]) => { const Metric = Icon as typeof UsersRound; return <div key={String(label)} className="rounded-lg border border-emerald-500/15 bg-emerald-500/5 p-3"><Metric className="h-4 w-4 text-emerald-500" /><p className="mt-3 text-2xl font-bold text-neutral-900 dark:text-emerald-50">{String(value)}</p><p className="text-xs text-neutral-600 dark:text-emerald-100/55">{String(label)}</p></div>; })}</div>}
    {tab === 'departments' && <div className="mt-4 space-y-2">{departments.filter(item => item.isActive).map(item => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-emerald-500/15 p-3"><div><p className="font-medium text-neutral-900 dark:text-emerald-50">{item.name}</p><p className="text-xs text-neutral-500 dark:text-emerald-100/55">{item.departmentHeadName || t('organisation.noHead')}</p></div><button type="button" onClick={() => { setDialogError(''); setSelectedDepartment(item); }} className="rounded border border-emerald-500/25 px-3 py-2 text-xs font-bold text-emerald-700 dark:text-emerald-200">{t('organisation.edit')}</button></article>)}{!loading && !departments.length && <p className="text-sm text-neutral-500">{t('organisation.emptyDepartments')}</p>}</div>}
    {tab === 'teams' && <div className="mt-4 space-y-2">{teams.filter(item => item.isActive).map(item => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-emerald-500/15 p-3"><div><p className="font-medium text-neutral-900 dark:text-emerald-50">{item.name}</p><p className="text-xs text-neutral-500 dark:text-emerald-100/55">{item.memberCount} {t('organisation.members')}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => { setDialogError(''); setSelectedTeam(item); }} className="rounded border border-emerald-500/25 px-3 py-2 text-xs font-bold text-emerald-700 dark:text-emerald-200">{t('organisation.edit')}</button><button type="button" onClick={() => void archive(`/api/hr/organisation/teams/${item.id}/archive`)} className="rounded border border-red-500/25 px-3 py-2 text-xs font-bold text-red-700 dark:text-red-200">{t('organisation.archive')}</button></div></article>)}{!loading && !teams.length && <p className="text-sm text-neutral-500">{t('organisation.emptyTeams')}</p>}</div>}
    {tab === 'titles' && <div className="mt-4 space-y-2">{jobTitles.filter(item => item.isActive).map(item => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-emerald-500/15 p-3"><div><p className="font-medium text-neutral-900 dark:text-emerald-50">{item.name}</p><p className="text-xs text-neutral-500 dark:text-emerald-100/55">{item.level === null ? t('organisation.none') : `${t('organisation.level')}: ${item.level}`}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => { setDialogError(''); setSelectedJobTitle(item); }} className="rounded border border-emerald-500/25 px-3 py-2 text-xs font-bold text-emerald-700 dark:text-emerald-200">{t('organisation.edit')}</button><button type="button" onClick={() => void archive(`/api/hr/organisation/job-titles/${item.id}/archive`)} className="rounded border border-red-500/25 px-3 py-2 text-xs font-bold text-red-700 dark:text-red-200">{t('organisation.archive')}</button></div></article>)}{!loading && !jobTitles.length && <p className="text-sm text-neutral-500">{t('organisation.emptyTeams')}</p>}</div>}
    {selectedDepartment && modal(t('organisation.editDepartment'), event => void save(event, `/api/hr/organisation/departments/${selectedDepartment.id}`, () => setSelectedDepartment(null)), <><label className="mt-3 block text-sm font-medium">{t('organisation.name')}<input required name="name" defaultValue={selectedDepartment.name} className={inputClass} /></label><label className="mt-3 block text-sm font-medium">{t('organisation.description')}<textarea name="description" defaultValue={selectedDepartment.description || ''} className={inputClass} /></label><label className="mt-3 block text-sm font-medium">{t('organisation.parentDepartment')}<select name="parentDepartmentId" defaultValue={selectedDepartment.parentDepartmentId || ''} className={inputClass}><option value="">{t('organisation.none')}</option>{departments.filter(item => item.isActive && item.id !== selectedDepartment.id).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="mt-3 block text-sm font-medium">{t('organisation.departmentHead')}<select name="departmentHeadId" defaultValue={selectedDepartment.departmentHeadId || ''} className={inputClass}><option value="">{t('organisation.none')}</option>{people.map(item => <option key={item.id} value={item.id}>{item.fullName} ({item.email})</option>)}</select></label></>)}
    {selectedTeam && modal(t('organisation.editTeam'), event => void save(event, `/api/hr/organisation/teams/${selectedTeam.id}`, () => setSelectedTeam(null)), <><label className="mt-3 block text-sm font-medium">{t('organisation.name')}<input required name="name" defaultValue={selectedTeam.name} className={inputClass} /></label><label className="mt-3 block text-sm font-medium">{t('organisation.description')}<textarea name="description" defaultValue={selectedTeam.description || ''} className={inputClass} /></label><label className="mt-3 block text-sm font-medium">{t('organisation.departments')}<select name="departmentId" defaultValue={selectedTeam.departmentId || ''} className={inputClass}><option value="">{t('organisation.none')}</option>{departments.filter(item => item.isActive).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="mt-3 block text-sm font-medium">{t('organisation.teamLeader')}<select name="teamLeadId" defaultValue={selectedTeam.teamLeadId || ''} className={inputClass}><option value="">{t('organisation.none')}</option>{people.map(item => <option key={item.id} value={item.id}>{item.fullName} ({item.email})</option>)}</select></label><label className="mt-3 block text-sm font-medium">{t('organisation.location')}<select name="locationId" defaultValue={selectedTeam.locationId || ''} className={inputClass}><option value="">{t('organisation.none')}</option>{locations.filter(item => item.is_active).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></>)}
    {selectedJobTitle && modal(t('organisation.editJobTitle'), event => void save(event, `/api/hr/organisation/job-titles/${selectedJobTitle.id}`, () => setSelectedJobTitle(null)), <><label className="mt-3 block text-sm font-medium">{t('organisation.name')}<input required name="name" defaultValue={selectedJobTitle.name} className={inputClass} /></label><label className="mt-3 block text-sm font-medium">{t('organisation.description')}<textarea name="description" defaultValue={selectedJobTitle.description || ''} className={inputClass} /></label><label className="mt-3 block text-sm font-medium">{t('organisation.level')}<input name="level" type="number" min="0" max="100" step="1" defaultValue={selectedJobTitle.level ?? ''} className={inputClass} /></label></>)}
  </section>;
}
