import {useMemo,useState} from 'react';
import {useLanguage} from '../../lib/LanguageContext';
import {filterCapabilities,groupCapabilities,selectedCapabilities,type Capability} from '../../lib/role-capabilities';
import {Input,Select} from '../ui/FormControls';
export function PermissionPicker<T extends Capability>({items,onChange,disabled=false}:{items:T[];onChange:(items:T[])=>void;disabled?:boolean}){
 const {isRtl}=useLanguage();const text=(en:string,ar:string)=>isRtl?ar:en;
 const [search,setSearch]=useState(''),[only,setOnly]=useState(false),[category,setCategory]=useState('');
 const groups=useMemo(()=>groupCapabilities(filterCapabilities(items,search,only,category)),[items,search,only,category]);const selected=useMemo(()=>selectedCapabilities(items),[items]);const count=selected.reduce((sum,[,group])=>sum+group.length,0);
 const locked=(item:T)=>disabled||(!item.legacy&&(item.protected||item.delegatable===false||item.grantable===false));
 const change=(keys:Set<string>,checked:boolean)=>onChange(items.map(item=>keys.has(item.key)&&!locked(item)?{...item,selected:checked}:item));
 return <section className="permission-picker mt-4 space-y-3 min-w-0" aria-label={text('Permissions','الصلاحيات')}>
 <label className="block text-sm font-medium">{text('Search permissions','البحث في الصلاحيات')}<Input type="search" value={search} onChange={e=>setSearch(e.target.value)} /></label>
 <div className="flex flex-wrap gap-3 items-center"><label className="flex gap-2 items-center"><input type="checkbox" checked={only} onChange={e=>setOnly(e.target.checked)} />{text('Show selected only','عرض المحدد فقط')}</label><label className="min-w-0 flex-1">{text('Permission area','مجال الصلاحية')}<Select value={category} onChange={e=>setCategory(e.target.value)}><option value="">{text('All areas','كل المجالات')}</option>{groupCapabilities(items).map(([area])=><option key={area}>{area}</option>)}</Select></label></div>
 <p role="status" className="text-sm">{count} {text('permissions selected across','صلاحية محددة في')} {selected.length} {text('areas','مجالات')}</p>
 {!groups.length&&<p>{text('No permissions match these filters.','لا توجد صلاحيات تطابق المرشحات.')}</p>}
 {groups.map(([area,group])=><section key={area} className="rounded border border-emerald-500/20 p-3 min-w-0"><h4 className="font-bold break-words">{area}</h4>{!disabled&&<div className="flex flex-wrap gap-3 my-2"><button type="button" className="underline focus-visible:outline-2" onClick={()=>change(new Set(group.filter(item=>!item.legacy).map(item=>item.key)),true)}>{text('Select visible area','تحديد المجال الظاهر')}</button><button type="button" className="underline focus-visible:outline-2" onClick={()=>change(new Set(group.map(item=>item.key)),false)}>{text('Clear visible area','مسح المجال الظاهر')}</button></div>}
 <div className="space-y-2">{group.map(item=><label key={item.key} className="flex items-start gap-3 p-2 min-w-0"><input className="mt-1 shrink-0 accent-emerald-500 focus-visible:outline-2 focus-visible:outline-offset-2" type="checkbox" checked={Boolean(item.selected)} disabled={Boolean(locked(item))} onChange={e=>change(new Set([item.key]),e.target.checked)} /><span className="min-w-0 break-words"><strong className="block">{item.legacy?text('Unknown / legacy permission','صلاحية غير معروفة / قديمة'):item.label}</strong><span className="block text-sm opacity-80">{item.description}</span>{item.legacy&&<code dir="ltr" className="block break-all">{item.key}</code>}{locked(item)&&!disabled&&<small>{text('Restricted by existing grant rules.','مقيدة بقواعد المنح الحالية.')}</small>}</span></label>)}</div></section>)}
 <section aria-label={text('Selected capabilities','الإمكانات المحددة')} className="rounded border border-emerald-500/20 p-3"><h4 className="font-bold">{text('Selected capabilities','الإمكانات المحددة')}</h4>{selected.length?selected.map(([area,group])=><div key={area}><h5 className="font-semibold mt-2">{area}</h5><ul className="list-disc ps-5">{group.map(item=><li className="break-words" key={item.key}>{item.legacy?`${text('Unknown / legacy permission','صلاحية قديمة')}: ${item.key}`:item.label}</li>)}</ul></div>):<p>{text('No capabilities selected.','لم يتم تحديد إمكانات.')}</p>}</section>
 </section>;
}
