import type express from 'express';
import type { PoolClient } from 'pg';
import { withTenant } from '../../lib/hr-background';
import { recordAuditEvent } from '../audit/audit-events';

type Dependencies = { demoAuth: express.RequestHandler; requirePermission: (key: string) => express.RequestHandler };
type AssetStatus = 'available' | 'assigned' | 'maintenance' | 'lost' | 'retired';
const uuidPattern = new RegExp('^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$', 'i');
const uuid = (value: unknown): value is string => typeof value === 'string' && uuidPattern.test(value);
const categories = new Set(['laptop', 'desktop', 'monitor', 'phone', 'tablet', 'accessory', 'badge', 'furniture', 'other']);
const statuses = new Set<AssetStatus>(['available', 'assigned', 'maintenance', 'lost', 'retired']);
const conditions = new Set(['new', 'good', 'fair', 'damaged', 'unusable']);

class RouteError extends Error { constructor(message: string, readonly status: number) { super(message); } }
const cleanText = (value: unknown, max = 500) => typeof value === 'string' ? value.trim().slice(0, max) : '';
const optionalText = (value: unknown, max = 500) => cleanText(value, max) || null;
function optionalDate(value: unknown) {
  if (value === undefined || value === null || value === '') return null;
  const date = cleanText(value, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || Number.isNaN(Date.parse(`${date}T00:00:00Z`))) throw new RouteError('Invalid date.', 400);
  return date;
}
function page(query: express.Request['query']) { const value = Math.max(1, Math.min(10_000, Number(query.page) || 1)); const size = Math.max(1, Math.min(100, Number(query.pageSize) || 25)); return { value, size, offset: (value - 1) * size }; }
function sendError(res: express.Response, error: unknown, fallback: string) {
  if (error instanceof RouteError) return res.status(error.status).json({ success: false, error: error.message });
  if ((error as { code?: string })?.code === '23505') return res.status(409).json({ success: false, error: 'That record already exists.' });
  return res.status(500).json({ success: false, error: fallback });
}
const assetFields = `a.id,a.asset_tag AS "assetTag",a.name,a.category,a.manufacturer,a.model,a.serial_number AS "serialNumber",a.status,a.condition,a.purchase_date AS "purchaseDate",a.purchase_cost AS "purchaseCost",a.warranty_expires_at AS "warrantyExpiresAt",a.notes,a.created_at AS "createdAt",a.updated_at AS "updatedAt",assignment.id AS "activeAssignmentId",assignment.assigned_at AS "assignedAt",assignment.expected_return_at AS "expectedReturnAt",employee.id AS "assignedEmployeeId",employee.full_name AS "assignedEmployee"`;
async function lockedAsset(client: PoolClient, tenantId: string, assetId: string, lock = true) {
  const result = await client.query(`SELECT ${assetFields} FROM assets a LEFT JOIN asset_assignments assignment ON assignment.asset_id=a.id AND assignment.tenant_id=a.tenant_id AND assignment.status='active' LEFT JOIN employees employee ON employee.id=assignment.employee_id AND employee.tenant_id=a.tenant_id WHERE a.id=$1 AND a.tenant_id=$2${lock ? ' FOR UPDATE OF a' : ''}`, [assetId, tenantId]);
  if (!result.rows[0]) throw new RouteError('Asset not found.', 404);
  return result.rows[0];
}
function assetInput(body: Record<string, unknown>, partial = false) {
  const values: Record<string, unknown> = {};
  const fields: Array<[string, string, number]> = [['assetTag', 'asset_tag', 100], ['name', 'name', 180], ['manufacturer', 'manufacturer', 120], ['model', 'model', 120], ['serialNumber', 'serial_number', 160], ['notes', 'notes', 4000]];
  fields.forEach(([input, column, max]) => { if (!partial || Object.hasOwn(body, input)) values[column] = optionalText(body[input], max); });
  if (!partial || Object.hasOwn(body, 'category')) { if (!categories.has(body.category as string)) throw new RouteError('Invalid asset category.', 400); values.category = body.category; }
  if (!partial || Object.hasOwn(body, 'condition')) { const condition = body.condition ?? 'good'; if (!conditions.has(condition as string)) throw new RouteError('Invalid asset condition.', 400); values.condition = condition; }
  [['purchaseDate', 'purchase_date'], ['warrantyExpiresAt', 'warranty_expires_at']].forEach(([input, column]) => { if (!partial || Object.hasOwn(body, input)) values[column] = optionalDate(body[input]); });
  if (!partial || Object.hasOwn(body, 'purchaseCost')) { const cost = body.purchaseCost; if (cost === '' || cost === null || cost === undefined) values.purchase_cost = null; else if (typeof cost !== 'number' || !Number.isFinite(cost) || cost < 0) throw new RouteError('Invalid purchase cost.', 400); else values.purchase_cost = cost; }
  if (!partial && (!values.asset_tag || !values.name)) throw new RouteError('Asset tag and name are required.', 400);
  return values;
}

export function registerAssetRoutes(app: express.Express, { demoAuth, requirePermission }: Dependencies) {
  app.get('/api/hr/assets', demoAuth, requirePermission('assets.view'), async (req, res) => {
    const user = req.authUser!; const { value, size, offset } = page(req.query); const search = cleanText(req.query.search, 100); const category = cleanText(req.query.category, 30); const status = cleanText(req.query.status, 20);
    if (category && !categories.has(category)) return res.status(400).json({ success: false, error: 'Invalid category filter.' });
    if (status && !statuses.has(status as AssetStatus)) return res.status(400).json({ success: false, error: 'Invalid status filter.' });
    try {
      const result = await withTenant(user.tenantId, async (client) => {
        const where = `WHERE a.tenant_id=$1 AND ($2='' OR a.name ILIKE '%' || $2 || '%' OR a.asset_tag ILIKE '%' || $2 || '%') AND ($3='' OR a.category=$3) AND ($4='' OR a.status=$4)`; const params = [user.tenantId, search, category, status];
        const [assets, count, summary] = await Promise.all([
          client.query(`SELECT ${assetFields} FROM assets a LEFT JOIN asset_assignments assignment ON assignment.asset_id=a.id AND assignment.tenant_id=a.tenant_id AND assignment.status='active' LEFT JOIN employees employee ON employee.id=assignment.employee_id AND employee.tenant_id=a.tenant_id ${where} ORDER BY a.created_at DESC LIMIT $5 OFFSET $6`, [...params, size, offset]),
          client.query(`SELECT COUNT(*)::integer AS total FROM assets a ${where}`, params),
          client.query(`SELECT COUNT(*)::integer AS total,COUNT(*) FILTER(WHERE status='available')::integer AS available,COUNT(*) FILTER(WHERE status='assigned')::integer AS assigned,COUNT(*) FILTER(WHERE status='maintenance')::integer AS maintenance,COUNT(*) FILTER(WHERE status='lost')::integer AS lost,COUNT(*) FILTER(WHERE warranty_expires_at BETWEEN CURRENT_DATE AND CURRENT_DATE+30)::integer AS "warrantiesExpiringSoon" FROM assets WHERE tenant_id=$1`, [user.tenantId]),
        ]);
        return { assets: assets.rows, total: count.rows[0].total, summary: summary.rows[0] };
      });
      res.json({ success: true, page: value, pageSize: size, ...result });
    } catch (error) { sendError(res, error, 'Unable to load assets.'); }
  });

  app.post('/api/hr/assets', demoAuth, requirePermission('assets.manage'), async (req, res) => {
    const user = req.authUser!;
    try { const input = assetInput(req.body || {}); const asset = await withTenant(user.tenantId, async (client) => {
      const result = await client.query(`INSERT INTO assets(tenant_id,asset_tag,name,category,manufacturer,model,serial_number,condition,purchase_date,purchase_cost,warranty_expires_at,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id,asset_tag AS "assetTag",name,category,status,condition`, [user.tenantId,input.asset_tag,input.name,input.category,input.manufacturer,input.model,input.serial_number,input.condition,input.purchase_date,input.purchase_cost,input.warranty_expires_at,input.notes,user.employeeId]);
      await recordAuditEvent(client, { tenantId: user.tenantId, actorId: user.employeeId, action: 'asset.created', targetType: 'asset', targetId: result.rows[0].id, metadata: { assetTag: result.rows[0].assetTag, category: String(input.category) } }); return result.rows[0];
    }); res.status(201).json({ success: true, asset }); } catch (error) { sendError(res, error, 'Unable to create asset.'); }
  });

  app.get('/api/hr/assets/:assetId', demoAuth, requirePermission('assets.view'), async (req, res) => {
    const user = req.authUser!; if (!uuid(req.params.assetId)) return res.status(400).json({ success: false, error: 'Invalid asset id.' });
    try { const asset = await withTenant(user.tenantId, async (client) => { const current = await lockedAsset(client, user.tenantId, req.params.assetId, false); const [assignments, reports] = await Promise.all([
      client.query(`SELECT aa.id,aa.employee_id AS "employeeId",e.full_name AS "employeeName",aa.assigned_at AS "assignedAt",aa.expected_return_at AS "expectedReturnAt",aa.returned_at AS "returnedAt",aa.return_condition AS "returnCondition",aa.return_notes AS "returnNotes",aa.status FROM asset_assignments aa JOIN employees e ON e.id=aa.employee_id AND e.tenant_id=aa.tenant_id WHERE aa.tenant_id=$1 AND aa.asset_id=$2 ORDER BY aa.assigned_at DESC`, [user.tenantId, req.params.assetId]),
      client.query(`SELECT report.id,report.assignment_id AS "assignmentId",report.condition,report.notes,CASE WHEN report.evidence_url IS NULL THEN NULL ELSE '/api/assets/evidence/' || report.id::text END AS "evidenceUrl",report.created_at AS "createdAt",e.full_name AS "reportedBy" FROM asset_condition_reports report LEFT JOIN employees e ON e.id=report.reported_by AND e.tenant_id=report.tenant_id WHERE report.tenant_id=$1 AND report.asset_id=$2 ORDER BY report.created_at DESC`, [user.tenantId, req.params.assetId]),
    ]); return { ...current, assignments: assignments.rows, conditionReports: reports.rows }; }); res.json({ success: true, asset }); } catch (error) { sendError(res, error, 'Unable to load asset.'); }
  });

  app.patch('/api/hr/assets/:assetId', demoAuth, requirePermission('assets.manage'), async (req, res) => {
    const user = req.authUser!; if (!uuid(req.params.assetId)) return res.status(400).json({ success: false, error: 'Invalid asset id.' });
    try { const input = assetInput(req.body || {}, true); if (!Object.keys(input).length) throw new RouteError('No asset changes supplied.', 400); const asset = await withTenant(user.tenantId, async (client) => {
      const current = await lockedAsset(client, user.tenantId, req.params.assetId); if (input.condition === 'unusable' && current.status === 'assigned') throw new RouteError('Return an assigned asset before marking it unusable.', 409);
      const columns = Object.keys(input); const values = columns.map((column) => input[column]); const result = await client.query(`UPDATE assets SET ${columns.map((column, index) => `${column}=$${index + 1}`).join(', ')},updated_at=NOW() WHERE id=$${values.length + 1} AND tenant_id=$${values.length + 2} RETURNING id,asset_tag AS "assetTag",name,category,status,condition`, [...values, req.params.assetId, user.tenantId]);
      await recordAuditEvent(client, { tenantId: user.tenantId, actorId: user.employeeId, action: 'asset.updated', targetType: 'asset', targetId: current.id, metadata: { assetTag: current.assetTag } }); return result.rows[0];
    }); res.json({ success: true, asset }); } catch (error) { sendError(res, error, 'Unable to update asset.'); }
  });

  app.post('/api/hr/assets/:assetId/assign', demoAuth, requirePermission('assets.assign'), async (req, res) => {
    const user = req.authUser!; const employeeId = req.body?.employeeId; if (!uuid(req.params.assetId) || !uuid(employeeId)) return res.status(400).json({ success: false, error: 'Invalid asset or employee.' });
    try { await withTenant(user.tenantId, async (client) => { const asset = await lockedAsset(client, user.tenantId, req.params.assetId); if (asset.status !== 'available') throw new RouteError('Asset is not available.', 409);
      const employee = await client.query(`SELECT id FROM employees WHERE id=$1 AND tenant_id=$2 AND is_active=true AND employment_status='active'`, [employeeId,user.tenantId]); if (!employee.rows[0]) throw new RouteError('Employee is not active.',400);
      await client.query(`INSERT INTO asset_assignments(tenant_id,asset_id,employee_id,assigned_by,expected_return_at) VALUES($1,$2,$3,$4,$5)`,[user.tenantId,req.params.assetId,employeeId,user.employeeId,optionalDate(req.body?.expectedReturnAt)]); await client.query(`UPDATE assets SET status='assigned',updated_at=NOW() WHERE id=$1 AND tenant_id=$2`,[req.params.assetId,user.tenantId]);
      await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'asset.assigned',targetType:'asset',targetId:req.params.assetId,metadata:{assetTag:asset.assetTag,targetEmployeeId:employeeId}}); }); res.json({success:true}); } catch(error){sendError(res,error,'Unable to assign asset.');}
  });

  app.post('/api/hr/assets/:assetId/return', demoAuth, requirePermission('assets.return'), async (req, res) => {
    const user=req.authUser!, condition=req.body?.condition; if(!uuid(req.params.assetId)||!conditions.has(condition)) return res.status(400).json({success:false,error:'Invalid return.'});
    try { await withTenant(user.tenantId,async(client)=>{const asset=await lockedAsset(client,user.tenantId,req.params.assetId);if(asset.status!=='assigned')throw new RouteError('Asset has no active assignment.',409);const notes=optionalText(req.body?.notes,4000);const assignment=await client.query(`UPDATE asset_assignments SET returned_at=NOW(),return_condition=$3,return_notes=$4,status=CASE WHEN $3 IN ('damaged','unusable') THEN 'damaged' ELSE 'returned' END,updated_at=NOW() WHERE tenant_id=$1 AND asset_id=$2 AND status='active' RETURNING id`,[user.tenantId,req.params.assetId,condition,notes]);if(!assignment.rows[0])throw new RouteError('No active assignment found.',409);const next=['damaged','unusable'].includes(condition)?'maintenance':'available';await client.query(`UPDATE assets SET status=$3,condition=$4,updated_at=NOW() WHERE id=$1 AND tenant_id=$2`,[req.params.assetId,user.tenantId,next,condition]);if(next==='maintenance')await client.query(`INSERT INTO asset_condition_reports(tenant_id,asset_id,assignment_id,reported_by,condition,notes) VALUES($1,$2,$3,$4,$5,$6)`,[user.tenantId,req.params.assetId,assignment.rows[0].id,user.employeeId,condition,notes]);await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'asset.returned',targetType:'asset',targetId:req.params.assetId,metadata:{assetTag:asset.assetTag,condition}});});res.json({success:true});}catch(error){sendError(res,error,'Unable to return asset.');}
  });

  app.post('/api/hr/assets/:assetId/report-condition', demoAuth, requirePermission('assets.manage'), async (req,res)=>{
    const user=req.authUser!, condition=req.body?.condition;if(!uuid(req.params.assetId)||!conditions.has(condition))return res.status(400).json({success:false,error:'Invalid condition report.'});
    try{await withTenant(user.tenantId,async(client)=>{const asset=await lockedAsset(client,user.tenantId,req.params.assetId);if(asset.status==='lost'||asset.status==='retired')throw new RouteError('Condition cannot be updated for this asset state.',409);const assignment=await client.query(`SELECT id FROM asset_assignments WHERE tenant_id=$1 AND asset_id=$2 AND status='active'`,[user.tenantId,req.params.assetId]);await client.query(`INSERT INTO asset_condition_reports(tenant_id,asset_id,assignment_id,reported_by,condition,notes) VALUES($1,$2,$3,$4,$5,$6)`,[user.tenantId,req.params.assetId,assignment.rows[0]?.id||null,user.employeeId,condition,optionalText(req.body?.notes,4000)]);await client.query(`UPDATE assets SET condition=$3,status=CASE WHEN $3 IN ('damaged','unusable') AND status='available' THEN 'maintenance' ELSE status END,updated_at=NOW() WHERE id=$1 AND tenant_id=$2`,[req.params.assetId,user.tenantId,condition]);await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'asset.condition_reported',targetType:'asset',targetId:req.params.assetId,metadata:{assetTag:asset.assetTag,condition}});});res.status(201).json({success:true});}catch(error){sendError(res,error,'Unable to report asset condition.');}
  });

  (['mark-lost','retire'] as const).forEach((operation)=>app.post(`/api/hr/assets/:assetId/${operation}`,demoAuth,requirePermission('assets.manage'),async(req,res)=>{const user=req.authUser!,next=operation==='mark-lost'?'lost':'retired';if(!uuid(req.params.assetId))return res.status(400).json({success:false,error:'Invalid asset id.'});try{await withTenant(user.tenantId,async(client)=>{const asset=await lockedAsset(client,user.tenantId,req.params.assetId);if(asset.status===next)throw new RouteError(`Asset is already ${next}.`,409);if(['assigned','lost','retired'].includes(asset.status))throw new RouteError('Return the asset before changing its final state.',409);await client.query(`UPDATE assets SET status=$3,updated_at=NOW() WHERE id=$1 AND tenant_id=$2`,[req.params.assetId,user.tenantId,next]);await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:operation==='mark-lost'?'asset.lost':'asset.retired',targetType:'asset',targetId:req.params.assetId,metadata:{assetTag:asset.assetTag}});});res.json({success:true});}catch(error){sendError(res,error,`Unable to ${operation} asset.`);}}));

  app.get('/api/hr/software-licenses',demoAuth,requirePermission('assets.view'),async(req,res)=>{const user=req.authUser!,{value,size,offset}=page(req.query),search=cleanText(req.query.search,100);try{const result=await withTenant(user.tenantId,async(client)=>{const where=`WHERE license.tenant_id=$1 AND ($2='' OR license.name ILIKE '%' || $2 || '%' OR COALESCE(license.vendor,'') ILIKE '%' || $2 || '%')`,params=[user.tenantId,search];const [licenses,count,summary]=await Promise.all([client.query(`SELECT license.id,license.name,license.vendor,license.license_reference_masked AS "licenseReferenceMasked",license.vault_reference AS "vaultReference",license.seat_count AS "seatCount",license.seats_used AS "seatsUsed",license.expires_at AS "expiresAt",license.notes FROM software_licenses license ${where} ORDER BY license.created_at DESC LIMIT $3 OFFSET $4`,[...params,size,offset]),client.query(`SELECT COUNT(*)::integer AS total FROM software_licenses license ${where}`,params),client.query(`SELECT COUNT(*)::integer AS "totalLicenses",COALESCE(SUM(seat_count),0)::integer AS "totalSeats",COALESCE(SUM(seats_used),0)::integer AS "seatsUsed",COUNT(*) FILTER(WHERE expires_at BETWEEN CURRENT_DATE AND CURRENT_DATE+30)::integer AS "expiringSoon" FROM software_licenses WHERE tenant_id=$1`,[user.tenantId])]);return{licenses:licenses.rows,total:count.rows[0].total,summary:summary.rows[0]};});res.json({success:true,page:value,pageSize:size,...result});}catch(error){sendError(res,error,'Unable to load software licenses.');}});

  app.post('/api/hr/software-licenses',demoAuth,requirePermission('assets.manage'),async(req,res)=>{const user=req.authUser!,body=req.body||{},name=cleanText(body.name,180),seatCount=body.seatCount===null||body.seatCount===undefined||body.seatCount===''?null:Number(body.seatCount);if(!name||(seatCount!==null&&(!Number.isInteger(seatCount)||seatCount<0)))return res.status(400).json({success:false,error:'Invalid license details.'});try{const license=await withTenant(user.tenantId,async(client)=>{const result=await client.query(`INSERT INTO software_licenses(tenant_id,name,vendor,license_reference_masked,vault_reference,seat_count,expires_at,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,name,seat_count AS "seatCount",seats_used AS "seatsUsed",expires_at AS "expiresAt"`,[user.tenantId,name,optionalText(body.vendor,120),optionalText(body.licenseReferenceMasked,120),optionalText(body.vaultReference,255),seatCount,optionalDate(body.expiresAt),optionalText(body.notes,4000)]);await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'software_license.created',targetType:'software_license',targetId:result.rows[0].id,metadata:{licenseName:name}});return result.rows[0];});res.status(201).json({success:true,license});}catch(error){sendError(res,error,'Unable to create software license.');}});

  app.get('/api/hr/software-licenses/:licenseId',demoAuth,requirePermission('assets.view'),async(req,res)=>{const user=req.authUser!;if(!uuid(req.params.licenseId))return res.status(400).json({success:false,error:'Invalid license id.'});try{const license=await withTenant(user.tenantId,async(client)=>{const current=await client.query(`SELECT id,name,vendor,license_reference_masked AS "licenseReferenceMasked",vault_reference AS "vaultReference",seat_count AS "seatCount",seats_used AS "seatsUsed",expires_at AS "expiresAt",notes FROM software_licenses WHERE id=$1 AND tenant_id=$2`,[req.params.licenseId,user.tenantId]);if(!current.rows[0])throw new RouteError('Software license not found.',404);const assignments=await client.query(`SELECT assignment.id,assignment.employee_id AS "employeeId",employee.full_name AS "employeeName",assignment.assigned_at AS "assignedAt",assignment.revoked_at AS "revokedAt" FROM software_license_assignments assignment JOIN employees employee ON employee.id=assignment.employee_id AND employee.tenant_id=assignment.tenant_id WHERE assignment.tenant_id=$1 AND assignment.software_license_id=$2 ORDER BY assignment.assigned_at DESC`,[user.tenantId,req.params.licenseId]);return{...current.rows[0],assignments:assignments.rows};});res.json({success:true,license});}catch(error){sendError(res,error,'Unable to load software license.');}});

  app.patch('/api/hr/software-licenses/:licenseId',demoAuth,requirePermission('assets.manage'),async(req,res)=>{const user=req.authUser!,body=req.body||{};if(!uuid(req.params.licenseId))return res.status(400).json({success:false,error:'Invalid license id.'});try{const fields:Record<string,unknown>={};if(Object.hasOwn(body,'name')){const name=cleanText(body.name,180);if(!name)throw new RouteError('License name is required.',400);fields.name=name;}if(Object.hasOwn(body,'vendor'))fields.vendor=optionalText(body.vendor,120);if(Object.hasOwn(body,'licenseReferenceMasked'))fields.license_reference_masked=optionalText(body.licenseReferenceMasked,120);if(Object.hasOwn(body,'vaultReference'))fields.vault_reference=optionalText(body.vaultReference,255);if(Object.hasOwn(body,'expiresAt'))fields.expires_at=optionalDate(body.expiresAt);if(Object.hasOwn(body,'notes'))fields.notes=optionalText(body.notes,4000);if(Object.hasOwn(body,'seatCount')){const count=body.seatCount===null||body.seatCount===''?null:Number(body.seatCount);if(count!==null&&(!Number.isInteger(count)||count<0))throw new RouteError('Invalid seat count.',400);fields.seat_count=count;}if(!Object.keys(fields).length)throw new RouteError('No license changes supplied.',400);const license=await withTenant(user.tenantId,async(client)=>{const locked=await client.query(`SELECT id,seats_used FROM software_licenses WHERE id=$1 AND tenant_id=$2 FOR UPDATE`,[req.params.licenseId,user.tenantId]);if(!locked.rows[0])throw new RouteError('Software license not found.',404);if(fields.seat_count!==undefined&&fields.seat_count!==null&&Number(fields.seat_count)<locked.rows[0].seats_used)throw new RouteError('Seat count cannot be lower than active assignments.',409);const columns=Object.keys(fields),values=columns.map((column)=>fields[column]);const result=await client.query(`UPDATE software_licenses SET ${columns.map((column,index)=>`${column}=$${index+1}`).join(', ')},updated_at=NOW() WHERE id=$${values.length+1} AND tenant_id=$${values.length+2} RETURNING id,name,seat_count AS "seatCount",seats_used AS "seatsUsed"`,[...values,req.params.licenseId,user.tenantId]);await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'software_license.updated',targetType:'software_license',targetId:req.params.licenseId,metadata:{licenseName:result.rows[0].name}});return result.rows[0];});res.json({success:true,license});}catch(error){sendError(res,error,'Unable to update software license.');}});

  app.post('/api/hr/software-licenses/:licenseId/assign',demoAuth,requirePermission('assets.assign'),async(req,res)=>{const user=req.authUser!,employeeId=req.body?.employeeId;if(!uuid(req.params.licenseId)||!uuid(employeeId))return res.status(400).json({success:false,error:'Invalid license or employee.'});try{await withTenant(user.tenantId,async(client)=>{const license=await client.query(`SELECT id,name,seat_count,seats_used,expires_at FROM software_licenses WHERE id=$1 AND tenant_id=$2 FOR UPDATE`,[req.params.licenseId,user.tenantId]);if(!license.rows[0])throw new RouteError('Software license not found.',404);if(license.rows[0].expires_at&&String(license.rows[0].expires_at)<new Date().toISOString().slice(0,10))throw new RouteError('Expired licenses cannot be assigned.',409);if(license.rows[0].seat_count!==null&&license.rows[0].seats_used>=license.rows[0].seat_count)throw new RouteError('No license seats are available.',409);const employee=await client.query(`SELECT id FROM employees WHERE id=$1 AND tenant_id=$2 AND is_active=true AND employment_status='active'`,[employeeId,user.tenantId]);if(!employee.rows[0])throw new RouteError('Employee is not active.',400);await client.query(`INSERT INTO software_license_assignments(tenant_id,software_license_id,employee_id,assigned_by) VALUES($1,$2,$3,$4)`,[user.tenantId,req.params.licenseId,employeeId,user.employeeId]);await client.query(`UPDATE software_licenses SET seats_used=seats_used+1,updated_at=NOW() WHERE id=$1 AND tenant_id=$2`,[req.params.licenseId,user.tenantId]);await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'software_license.assigned',targetType:'software_license',targetId:req.params.licenseId,metadata:{licenseName:license.rows[0].name,targetEmployeeId:employeeId}});});res.json({success:true});}catch(error){sendError(res,error,'Unable to assign software license.');}});

  app.post('/api/hr/software-licenses/:licenseId/revoke',demoAuth,requirePermission('assets.assign'),async(req,res)=>{const user=req.authUser!,assignmentId=req.body?.assignmentId;if(!uuid(req.params.licenseId)||!uuid(assignmentId))return res.status(400).json({success:false,error:'Invalid license assignment.'});try{await withTenant(user.tenantId,async(client)=>{const license=await client.query(`SELECT id,name FROM software_licenses WHERE id=$1 AND tenant_id=$2 FOR UPDATE`,[req.params.licenseId,user.tenantId]);if(!license.rows[0])throw new RouteError('Software license not found.',404);const assignment=await client.query(`UPDATE software_license_assignments SET revoked_at=NOW() WHERE id=$1 AND tenant_id=$2 AND software_license_id=$3 AND revoked_at IS NULL RETURNING id`,[assignmentId,user.tenantId,req.params.licenseId]);if(!assignment.rows[0])throw new RouteError('Active license assignment not found.',409);await client.query(`UPDATE software_licenses SET seats_used=GREATEST(0,seats_used-1),updated_at=NOW() WHERE id=$1 AND tenant_id=$2`,[req.params.licenseId,user.tenantId]);await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'software_license.revoked',targetType:'software_license',targetId:req.params.licenseId,metadata:{licenseName:license.rows[0].name}});});res.json({success:true});}catch(error){sendError(res,error,'Unable to revoke software license.');}});

  app.get('/api/me/assets',demoAuth,async(req,res)=>{const user=req.authUser!;try{const assets=await withTenant(user.tenantId,(client)=>client.query(`SELECT a.id,a.asset_tag AS "assetTag",a.name,a.category,a.serial_number AS "serialNumber",a.condition,assignment.assigned_at AS "assignedAt",assignment.expected_return_at AS "expectedReturnAt",assignment.returned_at AS "returnedAt",assignment.status FROM asset_assignments assignment JOIN assets a ON a.id=assignment.asset_id AND a.tenant_id=assignment.tenant_id WHERE assignment.tenant_id=$1 AND assignment.employee_id=$2 ORDER BY assignment.assigned_at DESC`,[user.tenantId,user.employeeId]));res.json({success:true,assets:assets.rows});}catch(error){sendError(res,error,'Unable to load your equipment.');}});

  app.post('/api/me/assets/:assetId/report-condition',demoAuth,async(req,res)=>{const user=req.authUser!,condition=req.body?.condition;if(!uuid(req.params.assetId)||!conditions.has(condition))return res.status(400).json({success:false,error:'Invalid condition report.'});try{await withTenant(user.tenantId,async(client)=>{const assignment=await client.query(`SELECT assignment.id,a.asset_tag FROM asset_assignments assignment JOIN assets a ON a.id=assignment.asset_id AND a.tenant_id=assignment.tenant_id WHERE assignment.tenant_id=$1 AND assignment.asset_id=$2 AND assignment.employee_id=$3 AND assignment.status='active' FOR UPDATE OF assignment`,[user.tenantId,req.params.assetId,user.employeeId]);if(!assignment.rows[0])throw new RouteError('Active asset assignment not found.',404);await client.query(`INSERT INTO asset_condition_reports(tenant_id,asset_id,assignment_id,reported_by,condition,notes) VALUES($1,$2,$3,$4,$5,$6)`,[user.tenantId,req.params.assetId,assignment.rows[0].id,user.employeeId,condition,optionalText(req.body?.notes,4000)]);await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'asset.condition_reported',targetType:'asset',targetId:req.params.assetId,metadata:{assetTag:assignment.rows[0].asset_tag,condition}});});res.status(201).json({success:true});}catch(error){sendError(res,error,'Unable to report asset condition.');}});
}
