import type express from 'express';
import { withTenant } from '../../lib/hr-background';
import { recordAuditEvent } from '../audit/audit-events';

type Dependencies={demoAuth:express.RequestHandler;requirePermission:(key:string)=>express.RequestHandler};
const uuid=(value:string)=>/^[0-9a-f]{8}-[0-9a-f-]{34}$/i.test(value);
const categories=new Set(['laptop','desktop','monitor','phone','tablet','accessory','badge','furniture','other']); const statuses=new Set(['available','assigned','maintenance','lost','retired']); const conditions=new Set(['new','good','fair','damaged','unusable']);
export function registerAssetRoutes(app:express.Express,{demoAuth,requirePermission}:Dependencies){
 app.get('/api/hr/assets',demoAuth,requirePermission('assets.view'),async(req,res)=>{const u=req.authUser!;const page=Math.max(1,Number(req.query.page)||1),size=Math.min(100,Math.max(1,Number(req.query.pageSize)||25));const data=await withTenant(u.tenantId,c=>c.query(`SELECT a.id,a.asset_tag AS "assetTag",a.name,a.category,a.status,a.condition,a.serial_number AS "serialNumber",a.warranty_expires_at AS "warrantyExpiresAt",e.full_name AS "assignedEmployee",x.assigned_at AS "assignedAt",x.expected_return_at AS "expectedReturnAt" FROM assets a LEFT JOIN asset_assignments x ON x.asset_id=a.id AND x.tenant_id=a.tenant_id AND x.status='active' LEFT JOIN employees e ON e.id=x.employee_id AND e.tenant_id=a.tenant_id WHERE a.tenant_id=$1 AND ($2='' OR a.name ILIKE '%'||$2||'%' OR a.asset_tag ILIKE '%'||$2||'%') AND ($3='' OR a.category=$3) AND ($4='' OR a.status=$4) ORDER BY a.created_at DESC LIMIT $5 OFFSET $6`,[u.tenantId,String(req.query.search||'').slice(0,100),String(req.query.category||''),String(req.query.status||''),size,(page-1)*size]));res.json({success:true,page,pageSize:size,assets:data.rows});});
 app.post('/api/hr/assets',demoAuth,requirePermission('assets.manage'),async(req,res)=>{const u=req.authUser!,b=req.body||{};if(!String(b.assetTag||'').trim()||!String(b.name||'').trim()||!categories.has(b.category)||!conditions.has(b.condition||'good'))return res.status(400).json({success:false,error:'Invalid asset details.'});try{const asset=await withTenant(u.tenantId,async c=>{const r=await c.query(`INSERT INTO assets(tenant_id,asset_tag,name,category,manufacturer,model,serial_number,status,condition,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,'available',$8,$9) RETURNING id,asset_tag AS "assetTag",name,category,status,condition`,[u.tenantId,String(b.assetTag).trim(),String(b.name).trim(),b.category,b.manufacturer||null,b.model||null,b.serialNumber||null,b.condition||'good',u.employeeId]);await recordAuditEvent(c,{tenantId:u.tenantId,actorId:u.employeeId,action:'asset.created',targetType:'asset',targetId:r.rows[0].id,metadata:{assetTag:r.rows[0].assetTag,category:b.category}});return r.rows[0]});res.status(201).json({success:true,asset});}catch(e){res.status((e as any).code==='23505'?409:500).json({success:false,error:(e as any).code==='23505'?'Asset tag already exists.':'Unable to create asset.'})}});
 app.post('/api/hr/assets/:id/assign',demoAuth,requirePermission('assets.assign'),async(req,res)=>{const u=req.authUser!,id=req.params.id,employeeId=req.body?.employeeId;if(!uuid(id)||!uuid(employeeId))return res.status(400).json({success:false,error:'Invalid asset or employee.'});try{await withTenant(u.tenantId,async c=>{const a=await c.query(`SELECT id,status,asset_tag FROM assets WHERE id=$1 AND tenant_id=$2 FOR UPDATE`,[id,u.tenantId]);if(!a.rows[0])throw Object.assign(new Error('Asset not found.'),{status:404});if(a.rows[0].status!=='available')throw Object.assign(new Error('Asset is not available.'),{status:409});const e=await c.query(`SELECT id FROM employees WHERE id=$1 AND tenant_id=$2 AND is_active=true AND employment_status='active'`,[employeeId,u.tenantId]);if(!e.rows[0])throw Object.assign(new Error('Employee is not active.'),{status:400});await c.query(`INSERT INTO asset_assignments(tenant_id,asset_id,employee_id,assigned_by,expected_return_at) VALUES($1,$2,$3,$4,$5)`,[u.tenantId,id,employeeId,u.employeeId,req.body?.expectedReturnAt||null]);await c.query(`UPDATE assets SET status='assigned',updated_at=NOW() WHERE id=$1`,[id]);await recordAuditEvent(c,{tenantId:u.tenantId,actorId:u.employeeId,action:'asset.assigned',targetType:'asset',targetId:id,metadata:{assetTag:a.rows[0].asset_tag,targetEmployeeId:employeeId}})});res.json({success:true});}catch(e:any){res.status(e.status||500).json({success:false,error:e.message||'Unable to assign asset.'})}});
 app.post('/api/hr/assets/:id/return',demoAuth,requirePermission('assets.return'),async(req,res)=>{const u=req.authUser!,id=req.params.id,condition=req.body?.condition;if(!uuid(id)||!conditions.has(condition))return res.status(400).json({success:false,error:'Invalid return.'});try{await withTenant(u.tenantId,async c=>{const a=await c.query(`SELECT id,asset_tag FROM assets WHERE id=$1 AND tenant_id=$2 FOR UPDATE`,[id,u.tenantId]);const x=await c.query(`UPDATE asset_assignments SET returned_at=NOW(),return_condition=$3,status=CASE WHEN $3 IN ('damaged','unusable') THEN 'damaged' ELSE 'returned' END,updated_at=NOW() WHERE tenant_id=$1 AND asset_id=$2 AND status='active' RETURNING id`,[u.tenantId,id,condition]);if(!a.rows[0])throw Object.assign(new Error('Asset not found.'),{status:404});if(!x.rows[0])throw Object.assign(new Error('No active assignment found.'),{status:409});const state=['damaged','unusable'].includes(condition)?'maintenance':'available';await c.query(`UPDATE assets SET status=$2,condition=$3,updated_at=NOW() WHERE id=$1`,[id,state,condition]);if(state==='maintenance')await c.query(`INSERT INTO asset_condition_reports(tenant_id,asset_id,assignment_id,reported_by,condition,notes) VALUES($1,$2,$3,$4,$5,$6)`,[u.tenantId,id,x.rows[0].id,u.employeeId,condition,req.body?.notes||null]);await recordAuditEvent(c,{tenantId:u.tenantId,actorId:u.employeeId,action:'asset.returned',targetType:'asset',targetId:id,metadata:{assetTag:a.rows[0].asset_tag,condition}})});res.json({success:true});}catch(e:any){res.status(e.status||500).json({success:false,error:e.message||'Unable to return asset.'})}});
 app.get('/api/me/assets',demoAuth,async(req,res)=>{const u=req.authUser!;const data=await withTenant(u.tenantId,c=>c.query(`SELECT a.id,a.asset_tag AS "assetTag",a.name,a.category,a.serial_number AS "serialNumber",a.condition,x.assigned_at AS "assignedAt",x.expected_return_at AS "expectedReturnAt",x.status FROM asset_assignments x JOIN assets a ON a.id=x.asset_id AND a.tenant_id=x.tenant_id WHERE x.tenant_id=$1 AND x.employee_id=$2 ORDER BY x.assigned_at DESC`,[u.tenantId,u.employeeId]));res.json({success:true,assets:data.rows});});
}
