import type { EntityChoices, EntityRoute } from '../../lib/router-entities';
export function EntityClarification({route,isRtl,busy,onChoose}:{route:EntityRoute;isRtl:boolean;busy:boolean;onChoose:(type:keyof EntityChoices,id:string)=>void}) {
 const text=(en:string,ar:string)=>isRtl?ar:en;
 const buttonClass='w-full min-w-0 whitespace-normal break-words rounded border p-2 text-start hover:bg-emerald-500/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 disabled:opacity-50';
 return <div dir={isRtl?'rtl':'ltr'} className="mt-2 space-y-2" data-entity-status={route.status}>
  {route.entities.filter(entity=>entity.status==='ambiguous').map(entity=><fieldset key={entity.type} disabled={busy} className="min-w-0 space-y-2"><legend>{text('Which '+entity.type.replaceAll('_',' ')+' did you mean?','أي سجل تقصد؟')}</legend>{entity.candidates?.map(candidate=><button key={candidate.id} type="button" className={buttonClass} onClick={()=>onChoose(entity.type,candidate.id)}>{candidate.label}</button>)}{entity.truncated&&<p>{text('More matches exist. Enter a full name or identifier.','توجد نتائج أخرى. أدخل الاسم الكامل أو المعرّف.')}</p>}</fieldset>)}
  {route.entities.some(entity=>entity.type==='location')&&<p>{text("Location refers to the employee's current team, not the incident location.",'الموقع يشير إلى فريق الموظف الحالي وليس موقع الواقعة.')}</p>}
  {route.status==='ambiguous'&&route.cases.length>0&&<fieldset disabled={busy} className="min-w-0 space-y-2"><legend>{text('Which case did you mean?','أي قضية تقصد؟')}</legend>{route.cases.map(row=><button key={row.id} type="button" className={buttonClass} onClick={()=>onChoose('case',row.id)}>{row.reference} · {row.title}</button>)}{route.cases.length===8&&<p>{text('Use a case reference to narrow the results.','استخدم رقم القضية لتحديد النتائج.')}</p>}</fieldset>}
  {route.operational&&<p className="text-xs">{text('Read-only operational result · date convention: ','نتيجة تشغيلية للقراءة فقط · توقيت التاريخ: ')}{route.operational.timeZone} {route.operational.dateWindow.from} {route.operational.dateWindow.to&&'→ '+route.operational.dateWindow.to}</p>}{route.summary&&<p>{text(route.summary,({'Operational tickets':'طلبات الدعم التشغيلية','Operational hires':'تهيئة الموظفين الجدد','Operational candidates':'مرشحو التوظيف','Operational jobs':'الوظائف','Operational interviews':'المقابلات','Operational offers':'العروض','Open roles':'الوظائف المتاحة','Hiring candidates':'مرشحو التوظيف','Equipment assignments':'العهدة المسندة','Support requests':'طلبات الدعم','Interviews today (company database date)':'مقابلات اليوم (تاريخ قاعدة بيانات الشركة)','Review the prefilled support form; nothing has been submitted.':'راجع نموذج الدعم المعبأ؛ لم يتم إرسال أي طلب.'} as Record<string,string>)[route.summary]||route.summary)} {route.total!==undefined&&<span>{route.total}</span>}</p>}{route.items&&<ul>{route.items.map(row=><li key={row.id} className="break-words">{row.label} · {row.detail}</li>)}</ul>}
  {route.status==='resolved'&&route.caseId&&<p>{route.cases.find(row=>row.id===route.caseId)?.reference} · {route.cases.find(row=>row.id===route.caseId)?.title}</p>}
 </div>;
}
