BEGIN;
ALTER TABLE hiring_jobs ADD COLUMN IF NOT EXISTS application_questions jsonb NOT NULL DEFAULT '[]';
ALTER TABLE hiring_applicants ADD COLUMN IF NOT EXISTS application_answers jsonb NOT NULL DEFAULT '{}';
ALTER TABLE hiring_applicants ADD COLUMN IF NOT EXISTS question_snapshot jsonb NOT NULL DEFAULT '[]';
ALTER TABLE hiring_applicants ADD COLUMN IF NOT EXISTS screening_flags jsonb NOT NULL DEFAULT '[]';
CREATE TABLE IF NOT EXISTS hiring_application_reviews(id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id uuid NOT NULL REFERENCES tenants(id),applicant_id uuid NOT NULL,reviewer_id uuid NOT NULL,recommendation text NOT NULL CHECK(recommendation IN('advance','hold','reject')),score integer NOT NULL CHECK(score BETWEEN 1 AND 5),notes varchar(4000),created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(applicant_id,tenant_id) REFERENCES hiring_applicants(id,tenant_id),FOREIGN KEY(reviewer_id,tenant_id) REFERENCES employees(id,tenant_id));
ALTER TABLE hiring_offers ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1 CHECK(version>0);
ALTER TABLE hiring_offers ADD COLUMN IF NOT EXISTS root_id uuid;
UPDATE hiring_offers SET root_id=id WHERE root_id IS NULL;
ALTER TABLE hiring_offers ALTER COLUMN root_id SET NOT NULL;
ALTER TABLE hiring_offers ALTER COLUMN root_id SET DEFAULT uuid_generate_v4();
ALTER TABLE hiring_offers ADD COLUMN IF NOT EXISTS supersedes_id uuid;
ALTER TABLE hiring_offers ADD COLUMN IF NOT EXISTS changed_fields text[] NOT NULL DEFAULT '{}';
ALTER TABLE hiring_offers ADD COLUMN IF NOT EXISTS public_token_hash text;
CREATE UNIQUE INDEX IF NOT EXISTS hiring_offer_token_hash ON hiring_offers(public_token_hash) WHERE public_token_hash IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS hiring_offer_version ON hiring_offers(tenant_id,root_id,version);
ALTER TABLE hiring_offers ADD COLUMN IF NOT EXISTS terms jsonb NOT NULL DEFAULT '{}';
UPDATE hiring_offers o SET terms=jsonb_build_object('title',a.position_title,'department',j.department,'departmentId',j.department_id,'managerId',j.manager_id,'locationId',j.location_id,'location',l.name,'employmentType',j.employment_type) FROM hiring_applicants a LEFT JOIN hiring_jobs j ON j.tenant_id=a.tenant_id AND j.id=a.job_id LEFT JOIN company_locations l ON l.tenant_id=j.tenant_id AND l.id=j.location_id WHERE o.tenant_id=a.tenant_id AND o.applicant_id=a.id AND o.terms='{}'::jsonb;
ALTER TABLE hiring_offers DROP CONSTRAINT IF EXISTS hiring_offers_status_check;
ALTER TABLE hiring_offers ADD CONSTRAINT hiring_offers_status_check CHECK(status IN('draft','sent','accepted','rejected','withdrawn','expired','superseded'));
ALTER TABLE hiring_offers ADD COLUMN IF NOT EXISTS signature_status text NOT NULL DEFAULT 'not_configured' CHECK(signature_status IN('not_configured','pending','signed','failed'));
ALTER TABLE hiring_offers ADD COLUMN IF NOT EXISTS signature_at timestamptz;
ALTER TABLE hiring_offers ADD COLUMN IF NOT EXISTS signature_provider_reference text;
ALTER TABLE hiring_offers ADD COLUMN IF NOT EXISTS signed_document_version integer;
ALTER TABLE hiring_offers ADD COLUMN IF NOT EXISTS acknowledged_at timestamptz;
ALTER TABLE hiring_onboarding_tasks ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'custom' CHECK(kind IN('access','equipment','policy','orientation','payroll','manager_meeting','badge','first_shift','custom'));
UPDATE hiring_onboarding_tasks SET kind=CASE title WHEN 'Arrange equipment' THEN 'equipment' WHEN 'Plan first shift' THEN 'first_shift' WHEN 'Review employee profile' THEN 'access' ELSE kind END WHERE kind='custom';
ALTER TABLE hiring_onboarding_tasks ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','in_progress','blocked','completed'));
UPDATE hiring_onboarding_tasks SET status='completed' WHERE completed_at IS NOT NULL AND status<>'completed';
ALTER TABLE hiring_onboarding_tasks ADD COLUMN IF NOT EXISTS owner_id uuid;
ALTER TABLE hiring_onboarding_tasks ADD COLUMN IF NOT EXISTS due_on date;
ALTER TABLE hiring_onboarding_tasks ADD COLUMN IF NOT EXISTS notes varchar(4000);
ALTER TABLE hiring_onboarding_tasks ADD COLUMN IF NOT EXISTS dependency_id uuid;
ALTER TABLE hiring_onboarding_tasks ADD COLUMN IF NOT EXISTS template_id uuid;
CREATE UNIQUE INDEX IF NOT EXISTS hiring_onboarding_task_tenant_id ON hiring_onboarding_tasks(id,tenant_id);
CREATE TABLE IF NOT EXISTS hiring_onboarding_templates(id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id uuid NOT NULL REFERENCES tenants(id),name varchar(160) NOT NULL,tasks jsonb NOT NULL,created_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,name),FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,tenant_id));
CREATE TABLE IF NOT EXISTS hiring_onboarding_template_applications(tenant_id uuid NOT NULL,employee_id uuid NOT NULL,template_id uuid NOT NULL,applied_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,employee_id,template_id),FOREIGN KEY(employee_id,tenant_id) REFERENCES employees(id,tenant_id),FOREIGN KEY(template_id,tenant_id) REFERENCES hiring_onboarding_templates(id,tenant_id),FOREIGN KEY(applied_by,tenant_id) REFERENCES employees(id,tenant_id));
DO $$ BEGIN
IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='onboarding_owner_tenant') THEN ALTER TABLE hiring_onboarding_tasks ADD CONSTRAINT onboarding_owner_tenant FOREIGN KEY(owner_id,tenant_id) REFERENCES employees(id,tenant_id); END IF;
IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='onboarding_dependency_tenant') THEN ALTER TABLE hiring_onboarding_tasks ADD CONSTRAINT onboarding_dependency_tenant FOREIGN KEY(dependency_id,tenant_id) REFERENCES hiring_onboarding_tasks(id,tenant_id); END IF;
IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='onboarding_template_tenant') THEN ALTER TABLE hiring_onboarding_tasks ADD CONSTRAINT onboarding_template_tenant FOREIGN KEY(template_id,tenant_id) REFERENCES hiring_onboarding_templates(id,tenant_id); END IF;
IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='offer_supersedes_tenant') THEN ALTER TABLE hiring_offers ADD CONSTRAINT offer_supersedes_tenant FOREIGN KEY(supersedes_id,tenant_id) REFERENCES hiring_offers(id,tenant_id); END IF;
END $$;
DO $$ DECLARE tab text; BEGIN FOREACH tab IN ARRAY ARRAY['hiring_application_reviews','hiring_onboarding_templates','hiring_onboarding_template_applications'] LOOP
EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',tab);EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',tab);EXECUTE format('DROP POLICY IF EXISTS hiring_tenant ON %I',tab);EXECUTE format($p$CREATE POLICY hiring_tenant ON %I USING(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid) WITH CHECK(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid)$p$,tab);END LOOP;END $$;
CREATE OR REPLACE FUNCTION public.stanza_public_offer_tenant(token_hash text) RETURNS TABLE(tenant_id uuid) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ SELECT o.tenant_id FROM public.hiring_offers o WHERE o.public_token_hash=token_hash AND o.status IN('sent','accepted','rejected') AND o.expires_on>=current_date LIMIT 1 $$;
REVOKE ALL ON FUNCTION public.stanza_public_offer_tenant(text) FROM PUBLIC;
INSERT INTO tenant_permissions(permission_key,label,description) VALUES('hiring.review_applications','Review applications','Record structured screening reviews.'),('hiring.onboarding.view','View onboarding','View new-hire checklist state.'),('hiring.onboarding.manage','Manage onboarding','Configure templates and explicitly update checklists.') ON CONFLICT DO NOTHING;
INSERT INTO tenant_role_permissions(tenant_id,role_id,permission_key) SELECT r.tenant_id,r.id,p.permission_key FROM tenant_roles r JOIN tenant_permissions p ON p.permission_key IN('hiring.review_applications','hiring.onboarding.view','hiring.onboarding.manage') WHERE r.system_key='hr_admin' ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS router_operational_metrics(tenant_id uuid NOT NULL REFERENCES tenants(id),day date NOT NULL DEFAULT current_date,kind text NOT NULL CHECK(kind IN('single_intent','entity','filtered','composition')),method text NOT NULL,outcome text NOT NULL,fallback boolean NOT NULL,clarification boolean NOT NULL,queries integer NOT NULL DEFAULT 1,PRIMARY KEY(tenant_id,day,kind,method,outcome,fallback,clarification));
ALTER TABLE router_operational_metrics ENABLE ROW LEVEL SECURITY;ALTER TABLE router_operational_metrics FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operational_tenant ON router_operational_metrics;
CREATE POLICY operational_tenant ON router_operational_metrics USING(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid) WITH CHECK(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid);
COMMIT;
