CREATE TABLE IF NOT EXISTS assets (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  asset_tag VARCHAR(100) NOT NULL, category VARCHAR(30) NOT NULL CHECK (category IN ('laptop','desktop','monitor','phone','tablet','accessory','badge','furniture','other')),
  name VARCHAR(180) NOT NULL, manufacturer VARCHAR(120), model VARCHAR(120), serial_number VARCHAR(160),
  status VARCHAR(20) NOT NULL DEFAULT 'available' CHECK (status IN ('available','assigned','maintenance','lost','retired')),
  condition VARCHAR(20) NOT NULL DEFAULT 'good' CHECK (condition IN ('new','good','fair','damaged','unusable')),
  purchase_date DATE, purchase_cost NUMERIC(12,2) CHECK (purchase_cost IS NULL OR purchase_cost >= 0), warranty_expires_at DATE, notes TEXT,
  created_by UUID, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, asset_tag), UNIQUE (id, tenant_id), FOREIGN KEY (created_by, tenant_id) REFERENCES employees(id, tenant_id) ON DELETE SET NULL
);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='assets_id_tenant_unique') THEN ALTER TABLE assets ADD CONSTRAINT assets_id_tenant_unique UNIQUE(id,tenant_id); END IF; END $$;
CREATE TABLE IF NOT EXISTS asset_assignments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), tenant_id UUID NOT NULL, asset_id UUID NOT NULL, employee_id UUID NOT NULL, assigned_by UUID,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), expected_return_at DATE, returned_at TIMESTAMPTZ, return_condition VARCHAR(20) CHECK (return_condition IS NULL OR return_condition IN ('new','good','fair','damaged','unusable')), return_notes TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','returned','lost','damaged')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (id, tenant_id), FOREIGN KEY (asset_id, tenant_id) REFERENCES assets(id, tenant_id) ON DELETE CASCADE, FOREIGN KEY (employee_id, tenant_id) REFERENCES employees(id, tenant_id) ON DELETE CASCADE, FOREIGN KEY (assigned_by, tenant_id) REFERENCES employees(id, tenant_id) ON DELETE SET NULL
);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='assets_id_tenant_unique') THEN ALTER TABLE assets ADD CONSTRAINT assets_id_tenant_unique UNIQUE(id,tenant_id); END IF; END $$;
CREATE UNIQUE INDEX IF NOT EXISTS asset_assignments_one_active_asset ON asset_assignments(asset_id) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS assets_tenant_status_idx ON assets(tenant_id,status); CREATE INDEX IF NOT EXISTS assets_tenant_category_idx ON assets(tenant_id,category); CREATE INDEX IF NOT EXISTS asset_assignments_employee_active_idx ON asset_assignments(tenant_id,employee_id) WHERE status='active';
CREATE TABLE IF NOT EXISTS asset_condition_reports (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), tenant_id UUID NOT NULL, asset_id UUID NOT NULL, assignment_id UUID, reported_by UUID, condition VARCHAR(20) NOT NULL CHECK (condition IN ('new','good','fair','damaged','unusable')), notes TEXT, evidence_url TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), FOREIGN KEY(asset_id,tenant_id) REFERENCES assets(id,tenant_id) ON DELETE CASCADE, FOREIGN KEY(assignment_id,tenant_id) REFERENCES asset_assignments(id,tenant_id) ON DELETE SET NULL, FOREIGN KEY(reported_by,tenant_id) REFERENCES employees(id,tenant_id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS software_licenses (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, name VARCHAR(180) NOT NULL, vendor VARCHAR(120), license_reference_masked VARCHAR(120), vault_reference VARCHAR(255), seat_count INTEGER CHECK(seat_count IS NULL OR seat_count >= 0), seats_used INTEGER NOT NULL DEFAULT 0 CHECK(seats_used >= 0 AND (seat_count IS NULL OR seats_used <= seat_count)), expires_at DATE, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(id, tenant_id));
CREATE TABLE IF NOT EXISTS software_license_assignments (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), tenant_id UUID NOT NULL, software_license_id UUID NOT NULL, employee_id UUID NOT NULL, assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), revoked_at TIMESTAMPTZ, assigned_by UUID, FOREIGN KEY(software_license_id,tenant_id) REFERENCES software_licenses(id,tenant_id) ON DELETE CASCADE, FOREIGN KEY(employee_id,tenant_id) REFERENCES employees(id,tenant_id) ON DELETE CASCADE, FOREIGN KEY(assigned_by,tenant_id) REFERENCES employees(id,tenant_id) ON DELETE SET NULL);
CREATE UNIQUE INDEX IF NOT EXISTS software_license_assignments_active_unique ON software_license_assignments(software_license_id,employee_id) WHERE revoked_at IS NULL; CREATE INDEX IF NOT EXISTS software_licenses_expiry_idx ON software_licenses(tenant_id,expires_at);
ALTER TABLE assets ENABLE ROW LEVEL SECURITY; ALTER TABLE asset_assignments ENABLE ROW LEVEL SECURITY; ALTER TABLE asset_condition_reports ENABLE ROW LEVEL SECURITY; ALTER TABLE software_licenses ENABLE ROW LEVEL SECURITY; ALTER TABLE software_license_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY assets_tenant_isolation ON assets USING(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid) WITH CHECK(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid); CREATE POLICY asset_assignments_tenant_isolation ON asset_assignments USING(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid) WITH CHECK(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid); CREATE POLICY asset_condition_reports_tenant_isolation ON asset_condition_reports USING(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid) WITH CHECK(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid); CREATE POLICY software_licenses_tenant_isolation ON software_licenses USING(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid) WITH CHECK(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid); CREATE POLICY software_license_assignments_tenant_isolation ON software_license_assignments USING(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid) WITH CHECK(tenant_id=NULLIF(current_setting('app.current_tenant',true),'')::uuid);
INSERT INTO tenant_permissions(permission_key,label,description) VALUES ('assets.view','View assets','View tenant assets.'),('assets.manage','Manage assets','Create and update inventory.'),('assets.assign','Assign assets','Assign equipment and licenses.'),('assets.return','Return assets','Return tenant equipment.') ON CONFLICT(permission_key) DO NOTHING;
INSERT INTO tenant_role_permissions(tenant_id,role_id,permission_key) SELECT tr.tenant_id,tr.id,p.permission_key FROM tenant_roles tr CROSS JOIN (VALUES('assets.view'),('assets.manage'),('assets.assign'),('assets.return')) p(permission_key) WHERE tr.system_key='hr_admin' ON CONFLICT DO NOTHING;
