import {useCallback,useEffect,useState} from 'react';
import {apiFetch} from '../../lib/api';
import {useLanguage} from '../../lib/LanguageContext';
import {ComposerDialog} from '../workspace-composer/ComposerDialog';
import {Surface} from '../ui/Surface';
import {StanzaIcon} from '../ui/StanzaIcon';
const control='stanza-form-control';const button='stanza-interactive-control stanza-support-button';
async function request(path:string,body?:unknown){const r=await apiFetch('/api/support'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Support unavailable.');return data;}
export function SupportRequestButton({asset,onCreated}:{asset?:{id:string;name:string};onCreated?:()=>void}){const {isRtl}=useLanguage();const text=(en:string,ar:string)=>isRtl?ar:en;const [open,setOpen]=useState(false),[done,setDone]=useState('');return <><button type="button" className={button} onClick={()=>setOpen(true)}><StanzaIcon name="support"/>{asset?text('Report damage / get IT help','الإبلاغ عن تلف / طلب مساعدة تقنية'):text('New support request','طلب دعم جديد')}</button>{done&&<p role="status">{done}</p>}{open&&<SupportRequestDialog asset={asset} onClose={()=>setOpen(false)} onCreated={()=>{setOpen(false);setDone(text('Request saved. Track its status in IT & equipment support.','حُفظ الطلب. تابع حالته في الدعم التقني والمعدات.'));onCreated?.();}}/>}</>;}
function SupportRequestDialog({asset,onClose,onCreated}:{asset?:{id:string;name:string};onClose:()=>void;onCreated:()=>void}){const {isRtl}=useLanguage();const text=(en:string,ar:string)=>isRtl?ar:en;const [kind,setKind]=useState(asset?'damage':'it_help'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null);const [reportId,setReportId]=useState<string|null>(null);
 return <ComposerDialog title={text('IT & equipment support','الدعم التقني والمعدات')} onClose={()=>{if(!busy)onClose();}}><form className="stanza-support-form" onSubmit={async e=>{e.preventDefault();const values=new FormData(e.currentTarget);setBusy(true);setError('');try{let evidence=reportId;if(file&&asset&&!evidence){const data=new FormData();data.set('image',file);data.set('condition',kind==='damage'?'damaged':'good');data.set('notes',String(values.get('description')));const r=await apiFetch('/api/assets/'+asset.id+'/evidence',{method:'POST',body:data});const uploaded=await r.json();if(!r.ok)throw Error(uploaded.error);evidence=uploaded.report.id;setReportId(evidence);}await request('',{assetId:asset?.id,issueType:kind,summary:values.get('summary'),description:values.get('description'),urgency:values.get('urgency'),followUp:values.get('followUp'),evidenceReportId:evidence});onCreated();}catch(e){setError(e instanceof Error?e.message:text('Could not save request.','تعذر حفظ الطلب.'));}finally{setBusy(false);}}}>
 {asset&&<p>{text('Affected equipment','المعدات المتأثرة')}: <strong>{asset.name}</strong></p>}<label>{text('Issue type','نوع المشكلة')}<select className={control} value={kind} disabled={busy} onChange={e=>setKind(e.target.value)}>{asset&&<option value="damage">{text('Equipment damage','تلف المعدات')}</option>}<option value="it_help">{text('IT help','مساعدة تقنية')}</option><option value="equipment_issue">{text('General equipment issue','مشكلة عامة بالمعدات')}</option></select></label>
 <label>{text('Short summary','ملخص قصير')}<input className={control} name="summary" required maxLength={180} autoFocus disabled={busy}/></label><label>{text('Description','الوصف')}<textarea className={control} name="description" required maxLength={4000} rows={5} disabled={busy}/></label>
 <label>{text('Urgency','الأولوية')}<select className={control} name="urgency" disabled={busy}><option value="normal">{text('Normal','عادية')}</option><option value="high">{text('High — blocking work','عالية — تمنع العمل')}</option></select></label><label>{text('Preferred follow-up (optional)','طريقة المتابعة المفضلة (اختياري)')}<input className={control} name="followUp" maxLength={200} disabled={busy}/></label>
 {asset&&<label>{text('Evidence image (optional, up to 6 MB)','صورة توضيحية (اختياري، حتى ٦ ميجابايت)')}<input className={control} type="file" disabled={busy||!!reportId} accept="image/jpeg,image/png,image/webp" onChange={e=>{const next=e.target.files?.[0]??null;if(next&&(next.size>6*1024*1024||!['image/jpeg','image/png','image/webp'].includes(next.type))){setError(text('Choose JPEG, PNG or WebP up to 6 MB.','اختر JPEG أو PNG أو WebP حتى ٦ ميجابايت.'));e.target.value='';return;}setFile(next);}}/></label>}
 <p className="text-sm">{text('Saved inside your company. An authorized company support handler receives the request when available; otherwise it remains in the unassigned queue.','يُحفظ داخل شركتك. يتلقى الطلب مسؤول دعم مصرح له من الشركة إن وُجد؛ وإلا يبقى في قائمة الطلبات غير المسندة.')}</p>{error&&<p role="alert">{error}</p>}<button className={button} disabled={busy} type="submit">{busy?text('Saving…','جار الحفظ…'):text('Submit request','إرسال الطلب')}</button>
 </form></ComposerDialog>;
}
type Ticket={id:string;summary:string;description:string;status:string;issue_type:string;urgency:string;asset_name:string;requester_name:string;handler_name:string|null;assigned_to:string|null;created_at:string;follow_up?:string|null;evidence_report_id?:string|null};
export default function SupportPanel(){const {isRtl}=useLanguage();const text=(en:string,ar:string)=>isRtl?ar:en;const statusLabel=(s:string)=>({open:text('Open','مفتوح'),in_progress:text('In progress','قيد التنفيذ'),waiting_requester:text('Waiting for requester','بانتظار مقدم الطلب'),resolved:text('Resolved','تم الحل'),closed:text('Closed','مغلق')}[s]??s);const [tickets,setTickets]=useState<Ticket[]>([]),[queue,setQueue]=useState(false),[canQueue,setCanQueue]=useState(false),[canManage,setCanManage]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Ticket|null>(null),[history,setHistory]=useState<{id:string;status:string;note:string|null;created_at:string}[]>([]);
 const [handlers,setHandlers]=useState<{id:string;name:string}[]>([]);
 const load=useCallback(async()=>{setBusy(true);try{const d=await request(queue?'?queue=true':'');setTickets(d.tickets);setCanQueue(d.canQueue);setCanManage(d.canManage);if(queue&&d.canManage)setHandlers((await request('/handlers')).handlers);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[queue]);useEffect(()=>{void load();},[load]);
 return <section dir={isRtl?'rtl':'ltr'} className="space-y-4"><header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{text('IT & equipment support','الدعم التقني والمعدات')}</h2><p>{text('Company requests, assigned handlers and status history.','طلبات الشركة ومسؤولو الدعم وسجل الحالة.')}</p></div><SupportRequestButton onCreated={()=>void load()}/></header><div className="flex flex-wrap gap-2"><button className={button} aria-pressed={!queue} onClick={()=>setQueue(false)}>{text('My requests','طلباتي')}</button>{canQueue&&<button className={button} aria-pressed={queue} onClick={()=>setQueue(true)}>{text('Company support queue','قائمة دعم الشركة')}</button>}<button className={button} disabled={busy} onClick={()=>void load()}>{text('Refresh','تحديث')}</button></div>{error&&<p role="alert">{error}</p>}{!busy&&!tickets.length&&<p>{text('No requests here yet.','لا توجد طلبات بعد.')}</p>}
 {tickets.map(t=><Surface key={t.id} className="p-4 space-y-2"><h3 className="font-bold break-words">{t.summary}</h3><p>{statusLabel(t.status)} · {t.urgency==='high'?text('High urgency','أولوية عالية'):text('Normal urgency','أولوية عادية')} · {t.asset_name||text('General IT help','مساعدة تقنية عامة')}</p><p>{t.requester_name} · {t.handler_name||text('Awaiting an authorized company handler','بانتظار مسؤول دعم مصرح له')} · {new Date(t.created_at).toLocaleDateString(isRtl?'ar':'en')}</p><button className={button} onClick={async()=>{try{const d=await request('/'+t.id);setError('');setSelected(t);setHistory(d.history);}catch(e){setError((e as Error).message);}}}>{text('View request & history','عرض الطلب والسجل')}</button></Surface>)}
 {selected&&<ComposerDialog title={selected.summary} onClose={()=>{if(!busy)setSelected(null);}}>{error&&<p role="alert">{error}</p>}<p className="whitespace-pre-wrap break-words">{selected.description}</p><p>{statusLabel(selected.status)}</p>{selected.follow_up&&<p className="break-words">{selected.follow_up}</p>}{selected.evidence_report_id&&<img className="max-h-60 max-w-full rounded-lg" src={'/api/assets/evidence/'+selected.evidence_report_id} alt={text('Submitted equipment evidence','الصورة التوضيحية المقدمة')}/>}<ol>{history.map(h=><li key={h.id} className="py-2 border-b"><strong>{statusLabel(h.status)}</strong> · {new Date(h.created_at).toLocaleString(isRtl?'ar':'en')}<p className="whitespace-pre-wrap break-words">{h.note}</p></li>)}</ol>{canManage&&queue&&<form className="stanza-support-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await request('/'+selected.id+'/update',{status:f.get('status'),note:f.get('note'),assignedTo:f.get('assignedTo')||undefined});setSelected(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>{text('Status','الحالة')}<select className={control} name="status" disabled={busy} defaultValue={selected.status}>{['open','in_progress','waiting_requester','resolved','closed'].map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></label><label>{text('Assigned handler','مسؤول الدعم')}<select className={control} name="assignedTo" disabled={busy} defaultValue={selected.assigned_to??''}><option value="">{text('Keep current assignment','الاحتفاظ بالإسناد الحالي')}</option>{handlers.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label><label>{text('Update for requester','تحديث لمقدم الطلب')}<textarea className={control} name="note" disabled={busy} maxLength={2000} rows={3}/></label><button type="submit" className={button} disabled={busy}>{text('Save update','حفظ التحديث')}</button></form>}</ComposerDialog>}
 </section>;
}
