import {useCallback,useEffect,useState,useRef} from 'react';
import {apiFetch} from '../../lib/api';
import {useLanguage} from '../../lib/LanguageContext';
import {ComposerDialog} from '../workspace-composer/ComposerDialog';
import {supportAge,supportAgeCompact,supportStatusOptions} from '../../lib/support-presentation';
import {StanzaIcon} from '../ui/StanzaIcon';
const control='stanza-form-control';const button='stanza-interactive-control stanza-support-button';
async function request(path:string,body?:unknown){const r=await apiFetch('/api/support'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Support unavailable.');return data;}
export function SupportRequestButton({asset,onCreated}:{asset?:{id:string;name:string};onCreated?:()=>void}){const {isRtl}=useLanguage();const text=(en:string,ar:string)=>isRtl?ar:en;const [open,setOpen]=useState(false),[done,setDone]=useState('');return <><button type="button" className={button} onClick={()=>setOpen(true)}><StanzaIcon name="support"/>{asset?text('Report damage / get IT help','الإبلاغ عن تلف / طلب مساعدة تقنية'):text('New support request','طلب دعم جديد')}</button>{done&&<p role="status">{done}</p>}{open&&<SupportRequestDialog asset={asset} onClose={()=>setOpen(false)} onCreated={()=>{setOpen(false);setDone(text('Request saved. Track its status in IT & equipment support.','حُفظ الطلب. تابع حالته في الدعم التقني والمعدات.'));onCreated?.();}}/>}</>;}
function SupportRequestDialog({asset,onClose,onCreated,prefill}:{asset?:{id:string;name:string};prefill?:import('../../lib/router-entities').EntityRoute['prefill'];onClose:()=>void;onCreated:()=>void}){const {isRtl}=useLanguage();const text=(en:string,ar:string)=>isRtl?ar:en;const [kind,setKind]=useState(asset?'damage':'it_help'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null);const [reportId,setReportId]=useState<string|null>(null);
 return <ComposerDialog title={text('IT & equipment support','الدعم التقني والمعدات')} onClose={()=>{if(!busy)onClose();}}><form className="stanza-support-form" onSubmit={async e=>{e.preventDefault();const values=new FormData(e.currentTarget);setBusy(true);setError('');try{let evidence=reportId;if(file&&asset&&!evidence){const data=new FormData();data.set('image',file);data.set('condition',kind==='damage'?'damaged':'good');data.set('notes',String(values.get('description')));const r=await apiFetch('/api/assets/'+asset.id+'/evidence',{method:'POST',body:data});const uploaded=await r.json();if(!r.ok)throw Error(uploaded.error);evidence=uploaded.report.id;setReportId(evidence);}await request('',{assetId:asset?.id,requesterId:prefill?.requesterId,issueType:kind,summary:values.get('summary'),description:values.get('description'),urgency:values.get('urgency'),followUp:values.get('followUp'),evidenceReportId:evidence});onCreated();}catch(e){setError(e instanceof Error?e.message:text('Could not save request.','تعذر حفظ الطلب.'));}finally{setBusy(false);}}}>
 {asset&&<p>{text('Affected equipment','المعدات المتأثرة')}: <strong>{asset.name}</strong></p>}<label>{text('Issue type','نوع المشكلة')}<select className={control} value={kind} disabled={busy} onChange={e=>setKind(e.target.value)}>{asset&&<option value="damage">{text('Equipment damage','تلف المعدات')}</option>}<option value="it_help">{text('IT help','مساعدة تقنية')}</option><option value="equipment_issue">{text('General equipment issue','مشكلة عامة بالمعدات')}</option></select></label>
 <label>{text('Short summary','ملخص قصير')}<input className={control} name="summary" defaultValue={prefill?.summary} required maxLength={180} autoFocus disabled={busy}/></label><label>{text('Description','الوصف')}<textarea className={control} name="description" defaultValue={prefill?.description} required maxLength={4000} rows={5} disabled={busy}/></label>
 <label>{text('Urgency','الأولوية')}<select className={control} name="urgency" disabled={busy}><option value="normal">{text('Normal','عادية')}</option><option value="high">{text('High — blocking work','عالية — تمنع العمل')}</option></select></label><label>{text('Preferred follow-up (optional)','طريقة المتابعة المفضلة (اختياري)')}<input className={control} name="followUp" maxLength={200} disabled={busy}/></label>
 {asset&&<label>{text('Evidence image (optional, up to 6 MB)','صورة توضيحية (اختياري، حتى ٦ ميجابايت)')}<input className={control} type="file" disabled={busy||!!reportId} accept="image/jpeg,image/png,image/webp" onChange={e=>{const next=e.target.files?.[0]??null;if(next&&(next.size>6*1024*1024||!['image/jpeg','image/png','image/webp'].includes(next.type))){setError(text('Choose JPEG, PNG or WebP up to 6 MB.','اختر JPEG أو PNG أو WebP حتى ٦ ميجابايت.'));e.target.value='';return;}setFile(next);}}/></label>}
 <p className="text-sm">{text('Saved inside your company. An authorized company support handler receives the request when available; otherwise it remains in the unassigned queue.','يُحفظ داخل شركتك. يتلقى الطلب مسؤول دعم مصرح له من الشركة إن وُجد؛ وإلا يبقى في قائمة الطلبات غير المسندة.')}</p>{error&&<p role="alert">{error}</p>}<button className={button} disabled={busy} type="submit">{busy?text('Saving…','جار الحفظ…'):text('Submit request','إرسال الطلب')}</button>
 </form></ComposerDialog>;
}
type Ticket={id:string;requester_id:string;summary:string;description:string;status:string;issue_type:string;urgency:string;asset_name:string;asset_tag?:string;requester_name:string;handler_name:string|null;assigned_to:string|null;created_at:string;updated_at:string;follow_up?:string|null;evidence_report_id?:string|null;resolution?:string|null};
type TicketEvent={id:string;status:string;note:string|null;created_at:string;kind:string;visibility:string;actor_name:string};
export default function SupportPanel({prefill,onPrefillConsumed}:{prefill?:import('../../lib/router-entities').EntityRoute['prefill'];onPrefillConsumed?:()=>void}={}){
 const {isRtl}=useLanguage(),text=(en:string,ar:string)=>isRtl?ar:en;
 const statusLabel=(s:string)=>({open:text('Open','مفتوح'),in_progress:text('In progress','قيد التنفيذ'),waiting_requester:text('Waiting for requester','بانتظار مقدم الطلب'),resolved:text('Resolved','تم الحل'),closed:text('Closed','مغلق'),unresolved:text('Unresolved','غير محلولة')}[s]??s);
 const categoryLabel=(s:string)=>({damage:text('Damage','تلف'),it_help:text('IT help','مساعدة تقنية'),equipment_issue:text('Equipment issue','مشكلة معدات')}[s]??s);
 const date=(s:string)=>new Date(s).toLocaleString(isRtl?'ar':'en',{dateStyle:'medium',timeStyle:'short'});
 const age=(s:string)=>supportAge(s,isRtl?'ar':'en'),compactAge=(s:string)=>supportAgeCompact(s,isRtl?'ar':'en');
 const [sort,setSort]=useState('newest'),[urgencyFilter,setUrgencyFilter]=useState(''),[categoryFilter,setCategoryFilter]=useState(''),[ageFilter,setAgeFilter]=useState('');
 const [tickets,setTickets]=useState<Ticket[]>([]),[queue,setQueue]=useState(false),[canQueue,setCanQueue]=useState(false),[canManage,setCanManage]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Ticket|null>(null),[history,setHistory]=useState<TicketEvent[]>([]);
 const [nextCursor,setNextCursor]=useState<string|null>(null),[total,setTotal]=useState(0),[historyCursor,setHistoryCursor]=useState<string|null>(null);const sequence=useRef(0);
 const [handlers,setHandlers]=useState<{id:string;name:string}[]>([]);
 const [statusFilter,setStatusFilter]=useState(''),[assignmentFilter,setAssignmentFilter]=useState(''),[search,setSearch]=useState(''),[assetContext,setAssetContext]=useState<any>(null),[assetHistory,setAssetHistory]=useState<any[]>([]);
 const [requesterFilter,setRequesterFilter]=useState<{id:string;name:string}|null>(null),[assetFilter,setAssetFilter]=useState<{id:string;name:string}|null>(null);
 const [nextStatus,setNextStatus]=useState(''),[noteMode,setNoteMode]=useState('requester'),[noteDraft,setNoteDraft]=useState('');
 const load=useCallback(async(cursor?:string)=>{const seq=++sequence.current;setBusy(true);try{const params=new URLSearchParams();if(queue)params.set('queue','true');if(statusFilter)params.set('status',statusFilter);if(assignmentFilter&&queue)params.set('assignment',assignmentFilter);if(search)params.set('search',search);params.set('sort',sort);if(urgencyFilter)params.set('urgency',urgencyFilter);if(categoryFilter)params.set('category',categoryFilter);if(ageFilter)params.set('olderThanDays',ageFilter);if(requesterFilter)params.set('requesterId',requesterFilter.id);if(assetFilter)params.set('assetId',assetFilter.id);if(cursor)params.set('cursor',cursor);const d=await request('?'+params);if(seq!==sequence.current)return;setTickets(current=>cursor?[...current,...d.tickets.filter((t:Ticket)=>!current.some(old=>old.id===t.id))]:d.tickets);setNextCursor(d.nextCursor);setTotal(d.total);setCanQueue(d.canQueue);setCanManage(d.canManage);if(queue&&d.canManage)setHandlers((await request('/handlers')).handlers);setError('');}catch(e){setError((e as Error).message);}finally{if(seq===sequence.current)setBusy(false);}},[queue,statusFilter,assignmentFilter,search,sort,urgencyFilter,categoryFilter,ageFilter,requesterFilter,assetFilter]);useEffect(()=>{void load();},[load]);
 const filters=[requesterFilter&&{label:text('Requester','مقدم الطلب')+': '+requesterFilter.name,clear:()=>setRequesterFilter(null)},assetFilter&&{label:text('Equipment','المعدات')+': '+assetFilter.name,clear:()=>setAssetFilter(null)},ageFilter&&{label:text('Opened more than '+ageFilter+' days ago','فُتح منذ أكثر من '+ageFilter+' أيام'),clear:()=>setAgeFilter('')},statusFilter&&{label:text('Status','الحالة')+': '+statusLabel(statusFilter),clear:()=>setStatusFilter('')},queue&&assignmentFilter&&{label:text('Assignment','الإسناد')+': '+(assignmentFilter==='mine'?text('Assigned to me','مسندة لي'):text('Unassigned','غير مسندة')),clear:()=>setAssignmentFilter('')},search&&{label:text('Search','البحث')+': '+search,clear:()=>setSearch('')},urgencyFilter&&{label:text('Priority','الأولوية')+': '+(urgencyFilter==='high'?text('High','عالية'):text('Normal','عادية')),clear:()=>setUrgencyFilter('')},categoryFilter&&{label:categoryLabel(categoryFilter),clear:()=>setCategoryFilter('')},sort==='oldest'&&{label:text('Oldest first','الأقدم أولاً'),clear:()=>setSort('newest')}].filter(Boolean) as {label:string;clear:()=>void}[];
 const replyLabel=canManage&&queue?text('Reply to requester','رد لمقدم الطلب'):text('Reply to support','رد للدعم');
 const reset=()=>{setStatusFilter('');setAssignmentFilter('');setSearch('');setUrgencyFilter('');setCategoryFilter('');setAgeFilter('');setRequesterFilter(null);setAssetFilter(null);setSort('newest');};
 const openTicket=async(t:Ticket)=>{setBusy(true);try{const d=await request('/'+t.id);setError('');setSelected({...t,...d.ticket});setNextStatus(d.ticket.status);setNoteMode('requester');setNoteDraft('');setAssetContext(d.asset);setAssetHistory(d.assetHistory);setHistory(d.history);setHistoryCursor(d.historyNextCursor);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const status=(s:string,id?:string)=><span id={id} className="support-status" data-status={s}>{statusLabel(s)}</span>;
 return <section dir={isRtl?'rtl':'ltr'} className="support-panel space-y-4">
 {prefill&&<SupportRequestDialog prefill={prefill} asset={{id:prefill.assetId,name:prefill.assetName}} onClose={()=>onPrefillConsumed?.()} onCreated={()=>{onPrefillConsumed?.();void load();}}/>}
 <header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{text('IT & equipment support','الدعم التقني والمعدات')}</h2><p className="support-secondary">{text('Company requests, assigned handlers and status history.','طلبات الشركة ومسؤولو الدعم وسجل الحالة.')}</p></div><SupportRequestButton onCreated={()=>void load()}/></header>
 <div className="support-toolbar"><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} aria-pressed={!queue} onClick={()=>setQueue(false)}>{text('My requests','طلباتي')}</button>{canQueue&&<button className={button} disabled={busy} aria-pressed={queue} onClick={()=>setQueue(true)}>{text('Company support queue','قائمة دعم الشركة')}</button>}</div><button className={button} disabled={busy} onClick={()=>void load()}>{text('Refresh','تحديث')}</button></div>
 <div className="support-filters"><label>{text('Status filter','تصفية الحالة')}<select className={control} value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">{text('All statuses','كل الحالات')}</option>{['unresolved','open','in_progress','waiting_requester','resolved','closed'].map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></label>
 {queue&&<label>{text('Assignment filter','تصفية الإسناد')}<select className={control} value={assignmentFilter} onChange={e=>setAssignmentFilter(e.target.value)}><option value="">{text('All handlers','كل المسؤولين')}</option><option value="mine">{text('Assigned to me','مسندة لي')}</option><option value="unassigned">{text('Unassigned','غير مسندة')}</option></select></label>}
 <label className="support-search">{text('Search summary','بحث في الملخص')}<input className={control} maxLength={160} value={search} onChange={e=>setSearch(e.target.value)}/></label>
 <details className="support-more-filters"><summary>{text('More filters / order','المزيد من المرشحات / الترتيب')}</summary><div className="support-filters"><label>{text('Ticket age','عمر الطلب')}<select className={control} value={ageFilter} onChange={e=>setAgeFilter(e.target.value)}><option value="">{text('Any age','كل الأعمار')}</option>{[3,7,30].map(days=><option key={days} value={days}>{text('More than '+days+' days','أكثر من '+days+' أيام')}</option>)}</select></label><label>{text('Order','الترتيب')}<select className={control} value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">{text('Newest first','الأحدث أولاً')}</option><option value="oldest">{text('Oldest first','الأقدم أولاً')}</option></select></label><label>{text('Priority','الأولوية')}<select className={control} value={urgencyFilter} onChange={e=>setUrgencyFilter(e.target.value)}><option value="">{text('All priorities','كل الأولويات')}</option><option value="high">{text('High','عالية')}</option><option value="normal">{text('Normal','عادية')}</option></select></label><label>{text('Category','الفئة')}<select className={control} value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">{text('All categories','كل الفئات')}</option>{['damage','it_help','equipment_issue'].map(s=><option key={s} value={s}>{categoryLabel(s)}</option>)}</select></label></div></details></div>
 {filters.length>0&&<div className="support-filter-feedback" aria-label={text('Active filters','المرشحات النشطة')}>{filters.map(f=><button key={f.label} className={button} disabled={busy} onClick={f.clear} aria-label={text('Remove filter: ','إزالة المرشح: ')+f.label}>{f.label}<StanzaIcon name="close" width={14} height={14}/></button>)}<button className={button} disabled={busy} onClick={reset}>{text('Clear filters','مسح المرشحات')}</button></div>}
 {error&&<p role="alert">{error}</p>}
 <p role="status" className="support-secondary">{busy?text('Loading requests…','جار تحميل الطلبات…'):text(`Showing ${tickets.length} of ${total} requests`,`عرض ${tickets.length} من ${total} طلب`)}</p>
 {!busy&&!tickets.length&&<p className="support-empty">{filters.length?text('No tickets match these filters.','لا توجد طلبات تطابق هذه المرشحات.'):queue?text('No tickets in the company support queue.','لا توجد طلبات في قائمة دعم الشركة.'):text('No support requests yet.','لا توجد طلبات دعم بعد.')}</p>}
 <div className="support-queue">{tickets.map(t=><button type="button" key={t.id} className="support-ticket-row" disabled={busy} aria-pressed={selected?.id===t.id} aria-describedby={'support-ticket-status-'+t.id+' support-ticket-meta-'+t.id} aria-label={text('Open ticket: ','فتح الطلب: ')+t.summary} onClick={()=>void openTicket(t)}><span className="support-row-identity"><strong>{t.summary}</strong>{status(t.status,'support-ticket-status-'+t.id)}{t.urgency==='high'&&<span className="support-priority">{text('High — blocking work','عالية — تمنع العمل')}</span>}<StanzaIcon name="forward" className="support-row-direction"/></span><span id={'support-ticket-meta-'+t.id} className="support-row-context"><span>{text('Requester','مقدم الطلب')}: {t.requester_name}</span><span>{text('Assigned to','مسند إلى')}: {t.handler_name||text('Unassigned','غير مسندة')}</span><time dateTime={t.created_at} title={date(t.created_at)} aria-label={text('Opened','فُتح')+' '+age(t.created_at)}>{text('Opened','فُتح')} <bdi>{compactAge(t.created_at)}</bdi></time></span><span className="support-row-context support-secondary"><span>{categoryLabel(t.issue_type)}{t.asset_name&&<> · {t.asset_name} {t.asset_tag}</>}</span><span>{text('Last activity','آخر نشاط')}: <time dateTime={t.updated_at}>{date(t.updated_at)}</time></span></span></button>)}</div>
 <div className="support-pagination">{nextCursor?<button type="button" className={button} disabled={busy} onClick={()=>void load(nextCursor)}>{text('Load more requests','تحميل طلبات أخرى')}</button>:!busy&&tickets.length>0&&<p className="support-secondary">{text('End of requests.','نهاية الطلبات.')}</p>}</div>
 {selected&&<ComposerDialog title={selected.summary} onClose={()=>{if(!busy)setSelected(null);}}><div className="support-detail">{error&&<p role="alert">{error}</p>}
 <div className="support-detail-identity">{status(selected.status)}{selected.urgency==='high'&&<span className="support-priority">{text('High — blocking work','عالية — تمنع العمل')}</span>}<time className="support-secondary" dateTime={selected.created_at} title={date(selected.created_at)} aria-label={text('Opened','فُتح')+' '+age(selected.created_at)}>{text('Opened','فُتح')} <bdi>{compactAge(selected.created_at)}</bdi></time></div>
 <dl className="support-ownership"><div><dt>{text('Requester','مقدم الطلب')}</dt><dd>{selected.requester_name}</dd>{queue&&<button type="button" className={button} disabled={busy} onClick={()=>{setRequesterFilter({id:selected.requester_id,name:selected.requester_name});setSelected(null);}}>{text("Show requester’s tickets","عرض طلبات مقدم الطلب")}</button>}</div><div><dt>{text('Assigned to','مسند إلى')}</dt><dd>{selected.handler_name||text('Unassigned','غير مسندة')}</dd></div><div><dt>{text('Category','الفئة')}</dt><dd>{categoryLabel(selected.issue_type)}</dd></div></dl>
 <p className="whitespace-pre-wrap break-words">{selected.description}</p>{selected.follow_up&&<p className="support-secondary break-words">{text('Preferred follow-up','طريقة المتابعة المفضلة')}: {selected.follow_up}</p>}
 {selected.evidence_report_id&&<img className="max-h-60 max-w-full rounded-lg" src={'/api/assets/evidence/'+selected.evidence_report_id} alt={text('Submitted equipment evidence','الصورة التوضيحية المقدمة')}/>}
 {assetContext&&<div className="support-asset-context"><h3>{text('Equipment context','سياق المعدات')}</h3><button type="button" className={button} disabled={busy} onClick={()=>{setAssetFilter({id:assetContext.id,name:assetContext.name});setSelected(null);}}>{text('Show equipment tickets','عرض طلبات المعدات')}<StanzaIcon name="forward" className="support-row-direction"/></button><p><strong>{assetContext.name}</strong> · <bdi>{assetContext.asset_tag}</bdi></p><p className="support-secondary">{({laptop:text('Laptop','حاسوب محمول'),desktop:text('Desktop','حاسوب مكتبي'),monitor:text('Monitor','شاشة'),phone:text('Phone','هاتف')} as Record<string,string>)[assetContext.category]||assetContext.category} · {({assigned:text('Assigned','مسند'),available:text('Available','متاح'),maintenance:text('Maintenance','صيانة'),retired:text('Retired','متقاعد')} as Record<string,string>)[assetContext.status]||assetContext.status}{assetContext.assignee&&' · '+assetContext.assignee}</p><details><summary>{text('Equipment details / recent requests','تفاصيل المعدات / أحدث الطلبات')}</summary>{assetContext.serial_number&&<p><bdi>{assetContext.serial_number}</bdi></p>}{assetHistory.map(t=><p key={t.id}>{t.summary} · {statusLabel(t.status)}</p>)}</details></div>}
 {selected.resolution&&<div className="support-resolution"><h3>{['resolved','closed'].includes(selected.status)?text('Resolution','الحل'):text('Previous resolution','الحل السابق')}</h3><p className="whitespace-pre-wrap break-words">{selected.resolution}</p></div>}
 {canManage&&queue&&<details className="support-update"><summary>{!selected.assigned_to?text('Assign / update status','إسناد / تحديث الحالة'):selected.status==='resolved'?text('Close / reopen / update assignment','إغلاق / إعادة فتح / تحديث الإسناد'):text('Update status / assignment','تحديث الحالة / الإسناد')}</summary><form className="stanza-support-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await request('/'+selected.id+'/update',{status:f.get('status'),expectedStatus:selected.status,note:f.get('note'),assignedTo:f.get('assignedTo')==='keep'?undefined:f.get('assignedTo')||null});setSelected(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <div className="support-update-fields"><label>{text('Status','الحالة')}<select className={control} name="status" disabled={busy} value={nextStatus} onChange={e=>setNextStatus(e.target.value)}>{supportStatusOptions(selected.status).map(s=><option key={s} value={s}>{selected.status==='resolved'&&s==='in_progress'?text('Reopen — In progress','إعادة فتح — قيد التنفيذ'):statusLabel(s)}</option>)}</select></label><label>{text('Assigned handler','مسؤول الدعم')}<select className={control} name="assignedTo" disabled={busy} defaultValue={selected.assigned_to??'keep'}><option value="keep">{text('Keep current assignment','الاحتفاظ بالإسناد الحالي')}</option><option value="">{text('Unassigned','غير مسندة')}</option>{handlers.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label></div>
 <label>{nextStatus==='resolved'&&selected.status!=='resolved'?text('Resolution note (required)','ملاحظة الحل (مطلوبة)'):text('Update for requester','تحديث لمقدم الطلب')}<textarea className={control} name="note" disabled={busy} maxLength={2000} rows={3} required={nextStatus==='resolved'&&selected.status!=='resolved'}/></label><button type="submit" className={button} disabled={busy}>{nextStatus==='resolved'&&selected.status!=='resolved'?text('Resolve ticket','حل الطلب'):text('Save update','حفظ التحديث')}</button></form></details>}
 <section className="support-conversation"><h3>{text('Conversation','المحادثة')}</h3>{!history.some(h=>h.kind==='comment')&&<p className="support-secondary">{text('No replies yet.','لا توجد ردود بعد.')}</p>}<ol>{history.filter(h=>h.kind==='comment').map(h=><li key={h.id} className="support-message" data-visibility={h.visibility}><div className="support-message-meta"><strong>{h.actor_name}</strong><time dateTime={h.created_at}>{date(h.created_at)}</time><span>{h.visibility==='internal'?text('Internal — hidden from requester','داخلي — مخفي عن مقدم الطلب'):text('Reply — visible to requester','رد — مرئي لمقدم الطلب')}</span></div><p className="whitespace-pre-wrap break-words">{h.note}</p></li>)}</ol></section>
 {selected.status!=='closed'&&<form className="stanza-support-form support-reply" data-mode={canManage&&queue?noteMode:'requester'} onSubmit={async e=>{e.preventDefault();setBusy(true);try{await request('/'+selected.id+'/comments',{note:noteDraft,visibility:canManage&&queue?noteMode:'requester'});const d=await request('/'+selected.id);setHistory(d.history);setHistoryCursor(d.historyNextCursor);setSelected(current=>current?{...current,...d.ticket}:null);setNoteDraft('');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 {canManage&&queue&&<div className="support-composer-modes" role="group" aria-label={text('Comment audience','جمهور التعليق')}>{['requester','internal'].map(mode=><button type="button" className={button} key={mode} disabled={busy} aria-pressed={noteMode===mode} onClick={()=>setNoteMode(mode)}><span aria-hidden="true" className={'inline-block w-4 shrink-0 '+(noteMode===mode?'':'invisible')}>✓</span>{mode==='internal'?text('Internal note','ملاحظة داخلية'):text('Reply to requester','رد لمقدم الطلب')}</button>)}</div>}
 <p id="support-composer-audience" className="support-secondary">{canManage&&queue&&noteMode==='internal'?text('Only authorized support handlers can read this note. The requester will not see it.','يمكن لمسؤولي الدعم المصرح لهم فقط قراءة هذه الملاحظة. لن يراها مقدم الطلب.'):text('This reply is visible to the requester and authorized support handlers.','هذا الرد مرئي لمقدم الطلب ومسؤولي الدعم المصرح لهم.')}</p>
 <label>{canManage&&queue&&noteMode==='internal'?text('Internal note','ملاحظة داخلية'):replyLabel}<textarea className={control} name="note" aria-describedby="support-composer-audience" maxLength={2000} rows={3} required disabled={busy} value={noteDraft} onChange={e=>setNoteDraft(e.target.value)}/></label><button className={button+' stanza-primary-action stanza-theme-primary'} disabled={busy} type="submit">{canManage&&queue&&noteMode==='internal'?text('Save internal note','حفظ الملاحظة الداخلية'):text('Send reply','إرسال الرد')}</button></form>}
 <details className="support-history"><summary>{text('History / status changes','السجل / تغييرات الحالة')}</summary><ol>{history.filter(h=>h.kind!=='comment').map((h,index)=><li key={h.id}><strong>{({assignment:text('Assignment updated','تم تحديث الإسناد'),resolution:text('Resolved','تم الحل'),status:index===0&&h.status==='open'?text('Created','تم الإنشاء'):text('Status recorded','تم تسجيل الحالة')} as Record<string,string>)[h.kind]||text('Ticket updated','تم تحديث الطلب')} · {statusLabel(h.status)}</strong><p className="support-secondary">{h.actor_name} · <time dateTime={h.created_at}>{date(h.created_at)}</time></p>{h.note&&<p className="whitespace-pre-wrap break-words">{h.note}</p>}</li>)}</ol></details>
 {historyCursor&&<button type="button" className={button} disabled={busy} onClick={async()=>{setBusy(true);try{const d=await request('/'+selected.id+'?historyCursor='+encodeURIComponent(historyCursor));setHistory(current=>[...current,...d.history]);setHistoryCursor(d.historyNextCursor);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{text('Load more conversation / history','تحميل مزيد من المحادثة / السجل')}</button>}
 </div></ComposerDialog>}
 </section>;
}
