import type express from 'express';
import type {PoolClient} from 'pg';
import {withTenant} from '../../lib/hr-background';
import {resolveScopedPermission} from '../organisation/scoped-permissions';
import {recordAuditEvent} from '../audit/audit-events';
import {logServerError} from '../../lib/server-logging';
type Actor={tenantId:string;employeeId:string};
export async function supportAuthority(c:PoolClient,u:Actor,key='support.view'){if(!(await c.query("SELECT 1 FROM employees WHERE tenant_id=$1 AND id=$2 AND is_active AND employment_status='active'",[u.tenantId,u.employeeId])).rowCount)return false;return (await resolveScopedPermission(c,{tenantId:u.tenantId,actorEmployeeId:u.employeeId,permissionKey:key})).allowed;}
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(v);
const fail=(message:string,statusCode=400)=>{throw Object.assign(Error(message),{statusCode});};
const text=(v:unknown,max:number,required=false)=>{if(v==null&&!required)return null;if(typeof v!=='string'||v.trim().length>max||required&&!v.trim())fail('Invalid support field.');return (v as string).trim()||null;};
async function event(c:PoolClient,u:Actor,id:string,status:string,note:string|null){await c.query('INSERT INTO support_ticket_events(tenant_id,ticket_id,actor_id,status,note) VALUES($1,$2,$3,$4,$5)',[u.tenantId,id,u.employeeId,status,note]);await recordAuditEvent(c,{tenantId:u.tenantId,actorId:u.employeeId,action:'support.updated',targetType:'support_ticket',targetId:id,metadata:{status}});}
export function registerSupportRoutes(app:express.Express,deps:{standardAuth:express.RequestHandler;mutationGuard:express.RequestHandler;rateLimiter:express.RequestHandler}){
 const route=(method:'get'|'post',path:string,fn:(r:express.Request,c:PoolClient,u:Actor)=>Promise<unknown>)=>app[method]('/api/support'+path,deps.standardAuth,...(method==='post'?[deps.rateLimiter,deps.mutationGuard]:[]),async(r,res)=>{res.setHeader('Cache-Control','no-store');try{const data=await withTenant(r.authUser!.tenantId,async c=>{const u=r.authUser!;if(!(await c.query("SELECT 1 FROM employees WHERE tenant_id=$1 AND id=$2 AND is_active AND employment_status='active'",[u.tenantId,u.employeeId])).rowCount)fail('Support unavailable.',403);return fn(r,c,u);});res.status(method==='post'?201:200).json({success:true,...data as object});}catch(e){const status=Number((e as {statusCode?:number}).statusCode)||500;if(status===500)logServerError('support request failed',e);res.status(status).json({success:false,error:status===500?'Support request failed.':(e as Error).message});}});
 route('get','',async(r,c,u)=>{const queue=r.query.queue==='true';const view=await supportAuthority(c,u),manage=await supportAuthority(c,u,'support.manage');if(queue&&!view&&!manage)fail('Support queue requires permission.',403);const tickets=(await c.query(`SELECT t.*,a.name asset_name,a.asset_tag,e.full_name requester_name,h.full_name handler_name FROM support_tickets t LEFT JOIN assets a ON a.tenant_id=t.tenant_id AND a.id=t.asset_id JOIN employees e ON e.tenant_id=t.tenant_id AND e.id=t.requester_id LEFT JOIN employees h ON h.tenant_id=t.tenant_id AND h.id=t.assigned_to WHERE t.tenant_id=$1 AND ($2::boolean OR t.requester_id=$3) ORDER BY t.created_at DESC LIMIT 50`,[u.tenantId,queue,u.employeeId])).rows;return {tickets,canQueue:view||manage,canManage:manage};});
 route('post','',async(r,c,u)=>{const b=r.body??{};if(Object.keys(b).some(k=>!['assetId','issueType','summary','description','urgency','followUp','evidenceReportId'].includes(k)))fail('Unknown support field.');if(!['damage','it_help','equipment_issue'].includes(b.issueType)||!['normal','high'].includes(b.urgency))fail('Invalid issue type or urgency.');const summary=text(b.summary,180,true),description=text(b.description,4000,true),followUp=text(b.followUp,200);
 if(b.assetId&&!uuid(b.assetId)||b.evidenceReportId&&!uuid(b.evidenceReportId))fail('Invalid asset or evidence.');
 if(b.issueType==='damage'&&!b.assetId)fail('Choose affected equipment.');
 let assignment:string|null=null;if(b.assetId){assignment=(await c.query("SELECT id FROM asset_assignments WHERE tenant_id=$1 AND asset_id=$2 AND employee_id=$3 AND status='active'",[u.tenantId,b.assetId,u.employeeId])).rows[0]?.id??null;if(!assignment)fail('Assigned equipment unavailable.',404);}
 if(b.evidenceReportId&&!(await c.query('SELECT 1 FROM asset_condition_reports WHERE tenant_id=$1 AND id=$2 AND asset_id=$3 AND reported_by=$4 AND evidence_url IS NOT NULL',[u.tenantId,b.evidenceReportId,b.assetId,u.employeeId])).rowCount)fail('Evidence unavailable.',404);
 // Only explicit, active company-scope support handlers are eligible; the API revalidates every assignment.
 const handlers=(await c.query("SELECT e.id FROM employees e WHERE e.tenant_id=$1 AND e.is_active AND e.employment_status='active' AND EXISTS(SELECT 1 FROM employee_role_assignments a JOIN tenant_role_permissions p ON p.tenant_id=a.tenant_id AND p.role_id=a.role_id WHERE a.tenant_id=e.tenant_id AND a.employee_id=e.id AND a.scope_type='company' AND a.revoked_at IS NULL AND a.assigned_at<=now() AND (a.expires_at IS NULL OR a.expires_at>now()) AND p.permission_key='support.manage') ORDER BY (SELECT count(*) FROM support_tickets t WHERE t.tenant_id=e.tenant_id AND t.assigned_to=e.id AND t.status IN ('open','in_progress','waiting_requester')),e.id LIMIT 1",[u.tenantId])).rows;
 const ticket=(await c.query('INSERT INTO support_tickets(tenant_id,requester_id,asset_id,assigned_to,evidence_report_id,issue_type,summary,description,urgency,follow_up) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[u.tenantId,u.employeeId,b.assetId||null,handlers[0]?.id||null,b.evidenceReportId||null,b.issueType,summary,description,b.urgency,followUp])).rows[0];
 if(b.issueType==='damage'&&!b.evidenceReportId)await c.query("INSERT INTO asset_condition_reports(tenant_id,asset_id,assignment_id,reported_by,condition,notes) VALUES($1,$2,$3,$4,'damaged',$5)",[u.tenantId,b.assetId,assignment,u.employeeId,description]);await event(c,u,ticket.id,'open',null);return {ticket};});
 route('get','/handlers',async(_r,c,u)=>{if(!await supportAuthority(c,u,'support.manage'))fail('Support handling requires permission.',403);const handlers=[];for(const e of (await c.query("SELECT id,full_name name FROM employees WHERE tenant_id=$1 AND is_active AND employment_status='active' ORDER BY full_name LIMIT 200",[u.tenantId])).rows)if(await supportAuthority(c,{tenantId:u.tenantId,employeeId:e.id},'support.manage'))handlers.push(e);return {handlers};});
 route('get','/:id',async(r,c,u)=>{if(!uuid(r.params.id))fail('Ticket unavailable.',404);const manager=await supportAuthority(c,u)||await supportAuthority(c,u,'support.manage');const ticket=(await c.query('SELECT * FROM support_tickets WHERE tenant_id=$1 AND id=$2 AND ($3::boolean OR requester_id=$4)',[u.tenantId,r.params.id,manager,u.employeeId])).rows[0];if(!ticket)fail('Ticket unavailable.',404);const history=(await c.query('SELECT id,status,note,created_at FROM support_ticket_events WHERE tenant_id=$1 AND ticket_id=$2 ORDER BY created_at,id',[u.tenantId,ticket.id])).rows;return {ticket,history};});
 route('post','/:id/update',async(r,c,u)=>{if(!uuid(r.params.id))fail('Ticket unavailable.',404);if(!await supportAuthority(c,u,'support.manage'))fail('Support handling requires permission.',403);const b=r.body??{};if(Object.keys(b).some(k=>!['status','assignedTo','note'].includes(k))||!['open','in_progress','waiting_requester','resolved','closed'].includes(b.status))fail('Invalid ticket update.');if(b.assignedTo&&!uuid(b.assignedTo))fail('Invalid handler.');if(b.assignedTo&&!await supportAuthority(c,{tenantId:u.tenantId,employeeId:b.assignedTo},'support.manage'))fail('Handler is not authorized in this company.',403);const updated=(await c.query('UPDATE support_tickets SET status=$3,assigned_to=COALESCE($4::uuid,assigned_to),updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id',[u.tenantId,r.params.id,b.status,b.assignedTo||null])).rows[0];if(!updated)fail('Ticket unavailable.',404);await event(c,u,updated.id,b.status,text(b.note,2000));return {updated:true};});
}
