import type express from 'express';
import type {PoolClient} from 'pg';
import {withTenant} from '../../lib/hr-background';
import {resolveScopedPermission} from '../organisation/scoped-permissions';
import {getIntent,normalizeQuery} from '../../lib/intelligent-router';
import {recordAuditEvent} from '../audit/audit-events';
import {logServerError} from '../../lib/server-logging';
import {sanitizeShared,analyzeExample,safeForTenant} from './semantic-privacy';
import {promoteCandidate} from './store';
import type {EmbeddingProvider} from './providers';
import {routerConfig} from './config';
import type {EntityTemplate} from '../../lib/router-entities';
type Actor={tenantId:string;employeeId:string};
type Deps={standardAuth:express.RequestHandler;mutationGuard:express.RequestHandler;rateLimiter:express.RequestHandler};
const uuid=(x:unknown):x is string=>typeof x==='string'&&/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(x);
const deny=()=>{throw Error('SEMANTIC_FORBIDDEN');};
export async function semanticCapabilities(c:PoolClient,u:Actor){
 const active=(await c.query("SELECT 1 FROM employees WHERE tenant_id=$1 AND id=$2 AND is_active AND employment_status='active'",[u.tenantId,u.employeeId])).rowCount;
 if(!active)return {tenant:[] as string[],platform:[] as string[]};
 const tenant:string[]=[];
 for(const key of ['view_analytics','review_candidates','manage_examples','manage_privacy'])if((await resolveScopedPermission(c,{tenantId:u.tenantId,actorEmployeeId:u.employeeId,permissionKey:'semantic.'+key})).allowed)tenant.push(key);
 const platform=(await c.query('SELECT capabilities FROM router_platform_authorities WHERE tenant_id=$1 AND employee_id=$2 AND revoked_at IS NULL',[u.tenantId,u.employeeId])).rows[0]?.capabilities??[];
 return {tenant,platform:platform as string[]};
}
export async function semanticAudit(c:PoolClient,tenant:string,actor:string,action:string,target:string,metadata:Record<string,unknown>={}){
 await c.query('INSERT INTO router_review_history(tenant_id,actor_reference,target_id,action,metadata) VALUES($1,$2,$3,$4,$5::jsonb)',[tenant,actor,target,action,JSON.stringify(metadata)]);
 await recordAuditEvent(c,{tenantId:tenant,actorId:null,action:'semantic.'+action,targetType:'semantic_intelligence',targetId:target,metadata:{actorReference:actor,...metadata}});
}
export async function privacyMode(c:PoolClient,tenant:string){return (await c.query('SELECT mode FROM router_privacy_settings WHERE tenant_id=$1',[tenant])).rows[0]?.mode??'PRIVATE';}
async function privacyLock(c:PoolClient,tenant:string){await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['semantic-privacy:'+tenant]);}
function templateFor(text:string):EntityTemplate|null{
 const placeholders=[...text.matchAll(/\{(employee|location|asset|job_opening|candidate|duration|date_range)\}/g)].map(m=>({type:m[1] as EntityTemplate['placeholders'][number]['type'],start:m.index,end:m.index+m[0].length}));
 return placeholders.length?{version:1,text,placeholders}:null;
}
async function tenantOverview(c:PoolClient,tenant:string,days:number){
 const counts=(await c.query(`SELECT (SELECT count(*) FROM router_semantic_examples WHERE tenant_id=$1 AND scope='TENANT_PRIVATE') private_examples,(SELECT count(*) FROM router_semantic_examples WHERE tenant_id=$1 AND approval_state='approved') approved_examples,(SELECT count(*) FROM router_candidates WHERE tenant_id=$1 AND review_state='pending' AND confirmation_state='confirmed' AND expires_at>now()) pending_candidates,(SELECT count(*) FROM router_candidates WHERE tenant_id=$1 AND review_state='rejected') rejected_candidates,(SELECT count(*) FROM router_candidates WHERE tenant_id=$1 AND classification IN ('exact_duplicate','near_duplicate')) duplicate_count,(SELECT count(*) FROM router_candidates WHERE tenant_id=$1 AND classification='cross_intent_conflict') conflict_count,(SELECT count(*) FROM router_shared_candidates WHERE tenant_id=$1 AND state='approved' AND reviewed_at>=current_date-($2::int-1)) shared_promotions`,[tenant,days])).rows[0];
 const daily=(await c.query('SELECT * FROM router_daily_metrics WHERE tenant_id=$1 AND day>=current_date-($2::int-1) ORDER BY day,method',[tenant,days])).rows;
 const sum=(rows:typeof daily,key:string)=>rows.reduce((n,r)=>n+Number(r[key]??0),0),requests=sum(daily,'requests');
 const metrics={requests,layerPercentages:Object.fromEntries(['existing','exact','rule','semantic','llm'].map(m=>[m,requests?sum(daily.filter(r=>r.method===m),'requests')*100/requests:0])),outcomePercentages:Object.fromEntries(['ambiguous','no_match','unauthorized','provider_unavailable'].map(m=>[m,requests?sum(daily.filter(r=>r.outcome===m),'requests')*100/requests:0])),llmFallbackPercent:requests?sum(daily,'fallbacks')*100/requests:0,promotions:sum(daily,'promotions'),learnedSemanticHits:sum(daily,'semantic_after_promotion'),learnedHitRate:requests?sum(daily,'semantic_after_promotion')/requests:0};
 const timings=(await c.query(`SELECT 'search' kind,embedding_model model,embedding_version revision,embedding_dimensions dimensions,max(semantic_row_count) corpus_size,percentile_cont(.5) WITHIN GROUP(ORDER BY sample) p50_ms,percentile_cont(.95) WITHIN GROUP(ORDER BY sample) p95_ms FROM router_vector_metrics LEFT JOIN LATERAL unnest(latency_samples) sample ON true WHERE tenant_id=$1 AND day>=current_date-($2::int-1) GROUP BY embedding_model,embedding_version,embedding_dimensions`,[tenant,days])).rows;
 // Rolling bounded timing samples, not raw queries or vectors.
 for(const table of ['router_embedding_metrics','router_http_metrics']){
  const rows=(await c.query(`SELECT ${table==='router_http_metrics'?'kind':"'embedding'::text kind"},percentile_cont(.5) WITHIN GROUP(ORDER BY sample) p50_ms,percentile_cont(.95) WITHIN GROUP(ORDER BY sample) p95_ms,count(sample) sample_count FROM ${table} LEFT JOIN LATERAL unnest(latency_samples) sample ON true WHERE tenant_id=$1 AND day>=current_date-($2::int-1) GROUP BY 1`,[tenant,days])).rows;timings.push(...rows);
 }
 const intents=(await c.query(`SELECT intent_key,sum(requests) requests,sum(fallbacks) fallbacks,sum(requests) FILTER(WHERE outcome='ambiguous') ambiguities,sum(semantic_after_promotion) learned_hits FROM router_daily_metrics WHERE tenant_id=$1 AND day>=current_date-($2::int-1) AND intent_key<>'' GROUP BY intent_key ORDER BY sum(requests) DESC LIMIT 50`,[tenant,days])).rows;
 const growth=(await c.query(`SELECT created_at::date AS day,count(*) added FROM router_semantic_examples WHERE tenant_id=$1 AND created_at>=current_date-($2::int-1) GROUP BY 1 ORDER BY 1`,[tenant,days])).rows;
 const health=(await c.query(`SELECT e.id,e.intent_key,e.created_at,COALESCE(sum(h.hits),0) hits FROM router_semantic_examples e LEFT JOIN router_example_hits h ON h.example_id=e.id AND h.tenant_id=$1 WHERE e.tenant_id=$1 AND e.created_at<now()-interval '30 days' GROUP BY e.id HAVING COALESCE(sum(h.hits),0)<3 ORDER BY hits,e.created_at LIMIT 50`,[tenant])).rows;
 const coverage=(await c.query("SELECT intent_key,count(*) examples FROM router_semantic_examples WHERE approval_state='approved' GROUP BY intent_key ORDER BY count(*),intent_key LIMIT 100")).rows;
 const lastActivity=(await c.query('SELECT max(day) last_activity FROM router_daily_metrics WHERE tenant_id=$1',[tenant])).rows[0]?.last_activity??null;
 const operational=(await c.query('SELECT kind,method,outcome,fallback,clarification,sum(queries)::int queries FROM router_operational_metrics WHERE tenant_id=$1 AND day>=current_date-($2::int-1) GROUP BY kind,method,outcome,fallback,clarification',[tenant,days])).rows;
 return {lastActivity,counts,metrics,operational,daily,intents,growth,timings,health,coverage,privacyMode:await privacyMode(c,tenant),windowDays:days};
}
async function timingSamples(c:PoolClient,tenant:string,days:number){
 const data:{kind:string;value:number}[]=[];
 for(const [table,kind] of [['router_vector_metrics','search'],['router_embedding_metrics','embedding'],['router_http_metrics','http']]){
 const rows=(await c.query(`SELECT ${table==='router_http_metrics'?'kind':'$3::text kind'},latency_samples FROM ${table} WHERE tenant_id=$1 AND day>=current_date-($2::int-1)`,table==='router_http_metrics'?[tenant,days]:[tenant,days,kind])).rows;
 for(const r of rows)for(const value of r.latency_samples)data.push({kind:r.kind,value:Number(value)});
 }return data;
}
function samplePercentiles(data:{kind:string;value:number}[]){return [...new Set(data.map(r=>r.kind))].map(kind=>{const v=data.filter(r=>r.kind===kind).map(r=>r.value).sort((a,b)=>a-b);const at=(q:number)=>{const n=(v.length-1)*q,i=Math.floor(n);return v[i]+(v[Math.ceil(n)]-v[i])*(n-i);};return {kind,p50_ms:at(.5),p95_ms:at(.95),sample_count:v.length};});}
export function registerSemanticAdminRoutes(app:express.Express,d:Deps,provider:EmbeddingProvider|undefined){
 const run=(method:'get'|'post',path:string,fn:(req:express.Request,u:Actor)=>Promise<object>)=>app[method]('/api/semantic-intelligence'+path,d.standardAuth,d.rateLimiter,...(method==='post'?[d.mutationGuard]:[]),async(req,res)=>{
  res.setHeader('Cache-Control','no-store');
  try{res.json({success:true,...await fn(req,{tenantId:req.authUser!.tenantId,employeeId:req.authUser!.employeeId})});}
  catch(e){const code=e instanceof Error?e.message:'';const expected=['SEMANTIC_FORBIDDEN','INVALID_QUERY','CANDIDATE_UNAVAILABLE','EMBEDDING_DISABLED','SENSITIVE','PRIVATE_MODE','CONTRADICTORY_EXAMPLE','REVIEW_DENIED','DUPLICATE','CONFIRM_REQUIRED','CONFLICT_REVIEW_REQUIRED','PRIVATE_ONLY'];if(expected.includes(code)){res.status(code==='SEMANTIC_FORBIDDEN'||code==='REVIEW_DENIED'?403:code==='CANDIDATE_UNAVAILABLE'?404:409).json({success:false,code});}else{logServerError('[Semantic intelligence]',e);res.status(503).json({success:false,code:'SEMANTIC_UNAVAILABLE'});}}
 });
 const check=async(c:PoolClient,u:Actor,key:string,platform=false)=>{const caps=await semanticCapabilities(c,u);if(!(platform?caps.platform:caps.tenant).includes(key))deny();await c.query("SELECT set_config('app.semantic_actor',$1,true)",[u.employeeId]);};
 const days=(r:express.Request)=>{const n=Number(r.query.days??30);if(![7,30,90].includes(n))throw Error('INVALID_QUERY');return n;};
 const page=(r:express.Request)=>{const n=Number(r.query.page??1);if(!Number.isInteger(n)||n<1||n>10000)throw Error('INVALID_QUERY');return n;};
 const id=(r:express.Request)=>{if(!uuid(r.params.id))throw Error('INVALID_QUERY');return r.params.id as string;};
 run('get','/capabilities',async(_r,u)=>withTenant(u.tenantId,c=>semanticCapabilities(c,u)));
 run('get','/overview',async(r,u)=>withTenant(u.tenantId,async c=>{await check(c,u,'view_analytics');return {...await tenantOverview(c,u.tenantId,days(r)),model:provider?{provider:routerConfig().embeddingProvider,model:provider.model,revision:provider.version,dimensions:provider.dimensions,quantization:routerConfig().embeddingProvider==='local'?'q8':null}:null};}));
 run('get','/privacy',async(_r,u)=>withTenant(u.tenantId,async c=>{await check(c,u,'manage_privacy');return {mode:await privacyMode(c,u.tenantId)};}));
 run('post','/privacy',async(r,u)=>withTenant(u.tenantId,async c=>{await check(c,u,'manage_privacy');if(!['SHARED','PRIVATE','STRICT_PRIVATE'].includes(r.body?.mode)||r.body.confirm!==true)throw Error('CONFIRM_REQUIRED');await privacyLock(c,u.tenantId);const old=await privacyMode(c,u.tenantId);await c.query('INSERT INTO router_privacy_settings(tenant_id,mode) VALUES($1,$2) ON CONFLICT(tenant_id) DO UPDATE SET mode=EXCLUDED.mode,updated_at=now()',[u.tenantId,r.body.mode]);await semanticAudit(c,u.tenantId,u.employeeId,'privacy_changed',u.tenantId,{previousMode:old,mode:r.body.mode});return {mode:r.body.mode};}));
 run('get','/candidates',async(r,u)=>withTenant(u.tenantId,async c=>{await check(c,u,'review_candidates');const rows=(await c.query(`SELECT id,COALESCE(entity_template->>'text',normalized_query) phrase,proposed_intent intent,confirmation_state,review_state,classification,analysis,private_only,entity_template,created_at,expires_at,resolution_source source FROM router_candidates WHERE tenant_id=$1 AND confirmation_state='confirmed' ORDER BY created_at DESC LIMIT 25 OFFSET $2`,[u.tenantId,(page(r)-1)*25])).rows;return {candidates:rows,page:page(r)};}));
 run('post','/candidates/:id/analyze',async(r,u)=>withTenant(u.tenantId,async c=>{await check(c,u,'review_candidates');if(!provider)throw Error('EMBEDDING_DISABLED');const row=(await c.query("SELECT * FROM router_candidates WHERE tenant_id=$1 AND id=$2 AND review_state='pending' AND confirmation_state='confirmed' AND expires_at>now() FOR UPDATE",[u.tenantId,id(r)])).rows[0];if(!row)throw Error('CANDIDATE_UNAVAILABLE');const analysis={...await analyzeExample(c,u.tenantId,row.normalized_query,row.proposed_intent,provider),privacySafe:await safeForTenant(c,u.tenantId,row.normalized_query,row.entity_template)};if(!analysis.privacySafe&&!['exact_duplicate','cross_intent_conflict','near_duplicate'].includes(analysis.classification))analysis.classification='sensitive';await c.query('UPDATE router_candidates SET classification=$3,analysis=$4::jsonb WHERE tenant_id=$1 AND id=$2',[u.tenantId,id(r),analysis.classification,JSON.stringify(analysis)]);return {analysis,sharedEligible:sanitizeShared(row.normalized_query,row.entity_template)&&await privacyMode(c,u.tenantId)==='SHARED'&&!row.private_only};}));
 run('post','/candidates/:id/review',async(r,u)=>{
  const candidateId=id(r),decision=r.body?.decision;
  if(!['approve','reject','dismiss_duplicate','private_only','change_intent'].includes(decision))throw Error('INVALID_QUERY');
  if(decision==='approve'){
   if(!provider)throw Error('EMBEDDING_DISABLED');
   await withTenant(u.tenantId,async c=>{await check(c,u,'review_candidates');const row=(await c.query("SELECT * FROM router_candidates WHERE tenant_id=$1 AND id=$2 AND review_state='pending' AND confirmation_state='confirmed' AND expires_at>now()",[u.tenantId,candidateId])).rows[0];if(!row)throw Error('CANDIDATE_UNAVAILABLE');const a=await analyzeExample(c,u.tenantId,row.normalized_query,row.proposed_intent,provider);await c.query('UPDATE router_candidates SET classification=$3,analysis=$4::jsonb WHERE tenant_id=$1 AND id=$2',[u.tenantId,candidateId,a.classification,JSON.stringify(a)]);if(a.classification==='cross_intent_conflict')throw Error('CONFLICT_REVIEW_REQUIRED');if(a.classification==='near_duplicate')throw Error('DUPLICATE');});
   const result=await promoteCandidate(u.tenantId,u.employeeId,candidateId,provider,async c=>{await check(c,u,'review_candidates');return true;});await withTenant(u.tenantId,c=>semanticAudit(c,u.tenantId,u.employeeId,'candidate_approved',candidateId));return result;
  }
  return withTenant(u.tenantId,async c=>{await check(c,u,'review_candidates');const row=(await c.query("SELECT * FROM router_candidates WHERE tenant_id=$1 AND id=$2 AND review_state='pending' AND confirmation_state='confirmed' FOR UPDATE",[u.tenantId,candidateId])).rows[0];if(!row)throw Error('CANDIDATE_UNAVAILABLE');if(decision==='change_intent'){if(!getIntent(r.body.intent)||row.entity_template&&!getIntent(r.body.intent)?.entities)throw Error('INVALID_QUERY');await c.query("UPDATE router_candidates SET proposed_intent=$3,classification='needs_review',analysis='{}' WHERE tenant_id=$1 AND id=$2",[u.tenantId,candidateId,r.body.intent]);}else if(decision==='private_only')await c.query('UPDATE router_candidates SET private_only=$3 WHERE tenant_id=$1 AND id=$2',[u.tenantId,candidateId,r.body.privateOnly!==false]);else await c.query("UPDATE router_candidates SET review_state='rejected',reviewed_at=now(),reviewed_by=$3,classification=CASE WHEN $4='dismiss_duplicate' THEN 'exact_duplicate' ELSE classification END WHERE tenant_id=$1 AND id=$2",[u.tenantId,candidateId,u.employeeId,decision]);await semanticAudit(c,u.tenantId,u.employeeId,'candidate_'+decision,candidateId,{intent:r.body.intent??row.proposed_intent});return {updated:true};});
 });
 run('get','/examples',async(r,u)=>withTenant(u.tenantId,async c=>{await check(c,u,'manage_examples');return {examples:(await c.query(`SELECT e.id,e.example_text phrase,e.intent_key intent,e.scope,e.source,e.approval_state,e.created_at,e.entity_template,(SELECT analysis FROM router_candidates c WHERE c.tenant_id=$1 AND c.id=e.source_candidate_id) analysis,(SELECT classification FROM router_candidates c WHERE c.tenant_id=$1 AND c.id=e.source_candidate_id) classification,COALESCE((SELECT sum(hits) FROM router_example_hits h WHERE h.tenant_id=$1 AND h.example_id=e.id),0) hit_count,(SELECT max(last_hit) FROM router_example_hits h WHERE h.tenant_id=$1 AND h.example_id=e.id) last_hit,(SELECT state FROM router_shared_candidates s WHERE s.source_example_id=e.id LIMIT 1) shared_state FROM router_semantic_examples e WHERE tenant_id=$1 AND scope='TENANT_PRIVATE' ORDER BY created_at DESC LIMIT 25 OFFSET $2`,[u.tenantId,(page(r)-1)*25])).rows,page:page(r)};}));
 run('post','/examples/:id/action',async(r,u)=>withTenant(u.tenantId,async c=>{await check(c,u,'manage_examples');const action=r.body?.action;if(!['deactivate','reactivate','delete'].includes(action)||r.body.confirm!==true)throw Error('CONFIRM_REQUIRED');const result=await c.query(action==='delete'?"DELETE FROM router_semantic_examples WHERE tenant_id=$1 AND id=$2 AND scope='TENANT_PRIVATE' RETURNING id":"UPDATE router_semantic_examples SET approval_state=$3 WHERE tenant_id=$1 AND id=$2 AND scope='TENANT_PRIVATE' RETURNING id",action==='delete'?[u.tenantId,id(r)]:[u.tenantId,id(r),action==='reactivate'?'approved':'disabled']);if(!result.rowCount)throw Error('CANDIDATE_UNAVAILABLE');await semanticAudit(c,u.tenantId,u.employeeId,'example_'+action,id(r));return {updated:true};}));
 run('post','/examples/:id/contribute',async(r,u)=>withTenant(u.tenantId,async c=>{await check(c,u,'manage_examples');if(r.body?.confirm!==true)throw Error('CONFIRM_REQUIRED');await privacyLock(c,u.tenantId);if(await privacyMode(c,u.tenantId)!=='SHARED')throw Error('PRIVATE_MODE');const row=(await c.query("SELECT * FROM router_semantic_examples WHERE tenant_id=$1 AND id=$2 AND scope='TENANT_PRIVATE' AND approval_state='approved'",[u.tenantId,id(r)])).rows[0];if(!row)throw Error('CANDIDATE_UNAVAILABLE');if(row.source_candidate_id&&(await c.query('SELECT private_only FROM router_candidates WHERE id=$1 AND tenant_id=$2',[row.source_candidate_id,u.tenantId])).rows[0]?.private_only)throw Error('PRIVATE_ONLY');const sharedText=row.entity_template?.text??row.example_text;if(!await safeForTenant(c,u.tenantId,sharedText,row.entity_template))throw Error('SENSITIVE');const candidate=(await c.query(`INSERT INTO router_shared_candidates(tenant_id,source_example_id,generalized_text,intent_key,entity_template,generalization_method) VALUES($1,$2,$3,$4,$5::jsonb,$6) ON CONFLICT(source_example_id) DO NOTHING RETURNING id`,[u.tenantId,row.id,sharedText,row.intent_key,row.entity_template?JSON.stringify(row.entity_template):null,row.entity_template?'typed_entities':'generic_vocabulary'])).rows[0];if(candidate)await semanticAudit(c,u.tenantId,u.employeeId,'shared_candidate_created',candidate.id,{sourceExample:row.id});return {created:Boolean(candidate)};}));
 run('get','/history',async(r,u)=>withTenant(u.tenantId,async c=>{await check(c,u,'view_analytics');return {history:(await c.query('SELECT target_id,action,metadata,created_at FROM router_review_history WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 50 OFFSET $2',[u.tenantId,(page(r)-1)*50])).rows};}));
 run('get','/platform/overview',async(r,u)=>{const summary=await withTenant(u.tenantId,async c=>{await check(c,u,'view_all',true);const counts=(await c.query("SELECT scope,count(*) count FROM router_semantic_examples WHERE tenant_id IS NULL GROUP BY scope")).rows;return {counts,tenantIds:(await c.query('SELECT id FROM tenants ORDER BY id')).rows.map(t=>t.id as string),pendingShared:(await c.query("SELECT count(*) FROM router_shared_candidates WHERE state='pending'")).rows[0].count,windowDays:days(r),model:provider?{provider:routerConfig().embeddingProvider,model:provider.model,revision:provider.version,dimensions:provider.dimensions}:null,strategy:'Exact pgvector search',thresholds:{score:.84,margin:.10}};});
  const overviews=[];for(let i=0;i<summary.tenantIds.length;i+=5)overviews.push(...await Promise.all(summary.tenantIds.slice(i,i+5).map(t=>withTenant(t,async c=>({...await tenantOverview(c,t,days(r)),samples:await timingSamples(c,t,days(r))})))));
  const counts:Record<string,number>=Object.fromEntries(summary.counts.map(c=>[c.scope,Number(c.count)]));for(const o of overviews)for(const [k,v] of Object.entries(o.counts))counts[k]=(counts[k]??0)+Number(v);
  counts.pending_shared=Number(summary.pendingShared);
  const requests=overviews.reduce((n,o)=>n+o.metrics.requests,0);const weighted=(key:'layerPercentages'|'outcomePercentages')=>Object.fromEntries([...new Set(overviews.flatMap(o=>Object.keys(o.metrics[key])))].map(k=>[k,requests?overviews.reduce((n,o)=>n+(o.metrics[key][k]??0)*o.metrics.requests,0)/requests:0]));
  const metrics={requests,layerPercentages:weighted('layerPercentages'),outcomePercentages:weighted('outcomePercentages'),llmFallbackPercent:requests?overviews.reduce((n,o)=>n+o.metrics.llmFallbackPercent*o.metrics.requests,0)/requests:0,learnedSemanticHits:overviews.reduce((n,o)=>n+o.metrics.learnedSemanticHits,0),promotions:overviews.reduce((n,o)=>n+o.metrics.promotions,0),learnedHitRate:requests?overviews.reduce((n,o)=>n+o.metrics.learnedSemanticHits,0)/requests:0};
  const combinedIntents=new Map<string,{intent_key:string;requests:number;fallbacks:number;ambiguities:number;learned_hits:number}>();for(const o of overviews)for(const i of o.intents){const prev=combinedIntents.get(i.intent_key)??{intent_key:i.intent_key,requests:0,fallbacks:0,ambiguities:0,learned_hits:0};for(const k of ['requests','fallbacks','ambiguities','learned_hits'] as const)prev[k]+=Number(i[k]??0);combinedIntents.set(i.intent_key,prev);}
 const combinedGrowth=new Map<string,number>();for(const o of overviews)for(const g of o.growth){const key=new Date(g.day).toISOString().slice(0,10);combinedGrowth.set(key,(combinedGrowth.get(key)??0)+Number(g.added));}
 const {tenantIds,...safe}=summary;return {...safe,counts,metrics,tenantCount:tenantIds.length,growth:[...combinedGrowth].map(([day,added])=>({day,added})),intents:[...combinedIntents.values()].sort((a,b)=>b.requests-a.requests),timings:samplePercentiles(overviews.flatMap(o=>o.samples))};
 });
 run('get','/platform/tenants',async(r,u)=>{
  const tenants=await withTenant(u.tenantId,async c=>{await check(c,u,'view_tenants',true);return (await c.query('SELECT id,company_name FROM tenants ORDER BY company_name,id LIMIT 25 OFFSET $1',[(page(r)-1)*25])).rows;});
  const rows=[];for(const t of tenants){const data=await withTenant(t.id,c=>tenantOverview(c,t.id,days(r)));rows.push({id:t.id,name:t.company_name,lastActivity:data.lastActivity,privacyMode:data.privacyMode,counts:data.counts,metrics:data.metrics,timings:data.timings,growth:data.growth,intents:data.intents});}return {tenants:rows,page:page(r),windowDays:days(r)};
 });
 run('get','/platform/tenants/:id',async(r,u)=>{const tenant=id(r);await withTenant(u.tenantId,async c=>{await check(c,u,'view_tenants',true);await check(c,u,'view_all',true);if(!(await c.query('SELECT 1 FROM tenants WHERE id=$1',[tenant])).rowCount)throw Error('CANDIDATE_UNAVAILABLE');await semanticAudit(c,u.tenantId,u.employeeId,'tenant_drilldown',tenant);});return withTenant(tenant,async c=>({...await tenantOverview(c,tenant,days(r)),examples:(await c.query('SELECT id,example_text phrase,intent_key intent,scope,approval_state FROM router_semantic_examples WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 25',[tenant])).rows}));});
 run('get','/platform/shared-review',async(r,u)=>withTenant(u.tenantId,async c=>{await check(c,u,'review_global',true);const candidates=(await c.query('SELECT id,tenant_id source_tenant_reference,generalized_text phrase,intent_key intent,entity_template,classification,analysis,generalization_method,state,created_at FROM router_shared_candidates ORDER BY created_at DESC LIMIT 25 OFFSET $1',[(page(r)-1)*25])).rows;for(const row of candidates)row.privacyMode=await withTenant(row.source_tenant_reference,tc=>privacyMode(tc,row.source_tenant_reference));return {candidates};}));
 run('post','/platform/shared-review/:id/analyze',async(r,u)=>withTenant(u.tenantId,async c=>{await check(c,u,'review_global',true);if(!provider)throw Error('EMBEDDING_DISABLED');const row=(await c.query("SELECT * FROM router_shared_candidates WHERE id=$1 AND state='pending' FOR UPDATE",[id(r)])).rows[0];if(!row)throw Error('CANDIDATE_UNAVAILABLE');const analysis=await analyzeExample(c,'00000000-0000-0000-0000-000000000000',row.generalized_text,row.intent_key,provider);await c.query('UPDATE router_shared_candidates SET classification=$2,analysis=$3::jsonb WHERE id=$1',[id(r),analysis.classification,JSON.stringify(analysis)]);return {analysis};}));
 run('post','/platform/shared-review/:id',async(r,u)=>{
  const sharedId=id(r);if(!['approve','reject','edit','sensitive','duplicate'].includes(r.body?.decision))throw Error('INVALID_QUERY');
  return withTenant(u.tenantId,async c=>{
   await check(c,u,'review_global',true);const row=(await c.query("SELECT * FROM router_shared_candidates WHERE id=$1 AND state='pending' FOR UPDATE",[sharedId])).rows[0];if(!row)throw Error('CANDIDATE_UNAVAILABLE');await privacyLock(c,row.tenant_id);
   const text=typeof r.body.text==='string'?r.body.text:row.generalized_text,intent=typeof r.body.intent==='string'?r.body.intent:row.intent_key,template=templateFor(text);
   if(!getIntent(intent)||getIntent(intent)?.entities&&!template||template&&!getIntent(intent)?.entities)throw Error('INVALID_QUERY');
   if(['reject','sensitive','duplicate'].includes(r.body.decision)){await c.query("UPDATE router_shared_candidates SET state='rejected',classification=CASE WHEN $2='sensitive' THEN 'sensitive' WHEN $2='duplicate' THEN 'near_duplicate' ELSE classification END,reviewed_at=now(),reviewer_reference=$3 WHERE id=$1",[sharedId,r.body.decision,u.employeeId]);await semanticAudit(c,u.tenantId,u.employeeId,'shared_'+r.body.decision,sharedId);return {updated:true};}
   if(!sanitizeShared(text,template))throw Error('SENSITIVE');
   const source=await withTenant(row.tenant_id,async tc=>({safe:await safeForTenant(tc,row.tenant_id,text,template),mode:await privacyMode(tc,row.tenant_id),exists:Boolean((await tc.query("SELECT 1 FROM router_semantic_examples WHERE id=$1 AND tenant_id=$2 AND scope='TENANT_PRIVATE' AND approval_state='approved'",[row.source_example_id,row.tenant_id])).rowCount)}));
   if(!source.safe)throw Error('SENSITIVE');
   if(source.mode!=='SHARED'||!source.exists)throw Error('PRIVATE_MODE');
   if(!provider)throw Error('EMBEDDING_DISABLED');
   await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['semantic-global:'+provider.model+':'+provider.version]);
   const exact=(await c.query('SELECT id FROM router_semantic_examples WHERE tenant_id IS NULL AND normalized_text=$1 AND embedding_model=$2 AND embedding_dimensions=$3 AND embedding_version=$4',[normalizeQuery(text),provider.model,provider.dimensions,provider.version])).rowCount;
   const vector=exact?undefined:await provider.embed(normalizeQuery(text));const analysis=await analyzeExample(c,'00000000-0000-0000-0000-000000000000',text,intent,provider,vector);
   if(r.body.decision==='edit'){await c.query('UPDATE router_shared_candidates SET generalized_text=$2,intent_key=$3,entity_template=$4::jsonb,classification=$5,analysis=$6::jsonb WHERE id=$1',[sharedId,text,intent,template?JSON.stringify(template):null,analysis.classification,JSON.stringify(analysis)]);await semanticAudit(c,u.tenantId,u.employeeId,'shared_text_edited',sharedId,{intent});return {analysis};}
   await check(c,u,'manage_global',true);
   if(r.body.confirm!==true)throw Error('CONFIRM_REQUIRED');
   if(analysis.classification==='cross_intent_conflict')throw Error('CONFLICT_REVIEW_REQUIRED');if(['exact_duplicate','near_duplicate'].includes(analysis.classification))throw Error('DUPLICATE');
   const shared=(await c.query(`INSERT INTO router_semantic_examples(tenant_id,scope,source,intent_key,example_text,normalized_text,embedding,embedding_model,embedding_dimensions,embedding_version,approval_state,entity_template) VALUES(NULL,'SHARED','shared',$1,$2,$3,$4::vector,$5,$6,$7,'approved',$8::jsonb) RETURNING id`,[intent,text,normalizeQuery(text),JSON.stringify(vector),provider.model,provider.dimensions,provider.version,template?JSON.stringify(template):null])).rows[0];
   await c.query("UPDATE router_shared_candidates SET state='approved',shared_example_id=$2,generalized_text=$3,intent_key=$4,classification=$5,analysis=$6::jsonb,reviewed_at=now(),reviewer_reference=$7 WHERE id=$1",[sharedId,shared.id,text,intent,analysis.classification,JSON.stringify(analysis),u.employeeId]);await semanticAudit(c,u.tenantId,u.employeeId,'shared_approved',sharedId,{intent,sharedExample:shared.id});return {promoted:true};
  });
 });
 run('get','/platform/corpus',async(r,u)=>{const data=await withTenant(u.tenantId,async c=>{await check(c,u,'view_all',true);const scope=r.query.scope??'SYSTEM';if(!['SYSTEM','SHARED'].includes(String(scope)))throw Error('INVALID_QUERY');return {tenantIds:(await c.query('SELECT id FROM tenants ORDER BY id')).rows.map(t=>t.id as string),examples:(await c.query('SELECT id,example_text phrase,intent_key intent,scope,source,embedding_model model,embedding_version revision,embedding_dimensions dimensions,approval_state,created_at FROM router_semantic_examples WHERE scope=$1 ORDER BY intent_key,created_at DESC LIMIT 25 OFFSET $2',[scope,(page(r)-1)*25])).rows,page:page(r)};});
 const totals=new Map<string,{hits:number;last:string|null}>();for(const tenant of data.tenantIds){const rows=await withTenant(tenant,async c=>(await c.query('SELECT example_id,sum(hits) hits,max(last_hit) last FROM router_example_hits WHERE tenant_id=$1 AND example_id=ANY($2::uuid[]) GROUP BY example_id',[tenant,data.examples.map(e=>e.id)])).rows);for(const r of rows){const prev=totals.get(r.example_id)??{hits:0,last:null};totals.set(r.example_id,{hits:prev.hits+Number(r.hits),last:prev.last&&new Date(prev.last)>new Date(r.last)?prev.last:r.last});}}
 return {examples:data.examples.map(e=>({...e,hit_count:totals.get(e.id)?.hits??0,last_hit:totals.get(e.id)?.last??null})),page:data.page};
 });
 run('post','/platform/corpus/:id',async(r,u)=>withTenant(u.tenantId,async c=>{await check(c,u,'manage_global',true);if(!['deactivate','reactivate'].includes(r.body?.action)||r.body.confirm!==true)throw Error('CONFIRM_REQUIRED');const row=(await c.query("UPDATE router_semantic_examples SET approval_state=$2 WHERE id=$1 AND scope IN ('SYSTEM','SHARED') RETURNING id",[id(r),r.body.action==='reactivate'?'approved':'disabled'])).rows[0];if(!row)throw Error('CANDIDATE_UNAVAILABLE');await semanticAudit(c,u.tenantId,u.employeeId,'corpus_'+r.body.action,id(r));return {updated:true};}));
}
