import { useCallback, useEffect, useState } from 'react';
import type { AuthUser } from '../../auth/auth-contract';
import { apiFetch, apiUrl } from '../../lib/api';
import { useLanguage } from '../../lib/LanguageContext';
import { CASE_STATUSES, CASE_PRIORITIES, CASE_CATEGORIES, CASE_TRANSITIONS, type CaseStatus } from '../../lib/grievance-contract';
import { GRIEVANCE_COPY } from '../../lib/grievance-copy';
import { Input, Select, Textarea } from '../ui/FormControls';
import { Surface } from '../ui/Surface';
import './grievances.css';
type Row = Record<string, any>;
const emptyFilters = { q: '', status: '', priority: '', department: '', assignee: '', category: '', from: '', to: '', view: 'all' };
const emptyForm = { title: '', description: '', category: 'general', priority: 'normal', destinationDepartmentId: '', confidentiality: 'standard' };
async function request(url: string, body?: unknown, method = 'POST', signal?: AbortSignal) { const response = await apiFetch(apiUrl('/api/grievances' + url), { method: body === undefined ? 'GET' : method, headers: body === undefined ? undefined : { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body), signal }); const data = await response.json(); if (!response.ok)
    throw Object.assign(new Error(data.error || 'Request failed'), { code: data.code, status: response.status }); return data; }
export default function GrievancesPanel({ user, onBack, onMutation, onEmailDraft, initialView = 'mine', initialCaseId }: {
    user: AuthUser;
    onBack: () => void;
    onMutation?: () => void;
    onEmailDraft?: () => void;
    initialView?: 'mine' | 'inbox' | 'new';
    initialCaseId?: string;
}) {
    const { isRtl } = useLanguage();
    const text = (key: string) => key in GRIEVANCE_COPY ? GRIEVANCE_COPY[key as keyof typeof GRIEVANCE_COPY][isRtl ? 1 : 0] : key;
    const [view, setView] = useState<'mine' | 'inbox' | 'new'>(initialView), [cases, setCases] = useState<Row[]>([]), [total, setTotal] = useState(0), [page, setPage] = useState(1), [filters, setFilters] = useState(emptyFilters), [options, setOptions] = useState<Row>({ departments: [], configure: false }), [selected, setSelected] = useState<string | null>(null), [detail, setDetail] = useState<Row | null>(null), [historyPage, setHistoryPage] = useState(1), [revision, setRevision] = useState(0), [busy, setBusy] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [form, setForm] = useState(emptyForm), [attachment, setAttachment] = useState<File | null>(null), [kind, setKind] = useState('response'), [body, setBody] = useState(''), [nextStatus, setNextStatus] = useState(''), [resolution, setResolution] = useState(''), [response, setResponse] = useState(''), [assignedEmployee, setAssignedEmployee] = useState(''), [assignedDepartment, setAssignedDepartment] = useState(''), [assignees, setAssignees] = useState<Row[]>([]), [priority, setPriority] = useState('normal'), [confidentiality, setConfidentiality] = useState('standard');
    const canCreate=user.permissions?user.permissions.includes('grievances.create'):user.role==='hr_admin';
    const canInbox = user.permissions ? user.permissions.some(p => p === 'grievances.view' || p === 'grievances.review') : user.role === 'hr_admin';
    useEffect(()=>{setView(initialView==='inbox'&&canInbox?'inbox':initialView==='new'&&canCreate?'new':'mine');setSelected(initialCaseId&&canInbox?initialCaseId:null);setPage(1);},[initialView,initialCaseId,canInbox,canCreate]);
    const accountKey = user.tenantId + user.id + user.role + JSON.stringify(user.permissions || []);
    const failure = useCallback((e: unknown) => { const code = (e as {
        code?: string;
    }).code; if([401,403,404].includes((e as {status?:number}).status || 0) || ['CASE_UNAVAILABLE','CASE_PERMISSION_DENIED','PERMISSION_DENIED','INBOX_DENIED'].includes(code||''))setDetail(null); setError(code === 'CASE_CONFLICT' ? GRIEVANCE_COPY.conflict[isRtl ? 1 : 0] : ['CASE_UNAVAILABLE', 'CASE_PERMISSION_DENIED', 'PERMISSION_DENIED', 'INBOX_DENIED'].includes(code || '') ? GRIEVANCE_COPY.denied[isRtl ? 1 : 0] : isRtl ? GRIEVANCE_COPY.error[1] : (e as Error).message); }, [isRtl]);
    useEffect(() => { const abort = new AbortController(); request('/options', undefined, 'GET', abort.signal).then(setOptions).catch(e => { if (!abort.signal.aborted)
        failure(e); }); return () => abort.abort(); }, [revision, accountKey, failure]);
    useEffect(() => { if (selected || view === 'new')
        return; const abort = new AbortController(); setLoading(true); setCases([]); const query = new URLSearchParams({ ...filters, page: String(page) }); request((view === 'mine' ? '/me' : '') + '?' + query, undefined, 'GET', abort.signal).then(data => { setCases(data.grievances); setTotal(data.total); }).catch(e => { if (!abort.signal.aborted)
        failure(e); }).finally(() => { if (!abort.signal.aborted)
        setLoading(false); }); return () => abort.abort(); }, [view, selected, filters, page, revision, accountKey, failure]);
    useEffect(() => { if (!selected) {
        setDetail(null);
        return;
    } const abort = new AbortController(); setLoading(true); setDetail(current => current?.grievance.id === selected ? current : null); request('/' + selected + '?page=' + historyPage, undefined, 'GET', abort.signal).then(data => { setDetail(data); setAssignedEmployee(data.grievance.assigned_to || ''); setAssignedDepartment(data.grievance.assigned_department_id || data.grievance.destination_department_id || ''); setPriority(data.grievance.priority); setConfidentiality(data.grievance.confidentiality); setKind(current => data.owner ? 'follow_up' : current === 'internal' && data.capabilities.internal_notes ? 'internal' : data.capabilities.respond ? 'response' : 'internal'); setNextStatus(''); }).catch(e => { if (!abort.signal.aborted)
        failure(e); }).finally(() => { if (!abort.signal.aborted)
        setLoading(false); }); return () => abort.abort(); }, [selected, historyPage, revision, accountKey, failure]);
    useEffect(() => { if (!selected || !detail?.capabilities.assign)
        return; const abort = new AbortController(); request('/' + selected + '/assignees?' + new URLSearchParams({ department: assignedDepartment }), undefined, 'GET', abort.signal).then(data => { setAssignees(data.assignees); setAssignedEmployee(current => data.assignees.some((a: Row) => a.id === current) ? current : ''); }).catch(e => { if (!abort.signal.aborted) {
        setAssignees([]);
        failure(e);
    } }); return () => abort.abort(); }, [selected, assignedDepartment, detail?.grievance.version, accountKey, failure]);
    const run = async (action: () => Promise<void>) => { if (busy)
        return; setBusy(true); setError(''); setNotice(''); try {
        await action();
        setRevision(n => n + 1);
        onMutation?.();
        setNotice(text('saved'));
    }
    catch (e) {
        failure(e);
    }
    finally {
        setBusy(false);
    } };
    const changeFilter = (key: string, value: string) => { setFilters(current => ({ ...current, [key]: value })); setPage(1); };
    const uploadFile = async (id: string, version: number, file: File) => { const data = new FormData(); data.append('file', file); data.append('version', String(version)); const r = await apiFetch(apiUrl(`/api/grievances/${id}/attachments`), { method: 'POST', body: data }); const result = await r.json(); if (!r.ok)
        throw new Error(result.error); };
    const open = (id: string) => { setSelected(id); setHistoryPage(1); setBody(''); setKind('response'); setAttachment(null); setError(''); setNotice(''); };
    const mutate = async (path: string, data: Row) => { await request('/' + selected + path, { version: detail!.grievance.version, ...data }, 'PATCH'); };
    const activeFilters = Object.entries(filters).filter(([key, value]) => value && !(key === 'view' && value === 'all')).length;
    const date = (value: string) => new Date(value).toLocaleString(isRtl ? 'ar-EG' : 'en-GB');
    const fileControl = <label>{text('attachments')}<Input type="file" key={(selected || 'new') + revision} accept="image/jpeg,image/png,image/webp,application/pdf" disabled={busy || loading} onChange={e => setAttachment(e.target.files?.[0] || null)}/><small>{text('attachmentHelp')}</small></label>;
    return <section className="grievance-workspace" dir={isRtl ? 'rtl' : 'ltr'} aria-labelledby="grievance-heading" aria-busy={loading || busy}>
 <header className="grievance-toolbar"><div><h2 id="grievance-heading">{text(selected ? 'caseDetail' : view === 'new' ? 'newCase' : view)}</h2><p>{text(view === 'new' ? 'submitHelp' : 'accessHelp')}</p></div><button type="button" onClick={selected ? () => { setSelected(null); setError(''); } : onBack}>{selected ? text('back') : text('backProfile')}</button></header>
 <nav className="grievance-toolbar grievance-modes" aria-label={text('heading')}>{(['mine', ...(canInbox ? ['inbox'] : []), ...(canCreate ? ['new'] : [])] as const).map(v => <button key={v} type="button" aria-pressed={view === v && !selected} onClick={() => { setView(v as typeof view); setSelected(null); setPage(1); setError(''); }}>{text(v === 'new' ? 'newCase' : v)}</button>)}<button type="button" disabled={busy || loading} onClick={() => setRevision(n => n + 1)}>{text('refresh')}</button></nav>
 {error && <p role="alert" className="grievance-error">{error}</p>}{notice && <p role="status">{text('saved')}</p>}{loading && <p role="status">{text('loading')}</p>}
 {!selected && canCreate && view === 'new' && <Surface className="stanza-grievance-submission"><form className="grievance-form" onSubmit={e => { e.preventDefault(); void run(async () => { const data = await request('', { ...form, destinationDepartmentId: form.destinationDepartmentId || null }); setForm(emptyForm); setView('mine'); open(data.grievanceId); if (attachment) {
            try {
                await uploadFile(data.grievanceId, data.grievance.version, attachment);
                setAttachment(null);
            }
            catch {
                setAttachment(null);
                throw new Error(text('attachmentRetry'));
            }
        } }); }}>
 <label>{text('subject')}<Input required maxLength={200} value={form.title} onChange={e => setForm({ ...form, title: e.target.value })}/></label>
 <label>{text('description')}<Textarea required rows={8} maxLength={20000} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></label>
 <div className="grievance-fields"><label>{text('category')}<Select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{CASE_CATEGORIES.map(v => <option key={v} value={v}>{text(v)}</option>)}</Select></label><label>{text('department')}<Select required={options.departments.some((d: Row) => d.grievance_enabled)} value={form.destinationDepartmentId} onChange={e => setForm({ ...form, destinationDepartmentId: e.target.value })}><option value="">{text('choose')}</option>{options.departments.filter((d: Row) => d.grievance_enabled).map((d: Row) => <option key={d.id} value={d.id}>{d.name}</option>)}</Select></label><label>{text('priority')}<Select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })}>{CASE_PRIORITIES.filter(v => v !== 'low').map(v => <option key={v} value={v}>{text(v)}</option>)}</Select></label><label>{text('confidentiality')}<Select value={form.confidentiality} onChange={e => setForm({ ...form, confidentiality: e.target.value })}>{['standard', 'confidential'].map(v => <option key={v} value={v}>{text(v)}</option>)}</Select></label></div>
 {!options.departments.some((d: Row) => d.grievance_enabled) && <p>{text('generalInbox')}</p>}{fileControl}<button className="grievance-primary" type="submit" disabled={busy||loading}>{text('submit')}</button></form></Surface>}
 {!selected && view !== 'new' && <><details className="grievance-filter-disclosure"><summary>{text('filters')}{activeFilters > 0 && <span> · {activeFilters} {text('activeFilters')}</span>}</summary><form className="grievance-filters" onSubmit={e => e.preventDefault()}><label>{text('search')}<Input maxLength={120} type="search" value={filters.q} onChange={e => changeFilter('q', e.target.value)}/></label><label>{text('status')}<Select value={filters.status} onChange={e => changeFilter('status', e.target.value)}><option value="">{text('all')}</option>{CASE_STATUSES.map(v => <option value={v} key={v}>{text(v)}</option>)}</Select></label><label>{text('priority')}<Select value={filters.priority} onChange={e => changeFilter('priority', e.target.value)}><option value="">{text('all')}</option>{CASE_PRIORITIES.map(v => <option key={v} value={v}>{text(v)}</option>)}</Select></label><label>{text('department')}<Select value={filters.department} onChange={e => changeFilter('department', e.target.value)}><option value="">{text('all')}</option>{options.departments.map((d: Row) => <option value={d.id} key={d.id}>{d.name}</option>)}</Select></label>{view === 'inbox' && <label>{text('assignee')}<Select value={filters.assignee} onChange={e => changeFilter('assignee', e.target.value)}><option value="">{text('all')}</option>{cases.filter((r, i, all) => r.assigned_to && all.findIndex(a => a.assigned_to === r.assigned_to) === i).map(r => <option key={r.assigned_to} value={r.assigned_to}>{r.assigned_to_name}</option>)}</Select></label>}<label>{text('category')}<Input maxLength={80} value={filters.category} onChange={e => changeFilter('category', e.target.value)}/></label><label>{text('from')}<Input type="date" value={filters.from} onChange={e => changeFilter('from', e.target.value)}/></label><label>{text('to')}<Input type="date" value={filters.to} onChange={e => changeFilter('to', e.target.value)}/></label>{view === 'inbox' && <label>{text('assignment')}<Select value={filters.view} onChange={e => changeFilter('view', e.target.value)}>{['all', 'mine', 'unassigned'].map(v => <option value={v} key={v}>{text(v === 'mine' ? 'assignedMine' : v)}</option>)}</Select></label>}</form><button type="button" disabled={!activeFilters || loading} onClick={() => { setFilters(emptyFilters); setPage(1); }}>{text('resetFilters')}</button></details>
 <ol className="grievance-records" aria-label={text(view)}>{cases.map(row => <li key={row.id}><button className="grievance-open" type="button" onClick={() => open(row.id)}><span className="grievance-record-heading"><strong>{row.title}</strong><span className="grievance-status" data-status={row.status}>{text(row.status)}</span></span><span className="grievance-record-context"><bdi dir="ltr">{row.case_number}</bdi><span>{text(row.category)}</span><time dateTime={row.created_at}>{date(row.created_at)}</time>{view === 'inbox' && <><span>{text('reporter')}: {row.reporter_name}</span><span>{text('assignee')}: {row.assigned_to_name || text('unassigned')}</span></>}</span><span className="grievance-open-label">{text('openCase')} <span aria-hidden="true">{isRtl ? '←' : '→'}</span></span></button></li>)}</ol>{!loading && !cases.length && <p className="grievance-empty">{text(activeFilters ? 'empty' : view === 'mine' ? 'emptyMine' : 'emptyInbox')}</p>}<div className="grievance-toolbar"><button disabled={page === 1 || loading} onClick={() => setPage(n => n - 1)}>{text('previous')}</button><span>{page} · {total}</span><button disabled={page * 20 >= total || loading} onClick={() => setPage(n => n + 1)}>{text('next')}</button></div></>}
 {detail && selected && <><header className="grievance-identity"><bdi dir="ltr">{detail.grievance.case_number}</bdi><h3>{detail.grievance.title}</h3><p><span className="grievance-status" data-status={detail.grievance.status}>{text(detail.grievance.status)}</span> · {text(detail.grievance.priority)}</p><p className="grievance-confidentiality">{text(detail.grievance.confidentiality)}</p></header><div className="grievance-detail"><div className="grievance-main"><Surface><h3>{text('original')}</h3><p className="grievance-prose">{detail.grievance.description}</p><p>{text('category')}: {text(detail.grievance.category)}</p>{detail.grievance.resolution_summary && <><h4>{text('resolution')}</h4><p className="grievance-prose">{detail.grievance.resolution_summary}</p></>}</Surface>
 <Surface><h3>{text('attachments')}</h3><ul>{detail.attachments.map((f: Row) => <li key={f.id}><a href={apiUrl(`/api/grievances/${selected}/attachments/${f.id}`)}>{f.filename} · {Math.ceil(f.size_bytes / 1024)} KB</a></li>)}</ul>{detail.grievance.status !== 'closed' && (detail.owner || detail.capabilities.respond) && <>{fileControl}<button type="button" disabled={!attachment || busy || loading} onClick={() => void run(async () => { await uploadFile(selected, detail.grievance.version, attachment!); setAttachment(null); })}>{text('upload')}</button></>}</Surface>
 <Surface><h3>{text('conversation')}</h3><ol className="grievance-timeline">{detail.messages.filter((m: Row) => m.kind !== 'internal').map((m: Row) => <li key={m.id}><strong>{m.actor_name}</strong><time dateTime={m.created_at}>{date(m.created_at)}</time><p className="grievance-prose">{m.body}</p>{detail.handler && detail.capabilities.respond && user.permissions?.includes('communications.send') && ['response', 'resolution'].includes(m.kind) && <button type="button" disabled={busy} onClick={() => void run(async () => { await request('/' + selected + '/email-draft', { messageId: m.id }); onEmailDraft?.(); })}>{text('emailDraft')}</button>}</li>)}</ol></Surface>
 {detail.handler && <Surface className="grievance-internal"><h3>{text('internal')}</h3><p>{text('privateHelp')}</p><ol className="grievance-timeline">{detail.messages.filter((m: Row) => m.kind === 'internal').map((m: Row) => <li key={m.id}><strong>{m.actor_name}</strong><time dateTime={m.created_at}>{date(m.created_at)}</time><p className="grievance-prose">{m.body}</p></li>)}</ol></Surface>}
 {detail.grievance.status === 'closed' ? <p>{text('closedHelp')}</p> : (detail.owner || detail.capabilities.respond || detail.capabilities.internal_notes) && <Surface><form className="grievance-form" onSubmit={e => { e.preventDefault(); void run(async () => { await request('/' + selected + '/messages', { version: detail.grievance.version, kind, body }); setBody(''); }); }}>{detail.owner ? <h3>{text('followUp')}</h3> : <label>{text('message')}<Select value={kind} onChange={e => setKind(e.target.value)}>{detail.capabilities.respond && <option value="response">{text('response')}</option>}{detail.capabilities.internal_notes && <option value="internal">{text('internal')}</option>}</Select></label>}<label>{text(kind === 'internal' ? 'internal' : detail.owner ? 'followUp' : 'response')}<Textarea required rows={5} maxLength={20000} value={body} onChange={e => setBody(e.target.value)}/></label><button disabled={busy} type="submit">{text('send')}</button></form></Surface>}
 <Surface><h3>{text('timeline')}</h3><ol className="grievance-timeline">{detail.events.map((ev: Row) => <li key={ev.id}><strong>{text(ev.kind)}</strong>{ev.actor_name && <span>{ev.actor_name}</span>}<time dateTime={ev.created_at}>{date(ev.created_at)}</time>{ev.metadata.newStatus && <p>{text(ev.metadata.previousStatus)} → {text(ev.metadata.newStatus)}</p>}</li>)}</ol><div className="grievance-toolbar"><button disabled={historyPage === 1 || loading} onClick={() => setHistoryPage(p => p - 1)}>{text('historyPrevious')}</button><span>{text('history')} {historyPage}</span><button disabled={!detail.hasMore || loading} onClick={() => setHistoryPage(p => p + 1)}>{text('historyMore')}</button></div></Surface></div>
 <aside className="grievance-metadata"><Surface><h3>{text('context')}</h3><dl>{['reporter_name', 'destination_name', 'department_name', 'assigned_to_name'].filter(k => detail.grievance[k]).map(k => <div key={k}><dt>{text(k === 'reporter_name' ? 'reporter' : k === 'department_name' ? 'currentDepartment' : k === 'destination_name' ? 'department' : 'assignee')}</dt><dd>{detail.grievance[k]}</dd></div>)}<div><dt>{text('created')}</dt><dd>{date(detail.grievance.created_at)}</dd></div><div><dt>{text('updated')}</dt><dd>{date(detail.grievance.updated_at)}</dd></div></dl></Surface>
 {detail.handler && detail.grievance.status !== 'closed' && <><h3>{text('handlerTools')}</h3>{detail.capabilities.assign && <Surface><form className="grievance-form" onSubmit={e => { e.preventDefault(); void run(() => mutate('/assignment', { employeeId: assignedEmployee || null, departmentId: assignedDepartment || null })); }}><h4>{text('assignment')}</h4><label>{text('assignee')}<Select value={assignedEmployee} onChange={e => setAssignedEmployee(e.target.value)}><option value="">{text('unassigned')}</option>{assignees.map((a: Row) => <option value={a.id} key={a.id}>{a.full_name}</option>)}</Select></label><label>{text('department')}<Select value={assignedDepartment} onChange={e => setAssignedDepartment(e.target.value)}><option value="">{text('none')}</option>{options.departments.filter((d: Row) => d.grievance_enabled).map((d: Row) => <option key={d.id} value={d.id}>{d.name}</option>)}</Select></label><button disabled={busy} type="submit">{text('assign')}</button></form></Surface>}
 <Surface><form className="grievance-form" onSubmit={e => { e.preventDefault(); void run(() => mutate('/status', { status: nextStatus, ...(nextStatus === 'resolved' ? { resolutionSummary: resolution, response: response || undefined } : {}) })); }}><label>{text('transition')}<Select required value={nextStatus} onChange={e => setNextStatus(e.target.value)}><option value="">{text('choose')}</option>{CASE_TRANSITIONS[detail.grievance.status as CaseStatus].filter(v => detail.capabilities[v === 'resolved' ? 'resolve' : v === 'closed' ? 'close' : 'triage']).map(v => <option key={v} value={v}>{text(v)}</option>)}</Select></label>{nextStatus === 'resolved' && <><label>{text('resolution')}<Textarea required rows={5} maxLength={10000} value={resolution} onChange={e => setResolution(e.target.value)}/></label>{detail.capabilities.respond && <label>{text('optionalResponse')}<Textarea rows={3} value={response} onChange={e => setResponse(e.target.value)}/></label>}</>}<button className="grievance-primary" disabled={busy || loading || !nextStatus} type="submit">{text('apply')}</button></form></Surface>
 {detail.capabilities.triage && <Surface><form className="grievance-form" onSubmit={e => { e.preventDefault(); void run(() => mutate('/settings', { priority, ...(detail.capabilities.confidential ? { confidentiality } : {}) })); }}><label>{text('priority')}<Select value={priority} onChange={e => setPriority(e.target.value)}>{CASE_PRIORITIES.map(v => <option key={v} value={v}>{text(v)}</option>)}</Select></label>{detail.capabilities.confidential && <label>{text('confidentiality')}<Select value={confidentiality} onChange={e => setConfidentiality(e.target.value)}>{['standard', 'confidential'].map(v => <option value={v} key={v}>{text(v)}</option>)}</Select></label>}<button disabled={busy} type="submit">{text('save')}</button></form></Surface>}</>}
 </aside></div></>}
 {!selected && options.configure && canInbox && <Surface><details><summary>{text('configure')}</summary><ul>{options.departments.map((d: Row) => <li key={d.id}><label><Input type="checkbox" checked={d.grievance_enabled} disabled={busy} onChange={e => void run(async () => { await request('/departments/' + d.id, { enabled: e.target.checked }, 'PATCH'); })}/>{d.name} · {text('enabled')}</label></li>)}</ul></details></Surface>}
 </section>;
}
