import {Suspense,useEffect,useRef,type PointerEvent,type ReactNode} from 'react';
import {useLanguage} from '../../lib/LanguageContext';
import {boundGeometry,layoutHeight,type WidgetInstance,type Surface} from './workspace-model';
import type {WidgetDefinition} from './widget-catalog';
import {StanzaIcon} from '../ui/StanzaIcon';
type Props={widget:WidgetInstance;definition:WidgetDefinition;editing:boolean;maximized:boolean;surface:Surface;allowed:boolean;children:ReactNode;onUpdate:(patch:Partial<WidgetInstance>)=>void;onMaximize:()=>void;onRemove:()=>void;onConfigure:()=>void;onOpen:()=>void};
export function WidgetFrame({widget,definition,editing,maximized,surface,allowed,children,onUpdate,onMaximize,onRemove,onConfigure,onOpen}:Props){
 const {isRtl}=useLanguage();const text=(en:string,ar:string)=>isRtl?ar:en;const ref=useRef<HTMLElement>(null);const raf=useRef(0);
 const gesture=useRef<{target:HTMLElement;pointer:number;startX:number;startY:number;step:number;scale:number;maxRow:number;mode:'move'|'resize';next:WidgetInstance;dx:number;dy:number;cleanup:()=>void}|null>(null);
 const cancel=()=>{const g=gesture.current;if(!g)return;gesture.current=null;cancelAnimationFrame(raf.current);raf.current=0;g.cleanup();if(g.target.hasPointerCapture(g.pointer))g.target.releasePointerCapture(g.pointer);const node=ref.current;if(node){node.style.removeProperty('transform');node.style.removeProperty('width');node.style.removeProperty('height');node.removeAttribute('data-dragging');node.removeAttribute('data-resizing');}};
 useEffect(()=>cancel,[]);useEffect(()=>{cancel();},[editing,maximized,widget]);
 const begin=(event:PointerEvent<HTMLButtonElement>,mode:'move'|'resize')=>{if(gesture.current||!event.isPrimary||!editing||maximized||event.button!==0||mode==='resize'&&widget.collapsed||!matchMedia('(min-width: 900px)').matches)return;
  const grid=ref.current!.parentElement!,rect=grid.getBoundingClientRect();event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();cancel();}},hidden=()=>{if(document.hidden)cancel();};document.addEventListener('keydown',escape);document.addEventListener('visibilitychange',hidden);
  gesture.current={target:event.currentTarget,pointer:event.pointerId,startX:event.clientX,startY:event.clientY,step:(grid.clientWidth+12)/12,scale:rect.width/grid.clientWidth,maxRow:Math.max(0,Math.floor(grid.clientHeight/64)-layoutHeight(widget)),mode,next:widget,dx:0,dy:0,cleanup:()=>{document.removeEventListener('keydown',escape);document.removeEventListener('visibilitychange',hidden);}};ref.current!.dataset.dragging='true';if(mode==='resize')ref.current!.dataset.resizing='true';};
 const paint=()=>{raf.current=0;const g=gesture.current,node=ref.current;if(!g||!node)return;const {dx,dy}=g;
  if(g.mode==='move')node.style.transform=`translate3d(${Math.max(-widget.x*g.step,Math.min((12-widget.width-widget.x)*g.step,dx))}px, ${Math.max(-widget.y*64,Math.min((g.maxRow-widget.y)*64,dy))}px, 0)`;
  else{node.style.width=`${Math.max(definition.minWidth*g.step-12,Math.min((12-widget.x)*g.step-12,widget.width*g.step-12+dx))}px`;node.style.height=`${Math.max(definition.minHeight*64-12,Math.min(12*64-12,widget.height*64-12+dy))}px`;}};
 const move=(event:PointerEvent<HTMLButtonElement>)=>{const g=gesture.current;if(!g||g.pointer!==event.pointerId)return;g.dx=(event.clientX-g.startX)/g.scale;g.dy=(event.clientY-g.startY)/g.scale;g.next=boundGeometry(g.mode==='move'?{...widget,x:widget.x+Math.round(g.dx/g.step),y:Math.min(g.maxRow,widget.y+Math.round(g.dy/64))}:{...widget,width:Math.min(12-widget.x,widget.width+Math.round(g.dx/g.step)),height:widget.height+Math.round(g.dy/64)});if(!raf.current)raf.current=requestAnimationFrame(paint);};
 const finish=(event:PointerEvent<HTMLButtonElement>)=>{const g=gesture.current;if(!g||g.pointer!==event.pointerId)return;const next=g.next;cancel();onUpdate({x:next.x,y:next.y,width:next.width,height:next.height});};
 const handlers={onPointerMove:move,onPointerUp:finish,onPointerCancel:cancel,onLostPointerCapture:cancel};
 const keyboard=(action:string)=>{const changes:Record<string,Partial<WidgetInstance>>={left:{x:widget.x-1},right:{x:widget.x+1},up:{y:widget.y-1},down:{y:widget.y+1},wider:{width:Math.min(12-widget.x,widget.width+1)},narrower:{width:widget.width-1},taller:{height:widget.height+1},shorter:{height:widget.height-1}};if(changes[action])onUpdate(changes[action]);};
 const title=isRtl?definition.titleAr:definition.title;
 return <article ref={ref} className="composer-widget stanza-surface" data-instance-id={widget.instanceId} data-surface={surface} data-accent={widget.accent??'default'} data-collapsed={widget.collapsed||undefined} data-maximized={maximized||undefined} dir={isRtl?'rtl':'ltr'} aria-label={title} style={maximized?undefined:{gridColumn:`${widget.x+1} / span ${widget.width}`,gridRow:`${widget.y+1} / span ${layoutHeight(widget)}`}}>
 <header><h3>{editing&&!maximized?<button type="button" className="composer-drag" aria-label={`${text('Drag','سحب')} ${title}`} onPointerDown={e=>begin(e,'move')} {...handlers}><StanzaIcon name="move"/>{title}</button>:title}</h3><div className="composer-header-actions"><button type="button" onClick={()=>{if(maximized)onMaximize();onUpdate({collapsed:!widget.collapsed});}} aria-label={`${widget.collapsed?text('Restore','استعادة'):text('Minimize','تصغير')} ${title}`} aria-expanded={!widget.collapsed}><StanzaIcon name={widget.collapsed?'restore':'collapse'}/></button>{!widget.collapsed&&<button type="button" onClick={onMaximize} aria-label={`${maximized?text('Restore size','استعادة الحجم'):text('Maximize','تكبير')} ${title}`}><StanzaIcon name="workspace"/></button>}</div></header>
 {editing&&<details className="composer-widget-menu"><summary>{text('Widget controls','أدوات اللوحة')}</summary><div className="composer-tools"><select aria-label={`${text('Move or resize','نقل أو تغيير حجم')} ${title}`} value="" onChange={e=>keyboard(e.target.value)} disabled={maximized||widget.collapsed}><option value="">{text('Move / resize…','نقل / حجم…')}</option>{[['left','Move left','يسار'],['right','Move right','يمين'],['up','Move up','أعلى'],['down','Move down','أسفل'],['wider','Make wider','توسيع'],['narrower','Make narrower','تضييق'],['taller','Make taller','زيادة الارتفاع'],['shorter','Make shorter','تقليل الارتفاع']].map(([id,en,ar])=><option key={id} value={id}>{text(en,ar)}</option>)}</select><button type="button" onClick={onConfigure}><StanzaIcon name="settings"/>{text('Configure','إعداد')}</button><button type="button" onClick={onRemove}>{text('Remove','إزالة')}</button></div></details>}
 <div className="composer-widget-body" hidden={!!widget.collapsed}><Suspense fallback={<p>{text('Loading…','جار التحميل…')}</p>}>{allowed?children:<p role="status">{text('This widget is unavailable with your current permissions.','هذه اللوحة غير متاحة لصلاحياتك الحالية.')}</p>}</Suspense></div>
 <footer hidden={!!widget.collapsed}>{allowed&&<button type="button" onClick={onOpen}>{text('Open module','فتح القسم')} <StanzaIcon name={isRtl?'back':'forward'}/></button>}{editing&&!maximized&&!widget.collapsed&&<button type="button" className="composer-resize" aria-label={`${text('Resize','تغيير حجم')} ${title}`} onPointerDown={e=>begin(e,'resize')} {...handlers}><StanzaIcon name="resize"/>{text('Resize','تغيير الحجم')}</button>}</footer>
 </article>;
}
