import {SurfaceSelector} from '../ui/SurfaceSelector';
import {StanzaIcon} from '../ui/StanzaIcon';
import { useState } from 'react';
import type { AuthUser } from '../../auth/auth-contract';
import type { DashboardWorkspaceId } from '../../navigation/workspace-registry';
import { useLanguage } from '../../lib/LanguageContext';
import { useComposerPreferences } from './ComposerPreferences';
import { ComposerDialog } from './ComposerDialog';
import { WIDGET_REGISTRY } from './widget-registry';
import { canUseWidget, widgetPath } from './widget-catalog';
import { createWidget, newId, MAX_WIDGETS, MAX_WORKSPACES, WIDGET_ACCENTS, layoutHeight, stackedOrder, type Surface } from './workspace-model';
import { useWidgetData } from './useWidgetData';
import { WidgetFrame } from './WidgetFrame';
import './composer.css';
export default function WorkspaceComposer({user,onOpen}:{user:AuthUser;onOpen:(id:DashboardWorkspaceId,widgetId?:string)=>void}){
 const {state,dispatch,saveError}=useComposerPreferences();const {isRtl}=useLanguage();const text=(en:string,ar:string)=>isRtl?ar:en;
 const [editing,setEditing]=useState(false),[dialog,setDialog]=useState<'library'|'create'|'rename'|'delete'|'reset'|null>(null),[name,setName]=useState(''),[search,setSearch]=useState(''),[group,setGroup]=useState(''),[maximized,setMaximized]=useState<string|null>(null),[configId,setConfigId]=useState<string|null>(null),[refresh,setRefresh]=useState(0);
 const workspace=state.workspaces.find(w=>w.id===state.activeId)!;
 const selectedMax=workspace.widgets.find(w=>w.instanceId===maximized);
 const visible=selectedMax?[selectedMax]:stackedOrder(workspace.widgets);
 const allowed=visible.filter(w=>canUseWidget(user,WIDGET_REGISTRY.find(d=>d.id===w.widgetId)!));
 const identity=JSON.stringify([user.tenantId,user.id,user.role,user.permissions]);
 const results=useWidgetData(allowed.map(w=>widgetPath(w.widgetId)),identity,refresh);
 const configure=workspace.widgets.find(w=>w.instanceId===configId);
 const groups=[...new Set(WIDGET_REGISTRY.filter(w=>canUseWidget(user,w)).map(w=>w.group))];
 const groupLabel=(value:string)=>isRtl?({Support:'الدعم',Attendance:'الحضور',Leave:'الإجازات',Finance:'المالية',Performance:'الأداء',Grievances:'الشكاوى',Hiring:'التوظيف',Communications:'التواصل'}[value]||value):value;
 const labelSurface=(value:Surface)=>({auto:text('Auto','تلقائي'),solid:text('Solid','مصمت'),glass:text('Glass','زجاجي'),transparent:text('Transparent','شفاف')}[value]);
 const controls=<><button type="button" onClick={()=>{setSearch('');setDialog('library');}} disabled={workspace.widgets.length>=MAX_WIDGETS}>{text('+ Add Widget','+ إضافة لوحة')}</button><button type="button" aria-pressed={editing} onClick={()=>setEditing(v=>!v)}>{editing?text('Done customizing','إنهاء التخصيص'):text('Customize Workspace','تخصيص المساحة')}</button><button type="button" onClick={()=>setRefresh(v=>v+1)}>{text('Refresh data','تحديث البيانات')}</button></>;
 return <section className="composer" dir={isRtl?'rtl':'ltr'} aria-label={text('Workspace Composer','منشئ مساحات العمل')}>
 <div className="composer-heading"><div><p className="composer-caption">{text('YOUR OPERATIONAL SCREENS','شاشاتك التشغيلية')}</p><h2>{text('Workspace Composer','منشئ مساحات العمل')}</h2><p>{text('Bring the tools you use together. Your original modules stay available.','اجمع الأدوات التي تستخدمها. تبقى الأقسام الأصلية متاحة.')}</p></div></div>
 <div className="composer-toolbar"><label>{text('Saved workspace','المساحة المحفوظة')}<select value={workspace.id} onChange={e=>{dispatch({type:'select',id:e.target.value});setMaximized(null);setEditing(false);}}>{state.workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><button type="button" disabled={state.workspaces.length>=MAX_WORKSPACES} onClick={()=>{setName('');setDialog('create');}}>{text('New workspace','مساحة جديدة')}</button><button type="button" onClick={()=>{setName(workspace.name);setDialog('rename');}}>{text('Rename','إعادة تسمية')}</button><button type="button" disabled={state.workspaces.length>=MAX_WORKSPACES} onClick={()=>{dispatch({type:'duplicate',id:workspace.id,newId:newId()});setMaximized(null);}}>{text('Duplicate','نسخ')}</button><button type="button" onClick={()=>setDialog('delete')}>{text('Delete','حذف')}</button></div>
 <div className="composer-toolbar">{controls}{editing&&<><SurfaceSelector value={state.surface} onChange={value=>dispatch({type:'surface',value})} /><button type="button" onClick={()=>setDialog('reset')}>{text('Reset layout','إفراغ التخطيط')}</button></>}</div>
 <p className="composer-caption">{editing?text('On desktop, drag the title or the Resize corner. Move / resize also works with a keyboard. On phones, cards stack in saved order. Escape cancels a drag.','على الكمبيوتر اسحب العنوان أو زاوية تغيير الحجم. نقل / حجم يعمل بلوحة المفاتيح أيضاً. تُرتب اللوحات على الهاتف رأسياً. Escape يلغي السحب.'):text('Layout locked. Customize to move, resize, configure or remove widgets.','التخطيط مقفل. خصص المساحة لنقل اللوحات وتغيير حجمها وإعدادها.')}</p>
 {saveError&&<p role="alert">{text('Browser storage is unavailable. Changes will not survive a refresh.','تعذر الحفظ في المتصفح. لن تبقى التغييرات بعد التحديث.')}</p>}
 {!workspace.widgets.length?<div className="composer-empty"><h3>{text('Your workspace is empty.','مساحتك فارغة.')}</h3><p>{text('Add the tools you use most.','أضف الأدوات الأكثر استخداماً.')}</p><button type="button" onClick={()=>setDialog('library')}>{text('+ Add Widget','+ إضافة لوحة')}</button></div>:<div className="composer-grid" dir="ltr" data-maximized={Boolean(selectedMax)||undefined} style={{minHeight:selectedMax?'min(75dvh, 850px)':`${Math.max(8,...workspace.widgets.map(w=>w.y+layoutHeight(w))) *64+(editing?256:0)}px`}}>
 {visible.map(widget=>{const definition=WIDGET_REGISTRY.find(w=>w.id===widget.widgetId)!;const Component=definition.component;const authorized=canUseWidget(user,definition);return <WidgetFrame key={widget.instanceId} widget={widget} definition={definition} editing={editing} maximized={Boolean(selectedMax)} surface={widget.surfaceOverride==='auto'?state.surface:widget.surfaceOverride} allowed={authorized} onUpdate={patch=>dispatch({type:'update',id:workspace.id,instanceId:widget.instanceId,patch})} onRemove={()=>{dispatch({type:'remove',id:workspace.id,instanceId:widget.instanceId});setMaximized(null);}} onConfigure={()=>setConfigId(widget.instanceId)} onMaximize={()=>setMaximized(selectedMax?null:widget.instanceId)} onOpen={()=>onOpen(definition.module,widget.widgetId)}>{authorized&&<Component widget={widget} result={results[widgetPath(widget.widgetId)]} onRefresh={()=>setRefresh(v=>v+1)}/>}</WidgetFrame>;})}
 </div>}
 {dialog==='library'&&<ComposerDialog title={text('Add Widget','إضافة لوحة')} onClose={()=>setDialog(null)}><label>{text('Search widgets','البحث عن لوحة')}<input autoFocus value={search} onChange={e=>setSearch(e.target.value)}/></label><label>{text('Domain','المجال')}<select value={group} onChange={e=>setGroup(e.target.value)}><option value="">{text('All domains','جميع المجالات')}</option>{groups.map(g=><option key={g} value={g}>{groupLabel(g)}</option>)}</select></label><div className="composer-library">{WIDGET_REGISTRY.filter(w=>canUseWidget(user,w)&&(!group||group===w.group)&&`${w.title} ${w.titleAr} ${w.description}`.toLowerCase().includes(search.toLowerCase())).map(w=><button type="button" key={w.id} disabled={workspace.widgets.length>=MAX_WIDGETS} onClick={()=>{dispatch({type:'add',id:workspace.id,widget:createWidget(w.id)});setDialog(null);setEditing(true);}}><small>{groupLabel(w.group)}</small><strong>{isRtl?w.titleAr:w.title}</strong><span>{isRtl?'ملخص مباشر. افتح القسم للتفاصيل والإجراءات.':w.description}</span></button>)}</div><p className="composer-caption">{text('Only authorized widgets are listed. Up to 20 widgets per workspace.','تظهر اللوحات المصرح بها فقط. الحد الأقصى 20 لوحة لكل مساحة.')}</p></ComposerDialog>}
 {(dialog==='create'||dialog==='rename')&&<ComposerDialog title={dialog==='create'?text('New workspace','مساحة جديدة'):text('Rename workspace','إعادة تسمية المساحة')} onClose={()=>setDialog(null)}><form onSubmit={e=>{e.preventDefault();if(!name.trim())return;dispatch(dialog==='create'?{type:'create',id:newId(),name}:{type:'rename',id:workspace.id,name});setDialog(null);setMaximized(null);}}><label>{text('Name','الاسم')}<input autoFocus required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><button type="submit">{text('Save','حفظ')}</button></form></ComposerDialog>}
 {(dialog==='delete'||dialog==='reset')&&<ComposerDialog title={text('Confirm layout change','تأكيد تغيير التخطيط')} onClose={()=>setDialog(null)}><p>{text(`This will ${dialog==='delete'?'delete':'empty'} “${workspace.name}”. Domain records will not change.`,`سيتم ${dialog==='delete'?'حذف':'إفراغ'} «${workspace.name}». لن تتغير سجلات النظام.`)}</p><button type="button" onClick={()=>{dispatch({type:dialog,id:workspace.id});setDialog(null);setMaximized(null);}}>{text('Confirm','تأكيد')}</button></ComposerDialog>}
 {configure&&<ComposerDialog title={text('Configure widget','إعداد اللوحة')} onClose={()=>setConfigId(null)}><p>{text('Auto inherits the workspace default.','تلقائي يستخدم سطح المساحة الافتراضي.')}</p><SurfaceSelector value={configure.surfaceOverride} onChange={surfaceOverride=>dispatch({type:'update',id:workspace.id,instanceId:configure.instanceId,patch:{surfaceOverride}})} /><label>{text('Workflow color','لون سير العمل')}<select aria-label={text('Workflow color','لون سير العمل')} value={configure.accent??'default'} onChange={e=>dispatch({type:'update',id:workspace.id,instanceId:configure.instanceId,patch:{accent:e.target.value as typeof configure.accent}})}>{WIDGET_ACCENTS.map((v,i)=><option key={v} value={v}>{isRtl?['افتراضي','أخضر','أزرق','بنفسجي','كهرماني','أحمر','محايد'][i]:v}</option>)}</select></label>{configure.widgetId==='attendance'?<label><input type="checkbox" checked={!!configure.config.compact} onChange={e=>dispatch({type:'update',id:workspace.id,instanceId:configure.instanceId,patch:{config:{...configure.config,compact:e.target.checked}}})}/>{text('Compact status','حالة مختصرة')}</label>:<label>{text('Maximum visible items','أقصى عدد للعناصر')}<select value={configure.config.limit||5} onChange={e=>dispatch({type:'update',id:workspace.id,instanceId:configure.instanceId,patch:{config:{...configure.config,limit:Number(e.target.value)}}})}>{[2,5,10].map(n=><option key={n}>{n}</option>)}</select></label>}<p>{text('The service may return fewer items. Scope is always enforced by the server.','قد تعيد الخدمة عدداً أقل. يفرض الخادم نطاق الصلاحيات دائماً.')}</p></ComposerDialog>}
 </section>;
}
