import type express from 'express';
import type { PoolClient } from 'pg';
import { withTenant } from '../../lib/hr-background';
import { recordAuditEvent } from '../audit/audit-events';
import { claimPendingRecognitionDelivery } from './recognition-delivery';

type Middleware = express.RequestHandler;
type Dependencies = {
  // `standardAuth` is the normal authenticated session-cookie middleware. It is
  // intentionally named here to avoid implying any demo-only access semantics.
  standardAuth: Middleware;
  requirePermission: (permission: string) => Middleware;
};

type CycleStatus = 'draft' | 'scheduled' | 'active' | 'calibration' | 'finalised' | 'cancelled';
type ReviewStatus = 'pending' | 'self_review' | 'peer_review' | 'manager_review' | 'calibration' | 'completed' | 'cancelled';
type AssignmentType = 'self' | 'manager' | 'peer';
const uuid = (value: unknown): value is string => typeof value === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const clean = (value: unknown, max: number) => typeof value === 'string' ? value.trim().slice(0, max) : '';
const routeError = (status: number, code: string, error: string) => Object.assign(new Error(error), { status, code });
const hasPermission = (req: express.Request, key: string) => req.authUser?.role === 'hr_admin' || Boolean(req.authUser?.permissions?.includes(key));
const isManagerOf = async (client: PoolClient, tenantId: string, managerId: string, employeeId: string) => Boolean((await client.query(
  `SELECT 1 FROM employees WHERE tenant_id=$1 AND id=$2 AND manager_id=$3 AND is_active=true AND employment_status='active'`,
  [tenantId, employeeId, managerId],
)).rowCount);
const isActiveEmployee = async (client: PoolClient, tenantId: string, employeeId: string) => Boolean((await client.query(
  `SELECT 1 FROM employees WHERE tenant_id=$1 AND id=$2 AND is_active=true AND employment_status='active'`,
  [tenantId, employeeId],
)).rowCount);
const fail = (res: express.Response, error: unknown, fallback: string) => {
  const typed = error as { status?: number; code?: string; message?: string };
  if (!typed.status || typed.status >= 500) console.error('[Performance]', error);
  return res.status(typed.status || 500).json({ success: false, code: typed.code || 'PERFORMANCE_REQUEST_FAILED', error: typed.status ? typed.message : fallback });
};
const date = (value: unknown, label: string, required = false) => {
  if (value === undefined || value === null || value === '') {
    if (required) throw routeError(400, 'PERFORMANCE_VALIDATION_ERROR', `${label} is required.`);
    return null;
  }
  const text = clean(value, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(text) || Number.isNaN(Date.parse(`${text}T00:00:00.000Z`))) throw routeError(400, 'PERFORMANCE_VALIDATION_ERROR', `${label} is invalid.`);
  return text;
};
const timestamp = (value: unknown, label: string) => {
  if (value === undefined || value === null || value === '') return null;
  const parsed = new Date(String(value));
  if (Number.isNaN(parsed.getTime())) throw routeError(400, 'PERFORMANCE_VALIDATION_ERROR', `${label} is invalid.`);
  return parsed.toISOString();
};
const cycleTransitions: Record<CycleStatus, readonly CycleStatus[]> = {
  draft: ['scheduled', 'cancelled'], scheduled: ['active', 'cancelled'], active: ['calibration', 'cancelled'], calibration: ['finalised', 'active', 'cancelled'], finalised: [], cancelled: [],
};
const reviewTransitions: Record<ReviewStatus, readonly ReviewStatus[]> = {
  pending: ['self_review', 'peer_review', 'manager_review', 'cancelled'], self_review: ['peer_review', 'manager_review', 'cancelled'], peer_review: ['manager_review', 'calibration', 'cancelled'], manager_review: ['calibration', 'completed', 'cancelled'], calibration: ['completed', 'manager_review', 'cancelled'], completed: [], cancelled: [],
};

async function assertReviewScope(client: PoolClient, req: express.Request, reviewId: string, mode: 'view' | 'manage') {
  const user = req.authUser!;
  const review = (await client.query(`SELECT * FROM performance_reviews WHERE tenant_id=$1 AND id=$2`, [user.tenantId, reviewId])).rows[0];
  if (!review) throw routeError(404, 'PERFORMANCE_REVIEW_NOT_FOUND', 'Performance review not found.');
  if (user.employeeId === review.employee_id) return review;
  if (user.employeeId === review.manager_id && (mode === 'view' ? hasPermission(req, 'performance.view_reports') : hasPermission(req, 'performance.review'))) return review;
  if (hasPermission(req, mode === 'view' ? 'performance.view_reports' : 'performance.manage_cycles')) return review;
  throw routeError(403, 'PERFORMANCE_SCOPE_DENIED', 'You are not authorised for this review.');
}

async function calculateScore(client: PoolClient, tenantId: string, reviewId: string) {
  const result = await client.query<{ score: string | null }>(`
    SELECT CASE WHEN SUM(COALESCE(question.weight, 1)) FILTER (WHERE response.score IS NOT NULL) = 0 THEN NULL
      ELSE SUM(response.score * COALESCE(question.weight, 1)) / SUM(COALESCE(question.weight, 1)) FILTER (WHERE response.score IS NOT NULL) END::text AS score
    FROM performance_review_assignments assignment
    JOIN performance_review_responses response ON response.tenant_id=assignment.tenant_id AND response.assignment_id=assignment.id
    JOIN performance_review_questions question ON question.tenant_id=response.tenant_id AND question.id=response.question_id
    WHERE assignment.tenant_id=$1 AND assignment.review_id=$2 AND assignment.status='submitted' AND question.question_type='rating'`, [tenantId, reviewId]);
  return result.rows[0]?.score === null || result.rows[0]?.score === undefined ? null : Number(result.rows[0].score);
}

function questionsFromBody(value: unknown) {
  if (!Array.isArray(value) || value.length === 0 || value.length > 50) throw routeError(400, 'PERFORMANCE_TEMPLATE_INVALID', 'A template needs between one and fifty questions.');
  return value.map((raw, index) => {
    const item = raw && typeof raw === 'object' ? raw as Record<string, unknown> : {};
    const questionType = clean(item.questionType, 20);
    if (!['rating', 'text', 'long_text', 'yes_no'].includes(questionType)) throw routeError(400, 'PERFORMANCE_TEMPLATE_INVALID', 'Question type is invalid.');
    const prompt = clean(item.prompt, 2000);
    if (!prompt) throw routeError(400, 'PERFORMANCE_TEMPLATE_INVALID', 'Question prompt is required.');
    const minScore = item.minScore === undefined || item.minScore === null || item.minScore === '' ? null : Number(item.minScore);
    const maxScore = item.maxScore === undefined || item.maxScore === null || item.maxScore === '' ? null : Number(item.maxScore);
    const weight = item.weight === undefined || item.weight === null || item.weight === '' ? null : Number(item.weight);
    if (questionType === 'rating' && (!Number.isFinite(minScore) || !Number.isFinite(maxScore) || minScore >= maxScore)) throw routeError(400, 'PERFORMANCE_TEMPLATE_INVALID', 'Rating bounds are invalid.');
    if (questionType !== 'rating' && (minScore !== null || maxScore !== null)) throw routeError(400, 'PERFORMANCE_TEMPLATE_INVALID', 'Only rating questions may have score bounds.');
    if (weight !== null && (!Number.isFinite(weight) || weight < 0)) throw routeError(400, 'PERFORMANCE_TEMPLATE_INVALID', 'Question weight is invalid.');
    return { prompt, questionType, minScore, maxScore, weight, isRequired: item.isRequired !== false, sortOrder: index };
  });
}

export function registerPerformanceRoutes(app: express.Express, { standardAuth, requirePermission }: Dependencies) {
  app.get('/api/hr/performance/cycles', standardAuth, requirePermission('performance.view'), async (req, res) => {
    try { const cycles = await withTenant(req.authUser!.tenantId, async client => (await client.query(`SELECT cycle.id,cycle.name,cycle.description,cycle.review_period_start AS "reviewPeriodStart",cycle.review_period_end AS "reviewPeriodEnd",cycle.status,cycle.self_review_due_at AS "selfReviewDueAt",cycle.peer_review_due_at AS "peerReviewDueAt",cycle.manager_review_due_at AS "managerReviewDueAt",COUNT(review.id)::int AS "reviewCount",COUNT(review.id) FILTER(WHERE review.status='completed')::int AS "completedCount" FROM performance_review_cycles cycle LEFT JOIN performance_reviews review ON review.tenant_id=cycle.tenant_id AND review.cycle_id=cycle.id WHERE cycle.tenant_id=$1 GROUP BY cycle.id ORDER BY cycle.review_period_start DESC`, [req.authUser!.tenantId])).rows); res.json({ success: true, cycles }); } catch (error) { fail(res, error, 'Unable to load review cycles.'); }
  });

  app.post('/api/hr/performance/cycles', standardAuth, requirePermission('performance.manage_cycles'), async (req, res) => {
    try { const body = req.body || {}; const name = clean(body.name, 160); const start = date(body.reviewPeriodStart, 'Review period start', true); const end = date(body.reviewPeriodEnd, 'Review period end', true); if (!name || end! < start!) throw routeError(400, 'PERFORMANCE_VALIDATION_ERROR', 'Cycle details are invalid.'); const cycle = await withTenant(req.authUser!.tenantId, async client => { const result = await client.query(`INSERT INTO performance_review_cycles(tenant_id,name,description,review_period_start,review_period_end,self_review_opens_at,self_review_due_at,peer_review_due_at,manager_review_due_at,status,created_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'draft',$10) RETURNING id,name,status,review_period_start AS "reviewPeriodStart",review_period_end AS "reviewPeriodEnd"`, [req.authUser!.tenantId, name, clean(body.description, 2000) || null, start, end, timestamp(body.selfReviewOpensAt, 'Self review opening'), timestamp(body.selfReviewDueAt, 'Self review due date'), timestamp(body.peerReviewDueAt, 'Peer review due date'), timestamp(body.managerReviewDueAt, 'Manager review due date'), req.authUser!.employeeId]); await recordAuditEvent(client, { tenantId: req.authUser!.tenantId, actorId: req.authUser!.employeeId, action: 'performance.cycle.created', targetType: 'performance_review_cycle', targetId: result.rows[0].id, metadata: { cycleName: name } }); return result.rows[0]; }); res.status(201).json({ success: true, cycle }); } catch (error) { fail(res, error, 'Unable to create review cycle.'); }
  });

  app.post('/api/hr/performance/cycles/:cycleId/start', standardAuth, requirePermission('performance.manage_cycles'), async (req, res) => {
    try { if (!uuid(req.params.cycleId)) throw routeError(404, 'PERFORMANCE_CYCLE_NOT_FOUND', 'Review cycle not found.'); const cycle = await withTenant(req.authUser!.tenantId, async client => { const current = (await client.query(`SELECT id,name,status FROM performance_review_cycles WHERE tenant_id=$1 AND id=$2 FOR UPDATE`, [req.authUser!.tenantId, req.params.cycleId])).rows[0]; if (!current) throw routeError(404, 'PERFORMANCE_CYCLE_NOT_FOUND', 'Review cycle not found.'); if (!cycleTransitions[current.status as CycleStatus].includes('active')) throw routeError(409, 'PERFORMANCE_INVALID_TRANSITION', 'This cycle cannot be started.'); const updated = (await client.query(`UPDATE performance_review_cycles SET status='active',updated_at=NOW() WHERE tenant_id=$1 AND id=$2 AND status=$3 RETURNING id,name,status`, [req.authUser!.tenantId, current.id, current.status])).rows[0]; await recordAuditEvent(client, { tenantId: req.authUser!.tenantId, actorId: req.authUser!.employeeId, action: 'performance.cycle.started', targetType: 'performance_review_cycle', targetId: current.id, metadata: { cycleName: current.name } }); return updated; }); res.json({ success: true, cycle }); } catch (error) { fail(res, error, 'Unable to start review cycle.'); }
  });

  app.get('/api/hr/performance/templates', standardAuth, requirePermission('performance.view'), async (req, res) => {
    try { const templates = await withTenant(req.authUser!.tenantId, async client => (await client.query(`SELECT template.id,template.name,template.description,template.is_active AS "isActive",COALESCE(json_agg(json_build_object('id',question.id,'prompt',question.prompt,'questionType',question.question_type,'sortOrder',question.sort_order,'isRequired',question.is_required,'minScore',question.min_score,'maxScore',question.max_score,'weight',question.weight) ORDER BY question.sort_order) FILTER(WHERE question.id IS NOT NULL),'[]') AS questions FROM performance_review_templates template LEFT JOIN performance_review_questions question ON question.tenant_id=template.tenant_id AND question.template_id=template.id WHERE template.tenant_id=$1 GROUP BY template.id ORDER BY template.created_at DESC`, [req.authUser!.tenantId])).rows); res.json({ success: true, templates }); } catch (error) { fail(res, error, 'Unable to load review templates.'); }
  });

  app.post('/api/hr/performance/templates', standardAuth, requirePermission('performance.manage_templates'), async (req, res) => {
    try { const body = req.body || {}; const name = clean(body.name, 160); if (!name) throw routeError(400, 'PERFORMANCE_TEMPLATE_INVALID', 'Template name is required.'); const questions = questionsFromBody(body.questions); const template = await withTenant(req.authUser!.tenantId, async client => { const created = (await client.query(`INSERT INTO performance_review_templates(tenant_id,name,description,created_by)VALUES($1,$2,$3,$4)RETURNING id,name,description,is_active AS "isActive"`, [req.authUser!.tenantId,name,clean(body.description,2000)||null,req.authUser!.employeeId])).rows[0]; for (const question of questions) await client.query(`INSERT INTO performance_review_questions(tenant_id,template_id,prompt,question_type,sort_order,is_required,min_score,max_score,weight)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`, [req.authUser!.tenantId,created.id,question.prompt,question.questionType,question.sortOrder,question.isRequired,question.minScore,question.maxScore,question.weight]); return created; }); res.status(201).json({ success: true, template }); } catch (error) { fail(res, error, 'Unable to create review template.'); }
  });

  app.get('/api/hr/performance/reviews', standardAuth, requirePermission('performance.view'), async (req, res) => {
    try { const user = req.authUser!; const employeeId = uuid(req.query.employeeId) ? String(req.query.employeeId) : null; const reviews = await withTenant(user.tenantId, async client => { if (employeeId && user.role !== 'hr_admin' && !hasPermission(req, 'performance.view_reports') && employeeId !== user.employeeId) throw routeError(403,'PERFORMANCE_SCOPE_DENIED','You are not authorised to view this employee.'); if (employeeId && user.role !== 'hr_admin' && employeeId !== user.employeeId && !(await isManagerOf(client,user.tenantId,user.employeeId,employeeId))) throw routeError(403,'PERFORMANCE_SCOPE_DENIED','You may only view direct reports.'); const scopedEmployeeId = employeeId || (user.role === 'hr_admin' ? null : user.employeeId); return (await client.query(`SELECT review.id,review.employee_id AS "employeeId",employee.full_name AS "employeeName",review.manager_id AS "managerId",manager.full_name AS "managerName",review.status,review.overall_score AS "overallScore",cycle.name AS "cycleName",template.name AS "templateName",COUNT(assignment.id)::int AS "assignmentCount",COUNT(assignment.id) FILTER(WHERE assignment.status='submitted')::int AS "submittedCount" FROM performance_reviews review JOIN employees employee ON employee.tenant_id=review.tenant_id AND employee.id=review.employee_id LEFT JOIN employees manager ON manager.tenant_id=review.tenant_id AND manager.id=review.manager_id JOIN performance_review_cycles cycle ON cycle.tenant_id=review.tenant_id AND cycle.id=review.cycle_id JOIN performance_review_templates template ON template.tenant_id=review.tenant_id AND template.id=review.template_id LEFT JOIN performance_review_assignments assignment ON assignment.tenant_id=review.tenant_id AND assignment.review_id=review.id WHERE review.tenant_id=$1 AND ($2::uuid IS NULL OR review.employee_id=$2) GROUP BY review.id,employee.full_name,manager.full_name,cycle.name,template.name ORDER BY review.updated_at DESC`, [user.tenantId, scopedEmployeeId])).rows; }); res.json({ success:true,reviews }); } catch (error) { fail(res,error,'Unable to load performance reviews.'); }
  });

  app.post('/api/hr/performance/reviews', standardAuth, requirePermission('performance.manage_cycles'), async (req,res) => {
    try { const user=req.authUser!; const {cycleId,employeeId,templateId}=req.body||{}; if(!uuid(cycleId)||!uuid(employeeId)||!uuid(templateId)) throw routeError(400,'PERFORMANCE_VALIDATION_ERROR','Cycle, employee, and template are required.'); const review=await withTenant(user.tenantId,async client=>{if(!(await isActiveEmployee(client,user.tenantId,employeeId))) throw routeError(400,'PERFORMANCE_EMPLOYEE_INACTIVE','Employee is not active.'); const cycle=(await client.query(`SELECT id,status,self_review_due_at,manager_review_due_at FROM performance_review_cycles WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[user.tenantId,cycleId])).rows[0]; if(!cycle) throw routeError(404,'PERFORMANCE_CYCLE_NOT_FOUND','Review cycle not found.'); if(['finalised','cancelled'].includes(cycle.status)) throw routeError(409,'PERFORMANCE_CYCLE_CLOSED','This cycle is closed.'); const employee=(await client.query(`SELECT manager_id FROM employees WHERE tenant_id=$1 AND id=$2`,[user.tenantId,employeeId])).rows[0]; const template=(await client.query(`SELECT id FROM performance_review_templates WHERE tenant_id=$1 AND id=$2 AND is_active=true`,[user.tenantId,templateId])).rows[0]; if(!template) throw routeError(400,'PERFORMANCE_TEMPLATE_INVALID','Template is unavailable.'); const created=(await client.query(`INSERT INTO performance_reviews(tenant_id,cycle_id,employee_id,manager_id,template_id,status)VALUES($1,$2,$3,$4,$5,'self_review') RETURNING id,employee_id AS "employeeId",manager_id AS "managerId",status`,[user.tenantId,cycleId,employeeId,employee.manager_id,templateId])).rows[0]; await client.query(`INSERT INTO performance_review_assignments(tenant_id,review_id,reviewer_employee_id,reviewer_type,due_at)VALUES($1,$2,$3,'self',$4)`,[user.tenantId,created.id,employeeId,cycle.self_review_due_at]); if(employee.manager_id) await client.query(`INSERT INTO performance_review_assignments(tenant_id,review_id,reviewer_employee_id,reviewer_type,due_at)VALUES($1,$2,$3,'manager',$4)`,[user.tenantId,created.id,employee.manager_id,cycle.manager_review_due_at]); await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'performance.review.assigned',targetType:'performance_review',targetId:created.id,metadata:{reviewerType:'self'}}); return created;});res.status(201).json({success:true,review});}catch(error){fail(res,error,'Unable to assign performance review.');}
  });

  app.post('/api/hr/performance/reviews/:reviewId/assign-peer', standardAuth, requirePermission('performance.review'), async(req,res)=>{
    try { const user=req.authUser!; if(!uuid(req.params.reviewId)||!uuid(req.body?.reviewerEmployeeId)) throw routeError(400,'PERFORMANCE_VALIDATION_ERROR','Review and reviewer are required.'); const assignment=await withTenant(user.tenantId,async client=>{const review=await assertReviewScope(client,req,req.params.reviewId,'manage'); if(user.role!=='hr_admin' && review.manager_id!==user.employeeId) throw routeError(403,'PERFORMANCE_SCOPE_DENIED','Only the review manager may assign a peer.'); const reviewerId=req.body.reviewerEmployeeId; if(reviewerId===review.employee_id) throw routeError(409,'PERFORMANCE_PEER_SELF_ASSIGNMENT','An employee cannot review themselves as a peer.'); if(!(await isActiveEmployee(client,user.tenantId,reviewerId))) throw routeError(400,'PERFORMANCE_REVIEWER_INELIGIBLE','Peer reviewer is not active.'); const due=(await client.query(`SELECT peer_review_due_at FROM performance_review_cycles WHERE tenant_id=$1 AND id=$2`,[user.tenantId,review.cycle_id])).rows[0]?.peer_review_due_at||null; const inserted=(await client.query(`INSERT INTO performance_review_assignments(tenant_id,review_id,reviewer_employee_id,reviewer_type,due_at,confidential_to_subject)VALUES($1,$2,$3,'peer',$4,true) ON CONFLICT(tenant_id,review_id,reviewer_employee_id) DO NOTHING RETURNING id,reviewer_employee_id AS "reviewerEmployeeId"`,[user.tenantId,review.id,reviewerId,due])).rows[0]; if(!inserted) throw routeError(409,'PERFORMANCE_DUPLICATE_PEER','This peer has already been assigned.'); await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'performance.peer.assigned',targetType:'performance_review',targetId:review.id,metadata:{}}); return inserted;});res.status(201).json({success:true,assignment});}catch(error){fail(res,error,'Unable to assign peer feedback.');}
  });

  app.get('/api/me/performance/reviews', standardAuth, async(req,res)=>{
    try { const user=req.authUser!;const reviews=await withTenant(user.tenantId,async client=>(await client.query(`SELECT review.id,review.status,review.overall_score AS "overallScore",review.final_summary AS "finalSummary",review.finalised_at AS "finalisedAt",cycle.name AS "cycleName",assignment.id AS "assignmentId",assignment.reviewer_type AS "reviewerType",assignment.status AS "assignmentStatus",assignment.due_at AS "dueAt" FROM performance_reviews review LEFT JOIN performance_review_assignments assignment ON assignment.tenant_id=review.tenant_id AND assignment.review_id=review.id AND assignment.reviewer_employee_id=$2 WHERE review.tenant_id=$1 AND (review.employee_id=$2 OR assignment.id IS NOT NULL) ORDER BY review.updated_at DESC`,[user.tenantId,user.employeeId])).rows);res.json({success:true,reviews}); }catch(error){fail(res,error,'Unable to load your performance reviews.');}
  });

  app.get('/api/me/performance/reviews/:reviewId', standardAuth, async(req,res)=>{
    try { const user=req.authUser!;if(!uuid(req.params.reviewId)) throw routeError(404,'PERFORMANCE_REVIEW_NOT_FOUND','Performance review not found.');const review=await withTenant(user.tenantId,async client=>{const current=await assertReviewScope(client,req,req.params.reviewId,'view');const assignments=(await client.query(`SELECT id,reviewer_employee_id AS "reviewerEmployeeId",reviewer_type AS "reviewerType",status,due_at AS "dueAt",submitted_at AS "submittedAt",confidential_to_subject AS "confidentialToSubject" FROM performance_review_assignments WHERE tenant_id=$1 AND review_id=$2 AND ($3::boolean OR reviewer_employee_id=$4 OR reviewer_type<>'peer')`,[user.tenantId,current.id,hasPermission(req,'performance.view_reports'),user.employeeId])).rows;const questions=(await client.query(`SELECT question.id,question.prompt,question.question_type AS "questionType",question.sort_order AS "sortOrder",question.is_required AS "isRequired",question.min_score AS "minScore",question.max_score AS "maxScore",question.weight FROM performance_review_questions question WHERE question.tenant_id=$1 AND question.template_id=$2 ORDER BY question.sort_order`,[user.tenantId,current.template_id])).rows;const own=assignments.find((assignment:{reviewerEmployeeId:string})=>assignment.reviewerEmployeeId===user.employeeId);const responses=own?(await client.query(`SELECT question_id AS "questionId",score,response_text AS "responseText" FROM performance_review_responses WHERE tenant_id=$1 AND assignment_id=$2`,[user.tenantId,own.id])).rows:[];const peerAggregate= current.employee_id===user.employeeId ? (await client.query(`SELECT COUNT(DISTINCT assignment.id)::int AS "submittedCount",AVG(response.score)::numeric AS "averageScore" FROM performance_review_assignments assignment JOIN performance_review_responses response ON response.tenant_id=assignment.tenant_id AND response.assignment_id=assignment.id WHERE assignment.tenant_id=$1 AND assignment.review_id=$2 AND assignment.reviewer_type='peer' AND assignment.status='submitted'`,[user.tenantId,current.id])).rows[0] : null;return {...current,assignments,questions,ownAssignment:own||null,responses,peerAggregate:peerAggregate&&peerAggregate.submittedCount>=3?peerAggregate:{submittedCount:peerAggregate?.submittedCount||0,insufficient:true}};});res.json({success:true,review});}catch(error){fail(res,error,'Unable to load performance review.');}
  });

  app.patch('/api/me/performance/assignments/:assignmentId/draft', standardAuth, async(req,res)=>{
    try {const user=req.authUser!;if(!uuid(req.params.assignmentId))throw routeError(404,'PERFORMANCE_ASSIGNMENT_NOT_FOUND','Review assignment not found.');const assignment=await withTenant(user.tenantId,async client=>{const current=(await client.query(`SELECT assignment.*,review.template_id FROM performance_review_assignments assignment JOIN performance_reviews review ON review.tenant_id=assignment.tenant_id AND review.id=assignment.review_id WHERE assignment.tenant_id=$1 AND assignment.id=$2 AND assignment.reviewer_employee_id=$3 FOR UPDATE`,[user.tenantId,req.params.assignmentId,user.employeeId])).rows[0];if(!current)throw routeError(404,'PERFORMANCE_ASSIGNMENT_NOT_FOUND','Review assignment not found.');if(['submitted','cancelled'].includes(current.status))throw routeError(409,'PERFORMANCE_ASSIGNMENT_LOCKED','This review response is locked.');if(!Array.isArray(req.body?.responses)||req.body.responses.length>50)throw routeError(400,'PERFORMANCE_VALIDATION_ERROR','Responses are invalid.');const questions=(await client.query(`SELECT id,question_type,min_score,max_score FROM performance_review_questions WHERE tenant_id=$1 AND template_id=$2`,[user.tenantId,current.template_id])).rows;const byId=new Map(questions.map(question=>[question.id,question]));for(const raw of req.body.responses){const response=raw&&typeof raw==='object'?raw as Record<string,unknown>:{};if(!uuid(response.questionId)||!byId.has(response.questionId))throw routeError(400,'PERFORMANCE_VALIDATION_ERROR','Question is invalid.');const question=byId.get(response.questionId)!;const score=response.score===undefined||response.score===null||response.score===''?null:Number(response.score);const text=clean(response.responseText,5000)||null;if(question.question_type==='rating'&&(score===null||!Number.isFinite(score)||score<Number(question.min_score)||score>Number(question.max_score)))throw routeError(400,'PERFORMANCE_SCORE_INVALID','Rating is outside the allowed range.');if(question.question_type!=='rating'&&score!==null)throw routeError(400,'PERFORMANCE_SCORE_INVALID','Only rating questions accept scores.');if(score===null&&!text)continue;await client.query(`INSERT INTO performance_review_responses(tenant_id,assignment_id,question_id,score,response_text)VALUES($1,$2,$3,$4,$5) ON CONFLICT(tenant_id,assignment_id,question_id) DO UPDATE SET score=EXCLUDED.score,response_text=EXCLUDED.response_text,updated_at=NOW()`,[user.tenantId,current.id,response.questionId,score,text]);}return(await client.query(`UPDATE performance_review_assignments SET status='in_progress',updated_at=NOW() WHERE tenant_id=$1 AND id=$2 RETURNING id,status`,[user.tenantId,current.id])).rows[0];});res.json({success:true,assignment});}catch(error){fail(res,error,'Unable to save review draft.');}
  });

  app.post('/api/me/performance/assignments/:assignmentId/submit', standardAuth, async(req,res)=>{
    try {const user=req.authUser!;if(!uuid(req.params.assignmentId))throw routeError(404,'PERFORMANCE_ASSIGNMENT_NOT_FOUND','Review assignment not found.');const assignment=await withTenant(user.tenantId,async client=>{const current=(await client.query(`SELECT assignment.*,review.template_id,review.id AS performance_review_id FROM performance_review_assignments assignment JOIN performance_reviews review ON review.tenant_id=assignment.tenant_id AND review.id=assignment.review_id WHERE assignment.tenant_id=$1 AND assignment.id=$2 AND assignment.reviewer_employee_id=$3 FOR UPDATE`,[user.tenantId,req.params.assignmentId,user.employeeId])).rows[0];if(!current)throw routeError(404,'PERFORMANCE_ASSIGNMENT_NOT_FOUND','Review assignment not found.');if(current.status==='submitted')throw routeError(409,'PERFORMANCE_ASSIGNMENT_SUBMITTED','This review was already submitted.');if(current.status==='cancelled')throw routeError(409,'PERFORMANCE_ASSIGNMENT_LOCKED','This review assignment is cancelled.');const missing=(await client.query(`SELECT question.id FROM performance_review_questions question LEFT JOIN performance_review_responses response ON response.tenant_id=question.tenant_id AND response.question_id=question.id AND response.assignment_id=$3 WHERE question.tenant_id=$1 AND question.template_id=$2 AND question.is_required=true AND response.id IS NULL LIMIT 1`,[user.tenantId,current.template_id,current.id])).rows[0];if(missing)throw routeError(409,'PERFORMANCE_REQUIRED_RESPONSE_MISSING','Complete all required questions before submitting.');const updated=(await client.query(`UPDATE performance_review_assignments SET status='submitted',submitted_at=NOW(),updated_at=NOW() WHERE tenant_id=$1 AND id=$2 AND status<>'submitted' RETURNING id,review_id AS "reviewId",reviewer_type AS "reviewerType"`,[user.tenantId,current.id])).rows[0];await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'performance.review.submitted',targetType:'performance_review_assignment',targetId:current.id,metadata:{reviewerType:current.reviewer_type}});return updated;});res.json({success:true,assignment});}catch(error){fail(res,error,'Unable to submit review.');}
  });

  app.post('/api/hr/performance/reviews/:reviewId/finalise', standardAuth, requirePermission('performance.manage_cycles'), async(req,res)=>{
    try {const user=req.authUser!;if(!uuid(req.params.reviewId))throw routeError(404,'PERFORMANCE_REVIEW_NOT_FOUND','Performance review not found.');const review=await withTenant(user.tenantId,async client=>{const current=await assertReviewScope(client,req,req.params.reviewId,'manage');if(current.status==='completed')throw routeError(409,'PERFORMANCE_REVIEW_FINALISED','This review is already finalised.');const missing=(await client.query(`SELECT 1 FROM performance_review_assignments WHERE tenant_id=$1 AND review_id=$2 AND reviewer_type IN('self','manager') AND status<>'submitted' LIMIT 1`,[user.tenantId,current.id])).rows[0];if(missing)throw routeError(409,'PERFORMANCE_ASSIGNMENTS_INCOMPLETE','Required self and manager reviews must be submitted first.');const score=await calculateScore(client,user.tenantId,current.id);const updated=(await client.query(`UPDATE performance_reviews SET status='completed',overall_score=$3,final_summary=$4,finalised_at=NOW(),version=version+1,updated_at=NOW() WHERE tenant_id=$1 AND id=$2 AND status<>'completed' RETURNING id,status,overall_score AS "overallScore",finalised_at AS "finalisedAt"`,[user.tenantId,current.id,score,clean(req.body?.finalSummary,5000)||null])).rows[0];await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'performance.review.finalised',targetType:'performance_review',targetId:current.id,metadata:{}});return updated;});res.json({success:true,review});}catch(error){fail(res,error,'Unable to finalise performance review.');}
  });

  app.get('/api/hr/performance/goals', standardAuth, requirePermission('performance.view'), async(req,res)=>{
    try {
      const user = req.authUser!;
      const employeeId = uuid(req.query.employeeId) ? String(req.query.employeeId) : null;
      const goals = await withTenant(user.tenantId, async (client) => {
        const canManageDirectReport = employeeId
          ? hasPermission(req, 'performance.manage_goals')
            && await isManagerOf(client, user.tenantId, user.employeeId, employeeId)
          : false;
        if (employeeId && employeeId !== user.employeeId && user.role !== 'hr_admin' && !canManageDirectReport) {
          throw routeError(403, 'PERFORMANCE_SCOPE_DENIED', 'You may only manage direct-report goals.');
        }
        const scopedEmployeeId = employeeId || (user.role === 'hr_admin' ? null : user.employeeId);
        return (await client.query(
          `SELECT goal.id,goal.employee_id AS "employeeId",employee.full_name AS "employeeName",goal.title,goal.description,goal.goal_type AS "goalType",goal.progress_percent AS "progressPercent",goal.target_value AS "targetValue",goal.current_value AS "currentValue",goal.unit,goal.status,goal.starts_at AS "startsAt",goal.due_at AS "dueAt",goal.completed_at AS "completedAt" FROM performance_goals goal JOIN employees employee ON employee.tenant_id=goal.tenant_id AND employee.id=goal.employee_id WHERE goal.tenant_id=$1 AND ($2::uuid IS NULL OR goal.employee_id=$2) ORDER BY goal.due_at NULLS LAST,goal.created_at DESC`,
          [user.tenantId, scopedEmployeeId],
        )).rows;
      });
      res.json({ success: true, goals });
    } catch (error) { fail(res, error, 'Unable to load goals.'); }
  });

  app.post('/api/hr/performance/goals', standardAuth, requirePermission('performance.manage_goals'), async(req,res)=>{
    try {const user=req.authUser!,body=req.body||{};if(!uuid(body.employeeId))throw routeError(400,'PERFORMANCE_VALIDATION_ERROR','Employee is required.');const goal=await withTenant(user.tenantId,async client=>{if(user.role!=='hr_admin'&&!(await isManagerOf(client,user.tenantId,user.employeeId,body.employeeId)))throw routeError(403,'PERFORMANCE_SCOPE_DENIED','You may only create goals for direct reports.');if(!(await isActiveEmployee(client,user.tenantId,body.employeeId)))throw routeError(400,'PERFORMANCE_EMPLOYEE_INACTIVE','Employee is not active.');const title=clean(body.title,240);if(!title||!['goal','objective','key_result'].includes(body.goalType||'goal'))throw routeError(400,'PERFORMANCE_VALIDATION_ERROR','Goal details are invalid.');const progress=body.progressPercent===undefined?0:Number(body.progressPercent);if(!Number.isInteger(progress)||progress<0||progress>100)throw routeError(400,'PERFORMANCE_VALIDATION_ERROR','Goal progress must be between 0 and 100.');const created=(await client.query(`INSERT INTO performance_goals(tenant_id,employee_id,cycle_id,title,description,goal_type,progress_percent,target_value,current_value,unit,status,starts_at,due_at,created_by,completed_at)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,CASE WHEN $7=100 THEN NOW() ELSE NULL END)RETURNING id,title,progress_percent AS "progressPercent",status`,[user.tenantId,body.employeeId,uuid(body.cycleId)?body.cycleId:null,title,clean(body.description,4000)||null,body.goalType||'goal',progress,body.targetValue===''||body.targetValue===undefined?null:Number(body.targetValue),body.currentValue===''||body.currentValue===undefined?null:Number(body.currentValue),clean(body.unit,80)||null,progress===100?'completed':(body.status||'planned'),date(body.startsAt,'Start date'),date(body.dueAt,'Due date'),user.employeeId])).rows[0];await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'performance.goal.created',targetType:'performance_goal',targetId:created.id,metadata:{goalType:body.goalType||'goal'}});return created;});res.status(201).json({success:true,goal});}catch(error){fail(res,error,'Unable to create goal.');}
  });

  app.patch('/api/me/performance/goals/:goalId/progress', standardAuth, async(req,res)=>{
    try {const user=req.authUser!;if(!uuid(req.params.goalId))throw routeError(404,'PERFORMANCE_GOAL_NOT_FOUND','Goal not found.');const goal=await withTenant(user.tenantId,async client=>{const current=(await client.query(`SELECT * FROM performance_goals WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[user.tenantId,req.params.goalId])).rows[0];if(!current)throw routeError(404,'PERFORMANCE_GOAL_NOT_FOUND','Goal not found.');const manager=await isManagerOf(client,user.tenantId,user.employeeId,current.employee_id);if(current.employee_id!==user.employeeId&&!manager&&!hasPermission(req,'performance.manage_goals'))throw routeError(403,'PERFORMANCE_SCOPE_DENIED','You may not update this goal.');const progress=Number(req.body?.progressPercent);if(!Number.isInteger(progress)||progress<0||progress>100)throw routeError(400,'PERFORMANCE_VALIDATION_ERROR','Goal progress must be between 0 and 100.');if(['completed','cancelled'].includes(current.status)&&progress!==current.progress_percent)throw routeError(409,'PERFORMANCE_GOAL_LOCKED','This goal is closed.');const status=progress===100?'completed':(req.body?.status==='at_risk'?'at_risk':'active');const updated=(await client.query(`UPDATE performance_goals SET progress_percent=$3,status=$4,current_value=COALESCE($5,current_value),completed_at=CASE WHEN $3=100 THEN COALESCE(completed_at,NOW()) ELSE NULL END,updated_at=NOW() WHERE tenant_id=$1 AND id=$2 RETURNING id,title,progress_percent AS "progressPercent",status,completed_at AS "completedAt"`,[user.tenantId,current.id,progress,status,req.body?.currentValue===undefined?null:Number(req.body.currentValue)])).rows[0];await client.query(`INSERT INTO performance_goal_updates(tenant_id,goal_id,updated_by,previous_progress,new_progress,note)VALUES($1,$2,$3,$4,$5,$6)`,[user.tenantId,current.id,user.employeeId,current.progress_percent,progress,clean(req.body?.note,2000)||null]);await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:progress===100?'performance.goal.completed':'performance.goal.updated',targetType:'performance_goal',targetId:current.id,metadata:progress===100?{}:{progressPercent:progress}});return updated;});res.json({success:true,goal});}catch(error){fail(res,error,'Unable to update goal progress.');}
  });

  app.get('/api/me/performance/goals', standardAuth, async(req,res)=>{try{const user=req.authUser!;const goals=await withTenant(user.tenantId,async client=>(await client.query(`SELECT id,title,description,goal_type AS "goalType",progress_percent AS "progressPercent",target_value AS "targetValue",current_value AS "currentValue",unit,status,starts_at AS "startsAt",due_at AS "dueAt",completed_at AS "completedAt" FROM performance_goals WHERE tenant_id=$1 AND employee_id=$2 ORDER BY due_at NULLS LAST,created_at DESC`,[user.tenantId,user.employeeId])).rows);res.json({success:true,goals});}catch(error){fail(res,error,'Unable to load your goals.');}});

  app.get('/api/hr/performance/recognitions', standardAuth, requirePermission('performance.manage_recognition'), async(req,res)=>{try{const user=req.authUser!;const recognitions=await withTenant(user.tenantId,async client=>(await client.query(`SELECT recognition.id,recognition.employee_id AS "employeeId",employee.full_name AS "employeeName",recognition.recognition_month AS "recognitionMonth",recognition.title,recognition.message,recognition.awarded_at AS "awardedAt",recognition.revoked_at AS "revokedAt",review.overall_score AS "finalisedReviewScore",COALESCE(goal_summary.completed_goals,0)::int AS "completedGoals" FROM employee_recognitions recognition JOIN employees employee ON employee.tenant_id=recognition.tenant_id AND employee.id=recognition.employee_id LEFT JOIN LATERAL(SELECT AVG(overall_score) AS overall_score FROM performance_reviews WHERE tenant_id=recognition.tenant_id AND employee_id=recognition.employee_id AND status='completed') review ON TRUE LEFT JOIN LATERAL(SELECT COUNT(*) AS completed_goals FROM performance_goals WHERE tenant_id=recognition.tenant_id AND employee_id=recognition.employee_id AND status='completed') goal_summary ON TRUE WHERE recognition.tenant_id=$1 ORDER BY recognition.recognition_month DESC,recognition.awarded_at DESC`,[user.tenantId])).rows);res.json({success:true,recognitions});}catch(error){fail(res,error,'Unable to load recognitions.');}});

  app.post('/api/hr/performance/recognitions/employee-of-month', standardAuth, requirePermission('performance.manage_recognition'), async(req,res)=>{try{const user=req.authUser!,body=req.body||{};if(!uuid(body.employeeId))throw routeError(400,'PERFORMANCE_VALIDATION_ERROR','Employee is required.');const month=date(body.recognitionMonth,'Recognition month',true);if(month!==`${month!.slice(0,7)}-01`)throw routeError(400,'PERFORMANCE_VALIDATION_ERROR','Recognition month must be the first day of the month.');const recognition=await withTenant(user.tenantId,async client=>{if(!(await isActiveEmployee(client,user.tenantId,body.employeeId)))throw routeError(400,'PERFORMANCE_EMPLOYEE_INACTIVE','Employee is not active.');const title=clean(body.title,160)||'Employee of the Month';const message=clean(body.message,1000)||null;try{const created=(await client.query(`INSERT INTO employee_recognitions(tenant_id,employee_id,recognition_type,recognition_month,title,message,cycle_id,awarded_by)VALUES($1,$2,'employee_of_month',$3,$4,$5,$6,$7)RETURNING id,employee_id AS "employeeId",recognition_month AS "recognitionMonth",title,message`,[user.tenantId,body.employeeId,month,title,message,uuid(body.cycleId)?body.cycleId:null,user.employeeId])).rows[0];await client.query(`INSERT INTO employee_recognition_deliveries(tenant_id,recognition_id,employee_id)VALUES($1,$2,$3)`,[user.tenantId,created.id,body.employeeId]);await recordAuditEvent(client,{tenantId:user.tenantId,actorId:user.employeeId,action:'performance.recognition.awarded',targetType:'employee_recognition',targetId:created.id,metadata:{recognitionMonth:month}});return created;}catch(error){if((error as {code?:string}).code==='23505')throw routeError(409,'PERFORMANCE_MONTHLY_RECOGNITION_EXISTS','An Employee of the Month already exists for this month.');throw error;}});res.status(201).json({success:true,recognition});}catch(error){fail(res,error,'Unable to award recognition.');}});

  app.get('/api/me/performance/recognitions', standardAuth, async(req,res)=>{try{const user=req.authUser!;const recognitions=await withTenant(user.tenantId,async client=>(await client.query(`SELECT recognition.id,recognition.recognition_month AS "recognitionMonth",recognition.title,recognition.message,recognition.awarded_at AS "awardedAt",recognition.revoked_at AS "revokedAt",delivery.delivery_status AS "deliveryStatus" FROM employee_recognitions recognition LEFT JOIN employee_recognition_deliveries delivery ON delivery.tenant_id=recognition.tenant_id AND delivery.recognition_id=recognition.id AND delivery.employee_id=$2 WHERE recognition.tenant_id=$1 AND recognition.employee_id=$2 ORDER BY recognition.recognition_month DESC`,[user.tenantId,user.employeeId])).rows);res.json({success:true,recognitions});}catch(error){fail(res,error,'Unable to load recognition history.');}});
  app.post('/api/me/performance/recognitions/claim-pending', standardAuth, async(req,res)=>{try{const user=req.authUser!;const recognition=await claimPendingRecognitionDelivery(user.tenantId,user.employeeId,'manual');res.json({success:true,recognition});}catch(error){fail(res,error,'Unable to claim pending recognition.');}});
}
