import { ChevronDown, ChevronUp, RotateCcw } from 'lucide-react';
import type { DashboardNavigationItem } from './DashboardNavigation';
import { useLanguage } from '../../lib/LanguageContext';

type Props = { items: DashboardNavigationItem[]; shortcuts: string[]; onChange: (shortcuts: string[]) => void };
const recommended = ['geofence', 'roster', 'feed', 'profile'];

export function MobileShortcutSettings({ items, shortcuts, onChange }: Props) {
  const { lang } = useLanguage();
  const valid = shortcuts.filter((id, index) => items.some((item) => item.id === id) && shortcuts.indexOf(id) === index);
  const selected = valid.length >= 4 ? valid : [...new Set([...valid, ...recommended.filter((id) => items.some((item) => item.id === id))])].slice(0, 4);
  const toggle = (id: string) => { if (selected.includes(id)) { if (selected.length <= 4) return; onChange(selected.filter((value) => value !== id)); } else onChange([...selected, id]); };
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= selected.length) return; const next = [...selected]; [next[index], next[target]] = [next[target], next[index]]; onChange(next); };
  return <section className="rounded-xl border border-emerald-500/15 bg-black/5 p-3 dark:bg-black/20"><div><h4 className="text-sm font-black">{lang === 'ar' ? 'اختصارات الهاتف' : 'Mobile shortcuts'}</h4><p className="mt-1 text-xs text-slate-500 dark:text-emerald-100/55">{lang === 'ar' ? 'اختر أربعة اختصارات على الأقل. زر Stanza والمزيد ثابتان.' : 'Choose at least four shortcuts. Stanza and More remain fixed.'}</p></div>{selected.length > 5 && <p role="status" className="mt-3 rounded-lg border border-amber-500/25 bg-amber-500/10 p-2 text-xs text-amber-800 dark:text-amber-100">{lang === 'ar' ? 'قد تؤدي إضافة المزيد من الاختصارات إلى ازدحام التنقل على الشاشات الصغيرة.' : 'Adding more shortcuts may make navigation crowded on smaller screens.'}</p>}<div className="mt-3 space-y-2">{items.map((item) => { const index = selected.indexOf(item.id); const checked = index >= 0; return <div key={item.id} className="flex min-h-10 items-center gap-2 rounded-lg border border-emerald-500/10 px-2"><input id={`shortcut-${item.id}`} type="checkbox" checked={checked} onChange={() => toggle(item.id)} disabled={checked && selected.length <= 4} className="h-4 w-4 accent-emerald-600" /><label htmlFor={`shortcut-${item.id}`} className="min-w-0 flex-1 text-xs font-bold">{item.label}</label>{checked && <><span className="text-[10px] text-slate-500 dark:text-emerald-100/45">{index + 1}</span><button type="button" onClick={() => move(index, -1)} disabled={index === 0} aria-label={`${item.label} previous`} className="rounded p-1 disabled:opacity-30"><ChevronUp className="h-4 w-4" /></button><button type="button" onClick={() => move(index, 1)} disabled={index === selected.length - 1} aria-label={`${item.label} next`} className="rounded p-1 disabled:opacity-30"><ChevronDown className="h-4 w-4" /></button></>}</div>; })}</div><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => onChange(recommended.filter((id) => items.some((item) => item.id === id)))} className="inline-flex min-h-10 items-center gap-1 rounded-lg border border-emerald-500/20 px-3 text-xs font-bold"><RotateCcw className="h-3.5 w-3.5" />{lang === 'ar' ? 'إعادة الضبط' : 'Reset defaults'}</button><button type="button" onClick={() => onChange(items.map((item) => item.id))} className="min-h-10 rounded-lg border border-emerald-500/20 px-3 text-xs font-bold">{lang === 'ar' ? 'إضافة الكل' : 'Add all'}</button></div></section>;
}
