import './router-env';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import {createRequire} from 'node:module';
import {getMigrationPool} from './migration-pool';
import {assertDatabaseMutationSafety,assertHttpMutationSafety} from './mutation-safety';
const base=assertHttpMutationSafety(process.env.BROWSER_BASE_URL||'http://localhost:3001','Assets browser');
assertDatabaseMutationSafety(process.env.DATABASE_URL,'Assets browser');
const {chromium}=createRequire(import.meta.url)(process.env.BROWSER_PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'}),db=getMigrationPool();
const tag=crypto.randomUUID(),password=crypto.randomBytes(24).toString('base64url'),tenants:string[]=[],assets:any[]=[];
let matrix=0;
try{
 const all=(await db.query('SELECT permission_key FROM tenant_permissions')).rows.map(r=>r.permission_key);
 async function tenant(label:string){const id=(await db.query('INSERT INTO tenants(slug,company_name) VALUES($1,$2) RETURNING id',['assets-polish-'+label+'-'+tag,'Assets polish fixture '+tag])).rows[0].id;tenants.push(id);return id;}
 const primary=await tenant('primary'),foreign=await tenant('foreign');
 async function actor(tenantId:string,name:string,keys:string[],admin=false){
 const email='assets-polish-'+name+'-'+tag+'@example.invalid';
 const id=(await db.query('INSERT INTO employees(tenant_id,full_name,email,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id',[tenantId,'Assets fixture '+name,email,await bcrypt.hash(password,10),admin?'hr_admin':'employee'])).rows[0].id;
 const role=(await db.query('INSERT INTO tenant_roles(tenant_id,name,is_system) VALUES($1,$2,false) RETURNING id',[tenantId,name])).rows[0].id;
 for(const key of keys)await db.query('INSERT INTO tenant_role_permissions(tenant_id,role_id,permission_key) VALUES($1,$2,$3)',[tenantId,role,key]);
 await db.query("INSERT INTO employee_role_assignments(tenant_id,employee_id,role_id,scope_type) VALUES($1,$2,$3,'company')",[tenantId,id,role]);
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,serviceWorkers:'block'});
 await context.addInitScript(()=>{localStorage.setItem('stanza.preferences.v1',JSON.stringify({tutorialsAutoStart:false,lanyardEnabled:false}));localStorage.setItem('horizon-language','en');localStorage.setItem('stanza-demo-notice-seen','true');});
 const response=await context.request.post(base+'/api/auth/login',{headers:{Origin:base},data:{email,password}});assert.equal(response.status(),200,'normal cookie login');const user=(await response.json()).user;return {id,user,context};
 }
 const admin=await actor(primary,'administrator',all,true),reader=await actor(primary,'holder',['assets.view']),outsider=await actor(foreign,'foreign',['assets.view']);
 async function req(path:string,body?:unknown,method=body?'POST':'GET',context=admin.context){const r=await context.request.fetch(base+path,{method,headers:{Origin:base},...(body?{data:body}:{})});return {...await r.json(),status:r.status()};}
 const p=await admin.context.newPage();p.setDefaultTimeout(15000);
 async function navigate(page:any,name:string){await page.locator('[data-tutorial-target=stanza-launcher]').click();await page.locator('#stanza-navigation-panel .stanza-navigation-item').filter({hasText:name}).last().click();}
 await p.goto(base);await p.locator('[data-tutorial-target=stanza-launcher]').waitFor();await navigate(p,'Assets & Equipment');
 await p.getByText('No assets yet.',{exact:true}).waitFor();await p.screenshot({path:process.env.TEMP+'/stanza-assets-empty.png',fullPage:true});
 for(let i=0;i<25;i++){const d=await req('/api/hr/assets',{assetTag:'AST-'+tag.slice(0,8)+'-'+i,name:'Owned equipment '+i,category:i===4?'monitor':'laptop',condition:'good'});assert.equal(d.status,201);assets.push(d.asset);}
 assert.equal((await req('/api/hr/assets/'+assets[1].id+'/assign',{employeeId:reader.id})).status,200);
 assert.equal((await req('/api/hr/assets/'+assets[2].id+'/report-condition',{condition:'damaged',notes:'Owned condition fixture'})).status,201);
 assert.equal((await req('/api/hr/assets/'+assets[1].id+'/report-condition',{condition:'damaged',notes:'Assigned condition fixture'})).status,201);
 assert.equal((await req('/api/hr/assets/'+assets[1].id)).asset.status,'assigned');
 assert.equal((await req('/api/hr/assets/'+assets[1].id+'/report-condition',{condition:'good',notes:'Assigned condition restored'})).status,201);

 assert.equal((await req('/api/hr/assets/'+assets[3].id+'/assign',{employeeId:reader.id})).status,200);
 assert.equal((await req('/api/hr/assets/'+assets[3].id+'/return',{condition:'good',notes:'Owned return fixture'})).status,200);
 assert.equal((await req('/api/hr/assets/'+assets[6].id+'/assign',{employeeId:reader.id})).status,200);assert.equal((await req('/api/hr/assets/'+assets[6].id+'/return',{condition:'damaged',notes:'Owned damaged return'})).status,200);const damagedReturn=(await req('/api/hr/assets/'+assets[6].id)).asset;assert.equal(damagedReturn.status,'maintenance');assert.equal(damagedReturn.condition,'damaged');assert.equal(damagedReturn.assignments[0].status,'damaged');assert.equal(Number((await db.query("SELECT count(*) FROM audit_logs WHERE tenant_id=$1 AND entity_id=$2 AND action='asset.returned'",[primary,assets[6].id])).rows[0].count),1);
 const issue=await req('/api/support',{assetId:assets[1].id,requesterId:reader.id,issueType:'equipment_issue',summary:'Owned battery issue',description:'Fictional verification only',urgency:'normal'});assert.equal(issue.status,201);
 const resolved=await req('/api/support',{assetId:assets[1].id,requesterId:reader.id,issueType:'it_help',summary:'Owned resolved issue',description:'Fictional historical issue',urgency:'normal'});assert.equal(resolved.status,201);
 assert.equal((await req('/api/support/'+resolved.ticket.id+'/update',{status:'in_progress',note:'Investigating'})).status,201);
 assert.equal((await req('/api/support/'+resolved.ticket.id+'/update',{status:'resolved',note:'Fixture repaired'})).status,201);
 async function search(page:any,value:string){const input=page.locator('.assets-filters input');if(await input.inputValue()!==value){const response=page.waitForResponse((r:any)=>{const u=new URL(r.url());return u.pathname==='/api/hr/assets'&&u.searchParams.get('search')===value;});await input.fill(value);assert.equal((await response).status(),200);}await page.locator('.assets-layout > div > p[role=status]').waitFor({state:'detached'});}
 await p.locator('.assets-panel').getByRole('button',{name:'Retry',exact:true}).click();
 await search(p,assets[0].assetTag);let row=p.locator('.assets-row').filter({hasText:'Owned equipment 0'});await row.waitFor();await row.focus();await p.keyboard.press('Enter');
 const detail=p.getByRole('region',{name:'Asset detail',exact:true});await detail.getByRole('button',{name:'Assign asset',exact:true}).waitFor();assert.equal(await row.getAttribute('aria-pressed'),'true');
 await detail.getByRole('button',{name:'Assign asset',exact:true}).click();let dialog=p.getByRole('dialog',{name:'Assign asset',exact:true});
 await dialog.getByRole('textbox',{name:'Find employee',exact:true}).fill('Assets fixture holder');await dialog.getByRole('button',{name:'Search employees',exact:true}).click();
 await dialog.getByRole('combobox',{name:'Employee',exact:true}).selectOption(reader.id);await dialog.getByRole('button',{name:'Confirm',exact:true}).click();await dialog.waitFor({state:'detached'});
 await detail.locator('.assets-facts').first().getByText('Assets fixture holder',{exact:true}).waitFor();await detail.getByRole('button',{name:'View holder context',exact:true}).click();await detail.locator('.assets-secondary').filter({hasText:'Assets fixture holder'}).waitFor();
 await detail.getByRole('button',{name:'Return / unassign',exact:true}).click();dialog=p.getByRole('dialog',{name:'Return / unassign',exact:true});await dialog.getByRole('combobox',{name:'Condition',exact:true}).selectOption('good');await dialog.getByRole('button',{name:'Confirm',exact:true}).click();await dialog.waitFor({state:'detached'});await detail.getByRole('button',{name:'Assign asset',exact:true}).waitFor();assert.equal(await detail.locator('p.assets-secondary').filter({hasText:'Assets fixture holder'}).count(),0,'returned inventory does not retain obsolete holder context');
 await detail.getByRole('button',{name:'Edit asset',exact:true}).click();dialog=p.getByRole('dialog',{name:'Edit asset',exact:true});await dialog.getByRole('textbox',{name:'Item name',exact:true}).fill('Owned equipment 0 updated');await dialog.getByRole('button',{name:'Save',exact:true}).click();await dialog.waitFor({state:'detached'});await detail.getByRole('heading',{name:'Owned equipment 0 updated',exact:true}).waitFor();
 await detail.getByRole('button',{name:'Close asset detail',exact:true}).click();row=p.locator('.assets-row').filter({has:p.getByText(assets[0].assetTag,{exact:true})});assert(await row.evaluate((el:HTMLElement)=>document.activeElement===el),'detail close restores the current row after edit refresh');await p.keyboard.press('Enter');await detail.getByRole('heading',{name:'Owned equipment 0 updated',exact:true}).waitFor();
 console.log('PASS actual keyboard selection/focus restoration, assignment/return confirmation, holder lookup, and explicit edit save.');
 await detail.getByText('QR / identification',{exact:true}).click();await detail.getByText('No QR label has been issued.',{exact:true}).waitFor();await detail.getByRole('button',{name:'Issue QR label',exact:true}).click();await detail.locator('.asset-qr-print svg').waitFor();
 const label=await req('/api/hr/assets/'+assets[0].id+'/qr-label');assert(label.label.verificationUrl);const token=new URL(label.label.verificationUrl).pathname.split('/').pop();assert.match(token,/^[A-Za-z0-9_-]{43}$/);
 const publicContext=await browser.newContext({viewport:{width:390,height:844}}),publicPage=await publicContext.newPage();await publicPage.goto(label.label.verificationUrl);await publicPage.getByRole('heading',{name:'Verified company asset',exact:true}).waitFor();
 for(const preset of ['custom','light']){const c=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});await c.addInitScript((preset:string)=>{localStorage.setItem('horizon-language','ar');localStorage.setItem('horizon-theme',preset==='light'?'light':'dark');localStorage.setItem('stanza.preferences.v1',JSON.stringify({backgroundPreset:preset==='light'?'emerald':'custom',customTheme:{accent:'#bf52e5'},interfaceScale:1.15,fontScale:1.2}));},preset);const page=await c.newPage();await page.goto(label.label.verificationUrl);await page.locator('.assets-public h1').waitFor();await page.getByText(label.label.display.label,{exact:true}).waitFor();assert.equal(await page.locator('.assets-public').getAttribute('dir'),'rtl');assert.equal(await page.locator('.assets-public a').evaluate((el:HTMLElement)=>getComputedStyle(el).color),await page.locator('.assets-public h1').evaluate((el:HTMLElement)=>getComputedStyle(el).color),'public verification action uses readable text rather than decorative accent');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:process.env.TEMP+'/stanza-public-asset-ar-'+preset+'-xl.png',fullPage:true});await c.close();}
 const publicData=await req('/api/public/verify/asset/'+token);assert.equal(publicData.status,200);for(const key of ['serialNumber','assignedEmployee','assignments','notes'])assert(!(key in publicData));
 const downloaded=p.waitForEvent('download');await detail.getByRole('button',{name:'Download SVG',exact:true}).click();const file=await downloaded;await file.saveAs(process.env.TEMP+'/stanza-assets-qr.svg');
 await p.emulateMedia({media:'print'});assert.equal(await p.locator('.asset-qr-print').evaluate((el:HTMLElement)=>getComputedStyle(el).visibility),'visible');await p.screenshot({path:process.env.TEMP+'/stanza-assets-qr-print.png',fullPage:true});await p.emulateMedia({media:'screen'});
 await detail.getByRole('button',{name:'Rotate label',exact:true}).click();dialog=p.getByRole('dialog',{name:'Rotate QR label?',exact:true});await dialog.waitFor();await p.keyboard.press('Tab');assert(await p.evaluate(()=>document.querySelector('dialog')?.contains(document.activeElement)));await dialog.getByRole('button',{name:'Confirm',exact:true}).click();await dialog.waitFor({state:'detached'});assert.notEqual((await req('/api/hr/assets/'+assets[0].id+'/qr-label')).label.verificationUrl,label.label.verificationUrl);assert.equal((await req('/api/public/verify/asset/'+token)).status,404);
 await detail.getByRole('button',{name:'Revoke label',exact:true}).click();dialog=p.getByRole('dialog',{name:'Revoke QR label?',exact:true});await dialog.getByRole('button',{name:'Confirm',exact:true}).click();await dialog.waitFor({state:'detached'});await detail.getByText('This label has been revoked.',{exact:true}).waitFor();await publicContext.close();
 console.log('PASS real QR issue/download/print/opaque public verification/rotation invalidation/revocation.');
 async function select(index:number){await search(p,assets[index].assetTag);await p.locator('.assets-row').filter({has:p.getByText(assets[index].assetTag,{exact:true})}).click();await detail.getByRole('heading',{name:assets[index].name,exact:true}).waitFor();}
 await select(2);await detail.getByText('Lifecycle actions',{exact:true}).click();await detail.getByRole('button',{name:'Report condition',exact:true}).click();dialog=p.getByRole('dialog',{name:'Report condition',exact:true});await dialog.getByRole('combobox',{name:'Condition',exact:true}).selectOption('fair');await dialog.getByRole('textbox',{name:'Notes',exact:true}).fill('Owned condition review');await dialog.getByRole('button',{name:'Confirm',exact:true}).click();await dialog.waitFor({state:'detached'});await detail.getByText('Assignment and condition history',{exact:true}).click();await detail.getByText('Owned condition review',{exact:true}).waitFor();assert.equal((await req('/api/hr/assets/'+assets[2].id)).asset.status,'maintenance','condition update does not invent status transitions');
 await select(1);await detail.getByText('Support activity',{exact:true}).click();await detail.getByRole('button',{name:'Owned battery issue',exact:false}).waitFor();await detail.getByRole('button',{name:'Owned resolved issue',exact:false}).waitFor();await detail.getByRole('button',{name:'Owned battery issue',exact:false}).click();await detail.getByText('Fictional verification only',{exact:true}).waitFor();assert.equal((await req('/api/support/'+issue.ticket.id,undefined,'GET',outsider.context)).status,404);
 await select(3);await detail.getByText('Assignment and condition history',{exact:true}).click();await detail.getByText('Owned return fixture',{exact:true}).waitFor();await detail.getByText('Support activity',{exact:true}).click();await detail.getByText('No Support issues for this asset.',{exact:true}).waitFor();
 for(const [index,action,labelText] of [[4,'retire','Retire'],[5,'mark-lost','Mark lost']] as const){await select(index);await detail.getByText('Lifecycle actions',{exact:true}).click();await detail.getByRole('button',{name:labelText,exact:true}).click();dialog=p.getByRole('dialog',{name:labelText,exact:true});assert((await dialog.innerText()).includes(assets[index].assetTag));await dialog.getByRole('button',{name:'Confirm',exact:true}).click();await dialog.waitFor({state:'detached'});assert.equal((await req('/api/hr/assets/'+assets[index].id)).asset.status,action==='retire'?'retired':'lost');}
 console.log('PASS condition/status distinction, real return/condition history, open/resolved/no Support context and guarded final-state actions.');
 await detail.getByRole('button',{name:'Close asset detail',exact:true}).click();await p.locator('.assets-panel').getByRole('button',{name:'Reset filters',exact:true}).click();
 await p.locator('.assets-pagination [role=status]').getByText('1–20 of 25',{exact:true}).waitFor();await p.getByRole('button',{name:'Next page',exact:true}).click();await p.getByText('21–25 of 25',{exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Next page',exact:true}).isDisabled(),true);
 await p.locator('.assets-filters').getByRole('combobox',{name:'Status',exact:true}).selectOption('assigned');await p.getByText('1–1 of 1',{exact:true}).waitFor();
 await p.locator('.assets-filters').getByRole('combobox',{name:'Category',exact:true}).selectOption('monitor');await p.getByText('No assets match these filters.',{exact:true}).waitFor();await p.getByRole('button',{name:'Reset filters',exact:true}).click();await p.getByText('1–20 of 25',{exact:true}).waitFor();
 assert.equal((await req('/api/hr/assets/'+assets[0].id+'/assign',{employeeId:reader.id},'POST',reader.context)).status,403);assert.equal((await req('/api/hr/assets/'+assets[0].id,undefined,'GET',outsider.context)).status,404);assert.equal((await req('/api/hr/assets/'+assets[0].id+'/assign',{employeeId:outsider.id})).status,400);assert.equal((await req('/api/hr/assets/'+assets[0].id,{},'PATCH',reader.context)).status,403);assert.equal((await req('/api/hr/assets/'+assets[0].id+'/qr-label/issue',{},'POST',reader.context)).status,403);
 const limited=await reader.context.newPage();await limited.goto(base);await limited.locator('[data-tutorial-target=stanza-launcher]').waitFor();await navigate(limited,'Assets & Equipment');await limited.locator('.assets-row').first().waitFor();assert.equal(await limited.getByRole('button',{name:'Create asset',exact:true}).count(),0);await limited.locator('.assets-row').first().click();await limited.locator('.assets-detail h3').waitFor();for(const name of ['Assign asset','Return / unassign','Edit asset','Report condition'])assert.equal(await limited.getByRole('button',{name,exact:true}).count(),0);
 console.log('PASS server pagination, composed filters/reset, limited UI and actual assignment/mutation/QR/foreign-tenant denials.');
 assert.equal((await req('/api/hr/assets/'+assets[1].id+'/qr-label/issue',{})).status,201);
 for(const ar of [false,true])for(const width of [390,820]){const c=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce',serviceWorkers:'block'});await c.addCookies(await reader.context.cookies());await c.addInitScript((ar:boolean)=>{localStorage.setItem('stanza.preferences.v1',JSON.stringify({tutorialsAutoStart:false,lanyardEnabled:false,backgroundPreset:'custom',customTheme:{accent:'#bf52e5'},interfaceScale:1.15,fontScale:1.2}));localStorage.setItem('horizon-language',ar?'ar':'en');localStorage.setItem('horizon-theme','dark');localStorage.setItem('stanza-demo-notice-seen','true');},ar);const me=await c.newPage();await me.goto(base);await me.locator('[data-tutorial-target=stanza-launcher]').waitFor();await navigate(me,ar?'الملف الشخصي':'Profile');const equipment=me.locator('.assets-equipment');await equipment.getByRole('heading',{name:'Owned equipment 1',exact:true}).waitFor();assert.equal(await equipment.getAttribute('dir'),ar?'rtl':'ltr');assert.equal(await equipment.locator('bdi').first().getAttribute('dir'),'ltr');await equipment.getByText(ar?'الحالة الفنية':'Condition',{exact:true}).first().waitFor();await equipment.scrollIntoViewIfNeeded();assert(await me.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await me.screenshot({path:process.env.TEMP+'/stanza-my-equipment-'+(ar?'ar':'en')+'-'+width+'.png',fullPage:true});await c.close();}console.log('PASS real employee equipment composition, independent condition labels and bilingual XL responsive presentation.');
 const cookies=await admin.context.cookies();
 for(const ar of [false,true])for(const width of [390,820,1440,1920])for(const preset of ['emerald','amethyst','custom','light'])for(const xl of [false,true]){
 const context=await browser.newContext({viewport:{width,height:width===390?844:1000},reducedMotion:xl?'reduce':'no-preference',serviceWorkers:'block'});await context.addCookies(cookies);
 await context.addInitScript(({ar,preset,xl})=>{localStorage.setItem('stanza.preferences.v1',JSON.stringify({tutorialsAutoStart:false,lanyardEnabled:false,backgroundPreset:preset==='light'?'emerald':preset,customTheme:{accent:'#bf52e5'},interfaceScale:xl?1.15:1,fontScale:xl?1.2:1}));localStorage.setItem('horizon-language',ar?'ar':'en');localStorage.setItem('horizon-theme',preset==='light'?'light':'dark');localStorage.setItem('stanza-demo-notice-seen','true');},{ar,preset,xl});
 const page=await context.newPage();page.setDefaultTimeout(15000);await page.goto(base);await page.locator('[data-tutorial-target=stanza-launcher]').waitFor();await navigate(page,ar?'الأصول والمعدات':'Assets & Equipment');await page.locator('.assets-row').first().waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(preset==='emerald'&&!xl)await page.screenshot({path:process.env.TEMP+'/stanza-assets-list-'+(ar?'ar':'en')+'-'+width+'.png',fullPage:true});
 await search(page,assets[1].assetTag);const chosen=page.locator('.assets-row').filter({has:page.getByText(assets[1].assetTag,{exact:true})});await chosen.waitFor();await chosen.click();const d=page.locator('.assets-detail');await d.locator('.assets-facts').first().getByText('Assets fixture holder',{exact:true}).waitFor();assert.equal(await chosen.getAttribute('aria-pressed'),'true');
 assert(await d.evaluate((el:HTMLElement)=>el.getBoundingClientRect().width<=innerWidth));assert.equal(await d.getAttribute('dir'),ar?'rtl':'ltr');assert.equal(await chosen.locator('bdi').getAttribute('dir'),'ltr');
 await d.getByText(ar?'سجل الإسناد والحالة الفنية':'Assignment and condition history',{exact:true}).click();await d.getByText(ar?'نشاط الدعم':'Support activity',{exact:true}).click();await d.getByRole('button',{name:'Owned battery issue',exact:false}).waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await d.getByRole('button',{name:ar?'تعديل الأصل':'Edit asset',exact:true}).click();const form=page.getByRole('dialog');await form.waitFor();assert(await page.evaluate(()=>{const dialog=document.querySelector('dialog')!;const before=document.activeElement;document.querySelector<HTMLElement>('[data-tutorial-target=stanza-launcher]')!.focus();return dialog.open&&document.activeElement===before;}),'native modal makes background controls inert');for(let i=0;i<14;i++){await page.keyboard.press('Tab');assert(await page.evaluate(()=>{const d=document.querySelector('dialog')!;return d.open&&(d.contains(document.activeElement)||document.activeElement===document.body);}),'Tab never enters background application controls');}await page.keyboard.press('Escape');await form.waitFor({state:'detached'});
 if(xl)assert.equal(await chosen.evaluate((el:HTMLElement)=>getComputedStyle(el).transitionDuration),'0s');
 await page.screenshot({path:process.env.TEMP+'/stanza-assets-'+(ar?'ar':'en')+'-'+width+'-'+preset+'-'+(xl?'xl':'normal')+'.png',fullPage:true});if(width===390&&xl){await d.getByText(ar?'رمز QR / التعريف':'QR / identification',{exact:true}).click();const qr=d.locator('.asset-qr-print svg');await qr.waitFor();await qr.scrollIntoViewIfNeeded();assert((await qr.boundingBox())!.width>=160);assert.equal(await d.locator('.asset-qr-print').evaluate((el:HTMLElement)=>getComputedStyle(el).backgroundColor),'rgb(255, 255, 255)','printable label retains white background in custom themes');assert.equal(await d.locator('.asset-qr-print p').first().evaluate((el:HTMLElement)=>getComputedStyle(el).color),'rgb(6, 20, 17)','printed asset identifier remains readable');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await d.getByRole('button',{name:ar?'تنزيل SVG':'Download SVG',exact:true}).waitFor();await page.screenshot({path:process.env.TEMP+'/stanza-assets-qr-'+(ar?'ar':'en')+'-'+preset+'-xl.png',fullPage:true});}matrix++;await context.close();if(matrix%8===0)console.log('PASS responsive/theme/RTL/scale/focus matrix',matrix);
 }
 // Existing Add to Workspace default / alternate selection, using normal UI and persisted browser preferences.
 const key='stanza.composer.v1:'+encodeURIComponent(admin.user.tenantId)+':'+encodeURIComponent(admin.user.id);
 await p.evaluate((key:string)=>localStorage.setItem(key,JSON.stringify({version:1,activeId:'asset-active',surface:'auto',workspaces:[{id:'asset-active',name:'Active assets',widgets:[]},{id:'asset-alternate',name:'Alternate assets',widgets:[]}]})),key);
 await p.reload();await p.locator('[data-tutorial-target=stanza-launcher]').waitFor();await navigate(p,'Assets & Equipment');
 await p.getByRole('button',{name:'Add to Workspace',exact:true}).first().click();dialog=p.getByRole('dialog');let workspace=dialog.getByRole('combobox',{name:'Workspace',exact:true});assert.equal(await workspace.inputValue(),'asset-active');await dialog.getByRole('button',{name:'Add widget',exact:true}).click();
 await p.getByRole('button',{name:'Add to Workspace',exact:true}).first().click();dialog=p.getByRole('dialog');workspace=dialog.getByRole('combobox',{name:'Workspace',exact:true});await workspace.selectOption('asset-alternate');await dialog.getByRole('button',{name:'Add widget',exact:true}).click();
 let stored=await p.evaluate((key:string)=>JSON.parse(localStorage.getItem(key)!),key);assert.equal(stored.activeId,'asset-active');assert.equal(stored.workspaces[0].widgets.length,1);assert.equal(stored.workspaces[1].widgets.length,1);
 await p.reload();await p.locator('[data-tutorial-target=stanza-launcher]').waitFor();await navigate(p,'Workspace Composer');await p.locator('.composer-widget').waitFor();assert.equal(await p.locator('.composer-widget .assets-panel').count(),0);console.log('PASS active/alternate Workspace destination and persisted compact inventory widget.');
 await navigate(p,'Assets & Equipment');await p.locator('.assets-row').first().waitFor();await p.locator('.assets-row').first().click();await p.locator('.assets-detail h3').waitFor();
 let calls=0;const count=(r:any)=>{if(new URL(r.url()).pathname.startsWith('/api/hr/assets')||new URL(r.url()).pathname.startsWith('/api/support'))calls++;};
 await p.waitForTimeout(800);p.on('request',count);await p.waitForTimeout(35000);p.off('request',count);assert.equal(calls,0);console.log('PASS 35-second Assets detail idle: zero Assets / Support requests; matrix',matrix);
}catch(error){for(const c of browser.contexts())for(const page of c.pages())await page.screenshot({path:process.env.TEMP+'/stanza-assets-failure-'+browser.contexts().indexOf(c)+'.png',fullPage:true}).catch(()=>{});throw error;}
finally{
 await browser.close();
 for(const id of tenants)assert.equal((await db.query('SELECT company_name FROM tenants WHERE id=$1',[id])).rows[0]?.company_name,'Assets polish fixture '+tag);
 for(const table of ['support_tickets','asset_condition_reports','asset_assignments','qr_access_tokens','assets'])await db.query(`DELETE FROM ${table} WHERE tenant_id=ANY($1::uuid[])`,[tenants]);
 await db.query('DELETE FROM tenants WHERE id=ANY($1::uuid[])',[tenants]);assert.equal(Number((await db.query('SELECT count(*) FROM tenants WHERE id=ANY($1::uuid[])',[tenants])).rows[0].count),0);console.log('Owned Assets fixtures cleaned; zero fixture tenants remain.');await db.end();
}
