import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { readCoordinates } from '../src/server/attendance/attendance-policy';
assert.throws(()=>readCoordinates({},'required'),/required/);
assert.throws(()=>readCoordinates({latitude:null,longitude:null},'required'),/required/);
assert.throws(()=>readCoordinates({latitude:91,longitude:0},'optional'),/Latitude/);
assert.throws(()=>readCoordinates({latitude:true,longitude:0},'optional'),/Invalid/);
assert.equal(readCoordinates({},'optional'),null);
assert.equal(readCoordinates({latitude:30,longitude:31},'disabled'),null);
assert.deepEqual(readCoordinates({latitude:30,longitude:31},'required'),{latitude:30,longitude:31});
const ui=readFileSync('src/components/attendance/AttendanceWorkspace.tsx','utf8');
assert.match(ui,/stanza-theme-primary stanza-geo-break-primary/);
assert.match(ui,/document.hidden/);
assert.match(ui,/clearInterval/);
assert.doesNotMatch(ui,/requestAnimationFrame/);
assert.match(ui,/r.canReview/);
assert.match(ui,/maximum_uses/);
console.log('PASS attendance coordinate validation, disabled privacy and finite UI lifecycle contracts');

import {formatAttendanceDuration} from '../src/lib/attendance-duration';
import {assertAttendanceIdentity,attendanceNote,validateDeparture} from '../src/server/attendance/attendance-state';
assert.equal(formatAttendanceDuration(65*60),'1 hour 5 minutes');
assert.equal(formatAttendanceDuration(120*60),'2 hours');
assert.equal(formatAttendanceDuration(60),'1 minute');
assert.equal(formatAttendanceDuration(0),'0 minutes');
assert.equal(formatAttendanceDuration(-60),'0 minutes');
assert.equal(formatAttendanceDuration(3600,'ar'),'ساعة');
assert.equal(formatAttendanceDuration(7200,'ar'),'ساعتان');
assert.equal(formatAttendanceDuration(120,'ar'),'دقيقتان');
assert.equal(formatAttendanceDuration(65*60,'ar'),'ساعة و٥ دقائق');
assert.equal(formatAttendanceDuration(0,'ar'),'٠ دقيقة');
assert.throws(()=>assertAttendanceIdentity({employeeId:'other'},{tenantId:'t',employeeId:'self'}),/own account/);
assert.throws(()=>assertAttendanceIdentity({tenantId:'other'},{tenantId:'t',employeeId:'self'}),/own account/);
assert.equal(attendanceNote('  '),null);assert.throws(()=>attendanceNote('a'.repeat(501)),/500/);
const state={serverNow:new Date('2027-01-01T23:00:00Z'),scheduledEnd:new Date('2027-01-02T03:00:00Z'),effectiveEnd:new Date('2027-01-02T03:00:00Z')};
assert.equal(validateDeparture('2027-01-02T01:30:00Z',state,new Date('2027-01-01T21:00:00Z')).earlySeconds,5400);
assert.throws(()=>validateDeparture('2027-01-02T04:00:00Z',state,new Date('2027-01-01T21:00:00Z')),/departure/);
assert.throws(()=>validateDeparture('2027-01-02T01:30:00',state,new Date('2027-01-01T21:00:00Z')),/valid/);
console.log('PASS shared English/Arabic durations, identity guards, optional notes and overnight authoritative departure validation');

import {getPermissionDefinition} from '../src/server/organisation/permission-registry';
import {managerPermissions} from './demo/organisation';
assert(getPermissionDefinition('attendance.early_leave.review')?.allowedScopeTypes.includes('direct_reports'));
assert(managerPermissions.includes('attendance.early_leave.review'));
