import {createRequire} from 'node:module';
import './router-env';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import {getMigrationPool} from './migration-pool';
import { assertDatabaseMutationSafety, assertHttpMutationSafety } from './mutation-safety';
import { getDbPool, getHrQueue } from '../src/lib/hr-background';
const base=assertHttpMutationSafety(process.env.ATTENDANCE_TEST_BASE_URL||'http://localhost:3001','Attendance instrument browser');
assertDatabaseMutationSafety(process.env.DATABASE_URL,'Attendance instrument browser');
const pool=getMigrationPool();
const tenants:string[]=[];const password=crypto.randomBytes(20).toString('base64url');const tag=crypto.randomUUID();
type Person={id:string;tenantId:string;email:string;cookie:string};
async function call(u:Person|null,path:string,body?:unknown,method='POST',origin=base) {
 const r=await fetch(base+path,{method:body===undefined?'GET':method,headers:{...(u?{Cookie:u.cookie}:{}),Origin:origin,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 assert.match(r.headers.get('content-type') || '', /^application\/json\b/, `${path} must return API JSON, not the SPA document`);
 return {status:r.status,body:await r.json()};
}
async function ok(u:Person,path:string,body?:unknown,method='POST') {const r=await call(u,path,body,method);assert(r.status<300,`${path}: ${r.status} ${JSON.stringify(r.body)}`);return r.body;}
async function person(tenantId:string,name:string,permissions:string[],scope='company',manager?:Person):Promise<Person> {
 const email=`${name}-${tag}@example.invalid`;
 const row=(await pool.query(`INSERT INTO employees(tenant_id,email,full_name,password_hash,role,manager_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[tenantId,email,'Instrument test '+name,await bcrypt.hash(password,10),name==='admin'?'hr_admin':name==='manager'?'manager':'employee',manager?.id||null])).rows[0];
 const role=(await pool.query(`INSERT INTO tenant_roles(tenant_id,name) VALUES($1,$2) RETURNING id`,[tenantId,name])).rows[0];
 for(const permission of permissions)await pool.query('INSERT INTO tenant_role_permissions(tenant_id,role_id,permission_key) VALUES($1,$2,$3)',[tenantId,role.id,permission]);
 await pool.query('INSERT INTO employee_role_assignments(tenant_id,employee_id,role_id,scope_type) VALUES($1,$2,$3,$4)',[tenantId,row.id,role.id,scope]);
 const r=await fetch(base+'/api/auth/login',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:JSON.stringify({email,password})});assert.equal(r.status,200,'Fixture login');const signedIn=(await r.json()).user;assert.equal(signedIn.tenantId,tenantId,'Fixture cookie must belong to the intended tenant');assert.equal(signedIn.id,row.id,'Fixture cookie must belong to the intended employee');
 return {id:row.id,tenantId,email,cookie:r.headers.get('set-cookie')!.split(';')[0]};
}
const {chromium}=createRequire(import.meta.url)(process.env.BROWSER_PLAYWRIGHT_MODULE||'C:/Users/10/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'});
try {
 const tenant=(await pool.query('INSERT INTO tenants(slug,company_name) VALUES($1,$2) RETURNING id',['attendance-instrument-'+tag,'Attendance instrument fixture'])).rows[0].id;tenants.push(tenant);
 const emp=await person(tenant,'employee',['attendance.clock']);const denied=await person(tenant,'denied',[]);
 await pool.query(`INSERT INTO company_locations(tenant_id,name,latitude,longitude,boundary) VALUES($1,'Instrument geofence',30,31,ST_Buffer(ST_SetSRID(ST_MakePoint(31,30),4326)::geography,1000)::geometry)`,[tenant]);
 async function pageFor(u=emp,width=1440,ar=false,xl=false,preset='emerald',light=false,reduce=false){const c=await browser.newContext({viewport:{width,height:width<500?844:1000},deviceScaleFactor:2,serviceWorkers:'block',reducedMotion:reduce?'reduce':'no-preference',geolocation:{latitude:30,longitude:31},permissions:['geolocation']});await c.addCookies([{name:u.cookie.split('=')[0],value:u.cookie.substring(u.cookie.indexOf('=')+1),url:base}]);await c.addInitScript(({ar,xl,preset,light})=>{localStorage.setItem('stanza.preferences.v1',JSON.stringify({tutorialsAutoStart:false,lanyardEnabled:false,desktopNavigationMode:'rail',backgroundPreset:preset,customTheme:{accent:'#398bfa'},interfaceScale:xl?1.15:1,fontScale:xl?1.2:1}));localStorage.setItem('stanza-demo-notice-seen','true');localStorage.setItem('horizon-language',ar?'ar':'en');localStorage.setItem('horizon-theme',light?'light':'dark');},{ar,xl,preset,light});const p=await c.newPage();p.setDefaultTimeout(15000);await p.goto(base);await p.locator('.attendance-terminal').waitFor();await p.waitForTimeout(600);return p;}
 async function bounds(p:any){const b=p.locator('.attendance-terminal');const core=b.locator('.attendance-terminal-core');assert.equal(await core.evaluate((e:HTMLElement)=>e.scrollHeight<=e.clientHeight+1&&e.scrollWidth<=e.clientWidth+1),true,'All action labels fit their face');assert.equal(await p.locator('.attendance-primary').evaluate((e:HTMLElement)=>e.scrollWidth<=e.clientWidth+1),true);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await b.evaluate((e:HTMLElement)=>e.getAnimations({subtree:true}).filter(a=>a.effect?.getComputedTiming().iterations===Infinity).length),0);}
 async function capture(p:any,name:string){await bounds(p);await p.screenshot({path:process.env.TEMP+'/stanza-instrument-'+name+'-page.png',scale:'css'});await p.locator('.attendance-primary').screenshot({path:process.env.TEMP+'/stanza-instrument-'+name+'-group.png',scale:'css'});await p.locator('.attendance-terminal').screenshot({path:process.env.TEMP+'/stanza-instrument-'+name+'-2x.png'});}
 const p=await pageFor();const b=p.locator('.attendance-terminal');await p.getByRole('heading',{name:'Ready to clock in',exact:true}).waitFor();await capture(p,'ready-green');
 await b.evaluate((e:any)=>{e.pointer={enter:0,leave:0};e.addEventListener('pointerenter',()=>e.pointer.enter++);e.addEventListener('pointerleave',()=>e.pointer.leave++);});await p.mouse.move(1,1);const rect=await b.boundingBox();await p.mouse.move(rect!.x+rect!.width/2,rect!.y+rect!.height-2);for(let i=0;i<55;i++){await p.waitForTimeout(100);assert.deepEqual(await b.boundingBox(),rect);assert.deepEqual(await b.evaluate((e:any)=>e.pointer),{enter:1,leave:0});}await capture(p,'hover-5s');await p.mouse.down();await p.waitForTimeout(140);assert.deepEqual(await b.boundingBox(),rect);await capture(p,'press');await b.evaluate((e:HTMLElement)=>e.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();},{capture:true,once:true}));await p.mouse.up();await p.mouse.move(1,1);await b.focus();await p.keyboard.press('Tab');await p.keyboard.press('Shift+Tab');assert(await b.evaluate((e:HTMLElement)=>e.matches(':focus-visible')));await capture(p,'focus');
 const session=await p.context().newCDPSession(p);await session.send('Performance.enable');const start=(await session.send('Performance.getMetrics')).metrics;let requests=0;const network=(r:any)=>{if(/\/api\/(attendance|clock-status|clock-in|clock-out|break-requests)/.test(r.url()))requests++;};p.on('request',network);await p.waitForTimeout(35000);p.off('request',network);const end=(await session.send('Performance.getMetrics')).metrics;const value=(m:any[],n:string)=>m.find((x:any)=>x.name===n)?.value||0;const scriptMs=1000*(value(end,'ScriptDuration')-value(start,'ScriptDuration'));assert.equal(requests,0,'Attendance stays network quiet');assert(scriptMs<100,'No idle scripting loop');console.log('PASS 5.5-second hover: 55 identical rectangles, one entry/no exits; press/focus; idle 35s',{requests,scriptMs});
 // Hold only transport, then continue the real request to exercise authoritative loading and success.
 let release!:()=>void;const held=new Promise<void>(r=>release=r);await p.route('**/api/clock-in',async(route:any)=>{await held;await route.continue();},{times:1});await b.click();await p.locator('.attendance-terminal[data-state=verifying]').waitFor();assert(await b.isDisabled());assert.deepEqual(await b.boundingBox(),rect);await capture(p,'loading-green');release();await p.locator('.attendance-terminal[data-state=success]').waitFor();await capture(p,'success-green');await p.getByRole('heading',{name:'Working',exact:true}).waitFor();await p.locator('.attendance-terminal[data-state=idle]').waitFor();assert.match(await b.innerText(),/CLOCK OUT/i);await capture(p,'working-green');
 for(const [theme,preset,light,ar,width,xl] of [['purple','amethyst',false,false,1440,false],['blue','custom',false,false,1440,false],['light','emerald',true,true,390,true]] as const){const q=await pageFor(emp,width,ar,xl,preset,light);await q.getByRole('heading',{name:ar?'في العمل':'Working',exact:true}).waitFor();await capture(q,'working-'+theme);await q.context().close();}
 await b.click();await p.locator('.attendance-terminal[data-state=clocked_out]').waitFor();await p.locator('.attendance-terminal[data-state=idle]').waitFor();await p.getByRole('heading',{name:'Ready to clock in',exact:true}).waitFor();
 for(const [theme,preset,light,ar,width,xl] of [['green','emerald',false,false,1440,false],['purple','amethyst',false,false,1440,false],['blue','custom',false,true,390,true],['light','emerald',true,true,390,true]] as const){const q=await pageFor(emp,width,ar,xl,preset,light);await q.context().setGeolocation({latitude:0,longitude:0});await q.locator('.attendance-terminal').click();await q.locator('.attendance-terminal[data-state=outside_geofence]').waitFor();await capture(q,'error-'+theme);assert.equal((await ok(emp,'/api/clock-status')).isClockedIn,false,'Rejected location cannot create attendance');await q.context().close();}
 const disabled=await pageFor(denied,390,true,true,'emerald',true,true);assert(await disabled.locator('.attendance-terminal').isDisabled());assert.equal((await call(denied,'/api/clock-in',{latitude:30,longitude:31})).status,403);await capture(disabled,'disabled-arabic-light');await disabled.context().close();console.log('PASS real loading, verified, working, clock-out, four-theme geofence errors and API permission denial');
 let count=0;for(const [w,width] of [1920,1440,820,390].entries())for(const xl of [false,true])for(const ar of [false,true]){const index=(w+(xl?2:0)+(ar?1:0))%4;const preset=['emerald','amethyst','custom','emerald'][index],light=index===3,reduce=xl&&ar;const q=await pageFor(emp,width,ar,xl,preset,light,reduce);await q.getByRole('heading',{name:ar?'جاهز لتسجيل الحضور':'Ready to clock in',exact:true}).waitFor();await capture(q,`ready-${width}-${xl}-${ar}-${preset}-${light}`);const button=q.locator('.attendance-terminal'),box=await button.boundingBox();await button.hover();await q.waitForTimeout(180);assert.deepEqual(await button.boundingBox(),box);await button.focus();await q.keyboard.press('Tab');await q.keyboard.press('Shift+Tab');assert(await button.evaluate((e:HTMLElement)=>e.matches(':focus-visible')));const core=button.locator('.attendance-terminal-core');if(reduce){assert.equal(await core.evaluate((e:HTMLElement)=>getComputedStyle(e).transitionDuration),'0s');}assert.equal(await q.evaluate(()=>document.documentElement.dir),ar?'rtl':'ltr');const state=await q.locator('.attendance-status-context').boundingBox();if(width===390)assert(box!.y>=state!.y+state!.height);await q.context().close();count++;}console.log('PASS '+count+' normal/XL English/Arabic pages at 1920/1440/820/390, all four themes, reduced motion, accepted composition');
 // Existing Appearance editor only: no Passkey section or behavior is exercised here.
 await p.bringToFront();await p.getByRole('button',{name:'Settings',exact:true}).click();await p.getByRole('button',{name:/Appearance/i}).click();await p.getByRole('radio',{name:'Custom',exact:true}).click();const picker=p.locator('.stanza-studio-fields').first().locator('input[type=color]').first();await picker.scrollIntoViewIfNeeded();await p.waitForTimeout(500);await p.evaluate(()=>{(window as any).writes=0;const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='stanza.preferences.v1')(window as any).writes++;return set.call(this,k,v);};});const before=(await session.send('Performance.getMetrics')).metrics;await picker.evaluate(async(e:HTMLInputElement)=>{const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!;for(let i=0;i<240;i++){set.call(e,'#'+((i*7919+123456)%0xffffff).toString(16).padStart(6,'0'));e.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(r=>setTimeout(r,8));}e.dispatchEvent(new Event('change',{bubbles:true}));});await p.waitForTimeout(650);const after=(await session.send('Performance.getMetrics')).metrics;const writes=await p.evaluate(()=>(window as any).writes);assert(writes<=2);console.log('PASS Theme picker 240 inputs',{writes,scriptMs:1000*(value(after,'ScriptDuration')-value(before,'ScriptDuration'))});
} catch(error){for(const c of browser.contexts())for(const p of c.pages())await p.screenshot({path:process.env.TEMP+'/stanza-instrument-failure-'+browser.contexts().indexOf(c)+'.png',scale:'css',fullPage:true}).catch(()=>{});throw error;}
finally{await browser.close();const queue=getHrQueue();for(const job of await queue.getJobs(['wait','delayed','completed','failed'],0,-1))if(tenants.includes(job.data?.tenantId))await job.remove();await queue.close();for(const t of tenants)await pool.query('DELETE FROM tenants WHERE id=$1',[t]);await pool.end();await getDbPool()?.end();}
