import assert from 'node:assert/strict';
import sharp from 'sharp';
import {BusinessFixtures} from './business-scenario-fixtures';
import {wrapStanzaDocument,validateFeedEditorDocument} from '../src/lib/stanza-document';
import {companyFeedImageStorage} from '../src/lib/company-feed-image-storage';
const f=new BusinessFixtures();
const node=(type:string,children:any[]=[],extra:any={})=>({type,version:1,format:'',indent:0,direction:null,children,...extra});
const text=(value:string)=>({type:'text',version:1,text:value,format:0,detail:0,mode:'normal',style:''});
const para=(value:string)=>node('paragraph',[text(value)]);
try {
 await f.setup('privacy-publication');const {admin,employee,limited,foreign}=f;
 const body='PRIVATE GRIEVANCE BODY '+f.tag,note='PRIVATE INTERNAL REVIEW '+f.tag,title='Scenario confidential case';
 const ep=await f.page(employee);await f.navigate(ep,'Grievances');await ep.getByRole('button',{name:'Submit grievance',exact:true}).click();await ep.getByLabel('Subject',{exact:true}).fill(title);await ep.getByLabel('Detailed description',{exact:true}).fill(body);await ep.getByLabel(/^Confidentiality/).selectOption('confidential');const submitted=ep.waitForResponse((r:any)=>new URL(r.url()).pathname==='/api/grievances'&&r.request().method()==='POST');await ep.getByRole('button',{name:'Submit case',exact:true}).click();assert.equal((await submitted).status(),201);await ep.getByText(body,{exact:true}).waitFor();
 let grievance=(await f.ok(employee,'/api/grievances/me')).grievances[0];
 await f.ok(admin,`/api/grievances/${grievance.id}/messages`,{version:grievance.version,kind:'internal',body:note});
 const own=await f.ok(employee,`/api/grievances/${grievance.id}`);assert(!JSON.stringify(own).includes(note));assert(JSON.stringify(own).includes(body));
 assert(JSON.stringify(await f.ok(admin,`/api/grievances/${grievance.id}`)).includes(note));
 for(const actor of [limited,foreign]){const r=await f.api(actor,`/api/grievances/${grievance.id}`);assert.equal(r.status,404);assert(!JSON.stringify(r.body).includes(body));assert(!JSON.stringify(r.body).includes(note));}
 const people=await f.ok(limited,'/api/hr/organisation/people');assert(!JSON.stringify(people).includes(title));assert(!JSON.stringify(people).includes(body));assert(!Object.keys(people.people.find((p:any)=>p.id===employee.id)).some(k=>/grievance|complaint/i.test(k)));
 const lp=await f.page(limited);await f.navigate(lp,'Organisation');await lp.locator('[data-tutorial-target=organisation-workspace]').getByRole('button',{name:'People & Hierarchy',exact:true}).click();await lp.locator('.people-search input').fill('Scenario Employee');await lp.locator('.people-open').first().click();let dialog=lp.getByRole('dialog');await dialog.getByText('Scenario Employee',{exact:true}).first().waitFor();assert(!((await dialog.innerText()).includes(title)));assert(!((await dialog.innerText()).includes(body)));assert(!((await dialog.innerText()).includes(note)));await f.shot(lp,'people-grievance-boundary');await lp.keyboard.press('Escape');
 const query="show me Scenario Employee's grievance";
 const reviewed=(await f.ok(admin,'/api/command-router/resolve',{query,allowReasoning:false})).result;assert.equal(reviewed.intentKey,'employee_grievance_lookup');assert.equal(reviewed.entityRoute.status,'resolved');assert.equal(reviewed.fallbackUsed,false);
 for(const actor of [limited,foreign]){const r=await f.ok(actor,'/api/command-router/resolve',{query,allowReasoning:false});assert(!JSON.stringify(r).includes(body));assert(!JSON.stringify(r).includes(note));assert(!JSON.stringify(r).includes(grievance.id));}
 const metrics=await f.ok(admin,'/api/command-router/metrics');assert(!JSON.stringify(metrics).includes(query));assert(!JSON.stringify(metrics).includes(body));assert(!JSON.stringify(metrics).includes(note));
 const gp=await f.page(admin);await f.navigate(gp,'Grievances');await gp.getByRole('button',{name:'Case Inbox',exact:true}).click();await gp.getByRole('button',{name:new RegExp(title)}).click();await gp.getByText(note,{exact:true}).waitFor();await ep.reload();await f.navigate(ep,'Grievances');await ep.getByRole('button',{name:new RegExp(title)}).click();assert.equal(await ep.getByText(note,{exact:true}).count(),0);console.log('PASS E actual grievance submit/review → own/People/router/telemetry/foreign boundaries; recognition grants no access');
 // Advanced publication begins as an author-private, versioned draft with a private image.
 const png=await sharp({create:{width:240,height:120,channels:3,background:'#10b981'}}).png().toBuffer();const upload=await admin.context.request.post(f.base+'/api/company-feed/images',{headers:{Origin:f.base},multipart:{image:{name:'owned.png',mimeType:'image/png',buffer:png}}});assert.equal(upload.status(),201);const image=(await upload.json()).image;
 const doc=wrapStanzaDocument({root:node('root',[para('Scenario advanced publication body'),node('table',[node('tablerow',[node('tablecell',[para('Cross-module publication cell')],{colSpan:1,rowSpan:1,headerState:0})])],{colWidths:[180]}),{type:'stanza-sketch',version:1,drawing:{description:'Scenario static sketch',shapes:[{tool:'line',color:'#10b981',points:[[1,1],[20,20]]}]}},{type:'image',version:1,src:image.url,uploadId:image.id,altText:'Scenario private image',width:240,height:120,maxWidth:800,showCaption:false,caption:'',align:'center'}])});const valid=validateFeedEditorDocument(doc);assert(valid.ok,JSON.stringify(valid));
 const draft=(await f.ok(admin,'/api/me/company-feed/draft',{title:'Scenario advanced publication',contentText:valid.extractedText,contentJson:doc},'PUT')).draft;
 assert.equal((await employee.context.request.get(f.base+image.url)).status(),404);assert.equal((await f.api(employee,'/api/me/company-feed/draft')).status,403);assert(!(await f.ok(employee,'/api/company-feed')).posts.length);assert.equal((await f.ok(foreign,'/api/me/company-feed/draft')).draft,null);
 await gp.goto(f.base);await f.navigate(gp,'Company Feed');const canvas=gp.locator('.stanza-feed-editor-surface');await canvas.waitFor();await gp.getByPlaceholder('Post title',{exact:true}).fill('Scenario advanced publication');
 // Real editor autosave, followed by real publication through the UI.
 await canvas.focus();await gp.keyboard.press('Control+End');await gp.keyboard.type(' Autosaved publication ending');await gp.waitForFunction(()=>document.querySelector('.stanza-feed-editor-surface')?.textContent?.includes('Autosaved publication ending'));
 await gp.waitForTimeout(1800);const saved=(await f.ok(admin,'/api/me/company-feed/draft')).draft;assert(saved.contentText.includes('Autosaved publication ending'));assert(saved.version>draft.version);
 assert.equal((await f.api(admin,'/api/me/company-feed/draft',{title:'Stale overwrite',contentText:valid.extractedText,contentJson:doc,expectedVersion:draft.version},'PUT')).status,409);
 await gp.getByRole('button',{name:'Publish Post',exact:true}).click();await gp.waitForTimeout(1000);const publication=(await f.ok(employee,'/api/company-feed')).posts.find((p:any)=>p.title==='Scenario advanced publication');assert(publication);assert.equal((await f.ok(admin,'/api/me/company-feed/draft')).draft,null);assert.equal((await employee.context.request.get(f.base+image.url)).status(),200);assert.equal((await foreign.context.request.get(f.base+image.url)).status(),404);
 const chunks:string[]=[];const rp=await employee.context.newPage();rp.setDefaultTimeout(20000);rp.on('request',(r:any)=>{if(new URL(r.url()).pathname.startsWith('/assets/'))chunks.push(r.url());});await rp.goto(f.base);await f.navigate(rp,'Company Feed');await rp.getByRole('button',{name:'Read: Scenario advanced publication',exact:true}).click();dialog=rp.getByRole('dialog');await dialog.locator('table').waitFor();await dialog.getByAltText('Scenario private image',{exact:true}).waitFor();await dialog.getByRole('img',{name:'Scenario static sketch',exact:true}).waitFor();assert(!chunks.some(u=>/RichTextEditor|AdvancedTools|SketchEditor/.test(u)));assert.equal(await rp.locator('.stanza-feed-editor-surface').count(),0);await f.shot(rp,'lightweight-publication');await rp.keyboard.press('Escape');
 assert.equal((await f.api(admin,'/api/company-feed/posts',{title:'Unsupported document',contentText:valid.extractedText,contentJson:{...doc,documentVersion:99},status:'published',visibility:[{type:'all'}]})).status,400);
 // Use a real active service worker and inspect CacheStorage, rather than an empty disabled cache.
 const offline=await f.browser.newContext({serviceWorkers:'allow'});await offline.addCookies(await employee.context.cookies());await offline.addInitScript(()=>{localStorage.setItem('stanza-demo-notice-seen','true');localStorage.setItem('stanza.preferences.v1',JSON.stringify({tutorialsAutoStart:false,lanyardEnabled:false}));});const op=await offline.newPage();await op.goto(f.base);await op.evaluate(()=>navigator.serviceWorker.ready);await f.navigate(op,'Company Feed');await op.locator('.company-feed-item').waitFor();assert.equal(await op.evaluate(async()=>{let n=0;for(const key of await caches.keys())for(const r of await(await caches.open(key)).keys())if(new URL(r.url).pathname.startsWith('/api/'))n++;return n;}),0);await offline.close();
 await f.audit(['company_feed.draft.published']);console.log('PASS F real private rich draft/autosave/stale protection → browser publication → ordinary lightweight table/sketch/image renderer; private image authorization and active service-worker API cache exclusion');
 // Persist multiple domains through actual add/switch/destination controls.
 const key=`stanza.composer.v1:${encodeURIComponent(f.primary)}:${encodeURIComponent(admin.id)}`;
 await gp.evaluate((key:string)=>localStorage.setItem(key,JSON.stringify({version:1,activeId:'business-active',surface:'auto',workspaces:[{id:'business-active',name:'Business active',widgets:[]},{id:'business-alternate',name:'Business alternate',widgets:[]},{id:'business-empty',name:'Business empty',widgets:[]}]})),key);
 await gp.reload();await f.navigate(gp,'Hiring');await gp.getByRole('button',{name:'Add to Workspace',exact:true}).first().click();dialog=gp.getByRole('dialog');if(await dialog.getByRole('combobox',{name:'Widget',exact:true}).count())await dialog.getByRole('combobox',{name:'Widget',exact:true}).selectOption('hiring');await dialog.getByRole('button',{name:'Add widget',exact:true}).click();
 await f.navigate(gp,'IT & equipment support');await gp.getByRole('button',{name:'Add to Workspace',exact:true}).first().click();dialog=gp.getByRole('dialog');await dialog.getByRole('combobox',{name:'Workspace',exact:true}).selectOption('business-alternate');await dialog.getByRole('button',{name:'Add widget',exact:true}).click();
 let state=await gp.evaluate((key:string)=>JSON.parse(localStorage.getItem(key)!),key);assert.equal(state.activeId,'business-active');assert.equal(state.workspaces[1].widgets.length,1);
 await f.navigate(gp,'Workspace Composer');await gp.locator('.composer').getByRole('button',{name:'+ Add Widget',exact:true}).first().click();await gp.locator('.composer-library button').filter({has:gp.getByText('Asset Inventory',{exact:true})}).click();await gp.locator('.composer-widget').last().waitFor();state=await gp.evaluate((key:string)=>JSON.parse(localStorage.getItem(key)!),key);assert.equal(state.workspaces[0].widgets.length,2);assert.equal(new Set(state.workspaces.flatMap((w:any)=>w.widgets.map((x:any)=>x.instanceId))).size,3);
 const persisted=JSON.stringify(state);await gp.reload();await f.navigate(gp,'Workspace Composer');assert.equal(JSON.stringify(await gp.evaluate((key:string)=>JSON.parse(localStorage.getItem(key)!),key)),persisted);await gp.getByRole('tab',{name:'Business alternate',exact:true}).click();assert.equal(await gp.locator('.composer-widget').count(),1);await gp.getByRole('tab',{name:'Business empty',exact:true}).click();await gp.locator('.composer-empty').waitFor();await f.shot(gp,'workspace-empty-continuity');
 const limitedKey=`stanza.composer.v1:${encodeURIComponent(f.primary)}:${encodeURIComponent(limited.id)}`;await lp.evaluate(({key})=>localStorage.setItem(key,JSON.stringify({version:1,activeId:'missing-workspace',surface:'auto',workspaces:[{id:'limited',name:'Limited',widgets:[{instanceId:'forged-grievance',widgetId:'grievances',x:0,y:0,width:6,height:5,config:{limit:5},surfaceOverride:'auto'}]}]})),{key:limitedKey});const forbiddenRequests:string[]=[];lp.on('request',(r:any)=>{if(new URL(r.url()).pathname==='/api/grievances')forbiddenRequests.push(r.url());});await lp.reload();await f.navigate(lp,'Workspace Composer');await lp.locator('.composer').waitFor();assert.equal(await lp.locator('.composer-widget').count(),1,'saved unavailable widget retains its shell without data');await lp.getByRole('status').filter({hasText:'This widget is unavailable with your current permissions.'}).waitFor();assert.equal(forbiddenRequests.length,0);assert(!((await lp.locator('.composer').innerText()).includes(title)));assert.equal(await lp.getByRole('tab',{name:'Limited',exact:true}).getAttribute('aria-selected'),'true','stale selection normalizes to an existing workspace');
 await gp.getByRole('tab',{name:'Business active',exact:true}).click();await gp.locator('.composer-widget').first().waitFor();await gp.waitForTimeout(1000);const requests:string[]=[];const record=(r:any)=>{const u=new URL(r.url()).pathname;if(u.startsWith('/api/'))requests.push(u);};gp.on('request',record);await gp.waitForTimeout(35000);gp.off('request',record);assert.equal(requests.length,0,'settled workspace should not poll any API');
 await rp.waitForTimeout(500);rp.on('request',record);requests.length=0;await rp.waitForTimeout(35000);rp.off('request',record);assert.equal(requests.filter(p=>p.includes('company-feed')).length,0);console.log('PASS H actual multi-domain widget controls, alternate destination, reload layout/identity, empty/stale recovery and permission filtering; 35-second settled Workspace/feed quiet');
} catch(e){console.error(e);for(const a of f.actors)for(const p of a.context.pages())await f.shot(p,'privacy-failure').catch(()=>{});throw e;}finally {
 for(const r of (await f.db.query('SELECT storage_key FROM company_feed_images WHERE tenant_id=ANY($1::uuid[])',[f.tenants])).rows)await companyFeedImageStorage.remove(r.storage_key);await f.cleanup();
}
