import assert from 'node:assert/strict';
import bcrypt from 'bcryptjs';
import {PDFDocument} from 'pdf-lib';
import {withTenant} from '../src/lib/hr-background';
import {createHiredEmployee} from '../src/server/hiring/employee-onboarding';
import {BusinessFixtures} from './business-scenario-fixtures';
const f=new BusinessFixtures();
try {
 await f.setup('hiring-equipment');
 const {admin,foreign,limited}=f;
 const job=(await f.ok(admin,'/api/hiring/jobs',{title:'Scenario Engineer',description:'Disposable integrated business workflow',managerId:admin.id,ownerId:admin.id,employmentType:'full_time',headcount:'1'})).job;
 await f.ok(admin,`/api/hiring/jobs/${job.id}/status`,{status:'open'});
 const applicantPage=await f.publicContext.newPage();await applicantPage.goto(f.base+'/careers/'+job.public_token);
 const name='Sarah Scenario',email=`hire-${f.tag}@example.invalid`;
 await applicantPage.getByLabel('Full name',{exact:true}).fill(name);await applicantPage.getByLabel('Email',{exact:true}).fill(email);
 const pdf=await PDFDocument.create();pdf.addPage();await applicantPage.locator('input[type=file]').setInputFiles({name:'fictional.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())});
 await applicantPage.locator('input[name=consent]').check();await applicantPage.getByRole('button',{name:'Submit application',exact:true}).click();await applicantPage.getByText('Application received. Thank you.',{exact:true}).waitFor();
 const candidate=(await f.db.query('SELECT * FROM hiring_applicants WHERE tenant_id=$1 AND job_id=$2',[f.primary,job.id])).rows[0];assert(candidate);
 assert.equal((await f.api(foreign,`/api/hiring/applicants/${candidate.id}/workflow`)).status,404);
 await f.ok(admin,`/api/hiring/applicants/${candidate.id}/reviews`,{recommendation:'hold',score:3,notes:'Reviewed required skills'});
 for(const targetStage of ['screening','hr_review','hiring_manager_review','interview','final_review','offer'])await f.ok(admin,`/api/hiring/applicants/${candidate.id}/stage`,{targetStage});
 const interview=await f.ok(admin,`/api/hiring/applicants/${candidate.id}/interviews`,{startsAt:new Date(Date.now()+3600000).toISOString(),endsAt:new Date(Date.now()+7200000).toISOString(),timezone:'Africa/Cairo',location:'Fixture meeting room',attendeeIds:[admin.id],interviewType:'Technical'});
 await f.ok(admin,`/api/hiring/interviews/${interview.interview.id}/evaluations`,{recommendation:'yes',score:'4',notes:'Private candidate evaluation'});
 const dates={startDate:new Date(Date.now()+86400000).toISOString().slice(0,10),expiresOn:new Date(Date.now()+7*86400000).toISOString().slice(0,10)};
 const offer=(await f.ok(admin,`/api/hiring/applicants/${candidate.id}/offers`,{salary:'5000',currency:'EGP',...dates})).offer;
 const old=await f.ok(admin,`/api/hiring/offers/${offer.id}/candidate-link`,{confirmed:true});
 const revised=(await f.ok(admin,`/api/hiring/offers/${offer.id}/revise`,{version:1,salary:'5500',currency:'EGP',...dates,notes:'Reviewed terms'})).offer;
 assert.equal((await f.api(null,'/api/public'+old.path)).status,404);
 const message=(await f.ok(admin,`/api/hiring/applicants/${candidate.id}/message`,{subject:'Fixture offer',body:'No external delivery is performed'})).message;
 // Delivery evidence is explicitly a fixture. All acceptance/conversion paths are real; no external email.
 await f.db.query("UPDATE communication_messages SET status='sent',sent_at=now() WHERE tenant_id=$1 AND id=$2",[f.primary,message.id]);
 await f.ok(admin,`/api/hiring/offers/${revised.id}/status`,{status:'sent',messageId:message.id});
 const link=await f.ok(admin,`/api/hiring/offers/${revised.id}/candidate-link`,{confirmed:true});
 await applicantPage.goto(f.base+link.path);await applicantPage.getByLabel('I reviewed this version and acknowledge my decision.',{exact:true}).check();await applicantPage.getByRole('button',{name:'Accept this offer',exact:true}).click();await applicantPage.getByRole('status').filter({hasText:/accepted/i}).waitFor();
 assert.equal((await f.db.query('SELECT hired_employee_id FROM hiring_applicants WHERE id=$1',[candidate.id])).rows[0].hired_employee_id,null,'public acceptance must not hire');
 assert.equal((await f.api(admin,`/api/hiring/applicants/${candidate.id}/hire`,{confirmed:false})).status,400);
 // Exercise the real conversion service and its transaction rollback before the normal confirmed hire.
 let rolledBackEmployee:string|undefined;
 await assert.rejects(withTenant(f.primary,async c=>{const row=await createHiredEmployee(c,f.primary,candidate,job,dates.startDate);rolledBackEmployee=row.id;assert.equal((await c.query('SELECT count(*)::int n FROM hiring_onboarding_tasks WHERE tenant_id=$1 AND employee_id=$2',[f.primary,row.id])).rows[0].n,5);throw Error('SCENARIO_CONVERSION_ROLLBACK');}),/SCENARIO_CONVERSION_ROLLBACK/);
 assert.equal((await f.db.query('SELECT count(*)::int n FROM employees WHERE tenant_id=$1 AND id=$2',[f.primary,rolledBackEmployee])).rows[0].n,0);assert.equal((await f.db.query('SELECT count(*)::int n FROM hiring_onboarding_tasks WHERE tenant_id=$1 AND employee_id=$2',[f.primary,rolledBackEmployee])).rows[0].n,0);
 const hp=await f.page(admin);await f.navigate(hp,'Hiring');await hp.getByLabel('Search candidates',{exact:true}).fill(name);await hp.getByRole('button').filter({hasText:name}).first().click();await hp.getByText(/employee not created yet/).waitFor();await hp.getByRole('button',{name:'Confirm hire',exact:true}).click();const confirm=hp.getByRole('dialog');await confirm.getByLabel('Type HIRE to confirm employee creation',{exact:true}).fill('HIRE');await confirm.getByRole('button',{name:'Review and save',exact:true}).click();await confirm.waitFor({state:'hidden'});
 const employee=(await f.db.query('SELECT e.* FROM employees e JOIN hiring_applicants a ON a.hired_employee_id=e.id AND a.tenant_id=e.tenant_id WHERE a.id=$1',[candidate.id])).rows[0];assert(employee);assert.equal(employee.tenant_id,f.primary);assert.equal(employee.full_name,name);assert.equal(employee.email,email);assert.equal(employee.manager_id,admin.id);
 assert.equal((await f.ok(admin,`/api/hiring/applicants/${candidate.id}/hire`,{confirmed:true})).employeeId,employee.id);
 const template=(await f.ok(admin,'/api/hiring/onboarding/templates',{name:'Scenario checklist',tasks:[{key:'orientation',title:'Orientation',kind:'orientation',dueOffsetDays:0},{key:'manager',title:'Manager meeting',kind:'manager_meeting',dueOffsetDays:1,dependsOn:'orientation'}]})).template;
 await f.ok(admin,`/api/hiring/onboarding/employees/${employee.id}/template`,{templateId:template.id});assert.equal((await f.ok(admin,`/api/hiring/onboarding/employees/${employee.id}/template`,{templateId:template.id})).applied,false);
 let readiness=(await f.ok(admin,`/api/hiring/onboarding/readiness?employeeId=${employee.id}`)).hires[0];assert.equal(readiness.readiness,'needs_attention');
 const dependent=readiness.tasks.find((t:any)=>t.kind==='manager_meeting');assert.equal((await f.api(admin,`/api/hiring/onboarding/tasks/${dependent.id}`,{status:'completed'})).status,409);
 for(const task of readiness.tasks.filter((t:any)=>t.id!==dependent.id))await f.ok(admin,`/api/hiring/onboarding/tasks/${task.id}`,{status:'completed'});
 await f.ok(admin,`/api/hiring/onboarding/tasks/${dependent.id}`,{status:'completed'});readiness=(await f.ok(admin,`/api/hiring/onboarding/readiness?employeeId=${employee.id}`)).hires[0];assert.equal(readiness.readiness,'ready');
 assert.equal((await f.db.query('SELECT count(*)::int n FROM hiring_onboarding_tasks WHERE tenant_id=$1 AND employee_id=$2',[f.primary,employee.id])).rows[0].n,7);
 await hp.reload();await f.navigate(hp,'Hiring');await hp.locator('section.hiring-onboarding > article').filter({visible:true}).filter({hasText:name}).last().getByText(/Ready/).first().waitFor();await f.shot(hp,'hire-onboarding');console.log('PASS A public application → review/interview/evaluation/revised acceptance → explicit browser hire → idempotent prerequisite checklist/readiness');
 // Continue with the exact employee created above; login provisioning affects only this owned fixture.
 await f.db.query('UPDATE employees SET password_hash=$2 WHERE tenant_id=$3 AND id=$1',[employee.id,await bcrypt.hash(f.password,10),f.primary]);const hire=await f.login(employee.id,f.primary,email);
 const asset=(await f.ok(admin,'/api/hr/assets',{assetTag:'BUS-LAP-001',name:'Scenario laptop',category:'laptop',condition:'good'})).asset;
 await f.ok(admin,`/api/hr/assets/${asset.id}/assign`,{employeeId:hire.id});assert.equal((await f.api(admin,`/api/hr/assets/${asset.id}/assign`,{employeeId:hire.id})).status,409);
 const equipment=await f.ok(hire,'/api/me/assets');assert.equal(equipment.assets.length,1);assert.equal(equipment.assets[0].id,asset.id);
 const ep=await f.page(hire);await f.navigate(ep,'Profile');await ep.locator('.assets-equipment').getByRole('heading',{name:'Scenario laptop',exact:true}).waitFor();await ep.getByRole('button',{name:'Report damage / get IT help',exact:true}).click();let d=ep.getByRole('dialog');await d.getByLabel('Short summary',{exact:true}).fill('Scenario damaged screen');await d.getByLabel('Description',{exact:true}).fill('Owned fixture repair request');await d.getByRole('button',{name:'Submit request',exact:true}).click();await d.waitFor({state:'hidden'});
 const ticket=(await f.ok(hire,'/api/support')).tickets[0];assert.equal(ticket.asset_id,asset.id);assert.equal(ticket.requester_id,hire.id);
 await f.ok(admin,`/api/support/${ticket.id}/update`,{status:'in_progress',assignedTo:admin.id,expectedStatus:'open'});
 await f.ok(admin,`/api/support/${ticket.id}/comments`,{note:'PRIVATE IT DIAGNOSIS '+f.tag,visibility:'internal'});
 await f.navigate(hp,'IT & equipment support');await hp.getByRole('button',{name:'Company support queue',exact:true}).click();await hp.getByRole('button',{name:'Open ticket: Scenario damaged screen',exact:true}).click();d=hp.getByRole('dialog');await d.getByRole('button',{name:'Reply to requester',exact:true}).click();await d.getByRole('textbox',{name:'Reply to requester',exact:true}).fill('Replacement screen arranged');await d.getByRole('button',{name:'Send reply',exact:true}).click();await d.getByText('Replacement screen arranged',{exact:true}).waitFor();await d.getByRole('button',{name:'Close',exact:true}).click();
 const own=await f.ok(hire,`/api/support/${ticket.id}`);assert(!JSON.stringify(own).includes('PRIVATE IT DIAGNOSIS'));assert(own.history.some((e:any)=>e.note==='Replacement screen arranged'));assert.equal((await f.api(hire,`/api/support/${ticket.id}/comments`,{note:'Not permitted',visibility:'internal'})).status,403);
 assert.equal((await f.api(foreign,`/api/support/${ticket.id}`)).status,404);assert.equal((await f.api(foreign,`/api/hr/assets/${asset.id}`)).status,404);
 await f.ok(admin,`/api/support/${ticket.id}/update`,{status:'resolved',assignedTo:admin.id,note:'Screen replaced',expectedStatus:'in_progress'});
 assert.equal((await f.api(admin,`/api/support/${ticket.id}/update`,{status:'closed',expectedStatus:'open'})).status,409,'stale operation rejected');
 assert.equal((await f.ok(hire,`/api/support/${ticket.id}`)).ticket.status,'resolved');assert.equal((await f.ok(admin,`/api/hr/assets/${asset.id}`)).asset.assignments.length,1);
 assert.equal((await f.db.query('SELECT count(*)::int n FROM support_tickets WHERE tenant_id=$1',[f.primary])).rows[0].n,1);
 await f.navigate(ep,'IT & equipment support');await ep.getByRole('button',{name:'Open ticket: Scenario damaged screen',exact:true}).click();await ep.getByRole('dialog').getByText('Screen replaced',{exact:true}).first().waitFor();assert.equal(await ep.getByText('PRIVATE IT DIAGNOSIS '+f.tag,{exact:true}).count(),0);await f.shot(ep,'equipment-support-resolved');
 console.log('PASS B hired employee → real asset assignment/profile → browser Support submission/reply → private handling/resolution, no duplicated assignments/tickets');
 const queries=['what laptop is Sarah Scenario using?','who has BUS-LAP-001?','show support issues for Sarah Scenario','show candidates who accepted offers but have incomplete onboarding','which new hires still need equipment?'];
 const times:number[]=[];for(const query of queries){const start=performance.now();const r=(await f.ok(admin,'/api/command-router/resolve',{query,allowReasoning:false})).result;times.push(performance.now()-start);assert.equal(r.outcome,'matched',query+JSON.stringify(r));assert.equal(r.fallbackUsed,false);assert.equal(r.entityRoute.status,'resolved');if(query.startsWith('what laptop'))assert(r.entityRoute.items.some((i:any)=>i.id===asset.id));}
 const foreignResult=(await f.ok(foreign,'/api/command-router/resolve',{query:queries[0],allowReasoning:false})).result;assert(!foreignResult.entityRoute?.items?.some((i:any)=>i.id===asset.id));
 const denied=(await f.ok(limited,'/api/command-router/resolve',{query:queries[0],allowReasoning:false})).result;assert(!denied.entityRoute?.items?.some((i:any)=>i.id===asset.id));
 const duplicate=await f.person(f.primary,'Sarah Scenario',[]);const ambiguous=(await f.ok(admin,'/api/command-router/resolve',{query:queries[0],allowReasoning:false})).result;assert.equal(ambiguous.entityRoute.status,'ambiguous');assert(!ambiguous.entityRoute.items?.length);assert(duplicate.id!==hire.id);
 const successAudit=(await f.db.query("SELECT count(*)::int n FROM audit_logs WHERE tenant_id=$1 AND action='support.updated'",[f.primary])).rows[0].n;
 await f.db.query("DELETE FROM tenant_role_permissions WHERE tenant_id=$1 AND role_id=$2 AND permission_key='support.manage'",[f.primary,admin.roleId]);assert.equal((await f.api(admin,`/api/support/${ticket.id}/update`,{status:'closed'})).status,403);assert.equal((await f.db.query("SELECT count(*)::int n FROM audit_logs WHERE tenant_id=$1 AND action='support.updated'",[f.primary])).rows[0].n,successAudit);
 console.log('PASS G local cross-module queries/foreign and permission gates/ambiguous employee; revoked handler cannot mutate; HTTP ms',times.map(n=>n.toFixed(1)));
 await f.audit(['asset.created','asset.assigned']);assert((await f.db.query("SELECT count(*)::int n FROM audit_logs WHERE tenant_id=$1 AND action LIKE 'hiring.%'",[f.primary])).rows[0].n>0);assert((await f.db.query("SELECT count(*)::int n FROM outbox_events WHERE tenant_id=$1 AND event_type='notification.support_updated'",[f.primary])).rows[0].n>0);
} catch(e) {console.error(e);for(const a of f.actors)for(const p of a.context.pages())await f.shot(p,'hiring-failure').catch(()=>{});throw e;} finally {await f.cleanup();}
