import assert from 'node:assert/strict';
import {Queue,QueueEvents,Worker} from 'bullmq';
import {completeBackground} from '../src/lib/durable-background';
import {BusinessFixtures} from './business-scenario-fixtures';
import {rollupAttendanceDailySummary} from '../src/server/attendance/attendance-rollup';
import {getRedisConnection,withTenant} from '../src/lib/hr-background';
const f=new BusinessFixtures();
let queue:Queue|undefined,events:QueueEvents|undefined,worker:Worker|undefined;
try {
 await f.setup('attendance-leave');const {admin,employee,foreign}=f;
 const location=(await f.db.query("INSERT INTO company_locations(tenant_id,name,latitude,longitude,boundary) VALUES($1,'Scenario geofence',30,31,ST_Buffer(ST_SetSRID(ST_MakePoint(31,30),4326)::geography,1000)::geometry) RETURNING id",[f.primary])).rows[0].id;
 const now=Date.now(),end=new Date(now+2*3600000).toISOString(),planned={startTime:new Date(now-120000).toISOString(),endTime:new Date(now+300000).toISOString()};
 const scheduled=(await f.ok(admin,'/api/roster/shifts',{employeeId:employee.id,startTime:new Date(now-3600000).toISOString(),endTime:end,plannedBreaks:[planned]})).shift;
 assert.equal(scheduled.status,'scheduled');assert.equal((await f.api(employee,'/api/clock-in',{})).status,400);assert.equal((await f.api(employee,'/api/clock-in',{latitude:0,longitude:0})).status,403);
 await employee.context.grantPermissions(['geolocation'],{origin:f.base});await employee.context.setGeolocation({latitude:30,longitude:31});const p=await f.page(employee,'/?section=attendance');await p.locator('[data-geo-interaction=clock]').waitFor();
 const hydrationRequests:string[]=[];const recordHydration=(r:any)=>{const pathname=new URL(r.url()).pathname;if(pathname.startsWith('/api/'))hydrationRequests.push(pathname);};p.on('request',recordHydration);
 const incoming=p.waitForResponse((r:any)=>new URL(r.url()).pathname==='/api/clock-in'&&r.request().method()==='POST');await p.locator('[data-geo-interaction=clock]').click();assert.equal((await incoming).status(),200);
 let status=await f.ok(employee,'/api/clock-status');const logId=status.timeLogId;const stored=(await f.db.query('SELECT * FROM time_logs WHERE tenant_id=$1 AND id=$2',[f.primary,logId])).rows[0];assert.equal(stored.attendance_method,'geofenced');assert.equal(new Date(stored.scheduled_end_time).toISOString(),end);assert(stored.clock_in_location);assert(stored.is_valid_geofence);
 await p.getByRole('button',{name:'Start break',exact:true}).waitFor();p.off('request',recordHydration);assert.equal(hydrationRequests.filter(u=>u==='/api/clock-status').length,1,'successful geofenced clock-in hydrates attendance exactly once');assert(!hydrationRequests.some(u=>/hiring|assets|support|company-feed|grievances/.test(u)),'clock-in must not fan out across unrelated modules');await p.locator('[data-geo-interaction=clock]').click();await p.getByRole('button',{name:'End break',exact:true}).first().waitFor();status=await f.ok(employee,'/api/clock-status');assert.equal(new Date(status.attendance.activeBreak.planned_start_time??status.attendance.activeBreak.plannedStartTime).toISOString(),planned.startTime);
 const resumed=p.waitForResponse((r:any)=>new URL(r.url()).pathname==='/api/attendance/breaks/resume'&&r.request().method()==='POST');await p.locator('[data-geo-interaction=clock]').click();assert.equal((await resumed).status(),200);await p.getByRole('button',{name:'Request early leave',exact:true}).waitFor();
 // Accelerate only owned persisted timestamps to exercise nonzero minute arithmetic without changing the server clock.
 await f.db.query("UPDATE time_logs SET clock_in_time=now()-interval '20 minutes' WHERE tenant_id=$1 AND id=$2",[f.primary,logId]);await f.db.query("UPDATE attendance_breaks SET started_at=now()-interval '10 minutes',ended_at=now()-interval '5 minutes' WHERE tenant_id=$1 AND time_log_id=$2",[f.primary,logId]);
 await p.getByRole('button',{name:'Request early leave',exact:true}).click();let d=p.getByRole('dialog',{name:'Request early leave',exact:true});const local=new Date();const requested=new Date(local.getTime()-local.getTimezoneOffset()*60000).toISOString().slice(0,16);await d.getByLabel('Requested departure',{exact:true}).fill(requested);await d.getByLabel('Note (optional)').fill('Owned fixture appointment');await d.getByRole('button',{name:'Send request',exact:true}).click();await d.waitFor({state:'hidden'});assert((await f.ok(employee,'/api/clock-status')).isClockedIn,'request alone must not clock out');
 const request=(await f.db.query('SELECT * FROM attendance_early_leave_requests WHERE tenant_id=$1 AND time_log_id=$2',[f.primary,logId])).rows[0];assert.equal((await f.api(employee,`/api/attendance/early-leave/${request.id}/review`,{status:'approved'},'PATCH')).status,403);assert.equal((await f.api(foreign,`/api/attendance/early-leave/${request.id}/review`,{status:'approved'},'PATCH')).status,404);
 const rp=await f.page(admin,'/?section=attendance');await rp.getByRole('button',{name:'Team queue',exact:true}).click();await rp.getByText('Early leave requests',{exact:true}).click();const approved=rp.waitForResponse((r:any)=>new URL(r.url()).pathname===`/api/attendance/early-leave/${request.id}/review`&&r.request().method()==='PATCH');await rp.getByRole('button',{name:'Approve',exact:true}).click();assert.equal((await approved).status(),200);
 status=await f.ok(employee,'/api/clock-status');assert.equal(new Date(status.attendance.scheduledEnd).toISOString(),end);assert.equal(new Date(status.attendance.effectiveEnd).toISOString(),new Date(request.requested_departure_time).toISOString());
 await p.getByRole('button',{name:'Refresh',exact:true}).click();await p.getByText(/Early leave request: Approved/).waitFor();await p.locator('[data-geo-interaction=clock]').click();await p.getByRole('heading',{name:'Ready to clock in',exact:true}).waitFor();assert(!(await f.ok(employee,'/api/clock-status')).isClockedIn);await f.shot(p,'geofenced-approved-departure');
 const closed=(await f.db.query('SELECT * FROM time_logs WHERE tenant_id=$1 AND id=$2',[f.primary,logId])).rows[0];assert(closed.clock_out_time);assert.equal(new Date(closed.scheduled_end_time).toISOString(),end);
 const data={tenantId:f.primary,employeeId:employee.id,workDate:new Date(closed.clock_in_time).toISOString().slice(0,10)};
 const connection=getRedisConnection(),name='business-rollup-'+f.tag;assert(['127.0.0.1','localhost','::1'].includes(connection.host!),'isolated queue must use local Redis');queue=new Queue(name,{connection});events=new QueueEvents(name,{connection});await events.waitUntilReady();
 const dispatch=(await f.db.query("SELECT id,payload FROM outbox_events WHERE tenant_id=$1 AND event_type='background.hr' AND payload->>'name'='rollupAttendanceDailySummary' ORDER BY created_at DESC LIMIT 1",[f.primary])).rows[0];assert(dispatch,'real clock mutation emits durable rollup');
 const delayed=await queue.add('rollupAttendanceDailySummary',{...data,dispatchId:dispatch.id},{attempts:2,backoff:{type:'fixed',delay:50}});assert(['waiting','wait'].includes(await delayed.getState()),'no worker: durable job remains pending');assert((await f.db.query('SELECT clock_out_time FROM time_logs WHERE id=$1',[logId])).rows[0].clock_out_time,'authoritative state survives worker absence');
 let attempts=0;worker=new Worker(name,async job=>{if(attempts++===0)throw Error('Disposable worker retry fixture');await rollupAttendanceDailySummary(job.data);await completeBackground(job.data.tenantId,job.data.dispatchId);},{connection});worker.on('error',()=>{});await delayed.waitUntilFinished(events,20000);await rollupAttendanceDailySummary(data);await completeBackground(f.primary,dispatch.id);assert((await f.db.query('SELECT processed_at FROM outbox_events WHERE tenant_id=$1 AND id=$2',[f.primary,dispatch.id])).rows[0].processed_at);
 const summary=(await f.db.query('SELECT * FROM attendance_daily_summaries WHERE tenant_id=$1 AND employee_id=$2 AND work_date=$3',[f.primary,employee.id,data.workDate])).rows;assert.equal(summary.length,1);assert.equal(new Date(summary[0].first_clock_in).toISOString(),new Date(closed.clock_in_time).toISOString());assert.equal(new Date(summary[0].last_clock_out).toISOString(),new Date(closed.clock_out_time).toISOString());assert.equal(summary[0].invalid_geofence_count,0);assert.equal(summary[0].total_break_minutes,5);
 const elapsed=(new Date(closed.clock_out_time).getTime()-new Date(closed.clock_in_time).getTime())/1000;assert.equal(summary[0].total_minutes,Math.floor((elapsed-300)/60));assert(attempts>=2);
 await withTenant(f.foreignTenant,async c=>assert.equal((await c.query('SELECT count(*)::int n FROM attendance_daily_summaries WHERE employee_id=$1',[employee.id])).rows[0].n,0));await f.audit(['attendance.clock_out','attendance.early_leave.requested','attendance.early_leave.approved']);console.log('PASS C scheduled roster → real PostGIS browser clock-in/break/approved departure → source-derived UTC summary, worker unavailable/retry/idempotent replay');
 // Existing Leave emits conflict context, but does not rewrite the authoritative schedule or attendance.
 const future=(await f.ok(admin,'/api/roster/shifts',{employeeId:employee.id,startTime:'2030-01-02T08:00:00Z',endTime:'2030-01-02T16:00:00Z'})).shift;
 const lp=await f.page(employee,'/?section=roster&view=leave');await lp.locator('[data-leave-workspace]').getByRole('button',{name:'Request leave',exact:true}).click();d=lp.getByRole('dialog');await d.getByLabel('Start date',{exact:true}).fill('2030-01-02');await d.getByLabel('End date',{exact:true}).fill('2030-01-03');await d.getByRole('button',{name:'Review request',exact:true}).click();await d.getByRole('button',{name:'Submit request',exact:true}).click();await d.getByText('Leave request submitted',{exact:true}).waitFor();await d.getByRole('button',{name:'Close',exact:true}).click();
 const leave=(await f.ok(employee,'/api/me/leave-requests')).requests[0];assert.equal(leave.startDate,'2030-01-02');assert.equal(leave.endDate,'2030-01-03');assert.equal((await f.api(employee,`/api/hr/leave-requests/${leave.requestId}/approve`,{expectedVersion:leave.version})).status,404);assert.equal((await f.api(foreign,`/api/hr/leave-requests/${leave.requestId}`)).status,404);
 await rp.goto(f.base+'/?section=roster&view=leave&leaveView=approvals');await rp.locator('[data-leave-workspace]').getByRole('button',{name:'Review',exact:true}).first().click();await rp.getByRole('dialog').getByRole('button',{name:'Approve',exact:true}).click();await rp.getByRole('dialog').getByRole('button',{name:'Approve',exact:true}).click();await rp.getByText('Leave decision saved.',{exact:true}).waitFor();
 const own=(await f.ok(employee,`/api/me/leave-requests/${leave.requestId}`)).request;assert.equal(own.status,'approved');assert.equal(own.startDate,'2030-01-02');assert.equal((await f.api(admin,`/api/hr/leave-requests/${leave.requestId}/reject`,{expectedVersion:leave.version})).status,409);
 const after=(await f.db.query('SELECT * FROM roster_shifts WHERE tenant_id=$1 AND id=$2',[f.primary,future.id])).rows[0];assert.equal(after.status,'scheduled');assert.equal(new Date(after.end_time).toISOString(),'2030-01-02T16:00:00.000Z');assert.equal((await f.db.query('SELECT count(*)::int n FROM time_logs WHERE tenant_id=$1 AND employee_id=$2',[f.primary,employee.id])).rows[0].n,1);
 const balance=(await f.ok(employee,'/api/command-router/resolve',{query:'leave balance',allowReasoning:false})).result;assert.equal(balance.fallbackUsed,false);assert.equal(balance.answer,undefined,'balance command navigates; no policy-derived balance is fabricated');await f.audit(['leave.requested','leave.approved']);await lp.reload();await lp.locator('.leave-record').getByText('Approved',{exact:true}).first().waitFor();await f.shot(lp,'leave-approved-boundary');console.log('PASS D browser Leave submit/reviewer decision → stable own history/dates; existing roster retained, no attendance mutation, self/stale/foreign denied');
} catch(e){console.error(e);for(const a of f.actors)for(const p of a.context.pages())await f.shot(p,'attendance-failure').catch(()=>{});throw e;}finally{await worker?.close();await events?.close();if(queue){await queue.obliterate({force:true});await queue.close();}await f.cleanup();}
