import './router-env';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import sharp from 'sharp';
import {createRequire} from 'node:module';
import {getMigrationPool} from './migration-pool';
import {assertDatabaseMutationSafety,assertHttpMutationSafety} from './mutation-safety';
import {validateFeedEditorDocument,wrapStanzaDocument} from '../src/lib/stanza-document';
import {companyFeedImageStorage} from '../src/lib/company-feed-image-storage';
import {withTenant,closeHrResources} from '../src/lib/hr-background';
const base=assertHttpMutationSafety(process.env.BROWSER_BASE_URL||'http://localhost:3001','Feed browser');
assertDatabaseMutationSafety(process.env.DATABASE_URL,'Feed browser');
const {chromium}=createRequire(import.meta.url)(process.env.BROWSER_PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({channel:'msedge',headless:true}),db=getMigrationPool();
const tag=crypto.randomUUID(),password=crypto.randomBytes(24).toString('base64url'),tenants:string[]=[];
const feedLoads:number[]=[],readerOpens:number[]=[];
const node=(type:string,children:any[]=[],extra:any={})=>({type,version:1,format:'',indent:0,direction:null,children,...extra});
const text=(value:string)=>({type:'text',version:1,text:value,format:0,detail:0,mode:'normal',style:''});
const para=(value:string)=>node('paragraph',[text(value)]);
const makeDocument=(children:any[])=>wrapStanzaDocument({root:node('root',children)});
try {
 async function tenant(){const id=(await db.query('INSERT INTO tenants(slug,company_name) VALUES($1,$2) RETURNING id',['feed-polish-'+crypto.randomUUID(),'Feed polish fixture '+tag])).rows[0].id;tenants.push(id);return id;}
 const primary=await tenant(),foreign=await tenant();
 const all=(await db.query('SELECT permission_key FROM tenant_permissions')).rows.map(r=>r.permission_key);
 async function actor(tid:string,name:string,keys:string[],admin=false){
  const email='feed-polish-'+name+'-'+tag+'@example.invalid';
  const id=(await db.query('INSERT INTO employees(tenant_id,email,full_name,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id',[tid,email,'Feed fixture '+name,await bcrypt.hash(password,10),admin?'hr_admin':'employee'])).rows[0].id;
  const role=(await db.query('INSERT INTO tenant_roles(tenant_id,name,is_system) VALUES($1,$2,false) RETURNING id',[tid,name])).rows[0].id;
  for(const key of keys)await db.query('INSERT INTO tenant_role_permissions(tenant_id,role_id,permission_key) VALUES($1,$2,$3)',[tid,role,key]);
  await db.query("INSERT INTO employee_role_assignments(tenant_id,employee_id,role_id,scope_type) VALUES($1,$2,$3,'company')",[tid,id,role]);
  const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
  await context.addInitScript(()=>{if(!localStorage.getItem('stanza.preferences.v1'))localStorage.setItem('stanza.preferences.v1',JSON.stringify({tutorialsAutoStart:false,lanyardEnabled:false}));if(!localStorage.getItem('horizon-language'))localStorage.setItem('horizon-language','en');localStorage.setItem('stanza-demo-notice-seen','true');});
  const login=await context.request.post(base+'/api/auth/login',{headers:{Origin:base},data:{email,password}});assert.equal(login.status(),200);return {id,context,user:(await login.json()).user};
 }
 const author=await actor(primary,'author',all,true),reader=await actor(primary,'reader',['feed.read']),limited=await actor(primary,'limited',[]),other=await actor(foreign,'other',['feed.read','feed.publish']);
 async function req(path:string,body?:any,method=body?'POST':'GET',context=author.context){const r=await context.request.fetch(base+path,{method,headers:{Origin:base},...(body?{data:body}:{})});return {status:r.status(),...(r.headers()['content-type']?.includes('json')?await r.json():{})};}
 async function navigate(p:any,name='Company Feed'){await p.locator('[data-tutorial-target=stanza-launcher]').click();await p.locator('#stanza-navigation-panel .stanza-navigation-item').filter({hasText:name}).last().click();}
 const p=await author.context.newPage();p.setDefaultTimeout(15000);await p.goto(base);await navigate(p);await p.getByText('No company posts yet.',{exact:true}).waitFor();await p.screenshot({path:process.env.TEMP+'/stanza-feed-empty.png',fullPage:true});
 const short=makeDocument([para('Short workplace update العربية')]),long=makeDocument(Array.from({length:30},(_,i)=>para(`Long paragraph ${i} العربية `+'Readable company information. '.repeat(8))));
 const block=(kind:string,value:string)=>node('stanza-block',[para(value)],{kind,title:'Rich note العربية',tone:'info',border:'outer',shaded:true,thickness:1,open:true});
 const rich=makeDocument([node('heading',[text('Publication heading عنوان')],{tag:'h2'}),node('list',[node('listitem',[text('List item عنصر')],{value:1})],{listType:'bullet',tag:'ul',start:1}),node('table',[node('tablerow',Array.from({length:4},(_,i)=>node('tablecell',[para('Column '+i+' البيانات')],{colSpan:1,rowSpan:1,headerState:1})))],{colWidths:[180,180,180,180]}),block('callout','Callout guidance تنبيه'),block('section','Collapsible content تفاصيل'),block('code','const message = "hello";\n'+'x'.repeat(160)),node('list',[node('listitem',[text('Completed task مهمة')],{value:1,checked:true})],{listType:'check',tag:'ul',start:1}),{type:'stanza-sketch',version:1,drawing:{description:'Accessible sketch رسم توضيحي',shapes:[{tool:'arrow',color:'#10b981',points:[[10,20],[100,200]]}]}}]);
 const png=await sharp({create:{width:240,height:120,channels:3,background:'#10b981'}}).png().toBuffer();
 const upload=await author.context.request.post(base+'/api/company-feed/images',{headers:{Origin:base},multipart:{image:{name:'feed-fixture.png',mimeType:'image/png',buffer:png}}});assert.equal(upload.status(),201);const image=(await upload.json()).image;
 rich.root.children.push({type:'image',version:1,src:image.url,uploadId:image.id,altText:'Private published image صورة',width:240,height:120,maxWidth:800,showCaption:false,caption:'Associated caption وصف',align:'center'});
 const posts:any[]=[];
 for(const [title,doc] of [['Short update',short],['Long publication',long],['Advanced publication',rich]] as const){const v=validateFeedEditorDocument(doc);assert(v.ok,JSON.stringify(v));const created=await req('/api/company-feed/posts',{title,postType:'general',contentText:v.extractedText,contentJson:doc,status:'published',visibility:[{type:'all'}]});assert.equal(created.status,201,JSON.stringify(created));posts.push(created.post);}
 const unpublished=await req('/api/company-feed/posts',{title:'Unpublished company fixture',postType:'general',contentText:'Short workplace update العربية',contentJson:short,status:'draft',visibility:[{type:'all'}]});assert.equal(unpublished.status,201);assert(!(await req('/api/company-feed')).posts.some((post:any)=>post.id===unpublished.post.id));
 await db.query("UPDATE company_feed_posts SET updated_at=published_at+interval '2 minutes' WHERE tenant_id=$1 AND id=$2",[primary,posts[0].id]);
 assert.equal((await req('/api/company-feed/posts',{title:'Unsupported',contentText:'Unsafe',contentJson:{...short,documentVersion:99}})).status,400);
 assert.equal((await req('/api/company-feed/posts',{title:'Unsafe',contentText:'Unsafe',contentJson:makeDocument([node('script')])})).status,400);
 assert.equal((await req('/api/company-feed/posts',{title:'Denied',contentText:'Denied'},'POST',reader.context)).status,403);
 assert.equal((await req('/api/company-feed',undefined,'GET',limited.context)).status,403);assert.equal((await req('/api/me/company-feed/draft',undefined,'GET',reader.context)).status,403);
 assert.equal((await req('/api/company-feed',undefined,'GET',other.context)).posts.length,0);
 assert.equal((await req('/api/company-feed/posts/'+posts[0].id+'/content',{title:'Foreign',contentText:'Short workplace update العربية',contentJson:short,expectedUpdatedAt:posts[0].updated_at},'PUT',other.context)).status,404);
 assert.equal((await other.context.request.get(base+image.url)).status(),404);
 assert.equal((await limited.context.request.get(base+image.url)).status(),403);
 assert.equal((await withTenant(foreign,c=>c.query('SELECT id FROM company_feed_posts WHERE id=$1',[posts[0].id]))).rowCount,0);
 console.log('PASS real publications, version/HTML rejection, API permission denials, image privacy and tenant RLS');
 await p.getByRole('button',{name:'Refresh',exact:true}).click();await p.locator('.company-feed-item').first().waitFor();assert.equal(await p.locator('.company-feed-item .stanza-document-content').count(),0);await p.locator('.company-feed-item').filter({hasText:'Short update'}).getByText('Edited',{exact:true}).waitFor();
 await p.locator('.company-feed-management > summary').click();await p.locator('.company-feed-management').getByText('Unpublished company fixture',{exact:true}).waitFor();await p.locator('.company-feed-management').getByText(/Unpublished ·/).waitFor();await p.locator('.company-feed-management > summary').click();
 const canvas=p.locator('.stanza-feed-editor-surface');await canvas.click();await p.keyboard.type('Owned private draft content');await p.getByText('Private draft · Not published',{exact:true}).waitFor();await p.waitForTimeout(1500);assert((await req('/api/me/company-feed/draft')).draft);assert.equal((await req('/api/me/company-feed/draft',undefined,'GET',other.context)).draft,null);
 p.once('dialog',(d:any)=>d.dismiss());await p.getByRole('button',{name:'Discard draft',exact:true}).click();assert((await canvas.innerText()).includes('Owned private draft content'));p.once('dialog',(d:any)=>d.accept());await p.getByRole('button',{name:'Discard draft',exact:true}).click();await p.waitForTimeout(2200);assert.equal((await req('/api/me/company-feed/draft')).draft,null);assert(!(await canvas.innerText()).includes('Owned private draft content'));console.log('PASS private draft label and discard cancellation/acceptance without recreation');
 await p.route('**/api/company-feed',async(route:any)=>route.abort('failed'));await p.getByRole('button',{name:'Refresh',exact:true}).click();await p.locator('main [role=alert]').waitFor();await p.unroute('**/api/company-feed');await p.getByRole('button',{name:'Refresh',exact:true}).click();await p.locator('main [role=alert]').waitFor({state:'detached'});console.log('PASS injected transport failure and real refresh recovery');
 await p.route('**/api/me/company-feed/draft',async(route:any)=>{if(route.request().method()==='PUT')await route.abort('failed');else await route.continue()});await canvas.click();await p.keyboard.type('Private transport failure fixture');await p.getByRole('button',{name:'Retry save',exact:true}).waitFor();await p.unroute('**/api/me/company-feed/draft');await p.getByRole('button',{name:'Retry save',exact:true}).click();await p.waitForTimeout(1500);assert((await req('/api/me/company-feed/draft')).draft);await p.getByPlaceholder('Post title',{exact:true}).fill('Unsent publication fixture');await p.waitForTimeout(1500);await p.route('**/api/company-feed/posts',async(route:any)=>route.abort('failed'));await p.getByRole('button',{name:'Publish Post',exact:true}).click();await p.locator('main [role=alert]').waitFor();assert((await req('/api/me/company-feed/draft')).draft);await p.unroute('**/api/company-feed/posts');p.once('dialog',(d:any)=>d.accept());await p.getByRole('button',{name:'Discard draft',exact:true}).click();await p.waitForTimeout(1700);assert.equal((await req('/api/me/company-feed/draft')).draft,null);console.log('PASS bounded draft transport failure/retry and failed publish preserving private recovery');
 const emailDraft=await req('/api/communications/drafts',{subject:'Private workplace email العربية',body:'Fixture email, never sent.',category:'custom',recipientIds:[reader.id]});assert.equal(emailDraft.status,200);const commTemplate=await req('/api/communications/templates',{name:'Workplace template',subject:'Fixture subject',body:'Fixture template text',category:'custom'});assert.equal(commTemplate.status,200);
 await navigate(p,'Communications');await p.locator('.comms-link').filter({hasText:'Private workplace email العربية'}).waitFor();await p.locator('.comms-status').filter({hasText:'Private draft'}).waitFor();await p.locator('.comms-link').filter({hasText:'Private workplace email العربية'}).click();let commDialog=p.getByRole('dialog');await commDialog.getByRole('button',{name:'Save draft',exact:true}).waitFor();assert.equal((await req('/api/communications/drafts/'+emailDraft.message.id,{subject:'Concurrent fixture edit',body:'Fixture email, never sent.',category:'custom',recipientIds:[reader.id],version:emailDraft.message.version},'PUT')).status,200);await commDialog.getByRole('button',{name:'Save draft',exact:true}).click();await commDialog.getByRole('alert').waitFor();await p.keyboard.press('Escape');await p.getByRole('button',{name:'Refresh',exact:true}).click();await p.locator('.comms-link').first().waitFor();console.log('PASS real Communications private email, lazy compose and validation failure without sending');
 for(const width of [390,820,1440])for(const ar of [false,true]){
  await p.setViewportSize({width,height:1000});await p.evaluate((ar:boolean)=>{localStorage.setItem('horizon-language',ar?'ar':'en');localStorage.setItem('horizon-theme',ar?'light':'dark');localStorage.setItem('stanza.preferences.v1',JSON.stringify({tutorialsAutoStart:false,lanyardEnabled:false,backgroundPreset:ar?'custom':'emerald',customTheme:{accent:'#bf52e5'},interfaceScale:ar?1.15:1,fontScale:ar?1.2:1}));},ar);await p.reload();await navigate(p,ar?'التواصل':'Communications');await p.locator('.comms-link').first().waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:process.env.TEMP+`/stanza-communications-${width}-${ar?'ar':'en'}.png`,fullPage:true});await p.locator('.comms nav button').filter({hasText:ar?'القوالب':'Templates'}).click();await p.getByRole('button',{name:'Workplace template',exact:true}).click();commDialog=p.getByRole('dialog');await commDialog.getByText('Fixture template text',{exact:true}).waitFor();await p.keyboard.press('Escape');
 }
 await p.evaluate(()=>{localStorage.setItem('horizon-language','en');localStorage.setItem('horizon-theme','dark')});await p.reload();await navigate(p);console.log('PASS Communications mobile/tablet/desktop, RTL/light/custom/XL and template reader');
 const cookies=await reader.context.cookies();let matrix=0;
 for(const width of [390,820,1440,1920])for(const ar of [false,true])for(const preset of ['emerald','custom','light']){
  const xl=preset==='custom',c=await browser.newContext({viewport:{width,height:1000},serviceWorkers:'block',reducedMotion:xl?'reduce':'no-preference'});await c.addCookies(cookies);
  await c.addInitScript(({ar,preset,xl}:any)=>{localStorage.setItem('stanza.preferences.v1',JSON.stringify({tutorialsAutoStart:false,lanyardEnabled:false,backgroundPreset:preset==='light'?'emerald':preset,customTheme:{accent:'#bf52e5'},interfaceScale:xl?1.15:1,fontScale:xl?1.2:1}));localStorage.setItem('horizon-language',ar?'ar':'en');localStorage.setItem('horizon-theme',preset==='light'?'light':'dark');localStorage.setItem('stanza-demo-notice-seen','true');},{ar,preset,xl});
  const page=await c.newPage(),chunks:string[]=[];page.setDefaultTimeout(15000);page.on('request',(r:any)=>{if(r.url().includes('/assets/'))chunks.push(r.url())});await page.goto(base);await navigate(page,ar?'منشورات الشركة':'Company Feed');await page.locator('.company-feed-item').first().waitFor();assert.equal(await page.locator('.stanza-feed-editor-surface').count(),0);assert.equal(await page.locator('.company-feed-management').count(),0);
  const open=page.getByRole('button',{name:(ar?'قراءة: ':'Read: ')+'Advanced publication',exact:true});assert.equal(await open.evaluate((el:HTMLElement)=>getComputedStyle(el).color),await page.locator('.company-feed-heading h3').first().evaluate((el:HTMLElement)=>getComputedStyle(el).color));await open.focus();const openedAt=performance.now();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog');await dialog.locator('table').waitFor();readerOpens.push(performance.now()-openedAt);feedLoads.push(...await page.evaluate(()=>performance.getEntriesByType('resource').filter(e=>new URL(e.name).pathname==='/api/company-feed').map(e=>e.duration)));await dialog.getByAltText('Private published image صورة').waitFor();assert.equal(await dialog.locator('figcaption').filter({hasText:'Associated caption وصف'}).count(),1);assert.equal(await dialog.getByRole('img',{name:'Accessible sketch رسم توضيحي',exact:true}).count(),1);assert.equal(await dialog.getAttribute('dir'),ar?'rtl':'ltr');assert.equal(await dialog.locator('pre').evaluate((el:HTMLElement)=>getComputedStyle(el).direction),'ltr');assert.equal(await dialog.locator('pre').evaluate((el:HTMLElement)=>getComputedStyle(el).whiteSpace),'pre');assert.equal(await dialog.locator('pre p').evaluate((el:HTMLElement)=>getComputedStyle(el).textAlign),'left');assert(await dialog.locator('pre').evaluate((el:HTMLElement)=>el.scrollWidth>el.clientWidth));if(width===390)assert(await dialog.locator('.stanza-document-table-scroll').evaluate((el:HTMLElement)=>el.scrollWidth>el.clientWidth));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await dialog.evaluate((el:HTMLElement)=>el.getBoundingClientRect().width<=innerWidth));
  for(let i=0;i<8;i++){await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.querySelector('dialog')!.contains(document.activeElement)||document.activeElement===document.body));}
  assert(!chunks.some(u=>/RichTextEditor|AdvancedTools|SketchEditor/.test(u)));await page.screenshot({path:process.env.TEMP+`/stanza-feed-reader-${width}-${ar?'ar':'en'}-${preset}.png`,fullPage:true});await page.keyboard.press('Escape');await c.close();matrix++;
 }
 const quantiles=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b);return {p50:Math.round(sorted[Math.floor(sorted.length*.5)]*10)/10,p95:Math.round(sorted[Math.min(sorted.length-1,Math.floor(sorted.length*.95))]*10)/10}};console.log('PERFORMANCE feed API ms',quantiles(feedLoads),'reader open automation ms',quantiles(readerOpens));
 console.log('PASS rich reader 24 viewport/theme/RTL/scale/reduced-motion cases, keyboard and lazy chunks');
 const ordinary=await reader.context.newPage();await ordinary.goto(base);await navigate(ordinary);await ordinary.getByRole('button',{name:'Read: Short update',exact:true}).click();await ordinary.locator('.company-feed-reader').getByText('Short workplace update العربية',{exact:true}).waitFor();await ordinary.keyboard.press('Escape');await ordinary.getByRole('button',{name:'Read: Long publication',exact:true}).click();await ordinary.locator('.company-feed-reader').getByText(/^Long paragraph 29/).waitFor();assert.equal(await ordinary.locator('.stanza-feed-editor-surface').count(),0);await ordinary.close();console.log('PASS ordinary short and complete long publication readers');
 const ownedImage=(await db.query('SELECT storage_key FROM company_feed_images WHERE tenant_id=$1 AND id=$2',[primary,image.id])).rows[0];assert(ownedImage);await companyFeedImageStorage.remove(ownedImage.storage_key);assert.equal((await reader.context.request.get(base+image.url)).status(),404);const unavailable=await reader.context.newPage();await unavailable.goto(base);await navigate(unavailable);await unavailable.getByRole('button',{name:'Read: Advanced publication',exact:true}).click();const failedImage=unavailable.getByAltText('Private published image صورة');await failedImage.waitFor();await unavailable.waitForFunction(()=>{const img=document.querySelector<HTMLImageElement>('.company-feed-reader img');return img?.complete&&img.naturalWidth===0});await unavailable.getByText('Associated caption وصف',{exact:true}).waitFor();await unavailable.screenshot({path:process.env.TEMP+'/stanza-feed-image-unavailable.png',fullPage:true});await unavailable.close();console.log('PASS real private image file failure: protected 404 with alt text and caption retained');
 const deniedPage=await limited.context.newPage();await deniedPage.goto(base);await deniedPage.locator('[data-tutorial-target=stanza-launcher]').click();const deniedEntry=deniedPage.locator('#stanza-navigation-panel .stanza-navigation-item').filter({hasText:'Company Feed'});if(await deniedEntry.count()){await deniedEntry.last().click();await deniedPage.locator('main [role=alert]').waitFor();assert.equal(await deniedPage.locator('.company-feed-item').count(),0);}assert.equal(await deniedPage.locator('.stanza-document-workspace').count(),0);await deniedPage.close();console.log('PASS permission-limited view reveals no posts or authoring; API denial verified independently');
 const key='stanza.composer.v1:'+encodeURIComponent(author.user.tenantId)+':'+encodeURIComponent(author.user.id);
 await p.evaluate((key:string)=>localStorage.setItem(key,JSON.stringify({version:1,activeId:'feed-active',surface:'auto',workspaces:[{id:'feed-active',name:'Active feed',widgets:[]},{id:'feed-other',name:'Other feed',widgets:[]}]})),key);await p.reload();await navigate(p);
 for(const dest of ['feed-active','feed-other']){await p.getByRole('button',{name:'Add to Workspace',exact:true}).first().click();const d=p.getByRole('dialog');assert.equal(await d.getByRole('combobox',{name:'Workspace',exact:true}).inputValue(),'feed-active');await d.getByRole('combobox',{name:'Workspace',exact:true}).selectOption(dest);await d.getByRole('button',{name:'Add widget',exact:true}).click();}
 const stored=await p.evaluate((key:string)=>JSON.parse(localStorage.getItem(key)!),key);assert.equal(stored.activeId,'feed-active');assert(stored.workspaces.every((w:any)=>w.widgets.length===1));await p.reload();await navigate(p,'Workspace Composer');await p.locator('.composer-widget').waitFor();assert.equal(await p.locator('.composer-widget .stanza-feed-editor-surface').count(),0);console.log('PASS active/alternate persisted compact Workspace feed widget');
 await navigate(p);await p.locator('.company-feed-item').first().waitFor();await p.waitForTimeout(800);let calls=0;const count=(r:any)=>{if(new URL(r.url()).pathname.includes('company-feed'))calls++};p.on('request',count);await p.waitForTimeout(35000);p.off('request',count);assert.equal(calls,0);console.log('PASS 35-second settled idle: no feed/draft polling');
 const offlineContext=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'allow'});await offlineContext.addCookies(await author.context.cookies());await offlineContext.addInitScript(()=>{localStorage.setItem('stanza.preferences.v1',JSON.stringify({tutorialsAutoStart:false,lanyardEnabled:false}));localStorage.setItem('horizon-language','en');localStorage.setItem('stanza-demo-notice-seen','true')});const offlinePage=await offlineContext.newPage();offlinePage.setDefaultTimeout(15000);await offlinePage.goto(base);await navigate(offlinePage);await offlinePage.locator('.stanza-feed-editor-surface').waitFor();await offlinePage.evaluate(()=>navigator.serviceWorker.ready);await offlinePage.waitForTimeout(800);await offlineContext.setOffline(true);const offlineCanvas=offlinePage.locator('.stanza-feed-editor-surface');await offlineCanvas.click();await offlinePage.keyboard.type('Owned offline private recovery');await offlinePage.waitForFunction(()=>Object.keys(localStorage).some(key=>key.startsWith('stanza.company-feed.recovery.v1')&&localStorage.getItem(key)?.includes('Owned offline private recovery')));assert(await offlinePage.getByRole('button',{name:'Publish Post',exact:true}).isDisabled());assert.equal((await req('/api/me/company-feed/draft')).draft,null);assert.equal(await offlinePage.evaluate(async()=>{let count=0;for(const key of await caches.keys())for(const request of await (await caches.open(key)).keys())if(new URL(request.url).pathname.startsWith('/api/'))count++;return count}),0);await offlineContext.setOffline(false);await offlinePage.waitForTimeout(1500);const retryOffline=offlinePage.getByRole('button',{name:'Retry save',exact:true});if(await retryOffline.isVisible())await retryOffline.click();await offlinePage.waitForTimeout(1700);assert((await req('/api/me/company-feed/draft')).draft.contentText.includes('Owned offline private recovery'));await offlinePage.reload();await navigate(offlinePage);await offlineCanvas.waitFor();assert((await offlineCanvas.innerText()).includes('Owned offline private recovery'));offlinePage.once('dialog',(d:any)=>d.accept());await offlinePage.getByRole('button',{name:'Discard draft',exact:true}).click();await offlinePage.waitForTimeout(1700);assert.equal((await req('/api/me/company-feed/draft')).draft,null);await offlineContext.close();console.log('PASS real service-worker/offline recovery, disabled publishing, online retry/reload/discard and no private API caches');
}catch(error){
 for(const c of browser.contexts())for(const p of c.pages())await p.screenshot({path:process.env.TEMP+'/stanza-feed-failure-'+browser.contexts().indexOf(c)+'.png',fullPage:true}).catch(()=>{});throw error;
}finally{
 await browser.close();for(const id of tenants)assert.equal((await db.query('SELECT company_name FROM tenants WHERE id=$1',[id])).rows[0]?.company_name,'Feed polish fixture '+tag);
 const images=(await db.query('SELECT storage_key FROM company_feed_images WHERE tenant_id=ANY($1::uuid[])',[tenants])).rows;for(const image of images)await companyFeedImageStorage.remove(image.storage_key);
 for(const table of ['communication_messages','communication_templates','communication_meetings','company_feed_images','company_feed_drafts','company_feed_visibility','company_feed_posts'])await db.query(`DELETE FROM ${table} WHERE tenant_id=ANY($1::uuid[])`,[tenants]);await db.query('DELETE FROM tenants WHERE id=ANY($1::uuid[])',[tenants]);assert.equal((await db.query('SELECT id FROM tenants WHERE id=ANY($1::uuid[])',[tenants])).rowCount,0);await db.end();await closeHrResources();console.log('Owned feed fixtures and private image files cleaned');
}
