import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRoot, _roots } from '@react-three/fiber';
import { disconnectedLanyardEvents, readLanyardIsolation } from '../src/lib/dev-lanyard-isolation';
assert.equal(readLanyardIsolation(''), 'normal');
assert.equal(readLanyardIsolation('?stanzaLanyard=off'), 'off');
assert.equal(readLanyardIsolation('?stanzaLanyard=no-events'), 'no-events');
assert.equal(readLanyardIsolation('?stanzaLanyard=invalid'), 'normal');
const canvas = { width: 800, height: 600, style: {} } as HTMLCanvasElement;
let renders = 0, listeners = 0, callbacks = 0;
globalThis.requestAnimationFrame = () => 1;
globalThis.cancelAnimationFrame = () => undefined;
const root = createRoot(canvas);
await root.configure({ frameloop: 'never', events: disconnectedLanyardEvents, size: { width: 800, height: 600, top: 0, left: 0 }, gl: { render: () => renders++, setSize() {}, setPixelRatio() {}, xr: { isPresenting: false } } as never });
const store = _roots.get(canvas)!.store;
const state = store.getState();
state.events.connect?.({ addEventListener() { listeners++; } } as unknown as HTMLElement);
assert.equal(state.events.enabled, false);
assert.equal(Boolean(state.events.connected), false);
assert.equal(state.events.handlers, undefined);
assert.equal(listeners, 0);
state.internal.active = true;
const unsubscribe = state.internal.subscribe({ current: () => { callbacks++; } }, 0, store);
state.advance(1/60, false);
assert.equal(renders, 1);
assert.equal(callbacks, 1);
unsubscribe(); state.internal.active = false; _roots.delete(canvas);
const dashboard = readFileSync('src/pages/Dashboard.tsx', 'utf8');
assert.match(dashboard, /const shouldMountLanyard =[^;]+import\.meta\.env\.DEV[^;]+readLanyardIsolation\(window.location.search\) === 'off'/);
assert.match(dashboard, /const launcherLanyard = shouldMountLanyard &&/);
const scene = readFileSync('src/components/lanyard/Lanyard.tsx', 'utf8');
assert.match(scene, /events=\{import\.meta\.env\.DEV && readLanyardIsolation\(window.location.search\) === 'no-events' \? disconnectedLanyardEvents : undefined\}/);
console.log('PASS: DEV-only mount guard, default/invalid modes, real R3F no-events manager installs zero listeners while frame callbacks and rendering still execute.');
