import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const migration = await readFile('src/db/migrations/20260728_add_company_location_management.sql', 'utf8');
const routes = await readFile('src/server/locations/location-routes.ts', 'utf8');
const panel = await readFile('src/components/locations/LocationsPanel.tsx', 'utf8');
const registry = await readFile('src/server/organisation/permission-registry.ts', 'utf8');
const dashboard = await readFile('src/pages/Dashboard.tsx', 'utf8');
const css = await readFile('src/index.css', 'utf8');

assert.match(migration, /ADD COLUMN IF NOT EXISTS code/);
assert.match(migration, /archived_at/);
assert.match(migration, /company_locations_created_by_tenant_fk/);
assert.match(migration, /company_locations_active_name_unique/);
assert.match(migration, /company_locations_active_code_unique/);
assert.match(migration, /'locations\.view'/);
assert.match(migration, /'geofences\.manage'/);
assert.match(routes, /\/api\/hr\/locations/);
assert.match(routes, /locations\.manage/);
assert.match(routes, /geofences\.manage/);
assert.match(routes, /ST_SetSRID\(ST_MakePoint\(\$7,\$6\),4326\)/);
assert.match(routes, /Latitude must be between -90 and 90/);
assert.match(routes, /Longitude must be between -180 and 180/);
assert.match(routes, /Radius must be between 25 and 5000/);
assert.match(routes, /FOR UPDATE/);
assert.match(routes, /Location is still in active use/);
assert.match(routes, /tenant_id=\$1/);
assert.match(routes, /location\.archived/);
assert.match(routes, /location\.restored/);
assert.match(registry, /geofences\.manage/);
assert.match(panel, /MapPreview/);
assert.match(panel, /Use my current location/);
assert.match(panel, /data-location-preview-empty/);
assert.match(panel, /enableHighAccuracy: true/);
assert.match(panel, /position\.coords\.latitude/);
assert.match(panel, /position\.coords\.longitude/);
assert.match(panel, /Latitude/);
assert.match(panel, /dir=\{isRtl/);
assert.match(panel, /data-location-modal/);
assert.match(panel, /data-location-type-select/);
assert.match(panel, /Location type/);
assert.match(panel, /نوع الموقع/);
assert.match(panel, /stanza-select relative z-10 touch-manipulation pointer-events-auto/);
assert.match(panel, /relative z-0 mt-3 h-44 isolate/);
assert.match(panel, /sm:h-56/);
assert.match(panel, /z-\[90\]/);
assert.match(panel, /safe-area-inset-top/);
assert.match(panel, /safe-area-inset-bottom/);
assert.match(panel, /document\.body\.style\.overflow = 'hidden'/);
assert.match(panel, /min-h-0 overflow-y-auto overscroll-contain/);
assert.match(panel, /focus\(\{ preventScroll: true \}\)/);
assert.match(panel, /locationType: event\.target\.value/);
assert.match(panel, /JSON\.stringify\(\{[\s\S]*\.\.\.form/);
assert.doesNotMatch(panel, /departmentId|department_id/, 'the Location form must not invent a department relationship');
assert.doesNotMatch(routes, /departmentId|department_id/, 'the Location API remains limited to its real model');
assert.match(dashboard, /stanza-dashboard h-screen/);
assert.match(css, /\.stanza-dashboard select/);
assert.match(css, /--stanza-menu-bg/);
assert.match(css, /padding-inline-end/);
console.log('Location management and mobile form contracts passed: 44');
