// Frozen pre-calibration regression cases, moved without changing query/expected pairs.
export const CASES=[
 ["what's tomorrow's shift?",'tomorrow_shift'],['when is next payday?','next_payday'],['where can I see what I got paid?','payslips'],['show me the equipment assigned to me','my_assets'],['where are my clock-ins?','attendance'],['how much leave do I have left?','leave_balance'],['do I have meetings tomorrow?','tomorrow_meetings'],['who is my manager?','my_manager'],['عايز اعرف شيفتي بكرة','tomorrow_shift'],['المرتب هينزل امتى','next_payday'],['رصيد اجازاتي كام','leave_balance'],['العهدة اللي معايا','my_assets'],['my PTO balance كام','leave_balance'],['مصروفاتي لسه pending؟','pending_expenses'],['tomorow shfit','tomorrow_shift'],['leev balnce','leave_balance'],
 ['At what time am I scheduled to work the following day','tomorrow_shift'],['Can you find the list of company equipment in my custody','my_assets'],['Where do I check the unused days in my annual leave allowance','leave_balance'],['مين المسؤول المباشر عني في الشغل','my_manager'],['عندي ميتنجات بكره ولا لا','tomorrow_meetings'],['Which of my submitted claims have not yet been approved','pending_expenses'],['I want to ask for a vacation day','request_leave'],['How do I record the end of my working day','clock_out_help'],['What is happening with my complaint','grievance_status'],['Help me file a new complaint','submit_grievance'],['Has the expense claim been repaid to me','reimbursement_status'],
 ['show my most recent payslip','latest_payslip'],['what is included in my compensation','compensation_summary'],['I need to submit a new expense','submit_expense'],['show me expenses I filed before','expense_history'],['help me clock in','clock_in_help'],['I would like to request annual leave','request_leave'],
 ['cancel leave','no_match'],['modify salary','no_match'],['close grievance','no_match'],['الغاء الاجازة','no_match'],['اقفل الشكوى','no_match'],['recommend a pizza','no_match'],['Tell me tomorrow stock prices','no_match']
] as const;
export const COVERAGE_CASES:readonly (readonly [string,string])[]=[
 ['when is my shift?','current_shift'],['when do I work?','current_shift'],["what's my schedule?",'current_shift'],['next shift','next_shift'],['what time do I start tomorrow?','tomorrow_shift'],['when do I get paid?','next_payday'],['where is my payslip?','latest_payslip'],['how much leave do I have?','leave_balance'],['who is my boss?','my_manager'],['who is my manager?','my_manager'],['what equipment do I have?','my_assets'],['what meetings do I have tomorrow?','tomorrow_meetings'],
 ['شيفتي امتى','current_shift'],['هشتغل امتى','current_shift'],['جدولي ايه','current_shift'],['next shift امتى','next_shift'],['am I working tomorrow','tomorrow_shift'],['هقبض امتى','next_payday'],['مين رئيسي في الشغل','my_manager'],['باقي لي كام يوم اجازة','leave_balance'],
 ['Could you show my work schedule please','current_shift'],['When does my following shift begin','next_shift'],['Do I have to come to work tomorrow morning','tomorrow_shift'],['Who is my direct supervisor at the company','my_manager'],['I need the newest salary statement','latest_payslip'],['How much vacation time is still available','leave_balance'],
 ['When does my shift end','shift_end_time'],['where is the clock out control','clock_out_help'],['Can I see my old clock in records','attendance'],['show all my past salary statements','payslips'],['book me a flight tomorrow','no_match'],['cancel my meetings tomorrow','no_match']
];
export const PRODUCT_CASES:readonly (readonly [string,string])[]=[
 ['theme','appearance_settings'],['font','font_settings'],['change font','font_settings'],['text size','font_settings'],['cursor','appearance_settings'],['change my cursor','appearance_settings'],['dark mode','appearance_settings'],['announcement','company_feed'],['announcements','company_feed'],['news','company_feed'],['company news','company_feed'],["who's clocked in right now?",'live_employees'],['who is working right now?','live_employees'],['payday','next_payday'],['when is my next payday?','next_payday'],
 ['الثيم','appearance_settings'],['كبر الخط','font_settings'],['المؤشر','appearance_settings'],['اعلانات الشركة','company_feed'],['في اخبار جديدة؟','company_feed'],['مين شغال دلوقتي؟','live_employees'],['مين عامل clock in؟','live_employees'],
 ['Which employees are currently present at work','live_employees'],['Please show the newest announcements at work','company_feed'],['How can I adjust the appearance of my pointer','appearance_settings'],['I need larger text to read','font_settings'],['show my personal messages','communications'],['I need help clocking in','clock_in_help'],['Tell me tomorrow stock prices','no_match'],['who will be clocked in tomorrow','no_match']
];
export const ENTITY_CASES:readonly (readonly [string,string])[]=[
 ["show me Ahmed Hassan's grievance",'employee_grievance_lookup'],["show me Ahmed's grievance",'employee_grievance_lookup'],['find Ahmed Hassan disciplinary case','employee_grievance_lookup'],['show Ahmed Hassan grievance from Cairo warehouse','employee_grievance_lookup'],['open EMP-123 grievance','employee_grievance_lookup'],["show me Mona Ali's grievance",'employee_grievance_lookup'],['عايز اشوف شكوى احمد حسن','employee_grievance_lookup'],['وريني الشكوى بتاعت أحمد حسن','employee_grievance_lookup'],['grievance بتاعت Ahmed Hassan','employee_grievance_lookup'],['look up the complaint belonging to a colleague','employee_grievance_lookup']
];
export const evaluationCases=[...CASES,...COVERAGE_CASES,...PRODUCT_CASES,...ENTITY_CASES];
