import './router-env';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {getMigrationPool} from './migration-pool';
import {assertDatabaseMutationSafety} from './mutation-safety';
assertDatabaseMutationSafety(process.env.DATABASE_URL,'Operational palette browser fixtures');
const password=process.env.BROWSER_ADMIN_PASSWORD;assert(password);
const base=process.env.BROWSER_BASE_URL||'http://localhost:3001';assert(/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(base));
const {chromium}=createRequire(import.meta.url)(process.env.BROWSER_PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'}),db=getMigrationPool(),tag='OpsAmbig'+Date.now(),jobs:any[]=[];
let tenantId:string|undefined;
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage();p.setDefaultTimeout(15000);
 async function login(page:any,email:string){const response=await page.context().request.post(base+'/api/auth/login',{data:{email,password}});assert.equal(response.status(),200);await page.goto(base);await page.getByRole('button',{name:'Panel surface',exact:true}).waitFor();for(let i=0;i<8;i++){const skip=page.getByRole('button',{name:/^(Skip|Got it|I understand|تخطي)$/}).first();if(await skip.isVisible().catch(()=>false))await skip.click();else break;}}
 await login(p,'admin@stanza-demo.com');
 tenantId=await p.evaluate(async()=>(await(await fetch('/api/auth/session')).json()).user.tenantId);
 async function ask(page:any,query:string,status:string){await page.bringToFront();await page.evaluate(()=>document.activeElement instanceof HTMLElement&&document.activeElement.blur());await page.keyboard.press('Control+k');const input=page.getByPlaceholder(/Search commands or ask Stanza|ابحث عن أمر أو اسأل Stanza/);await input.fill(query);await page.locator('[data-entity-status="'+status+'"]').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 const queries=['who is interviewing today?','show candidates waiting for feedback','which open IT tickets are older than 3 days?','show unresolved tickets for Cairo Warehouse','which new hires still need equipment?','who starts this week?','show onboarding tasks overdue','show unresolved IT tickets for employees starting this week'];
 for(const q of queries){await ask(p,q,'resolved');assert(await p.locator('[data-entity-status="resolved"]').innerText());await p.keyboard.press('Escape');}
 for(const suffix of ['Alpha','Beta']){const r=await p.evaluate(async(title)=>(await(await fetch('/api/hiring/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,description:'Disposable ambiguity verification',employmentType:'full_time',headcount:'1',questions:['short_text','long_text','yes_no','single_select','multi_select','numeric'].map((type,i)=>({id:'field_'+i,label:'Field '+i,type,required:false,...(['single_select','multi_select'].includes(type)?{options:['One','Two']}: {})}))})})).json()),tag+' '+suffix);assert(r.success);jobs.push(r.job);}
 await ask(p,'who is interviewing for '+tag+' today?','ambiguous');const routes=p.locator('[data-entity-status="ambiguous"]');await routes.getByRole('button',{name:tag+' Alpha',exact:true}).click();await p.locator('[data-entity-status="resolved"]').waitFor();assert.match(await p.locator('[data-entity-status="resolved"]').innerText(),/Operational interviews 0/);await p.keyboard.press('Escape');
 await p.setViewportSize({width:390,height:844});await ask(p,'which new hires still need equipment?','resolved');await p.keyboard.press('Escape');await p.evaluate(()=>localStorage.setItem('horizon-language','ar'));await p.reload();await p.getByRole('button',{name:'سطح اللوحات',exact:true}).waitFor();await ask(p,'وريني الموظفين الجدد محتاجين معدات','resolved');assert.equal(await p.locator('[data-entity-status="resolved"]').getAttribute('dir'),'rtl');await p.keyboard.press('Escape');
 await p.bringToFront();await p.evaluate(()=>document.activeElement instanceof HTMLElement&&document.activeElement.blur());await p.keyboard.press('Control+k');await p.getByPlaceholder(/Search commands or ask Stanza|ابحث عن أمر أو اسأل Stanza/).fill('التوظيف');await p.getByRole('option').filter({hasText:'التوظيف'}).first().click();await p.getByText('التهيئة والاستعداد لليوم الأول',{exact:true}).first().waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const opened=await p.evaluate(async(id)=>(await fetch('/api/hiring/jobs/'+id+'/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'open'})})).status,jobs[0].id);assert.equal(opened,200);
 const publicContext=await browser.newContext({viewport:{width:390,height:844}});await publicContext.addInitScript(()=>localStorage.setItem('horizon-language','ar'));const publicPage=await publicContext.newPage();await publicPage.goto(base+'/careers/'+jobs[0].public_token);await publicPage.getByRole('combobox',{name:'Field 2',exact:true}).waitFor();assert.equal(await publicPage.locator('fieldset').count(),6);assert.equal(await publicPage.locator('main').getAttribute('dir'),'rtl');assert(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await publicPage.locator('input[name=answer_field_5]').getAttribute('type'),'number');

 const restricted=await browser.newContext({viewport:{width:390,height:844}}),e=await restricted.newPage();await login(e,'employee@stanza-demo.com');assert.equal(await e.evaluate(async()=>(await fetch('/api/hiring/onboarding/readiness')).status),403);await e.keyboard.press('Control+k');await e.getByPlaceholder('Search commands or ask Stanza…').fill('which new hires still need equipment?');await e.getByText('This capability is unavailable for your account.',{exact:true}).waitFor();assert.equal(await e.locator('[data-entity-status="resolved"]').count(),0);
 console.log('PASS eight actual palette queries, job ambiguity + chosen empty results, desktop/390px/Arabic RTL Hiring and six public question types, unauthorized palette and direct API denial. No commands were executed and no LLM consent was granted.');
}finally{await browser.close();for(const job of jobs){const r=(await db.query('SELECT title FROM hiring_jobs WHERE tenant_id=$1 AND id=$2',[tenantId,job.id])).rows[0];assert(r.title.startsWith(tag+' '));await db.query('DELETE FROM audit_logs WHERE tenant_id=$1 AND entity_id=$2',[tenantId,job.id]);await db.query('DELETE FROM hiring_jobs WHERE tenant_id=$1 AND id=$2',[tenantId,job.id]);}await db.end();}
