import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import {
  getPermissionDefinition,
  isKnownPermission,
  listPermissionDefinitions,
  validatePermissionKeys,
} from '../src/server/organisation/permission-registry';

const migration = await readFile('src/db/migrations/20260726_add_organisation_management.sql', 'utf8');
const evaluator = await readFile('src/server/organisation/scoped-permissions.ts', 'utf8');
const routes = await readFile('src/server/organisation/organisation-routes.ts', 'utf8');
const finalAdmin = await readFile('src/server/organisation/final-hr-admin.ts', 'utf8');
const legacyServer = await readFile('server.ts', 'utf8');
const organisationPanel = await readFile('src/components/organisation/OrganisationPanel.tsx', 'utf8');
const rolesPanel = await readFile('src/components/organisation/RolesPermissionsPanel.tsx', 'utf8');
const languageContext = await readFile('src/lib/LanguageContext.tsx', 'utf8');
const delegationRoutes = await readFile('src/server/organisation/delegation-routes.ts', 'utf8');
const approvalChain = await readFile('src/server/organisation/approval-chain.ts', 'utf8');
const delegationsPanel = await readFile('src/components/organisation/DelegationsPanel.tsx', 'utf8');
const hierarchyPanel = await readFile('src/components/organisation/HierarchyPanel.tsx', 'utf8');
const selectStyles = await readFile('src/index.css', 'utf8');

const permissionDefinitions = listPermissionDefinitions();
assert.ok(getPermissionDefinition('roles.view'));
assert.equal(getPermissionDefinition('unknown.permission'), null);
assert.equal(isKnownPermission('roles.view'), true);
assert.equal(isKnownPermission('unknown.permission'), false);
assert.deepEqual(validatePermissionKeys(['roles.view', 'roles.view']), ['roles.view']);
assert.equal(validatePermissionKeys(['roles.view', 'unknown.permission']), null);
assert.equal(new Set(permissionDefinitions.map((permission) => permission.key)).size, permissionDefinitions.length);
for (const permission of permissionDefinitions) {
  assert.ok(permission.label.length > 0 && permission.description.length > 0, `${permission.key} must be human readable`);
  assert.ok(permission.allowedScopeTypes.every((scope) => ['company', 'location', 'department', 'team', 'direct_reports', 'self'].includes(scope)));
}
assert.equal(getPermissionDefinition('roles.manage')?.protected, true);
assert.equal(getPermissionDefinition('roles.manage')?.delegatable, false);

for (const table of ['organisation_job_titles', 'organisation_departments', 'organisation_teams', 'organisation_team_memberships', 'permission_delegations']) {
  assert.match(migration, new RegExp(`ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY`), `${table} must enable RLS`);
  assert.match(migration, new RegExp(`${table}_id_tenant_unique UNIQUE \\(id, tenant_id\\)`), `${table} needs a composite key`);
}
assert.match(migration, /organisation_departments_not_self_parent/);
assert.match(migration, /employee_role_assignments_active_scope_unique/);
assert.match(migration, /revoked_at IS NULL/);
assert.match(evaluator, /resolveScopedPermission/);
assert.match(evaluator, /direct_reports/);
assert.match(evaluator, /source: 'role_assignment' \| 'delegation'/);
assert.match(routes, /assertNoDepartmentCycle/);
assert.match(routes, /assertNoReportingCycle/);
assert.match(routes, /organisation\.department\.created/);
assert.match(routes, /organisation\.delegation\.revoked/);
assert.match(routes, /teams\/:teamId\/members/);
assert.match(routes, /members\/move/);
assert.match(routes, /Employee is already an active member/);
assert.match(routes, /Team must belong to the selected department/);
assert.match(routes, /Job title must be active/);
assert.match(routes, /assertNoReportingCycle/);
assert.match(routes, /organisation\.team\.updated/);
assert.match(routes, /organisation\.job_title\.updated/);
assert.match(routes, /organisation\.employee_placement\.updated/);
assert.match(routes, /membership\.membership_type AS "membershipType"/);
assert.match(routes, /title\.name AS "jobTitle"/);
assert.match(routes, /department\.name AS department/);
assert.match(routes, /members\?page=|pageSize=Math\.min\(100/);
assert.match(routes, /Employee is already an active member of the target team/);
assert.match(routes, /Target team must belong to the employee department/);
assert.match(routes, /UPDATE organisation_team_memberships SET ends_at=CURRENT_DATE/);
assert.match(routes, /\/api\/hr\/organisation\/permission-registry/);
assert.match(routes, /\/api\/hr\/organisation\/roles'/);
assert.match(routes, /\/api\/hr\/organisation\/roles\/:roleId'/);
assert.match(routes, /\/api\/hr\/organisation\/roles\/:roleId\/permissions'/);
assert.match(routes, /assertCompanyPermission\(client,req,'roles\.view'\)/);
assert.match(routes, /role\.tenant_id=\$1/);
assert.match(routes, /pageSize=Math\.min\(100/);
assert.match(routes, /req\.query\.kind==='system'\|\|req\.query\.kind==='custom'/);
assert.match(routes, /req\.query\.activity==='archived'\?'archived':'active'/);
assert.match(routes, /if\(!uuid\(req\.params\.roleId\)\)throw fail\(404,'Role not found\.'\)/);
assert.match(routes, /selected:selected\.has\(permission\.key\)/);
assert.doesNotMatch(routes, /return \{\.\.\.row,privilegeLevel/);
assert.match(routes, /app\.post\('\/api\/hr\/organisation\/roles', rateLimiter, standardAuth, mutationGuard/);
assert.match(routes, /app\.patch\('\/api\/hr\/organisation\/roles\/:roleId', rateLimiter, standardAuth, mutationGuard/);
assert.match(routes, /app\.post\('\/api\/hr\/organisation\/roles\/:roleId\/duplicate', rateLimiter, standardAuth, mutationGuard/);
assert.match(routes, /app\.post\('\/api\/hr\/organisation\/roles\/:roleId\/archive', rateLimiter, standardAuth, mutationGuard/);
assert.match(routes, /assertAllowedFields\(req\.body, \['name', 'description'\]\)/);
assert.match(routes, /assertRoleNameAvailable/);
assert.match(routes, /if \(current\.is_system\) throw fail\(403, 'System roles cannot be edited\.'/);
assert.match(routes, /if \(source\.is_system\) throw fail\(403, 'System roles cannot be duplicated\.'/);
assert.match(routes, /if \(current\.is_system\) throw fail\(403, 'System roles cannot be archived\.'/);
assert.match(routes, /INSERT INTO tenant_role_permissions/);
assert.match(routes, /SELECT tenant_id,\$3,permission_key FROM tenant_role_permissions/);
assert.match(routes, /Revoke or migrate active role assignments before archiving this role\./);
assert.match(routes, /organisation\.role\.created/);
assert.match(routes, /organisation\.role\.updated/);
assert.match(routes, /organisation\.role\.duplicated/);
assert.match(routes, /organisation\.role\.archived/);
assert.match(routes, /await client\.query\('BEGIN'\)/);
assert.match(routes, /await client\.query\('ROLLBACK'\)/);
assert.match(routes, /app\.put\('\/api\/hr\/organisation\/roles\/:roleId\/permissions', rateLimiter, standardAuth, mutationGuard/);
assert.match(routes, /assertAllowedFields\(req\.body, \['permissionKeys'\]\)/);
assert.match(routes, /validatePermissionKeys\(req\.body\.permissionKeys\)/);
assert.match(routes, /Permission keys must be recognised registry keys\./);
assert.match(routes, /assertPermissionMutationAuthority/);
assert.match(routes, /await assertCompanyPermission\(client, req, 'roles\.manage'\)/);
assert.match(routes, /await assertCompanyPermission\(client, req, 'permissions\.manage'\)/);
assert.match(routes, /definition\.protected \|\| !definition\.delegatable/);
assert.match(routes, /You cannot grant permission:/);
assert.match(routes, /tenant_permissions WHERE permission_key = ANY\(\$1::varchar\[\]\)/);
assert.match(routes, /System role permissions cannot be changed\./);
assert.match(routes, /Archived role permissions cannot be changed\./);
assert.match(routes, /DELETE FROM tenant_role_permissions WHERE tenant_id=\$1 AND role_id=\$2/);
assert.match(routes, /INSERT INTO tenant_role_permissions\(tenant_id,role_id,permission_key\)/);
assert.match(routes, /unnest\(\$3::varchar\[\]\) AS requested\(permission_key\)/);
assert.match(routes, /previousPermissionCount: previousKeys\.length/);
assert.match(routes, /newPermissionCount: permissionKeys\.length/);
assert.match(routes, /addedCount,/);
assert.match(routes, /removedCount,/);
assert.match(routes, /organisation\.role\.permissions_updated/);
assert.match(routes, /tenant_id=\$1 AND id=\$2 FOR UPDATE/);
assert.match(evaluator, /export async function scopeContains/);
assert.match(evaluator, /export async function canDelegatePermissionAtScope/);
assert.match(evaluator, /assignment\.assigned_at<=NOW\(\)/);
assert.match(routes, /\/api\/hr\/organisation\/role-assignments/);
assert.match(routes, /\/api\/hr\/organisation\/employees\/:employeeId\/roles/);
assert.match(routes, /role-assignments\/:assignmentId\/revoke/);
assert.match(routes, /assertScopeTarget/);
assert.match(routes, /Scope target must be active and belong to this tenant/);
assert.match(routes, /This scope requires a scope ID/);
assert.match(routes, /This scope cannot have a scope ID/);
assert.match(routes, /Role must have at least one permission/);
assert.match(routes, /Archived role cannot be assigned/);
assert.match(routes, /Assignment dates are invalid/);
assert.match(routes, /canDelegatePermissionAtScope/);
assert.match(routes, /roles\.assign_privileged/);
assert.match(routes, /System role permissions cannot be changed/);
assert.match(routes, /UPDATE employee_role_assignments SET revoked_at=NOW\(\),revoked_by=\$4/);
assert.match(routes, /UPDATE auth_sessions SET revoked_at=NOW\(\)/);
assert.match(routes, /Role assignment is already revoked/);
assert.match(routes, /pageSize = Math\.min\(100/);
assert.match(routes, /organisation\.role\.assigned/);
assert.match(routes, /organisation\.role\.revoked/);
assert.match(finalAdmin, /pg_advisory_xact_lock\(hashtext\(\$1\), hashtext\('stanza-final-hr-admin'\)\)/);
assert.match(finalAdmin, /SELECT id FROM tenants WHERE id=\$1 FOR UPDATE/);
assert.match(finalAdmin, /FOR UPDATE OF assignment/);
assert.match(finalAdmin, /employee\.role='hr_admin'/);
assert.match(finalAdmin, /employee\.is_active=true/);
assert.match(finalAdmin, /employee\.employment_status='active'/);
assert.match(finalAdmin, /assignment\.assigned_at <= \$2/);
assert.match(finalAdmin, /assignment\.expires_at IS NULL OR assignment\.expires_at > \$2/);
assert.match(finalAdmin, /assertHrAdminAssignmentsMayBeRevoked/);
assert.match(finalAdmin, /assertHrAdminAssignmentTimingIsSafe/);
assert.match(finalAdmin, /Another active HR Admin is required before removing this access/);
const concurrencyTest = await readFile('scripts/organisation-final-admin-concurrency-test.ts', 'utf8');
assert.match(concurrencyTest, /const first = await beginTenantTransaction\(\)/);
assert.match(concurrencyTest, /const second = await beginTenantTransaction\(\)/);
assert.match(concurrencyTest, /await lockFinalHrAdminAuthority\(first, tenantId\)/);
assert.match(concurrencyTest, /await lockFinalHrAdminAuthority\(second, tenantId\)/);
assert.match(concurrencyTest, /FINAL_HR_ADMIN_REQUIRED/);
assert.match(routes, /lockFinalHrAdminAuthority\(client, user\.tenantId\)/);
assert.match(routes, /role\.system_key === HR_ADMIN_SYSTEM_KEY/);
assert.match(routes, /assertHrAdminAssignmentsMayBeRevoked\(client, user\.tenantId, current\.employee_id, \[current\.id\]\)/);
assert.match(routes, /assertHrAdminAssignmentTimingIsSafe\(client, user\.tenantId, startsAt, expiresAt\)/);
assert.match(routes, /UPDATE auth_sessions SET revoked_at=NOW\(\)/);
assert.match(legacyServer, /lockFinalHrAdminAuthority\(client, tenantId\)/);
assert.match(legacyServer, /assertHrAdminAssignmentsMayBeRevoked\(client, tenantId, employeeId, activeAssignments\)/);
assert.match(legacyServer, /tenantRole\?\.system_key !== HR_ADMIN_SYSTEM_KEY && employeeId === actorEmployeeId/);
assert.match(legacyServer, /statusCode === 400 \|\| statusCode === 403 \|\| statusCode === 409/);
assert.match(organisationPanel, /RolesPermissionsPanel/);
assert.match(organisationPanel, /'roles'/);
assert.match(rolesPanel, /\/api\/hr\/organisation\/roles/);
assert.match(rolesPanel, /\/api\/hr\/organisation\/permission-registry/);
assert.match(rolesPanel, /\/api\/hr\/organisation\/roles\/\$\{role\.id\}\/permissions/);
assert.match(rolesPanel, /\/api\/hr\/organisation\/employees\/\$\{employeeId\}\/roles/);
assert.match(rolesPanel, /\/api\/hr\/organisation\/role-assignments/);
assert.match(rolesPanel, /role-assignments\/\$\{dialog\.assignment\.assignmentId\}\/revoke/);
assert.match(rolesPanel, /organisation\.systemRoleProtected/);
assert.match(rolesPanel, /organisation\.finalAdminWarning/);
assert.match(rolesPanel, /\['company', 'location', 'department', 'team', 'direct_reports', 'self'\]/);
assert.match(rolesPanel, /selectedRole\.isSystem \|\| permission\.protected \|\| !permission\.delegatable/);
assert.match(rolesPanel, /role\.isSystem && <p/);
assert.match(rolesPanel, /role\.isActive/);
assert.match(rolesPanel, /roleActivity/);
assert.match(rolesPanel, /assignmentStatus/);
assert.match(rolesPanel, /aria-modal="true"/);
assert.match(rolesPanel, /event\.key === 'Escape'/);
assert.match(rolesPanel, /dir=\{isRtl \? 'rtl' : 'ltr'\}/);
assert.match(rolesPanel, /max-h-\[calc\(100dvh-1\.5rem\)\]/);
assert.match(languageContext, /'organisation\.roles': 'Roles & Permissions'/);
assert.match(languageContext, /'organisation\.roles': 'الأدوار والصلاحيات'/);
assert.match(delegationRoutes, /recipientEmployeeId/);
assert.match(delegationRoutes, /MAX_DELEGATION_MS = 90/);
assert.match(delegationRoutes, /definition\.delegatable \|\| definition\.protected/);
assert.match(delegationRoutes, /body\.scopeType === 'self'/);
assert.match(delegationRoutes, /An overlapping active delegation already exists/);
assert.match(delegationRoutes, /FOR UPDATE/);
assert.match(delegationRoutes, /await client\.query\('BEGIN'\)/);
assert.match(delegationRoutes, /organisation\.delegation\.created/);
assert.match(delegationRoutes, /organisation\.delegation\.revoked/);
assert.doesNotMatch(delegationRoutes, /delegation\.reason AS/);
assert.match(approvalChain, /resolveApprovalChain/);
assert.match(approvalChain, /direct_manager/);
assert.match(approvalChain, /team_leader/);
assert.match(approvalChain, /department_head/);
assert.match(approvalChain, /reporting_chain/);
assert.match(approvalChain, /No eligible approver configured/);
assert.match(approvalChain, /is_active=true AND employment_status='active'/);
assert.match(approvalChain, /excludedEmployeeIds/);
assert.match(organisationPanel, /DelegationsPanel/);
assert.match(delegationsPanel, /\/api\/hr\/organisation\/delegations/);
assert.match(delegationsPanel, /delegatable && !permission\.protected/);
assert.match(delegationsPanel, /90 \* 86400000/);
assert.match(delegationsPanel, /scopeType/);
assert.match(delegationsPanel, /aria-modal="true"/);
assert.match(delegationsPanel, /event\.key === 'Escape'/);
assert.match(delegationsPanel, /dir=\{isRtl \? 'rtl' : 'ltr'\}/);
assert.match(routes, /\/api\/hr\/organisation\/hierarchy/);
assert.match(routes, /assertCompanyPermission\(client,req,'organisation\.view'\)/);
assert.match(routes, /department_cycle/);
assert.match(routes, /reporting_cycle/);
assert.match(routes, /orphaned_team/);
assert.match(routes, /missing_department_head/);
assert.match(routes, /missing_team_leader/);
assert.match(routes, /missing_manager/);
assert.match(routes, /GROUP BY employee\.id/);
assert.match(routes, /employee\.tenant_id=\$1/);
assert.match(organisationPanel, /HierarchyPanel/);
assert.match(organisationPanel, /'hierarchy'/);
assert.match(hierarchyPanel, /role="tree"/);
assert.match(hierarchyPanel, /role="treeitem"/);
assert.match(hierarchyPanel, /aria-expanded/);
assert.match(hierarchyPanel, /ArrowRight/);
assert.match(hierarchyPanel, /ArrowLeft/);
assert.match(hierarchyPanel, /includeUnassigned=true/);
assert.match(hierarchyPanel, /dir=\{isRtl \? 'rtl' : 'ltr'\}/);
assert.doesNotMatch(hierarchyPanel, /react-flow|d3|canvas/i);
assert.match(organisationPanel, /<select name="departmentId"/);
assert.match(selectStyles, /\.stanza-dashboard select/);
assert.match(selectStyles, /\[dir="rtl"\] select/);
assert.match(selectStyles, /\[role="listbox"\]/);
assert.match(selectStyles, /\[aria-disabled="true"\]/);
console.log('Organisation foundation checks passed: 197');
