import './router-env';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import {createRequire} from 'node:module';
import {getMigrationPool} from './migration-pool';
import {assertDatabaseMutationSafety,assertHttpMutationSafety} from './mutation-safety';
const base=assertHttpMutationSafety(process.env.BROWSER_BASE_URL||'http://localhost:3001','People browser');
assertDatabaseMutationSafety(process.env.DATABASE_URL,'People browser');
const {chromium}=createRequire(import.meta.url)(process.env.BROWSER_PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'}),db=getMigrationPool();
const tag=crypto.randomUUID(),password=crypto.randomBytes(24).toString('base64url'),tenants:string[]=[];
let matrix=0;
try{
 const all=(await db.query('SELECT permission_key FROM tenant_permissions')).rows.map(r=>r.permission_key);
 async function tenant(label:string){const id=(await db.query('INSERT INTO tenants(slug,company_name) VALUES($1,$2) RETURNING id',['people-polish-'+label+'-'+tag,'People polish fixture '+tag])).rows[0].id;tenants.push(id);return id;}
 const primary=await tenant('primary'),foreign=await tenant('foreign');
 async function actor(tenantId:string,name:string,keys:string[],admin=false){
 const email='people-polish-'+name+'-'+tag+'@example.invalid';
 const id=(await db.query('INSERT INTO employees(tenant_id,full_name,email,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id',[tenantId,'People fixture '+name,email,await bcrypt.hash(password,10),admin?'hr_admin':'employee'])).rows[0].id;
 const role=(await db.query('INSERT INTO tenant_roles(tenant_id,name,is_system) VALUES($1,$2,false) RETURNING id',[tenantId,name])).rows[0].id;
 for(const key of keys)await db.query('INSERT INTO tenant_role_permissions(tenant_id,role_id,permission_key) VALUES($1,$2,$3)',[tenantId,role,key]);
 await db.query("INSERT INTO employee_role_assignments(tenant_id,employee_id,role_id,scope_type) VALUES($1,$2,$3,'company')",[tenantId,id,role]);
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,serviceWorkers:'block'});
 await context.addInitScript(()=>{localStorage.setItem('stanza.preferences.v1',JSON.stringify({tutorialsAutoStart:false,lanyardEnabled:false}));localStorage.setItem('horizon-language','en');localStorage.setItem('stanza-demo-notice-seen','true');});
 const response=await context.request.post(base+'/api/auth/login',{headers:{Origin:base},data:{email,password}});assert.equal(response.status(),200,'normal cookie login');const user=(await response.json()).user;return {id,user,context};
 }
 const admin=await actor(primary,'administrator',all,true),reader=await actor(primary,'reader',['organisation.view','assets.view']),limited=await actor(primary,'limited',[]),outsider=await actor(foreign,'foreign',all,true);
 async function req(path:string,body?:unknown,method=body?'POST':'GET',context=admin.context){const r=await context.request.fetch(base+path,{method,headers:{Origin:base},...(body?{data:body}:{})});return {...await r.json(),status:r.status()};}
 const departmentResult=await req('/api/hr/organisation/departments',{name:'People Engineering'});assert.equal(departmentResult.status,201);const department=departmentResult.department;
 const title=(await req('/api/hr/organisation/job-titles',{name:'Systems Engineer مهندس نظم'})).jobTitle;
 const team=(await req('/api/hr/organisation/teams',{name:'People Platform',departmentId:department.id})).team;
 assert.equal((await req(`/api/hr/organisation/employees/${admin.id}/placement`,{departmentId:department.id,teamId:team.id,jobTitleId:title.id},'PATCH')).status,200);
 const people:any[]=[];
 for(let i=0;i<27;i++){const person=(await db.query("INSERT INTO employees(tenant_id,full_name,email,password_hash,role,is_active,employment_status) VALUES($1,$2,$3,'unused','employee',$4,$5) RETURNING id",[primary,`Directory person ${String(i).padStart(2,'0')} العربية`,`${tag}-${i}@example.invalid`,i!==26,i===26?'archived':'active'])).rows[0];people.push(person);}
 assert.equal((await req(`/api/hr/organisation/employees/${people[0].id}/placement`,{departmentId:department.id,teamId:team.id,jobTitleId:title.id},'PATCH')).status,200);
 assert.equal((await req(`/api/hr/organisation/employees/${people[0].id}/reporting-line`,{managerId:admin.id},'PATCH')).status,200);
 const loc={location:(await db.query("INSERT INTO company_locations(tenant_id,name,code,latitude,longitude,radius_meters,location_type,boundary) VALUES($1,'People Cairo work site','PEOPLE',30.0444,31.2357,300,'branch',ST_Buffer(ST_SetSRID(ST_MakePoint(31.2357,30.0444),4326)::geography,300)::geometry) RETURNING id",[primary])).rows[0]};
 // Only fixture setup uses the migration connection; application reads and edits use real cookie sessions.
 await db.query('UPDATE organisation_teams SET location_id=$1 WHERE tenant_id=$2 AND id=$3',[loc.location.id,primary,team.id]);
 const equipment=[];
 for(let i=0;i<2;i++){const result=await req('/api/hr/assets',{assetTag:'PPL-'+tag.slice(0,8)+'-'+i,name:'People equipment '+i,category:'laptop',condition:'good'});assert.equal(result.status,201);equipment.push(result.asset);assert.equal((await req('/api/hr/assets/'+result.asset.id+'/assign',{employeeId:reader.id})).status,200);if(i===0){assert.equal((await req('/api/me/assets',undefined,'GET',reader.context)).assets.length,1);const ep=await reader.context.newPage();await ep.goto(base);await navigate(ep,'Profile');await ep.locator('.assets-equipment').getByRole('heading',{name:'People equipment 0',exact:true}).waitFor();assert.equal(await ep.locator('.assets-equipment h4').count(),1);await ep.close();}}
 assert.equal((await req('/api/me/assets',undefined,'GET',reader.context)).assets.length,2);assert.equal((await req('/api/me/assets')).assets.length,0);

 const rows=await req('/api/hr/organisation/people?pageSize=25');assert.equal(rows.total,30);assert.equal(rows.people.length,25);assert(!JSON.stringify(rows).includes('password_hash'));assert(!JSON.stringify(rows).includes('salary'));
 assert.equal((await req('/api/hr/organisation/people',undefined,'GET',limited.context)).status,403);
 assert.equal((await req('/api/hr/organisation/roles',{name:'Denied role'},'POST',reader.context)).status,403);
 assert.equal((await req(`/api/hr/organisation/employees/${people[0].id}/placement`,{departmentId:null},'PATCH',reader.context)).status,403);
 assert.equal((await req(`/api/hr/organisation/employees/${people[0].id}/reporting-line`,{managerId:null},'PATCH',reader.context)).status,403);
 assert.equal((await req(`/api/hr/organisation/employees/${people[0].id}/placement`,{departmentId:null},'PATCH',outsider.context)).status,404);
 assert.equal((await req(`/api/hr/organisation/employees/${people[0].id}/reporting-line`,{managerId:null},'PATCH',outsider.context)).status,404);
 assert.equal((await req('/api/hr/organisation/people?search=Directory%20person',undefined,'GET',outsider.context)).total,0);
 async function navigate(p:any,name:string){await p.locator('[data-tutorial-target=stanza-launcher]').click();await p.locator('#stanza-navigation-panel .stanza-navigation-item').filter({hasText:name}).last().click();}
 async function directory(p:any,ar=false){await navigate(p,ar?'الهيكل التنظيمي':'Organisation');await p.locator('[data-tutorial-target=organisation-workspace]').getByRole('button',{name:ar?'الأشخاص والهيكل':'People & Hierarchy',exact:true}).click();await p.locator('.people-row').first().waitFor();}
 const p=await admin.context.newPage();p.setDefaultTimeout(15000);await p.goto(base);await directory(p);
 const search=p.locator('.people-search input');await search.fill('No such employee');await p.getByText('No employees match this search.',{exact:true}).waitFor();await p.getByRole('button',{name:'Clear search',exact:true}).click();await p.locator('.people-row').first().waitFor();
 await p.getByRole('button',{name:'Next',exact:true}).click();await p.locator('.people-pagination').getByText('26–30 / 30 · Page 2',{exact:true}).waitFor();assert(await p.getByRole('button',{name:'Next',exact:true}).isDisabled());await p.getByRole('button',{name:'Previous',exact:true}).click();
 const requests:string[]=[];p.on('request',(r:any)=>{if(r.url().includes('/api/'))requests.push(new URL(r.url()).pathname);});
 await search.fill('Directory person 00');await p.locator('.people-row').filter({hasText:'Directory person 00'}).waitFor();assert.equal(await p.locator('.people-row').count(),1);assert(!requests.some(path=>path.includes('/overview')||path.includes('/departments')||path.includes('/teams')),'search does not reload unrelated organization datasets');
 await p.locator('.people-open').click();let dialog=p.getByRole('dialog',{name:'Employee profile',exact:true});await dialog.getByText('People fixture administrator',{exact:true}).waitFor();await dialog.getByText('Systems Engineer مهندس نظم',{exact:true}).waitFor();await dialog.getByText('People Cairo work site',{exact:true}).waitFor();assert(!await dialog.getByText('Access role',{exact:true}).count());await p.keyboard.press('Escape');await p.locator('.people-open').focus();await p.keyboard.press('Enter');await dialog.waitFor();await dialog.getByRole('button',{name:'Edit Placement',exact:true}).click();dialog=p.getByRole('dialog',{name:'Edit Placement',exact:true});await dialog.waitFor();await dialog.getByRole('combobox',{name:'Job title',exact:true}).selectOption('');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal((await req('/api/hr/organisation/people?search=Directory%20person%2000')).people[0].jobTitleId,title.id);
 await p.locator('.people-row-actions').getByRole('button',{name:'Edit Placement',exact:true}).click();dialog=p.getByRole('dialog',{name:'Edit Placement',exact:true});await dialog.getByRole('combobox',{name:'Job title',exact:true}).selectOption('');await dialog.getByRole('button',{name:'Save',exact:true}).click();await dialog.waitFor({state:'detached'});await p.locator('.people-row').getByText('No job title assigned',{exact:true}).waitFor();assert.equal(Number((await db.query("SELECT count(*) FROM audit_logs WHERE tenant_id=$1 AND entity_id=$2 AND action='organisation.employee_placement.updated'",[primary,people[0].id])).rows[0].count),2);
 await p.locator('.people-row-actions').getByRole('button',{name:'Change Manager',exact:true}).click();dialog=p.getByRole('dialog',{name:'Change Manager',exact:true});await dialog.getByRole('combobox').selectOption('');assert.equal(await dialog.getByRole('checkbox').isChecked(),false);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
 await search.fill('Directory person 01');await p.locator('.people-row').filter({hasText:'Directory person 01'}).waitFor();await p.locator('.people-open').click();dialog=p.getByRole('dialog',{name:'Employee profile',exact:true});await dialog.getByText('No manager assigned',{exact:true}).waitFor();await dialog.getByText('No team assigned',{exact:true}).waitFor();await dialog.getByText('No team work location assigned',{exact:true}).waitFor();await p.keyboard.press('Escape');
 const rp=await reader.context.newPage();await rp.goto(base);await directory(rp);assert.equal(await rp.locator('.people-row-actions').count(),0);await rp.locator('.people-open').first().click();assert.equal(await rp.getByRole('dialog').getByRole('button',{name:'Edit Placement',exact:true}).count(),0);await rp.keyboard.press('Escape');await navigate(rp,'Profile');await rp.locator('.people-self-profile').getByRole('heading',{name:'People fixture reader',exact:true}).waitFor();await rp.locator('.assets-equipment').getByRole('heading',{name:'People equipment 1',exact:true}).waitFor();await rp.getByText('Access role: reader',{exact:true}).click();await rp.locator('.people-self-profile details').getByText('Account role: Employee',{exact:true}).waitFor();
 await search.fill('Directory person 26');await p.locator('.people-row').getByText('Archived',{exact:true}).waitFor();await p.locator('.people-open').click();await p.getByRole('dialog').getByText('Archived',{exact:true}).waitFor();await p.keyboard.press('Escape');
 await p.locator('[data-tutorial-target=organisation-workspace]').getByRole('button',{name:'Hierarchy',exact:true}).click();await p.getByRole('button',{name:'Reporting Lines',exact:true}).click();await p.getByText('People fixture administrator',{exact:true}).first().waitFor();await p.getByText('Directory person 00 العربية',{exact:true}).first().waitFor();
 await p.locator('[data-tutorial-target=organisation-workspace]').getByRole('button',{name:'People & Hierarchy',exact:true}).click();await search.fill('Directory person 00');await p.locator('.people-row').filter({hasText:'Directory person 00'}).waitFor();
 const noEquipment=await admin.context.newPage();await noEquipment.goto(base);await navigate(noEquipment,'Profile');await noEquipment.locator('.assets-equipment').getByText('No equipment assignments found.',{exact:true}).waitFor();await noEquipment.close();
 console.log('PASS actual directory search/empty/reset/server pagination/manager/missing placement/status/public projection/read-only permission and edit Save/Cancel/foreign denial');
 for(const ar of [false,true])for(const width of [390,820,1440])for(const variant of ['dark','light','custom','xl']){
 const c=await browser.newContext({viewport:{width,height:1000},reducedMotion:variant==='xl'?'reduce':'no-preference'});await c.addCookies(await admin.context.cookies());await c.addInitScript(({ar,variant})=>{localStorage.setItem('horizon-language',ar?'ar':'en');localStorage.setItem('horizon-theme',variant==='light'?'light':'dark');localStorage.setItem('stanza.preferences.v1',JSON.stringify({tutorialsAutoStart:false,lanyardEnabled:false,backgroundPreset:variant==='custom'?'custom':'emerald',customTheme:{accent:'#bf52e5'},interfaceScale:variant==='xl'?1.15:1,fontScale:variant==='xl'?1.2:1}));localStorage.setItem('stanza-demo-notice-seen','true');},{ar,variant});
 const page=await c.newPage();page.setDefaultTimeout(15000);await page.goto(base);await directory(page,ar);await page.locator('.people-search input').fill('Directory person 00');await page.waitForFunction(()=>document.querySelector('.people-directory')?.getAttribute('aria-busy')==='false'&&document.querySelectorAll('.people-row').length===1);await page.locator('.people-open').click();const d=page.getByRole('dialog');await d.getByText('People Platform',{exact:true}).waitFor();assert.equal(await d.getAttribute('dir'),ar?'rtl':'ltr');assert.equal(await d.locator('.people-profile>header').evaluate((el:HTMLElement)=>getComputedStyle(el).display),'block');assert.equal(await d.locator('bdi').getAttribute('dir'),'ltr');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:process.env.TEMP+`/stanza-people-${ar?'ar':'en'}-${width}-${variant}.png`,fullPage:true});
 await d.getByRole('button',{name:ar?'تعديل التعيين':'Edit Placement',exact:true}).click();
 const form=page.getByRole('dialog');await form.getByRole('combobox').first().waitFor();for(let i=0;i<9;i++){await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.querySelector('dialog')?.contains(document.activeElement)||document.activeElement===document.body),'native edit dialog never focuses background controls');}assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.keyboard.press('Escape');await navigate(page,ar?'الملف الشخصي':'Profile');await page.locator('.people-self-profile').getByRole('heading',{name:'People fixture administrator',exact:true}).waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));matrix++;console.log('PASS People responsive configuration',matrix,ar?'AR':'EN',width,variant);await c.close();
 }
 console.log('PASS',matrix,'People/profile theme/RTL/390/820/desktop/XL/reduced-motion/modal focus configurations');
 await search.fill('Directory person 00');await p.locator('.people-row').filter({hasText:'Directory person 00'}).waitFor();requests.length=0;await p.waitForTimeout(35000);assert.equal(requests.filter(path=>path.includes('/organisation/')).length,0);console.log('PASS 35 seconds settled directory: zero organization requests');
 await navigate(p,'Profile');await p.locator('.assets-equipment').getByText('No equipment assignments found.',{exact:true}).waitFor();await p.waitForTimeout(2000);requests.length=0;await p.waitForTimeout(35000);assert.equal(requests.filter(path=>path.startsWith('/api/me/')||path.startsWith('/api/profile/')||path.includes('/notifications')||path.includes('/sessions')).length,0);console.log('PASS 35 seconds settled self profile: zero profile/equipment/session/notification requests');
}catch(error){console.error('Verification failed:',error);throw error;}finally{await browser.close();for(const id of tenants){const owned=await db.query("SELECT id FROM tenants WHERE id=$1 AND slug LIKE 'people-polish-%'",[id]);if(!owned.rows.length)throw Error('Fixture ownership lost');await db.query("SELECT set_config('app.current_tenant',$1,false)",[id]);for(const table of ['asset_condition_reports','asset_assignments','assets','organisation_team_memberships','organisation_teams'])await db.query(`DELETE FROM ${table} WHERE tenant_id=$1`,[id]);await db.query('DELETE FROM tenants WHERE id=$1',[id]);}await db.end();}
