import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';import path from 'node:path';
import {buildSync} from 'esbuild';import {runInNewContext} from 'node:vm';
import {setupBadgeKey,validBadgeKey} from './setup-badge-key.mjs';
import {normaliseCustomTheme} from '../src/lib/custom-theme';
import {resolveLanyardAppearance} from '../src/lib/lanyard-appearance';
import {IDENTITY_CARD_ASPECT} from '../src/components/lanyard/IdentityCardArtwork';
import {HELP_ARTICLES} from '../src/components/tutorials/help-registry';
const auto=normaliseCustomTheme({}).lanyardStyle;
assert.equal(auto.appearanceMode,'theme');
const custom=normaliseCustomTheme({lanyardStyle:{cardColor:'#112233'}}).lanyardStyle;
assert.equal(custom.appearanceMode,'custom');assert.equal(custom.cardColor,'#112233');
const green={cardColor:'#061411',accentColor:'#10B981',strapColor:'#10B981'},purple={cardColor:'#1D162B',accentColor:'#9F7AEA',strapColor:'#9F7AEA'};
assert.deepEqual(resolveLanyardAppearance(auto,green),green);assert.deepEqual(resolveLanyardAppearance(auto,purple),purple);
assert.deepEqual(resolveLanyardAppearance(custom,green),resolveLanyardAppearance(custom,purple));
assert.deepEqual(resolveLanyardAppearance({...custom,appearanceMode:'theme'},purple),purple);
assert.equal(normaliseCustomTheme({lanyardStyle:{appearanceMode:'future'}}).lanyardStyle.appearanceMode,'theme');
assert(IDENTITY_CARD_ASPECT>.716&&IDENTITY_CARD_ASPECT<.717);
for(const id of ['semantic-intelligence','semantic-platform'])assert(HELP_ARTICLES.some(a=>a.id===id));
const directory=await mkdtemp(path.join(tmpdir(),'stanza-badge-key-'));
try{await writeFile(path.join(directory,'.env.development.local'),'UNRELATED=value\n');assert((await setupBadgeKey(directory,{})).created);const first=await readFile(path.join(directory,'.env.development.local'),'utf8');assert(first.includes('UNRELATED=value'));assert(validBadgeKey(first.match(/QR_TOKEN_ENCRYPTION_KEY=(.*)/)![1]));assert.equal((await setupBadgeKey(directory,{})).created,false);assert.equal(await readFile(path.join(directory,'.env.development.local'),'utf8'),first);await assert.rejects(setupBadgeKey(directory,{NODE_ENV:'production'}));await writeFile(path.join(directory,'.env.development.local'),'QR_TOKEN_ENCRYPTION_KEY=invalid');await assert.rejects(setupBadgeKey(directory,{}));}finally{await rm(directory,{recursive:true,force:true});}
let calls=0;const queued:Array<{resolve:(r:Response)=>void;signal:AbortSignal}>=[];
const source=buildSync({entryPoints:['src/lib/api.ts'],bundle:true,write:false,format:'cjs',platform:'node',define:{'import.meta.env':'{}'}}).outputFiles[0].text;
const module={exports:{} as any};runInNewContext(source,{module,exports:module.exports,Headers,Response,DOMException,AbortController,fetch:(_input:unknown,init:RequestInit)=>{calls++;return new Promise<Response>((resolve,reject)=>{queued.push({resolve,signal:init.signal!});init.signal!.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')));});}});
const api=module.exports;api.setApiRequestIdentity({id:'one',tenantId:'tenant'});
const abandoned=new AbortController(),first=api.apiFetchShared('/api/clock-status',{signal:abandoned.signal});first.catch(()=>{});abandoned.abort();const second=api.apiFetchShared('/api/clock-status');assert.equal(calls,1);queued[0].resolve(new Response(JSON.stringify({ok:true})));await assert.rejects(first);assert.deepEqual(await (await second).json(),{ok:true});
const fresh=api.apiFetchShared('/api/clock-status');assert.equal(calls,2);queued[1].resolve(new Response('{}'));await fresh;
const old=api.apiFetchShared('/api/clock-status');old.catch(()=>{});api.setApiRequestIdentity({id:'two',tenantId:'different'});await assert.rejects(old);assert(queued[2].signal.aborted);
const next=api.apiFetchShared('/api/clock-status');assert.equal(calls,4);queued[3].resolve(new Response('{}'));await next;
const failing=api.apiFetchShared('/api/clock-status');queued[4].resolve(new Response('{}',{status:503}));assert.equal((await failing).status,503);const retry=api.apiFetchShared('/api/clock-status');assert.equal(calls,6);queued[5].resolve(new Response('{}'));await retry;
const sharedA=api.apiFetchShared('/api/shared'),sharedB=api.apiFetchShared('/api/shared');
assert.equal(calls,7);queued[6].resolve(new Response('{"shared":true}'));
const responses=await Promise.all([sharedA,sharedB]);assert.notEqual(responses[0],responses[1]);
for(const response of responses)assert.deepEqual(await response.json(),{shared:true});
const beforeWrite=api.apiFetchShared('/api/shared');
const mutation=api.apiFetch('/api/update',{method:'POST',signal:new AbortController().signal});
const afterWrite=api.apiFetchShared('/api/shared');assert.equal(calls,10,'A mutation prevents sharing a read started before it');
for(const index of [7,8,9])queued[index].resolve(new Response('{}'));await Promise.all([beforeWrite,mutation,afterWrite]);
console.log('PASS lanyard inheritance/legacy overrides/reset/live resolution, semantic metadata, persistent local key safety and scoped concurrent reads, independent abort, fresh retries and auth boundaries.');
