import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import {runInNewContext} from 'node:vm';
let now=Date.parse('2026-10-09T22:00:00Z'),index=0,id=0,refreshes=0;const slots:any[]=[],timers=new Map<number,{at:number;fn:()=>void}>(),listeners=new Map<string,()=>void>();
const document={hidden:false,addEventListener:(n:string,f:()=>void)=>listeners.set(n,f),removeEventListener:(n:string)=>listeners.delete(n)};
const same=(a:any[],b:any[])=>a&&a.length===b.length&&a.every((v,i)=>v===b[i]);
const react={useRef:(value:any)=>{const n=index++;return slots[n]??=( {current:value});},useMemo:(fn:()=>any,deps:any[])=>{const n=index++;if(!slots[n]||!same(slots[n].deps,deps))slots[n]={deps,value:fn()};return slots[n].value;},useEffect:(fn:()=>any,deps:any[])=>{const n=index++;if(!slots[n]||!same(slots[n].deps,deps)){slots[n]?.cleanup?.();slots[n]={deps,cleanup:fn()};}}};
const module={exports:{} as any};runInNewContext(transformSync(readFileSync('src/hooks/useAttendanceBoundary.ts','utf8'),{loader:'ts',format:'cjs'}).code,{module,exports:module.exports,require:()=>react,Date:{now:()=>now,parse:Date.parse},document,setTimeout:(fn:()=>void,delay:number)=>{assert(delay>0&&delay<=2_147_483_647);timers.set(++id,{at:now+delay,fn});return id;},clearTimeout:(n:number)=>timers.delete(n)});
const render=(server=now,boundary=now+1000,identity='shift')=>{index=0;module.exports.useAttendanceBoundary(new Date(server).toISOString(),new Date(boundary).toISOString(),()=>refreshes++,identity);};
const advance=(ms:number)=>{const end=now+ms;while([...timers.values()].some(t=>t.at<=end)){const [key,t]=[...timers].sort((a,b)=>a[1].at-b[1].at)[0];timers.delete(key);now=t.at;t.fn();}now=end;};
const snapshot=now,boundary=now+1000;render(snapshot,boundary);for(let i=0;i<100;i++)render(snapshot,boundary);assert.equal(timers.size,1);advance(1050);assert.equal(refreshes,1);assert.equal(timers.size,0);
render(now-100, boundary);advance(10000);assert.equal(refreshes,1,'consumed boundary cannot loop on stale responses');render(now,now-100,'past');assert.equal(timers.size,0,'past server boundary never creates an immediate timer');
const overnight=now+6*3600000;render(now,overnight,'overnight');assert.equal(timers.size,1);document.hidden=true;listeners.get('visibilitychange')!();assert.equal(timers.size,0);advance(35000);document.hidden=false;listeners.get('visibilitychange')!();assert.equal(refreshes,2,'stale visibility restoration refreshes once');listeners.get('visibilitychange')!();assert.equal(refreshes,2,'duplicate visibility events are coalesced');assert.equal(timers.size,1,'visibility refresh does not consume a future overnight boundary');advance(6*3600000);assert.equal(refreshes,3);
render(now,now+3_000_000_000,'far-future');advance(2_147_483_647);assert.equal(refreshes,3,'long delays are safely chunked without overflowing or refetching');assert.equal(timers.size,1);for(const slot of slots)slot.cleanup?.();assert.equal(timers.size,0);assert.equal(listeners.size,0);
index=0;module.exports.useAttendanceBoundary(new Date(now-2000).toISOString(),new Date(now-1000).toISOString(),()=>refreshes++,'cached-remount',now-2000);assert.equal(refreshes,4,'cached remount accounts for elapsed time since the response');for(const slot of slots)slot.cleanup?.();
const resumeServer=now;render(resumeServer,now+1000,'hidden-due');document.hidden=true;listeners.get('visibilitychange')!();advance(35000);document.hidden=false;const beforeResume=refreshes;listeners.get('visibilitychange')!();assert.equal(refreshes,beforeResume+1,'stale resume and due boundary share a single refresh');assert.equal(timers.size,0);for(const slot of slots)slot.cleanup?.();
console.log('PASS real attendance hook: 100 stable rerenders, one-shot boundary, stale/past suppression, visibility deduplication, overnight schedule, long-delay chunking and unmount cleanup');// Execute production request helpers, hooks and AttendanceWorkspace with controlled transport.
const pending:Array<{url:string;init:any;resolve:(r:Response)=>void;reject:(e:Error)=>void}>=[];
const apiModule={exports:{} as any};runInNewContext(transformSync(readFileSync('src/lib/api.ts','utf8'),{loader:'ts',format:'cjs',define:{'import.meta.env.VITE_API_BASE_URL':'""'}}).code,{module:apiModule,exports:apiModule.exports,Response,Headers,DOMException,AbortController,fetch:(url:string,init:any)=>new Promise((resolve,reject)=>pending.push({url,init,resolve,reject}))});apiModule.exports.setApiRequestIdentity({id:'user',tenantId:'tenant'});
const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
function harness(file:string){let cursor=0;const values:any[]=[],handlers=new Map<string,Set<()=>void>>();
 const hooks={useState:(value:any)=>{const n=cursor++;values[n]??={value:typeof value==='function'?value():value};return [values[n].value,(v:any)=>{values[n].value=typeof v==='function'?v(values[n].value):v;}];},useRef:(value:any)=>{const n=cursor++;return values[n]??={current:value};},useMemo:(fn:()=>any,deps:any[])=>{const n=cursor++;if(!values[n]||!same(values[n].deps,deps))values[n]={deps,value:fn()};return values[n].value;},useCallback:(fn:any,deps:any[])=>hooks.useMemo(()=>fn,deps),useEffect:(fn:()=>any,deps:any[])=>{const n=cursor++;if(!values[n]||!same(values[n].deps,deps)){values[n]?.cleanup?.();values[n]={deps,cleanup:fn()};}}};
 const events={addEventListener:(name:string,fn:()=>void)=>{if(!handlers.has(name))handlers.set(name,new Set());handlers.get(name)!.add(fn);},removeEventListener:(name:string,fn:()=>void)=>handlers.get(name)?.delete(fn)};
 const m={exports:{} as any};runInNewContext(transformSync(readFileSync(file,'utf8'),{loader:file.endsWith('tsx')?'tsx':'ts',format:'cjs',jsx:'automatic'}).code,{module:m,exports:m.exports,Date:class extends Date{static now(){return now;}},AbortController,document:{...events,visibilityState:'visible',hidden:false},window:{...events,setInterval:()=>{throw Error('Attention polling is forbidden');},clearInterval:()=>{}},navigator:{onLine:true},setInterval:()=>{throw Error('No display timer is needed without an active break');},clearInterval:()=>{},require:(name:string)=>{if(name==='react')return hooks;if(name==='react/jsx-runtime')return {jsx:(type:any,props:any)=>({type,props}),jsxs:(type:any,props:any)=>({type,props})};if(name.endsWith('/api'))return apiModule.exports;if(name.endsWith('/api-response'))return {readApiJson:async(r:Response)=>{if(!r.ok)throw Error('Service unavailable');return r.json();}};if(name.endsWith('/LanguageContext'))return {useLanguage:()=>({isRtl:false})};if(name.endsWith('/dev-performance'))return {beginDevSpan:()=>()=>{},markDevPerformance:()=>{}};if(name.endsWith('/attendance-duration'))return {formatAttendanceDuration:()=>''};throw Error('Unexpected import '+name);}});
 return {run:(name:string,...args:any[])=>{cursor=0;return m.exports[name](...args);},event:(name:string)=>{for(const fn of handlers.get(name)||[])fn();},cleanup:()=>{for(const slot of values)slot.cleanup?.();},restartEffects:()=>{for(const slot of values)if(slot.cleanup){slot.cleanup();slot.deps=undefined;}},values};
}
function resolveReads(){for(const request of pending.splice(0))request.resolve(new Response(JSON.stringify(request.url.includes('/policy')?{attendanceLocationMode:'optional',breakPolicies:[],allowCustomBreaks:true,allowUnfiledBreaks:true}:request.url.includes('/breaks')?{breaks:[],requests:[]}:{success:true,requests:[],counts:{hiring:2}}),{headers:{'Content-Type':'application/json'}}));}
const attention=harness('src/hooks/useDashboardAttentionCounts.ts');attention.run('useDashboardAttentionCounts',{id:'user',tenantId:'tenant'});attention.restartEffects();attention.run('useDashboardAttentionCounts',{id:'user',tenantId:'tenant'});assert.equal(pending.length,1,'StrictMode replays share one physical request');resolveReads();await flush();for(let i=0;i<100;i++)attention.run('useDashboardAttentionCounts',{id:'user',tenantId:'tenant'});assert.equal(pending.length,0,'attention counts do not refetch on fresh object rerenders');now+=31000;attention.event('focus');attention.event('visibilitychange');assert.equal(pending.length,1,'focus and visibility coalesce');resolveReads();await flush();attention.cleanup();assert.equal(pending.length,0);
const workspace=harness('src/components/attendance/AttendanceWorkspace.tsx');let revision=0;const props={employeeId:'user',hasShift:true,canRequest:true,canTeam:false,offline:false,onPolicy:()=>{},onBreakState:()=>{},onChange:()=>revision++,refreshKey:0};
workspace.run('AttendanceWorkspace',props);assert.equal(pending.length,3);resolveReads();await flush();for(let i=0;i<100;i++)workspace.run('AttendanceWorkspace',{...props});assert.equal(pending.length,0,'100 attendance rerenders create no reads');
const nodes=(node:any):any[]=>!node||typeof node!=='object'?[]:[node,...(Array.isArray(node.props?.children)?node.props.children:[node.props?.children]).flatMap(nodes)];const tree=workspace.run('AttendanceWorkspace',props);const startBreak=nodes(tree).find(n=>n.type==='button'&&n.props.children==='Pause / Start break');assert(startBreak);startBreak.props.onClick();assert.equal(pending.length,1);assert.equal(pending[0].init.method,'POST');resolveReads();await flush();assert.equal(revision,1);assert.equal(pending.length,0,'mutation does not also perform an independent load before invalidation');workspace.run('AttendanceWorkspace',{...props,refreshKey:revision});assert.equal(pending.length,3,'one logical mutation refreshes exactly one attendance batch');resolveReads();await flush();
workspace.run('AttendanceWorkspace',{...props,refreshKey:2});for(const request of pending.splice(0))request.reject(new Error('offline'));await flush();const failed=workspace.run('AttendanceWorkspace',{...props,refreshKey:2});assert(nodes(failed).some(n=>n.props?.role==='alert'),'service failure is visible');for(let i=0;i<100;i++)workspace.run('AttendanceWorkspace',{...props,refreshKey:2});assert.equal(pending.length,0,'failure never starts a retry loop');workspace.run('AttendanceWorkspace',{...props,refreshKey:3});resolveReads();await flush();assert(!nodes(workspace.run('AttendanceWorkspace',{...props,refreshKey:3})).some(n=>n.props?.role==='alert'),'explicit refresh recovers');workspace.cleanup();
const {shouldRestart}=await import('./dev-watch.mjs');for(const file of ['.cache/model.onnx','dist/server.cjs','node_modules/.vite/deps/_metadata.json','src/pages/Dashboard.tsx','src/components/attendance/AttendanceActions.tsx','vite.config.ts','public/fonts.css','uploads/a.webp'])assert(!shouldRestart(file),file);for(const file of ['server.ts','src/server/attendance/attendance-state.ts','src/lib/request-context.ts','.env.development.local','src/workers/hr-worker.ts'])assert(shouldRestart(file),file);
const scripts=JSON.parse(readFileSync('package.json','utf8')).scripts;assert.equal(scripts.preview,'npm run preview:full');assert.equal(scripts['preview:frontend'],'vite preview');assert(scripts.dev.includes('--kill-others'));assert(scripts.start.includes("NODE_ENV='production'"));assert(readFileSync('vite.config.ts','utf8').includes('clearScreen: false'));
console.log('PASS real attendance/attention hooks and shared transport: StrictMode sharing, 100 stable rerenders, no polling, visibility dedup, single mutation batch, visible API failure/manual recovery, watcher scope and preview/production commands');
