import './router-env';
import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import express from 'express';import {once} from 'node:events';
import {getMigrationPool} from './migration-pool';import {assertDatabaseMutationSafety} from './mutation-safety';import {withTenant,closeHrResources} from '../src/lib/hr-background';
import {registerSemanticAdminRoutes} from '../src/server/intelligent-router/semantic-admin';import {PgSemanticSearch} from '../src/server/intelligent-router/store';import {sanitizeShared,analyzeExample} from '../src/server/intelligent-router/semantic-privacy';import {getPermissionDefinition} from '../src/server/organisation/permission-registry';import {generalizeEntities,findEntitySpan} from '../src/lib/router-entities';
assertDatabaseMutationSafety(process.env.DATABASE_URL,'Semantic admin integration');
const db=getMigrationPool(),tag=randomUUID(),tenants:string[]=[],globalExamples:string[]=[],actors=new Map<string,NonNullable<express.Request['authUser']>>();let embeds=0;
const provider={model:'semantic-admin-'+tag,version:'fixture-v1',dimensions:3,embed:async(text:string)=>{embeds++;return text.includes('resolved conduct')?[0,0,1]:text.includes('paid')||text.includes('payday')||text.includes('salary')?[1,0,0]:[0,1,0];}};
const app=express();app.use(express.json());registerSemanticAdminRoutes(app,{standardAuth:(req,res,next)=>{const a=actors.get(String(req.headers['x-test-actor']));if(!a){res.status(401).json({});return;}req.authUser=a;next();},mutationGuard:(_r,_s,n)=>n(),rateLimiter:(_r,_s,n)=>n()},provider);
const server=app.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert(address&&typeof address!=='string');const base='http://127.0.0.1:'+address.port;
async function api(actor:string,path:string,body?:object){const response=await fetch(base+'/api/semantic-intelligence'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','x-test-actor':actor},body:body?JSON.stringify(body):undefined});return {status:response.status,...await response.json()};}
async function person(t:string,name:string,keys:string[],platform=false){const browser=process.env.SEMANTIC_BROWSER_FIXTURE==='true';const hash=browser?(await db.query("SELECT password_hash FROM employees WHERE email='admin@stanza-demo.com' LIMIT 1")).rows[0]?.password_hash:'fixture-no-login';assert(hash);const email=browser?`${name}@semantic-fixture.invalid`:`${name}-${tag}@example.invalid`;const employee=(await db.query("INSERT INTO employees(tenant_id,email,full_name,role,password_hash) VALUES($1,$2,$3,$4,$5) RETURNING id",[t,email,'Semantic fixture '+name,keys.length>1?'hr_admin':'employee',hash])).rows[0].id;const role=(await db.query('INSERT INTO tenant_roles(tenant_id,name,is_system) VALUES($1,$2,false) RETURNING id',[t,name])).rows[0].id;for(const k of keys)await db.query('INSERT INTO tenant_role_permissions(tenant_id,role_id,permission_key) VALUES($1,$2,$3)',[t,role,k]);await db.query("INSERT INTO employee_role_assignments(tenant_id,employee_id,role_id,scope_type) VALUES($1,$2,$3,'company')",[t,employee,role]);if(platform)await db.query("INSERT INTO router_platform_authorities VALUES($1,$2,ARRAY['view_all','review_global','manage_global','view_tenants','manage_models'],NULL)",[t,employee]);actors.set(name,{tenantId:t,employeeId:employee,role:'hr_admin',email,permissions:['platform.semantic.view_all']});return employee;}
async function example(t:string|null,text:string,intent='employee_grievance_lookup',template:unknown=null,scope=t?'TENANT_PRIVATE':'SYSTEM',vector=[0,1,0]){const id=(await db.query(`INSERT INTO router_semantic_examples(tenant_id,scope,source,intent_key,example_text,normalized_text,embedding,embedding_model,embedding_version,embedding_dimensions,approval_state,entity_template) VALUES($1,$2,$3,$4,$5,$5,$6::vector,$7,'fixture-v1',3,'approved',$8::jsonb) RETURNING id`,[t,scope,scope==='SYSTEM'?'system':scope==='SHARED'?'shared':'tenant',intent,text,JSON.stringify(vector),provider.model,template?JSON.stringify(template):null])).rows[0].id;if(!t)globalExamples.push(id);return id;}
try{
 for(const n of ['a','b'])tenants.push((await db.query('INSERT INTO tenants(slug,company_name) VALUES($1,$2) RETURNING id',[`semantic-admin-${n}-${tag}`,'Semantic fixture '+n])).rows[0].id);const [a,b]=tenants;
 const permissions=['semantic.view_analytics','semantic.review_candidates','semantic.manage_examples','semantic.manage_privacy'];const admin=await person(a,'admin',permissions);await person(a,'employee',[]);await person(a,'restricted',['semantic.view_analytics']);await person(b,'other-admin',permissions);await person(b,'platform',permissions,true);
 assert.equal((await api('employee','/overview')).status,403);assert.equal((await api('restricted','/privacy')).status,403);assert.equal((await api('admin','/platform/tenants')).status,403,'forged platform claim/HR role has no platform authority');assert.equal((await api('other-admin','/platform/overview')).status,403);
 for(const k of ['view_all','review_global','manage_global','view_tenants','manage_models']){const p=getPermissionDefinition('platform.semantic.'+k)!;assert(p.protected&&!p.delegatable);}
 await withTenant(a,async c=>{await assert.rejects(c.query("INSERT INTO router_platform_authorities VALUES($1,$2,ARRAY['view_all'],NULL)",[a,admin]),e=>(e as {code:string}).code==='42501');});
 await withTenant(a,async c=>{const role=(await c.query('SELECT role_id FROM employee_role_assignments WHERE tenant_id=$1 AND employee_id=$2 LIMIT 1',[a,admin])).rows[0].role_id;await assert.rejects(c.query("INSERT INTO tenant_role_permissions(tenant_id,role_id,permission_key) VALUES($1,$2,'platform.semantic.view_all')",[a,role]),e=>(e as {code:string}).code==='42501');});
 const raw="show me Ahmed Hassan's grievance from Cairo Warehouse",template=generalizeEntities(raw,[{type:'employee',status:'resolved',evaluated:1,latencyMs:0,span:findEntitySpan(raw,'Ahmed Hassan','employee')},{type:'location',status:'resolved',evaluated:1,latencyMs:0,span:findEntitySpan(raw,'Cairo Warehouse','location')}])!;
 assert(sanitizeShared(template.text,template));for(const bad of ['show me Ahmed Hassan grievance','show me a@b.com grievance','call +201234567890','payroll 5000 EGP','case GRV-2026-000001','open '+randomUUID(),'show me Horizon company feed','medical leave cancer','project Orion status'])assert(!sanitizeShared(bad),bad);
 const learnedText='please find resolved conduct grievance for {employee} from {location}';const learnedTemplate={version:1 as const,text:learnedText,placeholders:[...learnedText.matchAll(/\{(employee|location)\}/g)].map(m=>({type:m[1] as 'employee'|'location',start:m.index!,end:m.index!+m[0].length}))};
 const learnedCandidate=(await db.query("INSERT INTO router_candidates(tenant_id,employee_id,normalized_query,proposed_intent,confirmation_state,entity_template,resolution_source) VALUES($1,$2,$3,'employee_grievance_lookup','confirmed',$4::jsonb,'entity') RETURNING id",[a,admin,learnedText.replaceAll(/[{}]/g,''),JSON.stringify(learnedTemplate)])).rows[0].id;
 assert.equal((await api('admin',`/candidates/${learnedCandidate}/review`,{decision:'approve'})).promoted,true);
 const learned=(await db.query('SELECT example_text,source_candidate_id FROM router_semantic_examples WHERE source_candidate_id=$1',[learnedCandidate])).rows[0];assert.equal(learned.example_text,learnedText);assert.equal(learned.source_candidate_id,learnedCandidate);
 const ex=await example(a,template.text,'employee_grievance_lookup',template);const foreign=await example(b,'show my employee complaint');
 assert.equal((await api('admin',`/examples/${ex}/contribute`,{confirm:true})).code,'PRIVATE_MODE');assert.equal((await api('admin','/privacy',{mode:'SHARED'})).status,409);assert.equal((await api('admin','/privacy',{mode:'SHARED',confirm:true})).status,200);
 assert.equal((await db.query('SELECT count(*) FROM router_shared_candidates WHERE tenant_id=$1',[a])).rows[0].count,'0','changing privacy never submits old examples');
 assert.equal((await api('admin',`/examples/${ex}/contribute`,{confirm:true})).created,true);assert.equal((await api('admin',`/examples/${ex}/contribute`,{confirm:true})).created,false);
 const shared=(await db.query('SELECT * FROM router_shared_candidates WHERE source_example_id=$1',[ex])).rows[0];assert(!JSON.stringify({text:shared.generalized_text,template:shared.entity_template}).includes('Ahmed'));assert(!shared.generalized_text.includes('Cairo'));
 const review=(await api('platform','/platform/shared-review')).candidates.find((r:{id:string})=>r.id===shared.id);assert(review);assert.equal((await api('admin',`/platform/shared-review/${shared.id}`,{decision:'approve',confirm:true})).status,403);
 await api('admin','/privacy',{mode:'PRIVATE',confirm:true});assert.equal((await api('platform',`/platform/shared-review/${shared.id}`,{decision:'approve',confirm:true})).code,'PRIVATE_MODE');await api('admin','/privacy',{mode:'SHARED',confirm:true});
 assert.equal((await api('platform',`/platform/shared-review/${shared.id}`,{decision:'approve',confirm:true})).promoted,true);const sharedEx=(await db.query('SELECT shared_example_id FROM router_shared_candidates WHERE id=$1',[shared.id])).rows[0].shared_example_id;globalExamples.push(sharedEx);
 assert.equal((await db.query('SELECT scope FROM router_semantic_examples WHERE id=$1',[ex])).rows[0].scope,'TENANT_PRIVATE');assert.equal((await api('other-admin',`/examples/${ex}/action`,{action:'delete',confirm:true})).status,404);
 const system=await example(null,'when is payday','next_payday',null,'SYSTEM',[1,0,0]);
 await api('other-admin','/privacy',{mode:'STRICT_PRIVATE',confirm:true});let hits=await new PgSemanticSearch(b,32).search([0,1,0],provider,['employee_grievance_lookup']);assert(hits.every(h=>h.exampleId!==sharedEx));assert(hits.some(h=>h.exampleId===foreign));assert((await new PgSemanticSearch(b,32).search([1,0,0],provider,['next_payday'])).some(h=>h.exampleId===system));
 await api('other-admin','/privacy',{mode:'PRIVATE',confirm:true});hits=await new PgSemanticSearch(b,32).search([0,1,0],provider,['employee_grievance_lookup']);assert(hits.some(h=>h.exampleId===sharedEx));assert(hits.every(h=>h.exampleId!==ex));
 const confidential=await example(a,'show employee grievance for secret-company');assert.equal((await api('admin',`/examples/${confidential}/contribute`,{confirm:true})).code,'SENSITIVE');
 // Exact duplicate avoids embedding, same-intent near duplicate is flagged, opposing intent is a conflict.
 embeds=0;const exact=await withTenant(a,c=>analyzeExample(c,a,'when is payday','next_payday',provider));assert.equal(exact.classification,'exact_duplicate');assert.equal(embeds,0);
 assert.equal((await withTenant(a,c=>analyzeExample(c,a,'when do we get paid','next_payday',provider))).classification,'near_duplicate');assert.equal((await withTenant(a,c=>analyzeExample(c,a,'what date salary paid','leave_balance',provider))).classification,'cross_intent_conflict');
 const candidate=(await db.query(`INSERT INTO router_candidates(tenant_id,employee_id,normalized_query,proposed_intent,confirmation_state) VALUES($1,$2,'when do we get paid','next_payday','confirmed') RETURNING id`,[a,admin])).rows[0].id;
 assert.equal((await api('admin',`/candidates/${candidate}/analyze`,{})).analysis.classification,'near_duplicate');assert.equal((await api('admin',`/candidates/${candidate}/review`,{decision:'approve'})).code,'DUPLICATE');assert.equal((await api('admin',`/candidates/${candidate}/review`,{decision:'dismiss_duplicate'})).status,200);
 for(const t of [a,b])await withTenant(t,async c=>{const other=t===a?b:a;for(const table of ['router_semantic_examples','router_candidates','router_review_history','router_daily_metrics','router_example_hits','router_privacy_settings','router_http_metrics'])assert.equal((await c.query(`SELECT * FROM ${table} WHERE tenant_id=$1`,[other])).rowCount,0,table);});
 const before=(await db.query('SELECT count(*) FROM router_review_history WHERE tenant_id=$1',[b])).rows[0].count;assert.equal((await api('platform',`/platform/tenants/${a}`)).status,200);assert(Number((await db.query('SELECT count(*) FROM router_review_history WHERE tenant_id=$1',[b])).rows[0].count)>Number(before));
 assert.equal((await api('admin','/platform/corpus?scope=SYSTEM')).status,403);assert.equal((await api('platform',`/platform/corpus/${system}`,{action:'deactivate',confirm:true})).status,200);assert.equal((await db.query('SELECT approval_state FROM router_semantic_examples WHERE id=$1',[system])).rows[0].approval_state,'disabled');assert.equal((await api('platform',`/platform/corpus/${system}`,{action:'reactivate',confirm:true})).status,200);assert.equal((await api('platform','/platform/corpus?scope=SHARED')).status,200);assert.equal((await api('platform','/platform/overview')).status,200);assert.equal((await api('admin','/overview')).status,200);assert.equal((await api('admin','/history')).status,200);assert.equal((await api('restricted','/examples')).status,403);
 console.log('PASS real stanza_runtime tenant isolation, operator-only platform authority, privacy modes, separate shared promotion, sanitization, duplicates/conflicts, audit history and analytics. Embedding vectors here are deterministic contract fixtures.');
 if(process.env.SEMANTIC_BROWSER_FIXTURE==='true')console.log(JSON.stringify({browserFixtureTenants:tenants,globalFixtureExamples:globalExamples,emails:[...actors.values()].map(a=>a.email)}));
}finally{await new Promise<void>(r=>server.close(()=>r()));if(process.env.SEMANTIC_BROWSER_FIXTURE!=='true'){await db.query('DELETE FROM router_semantic_examples WHERE id=ANY($1::uuid[])',[globalExamples]);for(const t of tenants){await db.query('DELETE FROM router_operational_metrics WHERE tenant_id=$1',[t]);await db.query('DELETE FROM tenants WHERE id=$1',[t]);}}await db.end();await closeHrResources();}
