import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const migration = await readFile('src/db/migrations/20260728_add_shift_swap_requests.sql', 'utf8');
const rosterParentMigration = await readFile('src/db/migrations/20260728_add_roster_shift_tenant_key.sql', 'utf8');
const approvalMigration = await readFile('src/db/migrations/20260728_add_shift_swap_approval_context.sql', 'utf8');
const routes = await readFile('src/server/roster/shift-swap-routes.ts', 'utf8');
const registry = await readFile('src/server/organisation/permission-registry.ts', 'utf8');
assert.match(migration, /CREATE TABLE IF NOT EXISTS shift_swap_requests/);
assert.match(migration, /BEGIN;/);
assert.match(migration, /COMMIT;/);
assert.match(rosterParentMigration, /roster_shifts_id_tenant_unique/);
assert.match(rosterParentMigration, /UNIQUE \(id, tenant_id\)/);
assert.match(migration, /REFERENCES roster_shifts\(id, tenant_id\)/);
assert.match(migration, /REFERENCES employees\(id, tenant_id\)/);
assert.match(migration, /shift_swap_requests_id_tenant_unique/);
assert.match(migration, /shift_swap_requests_requester_active_shift_unique/);
assert.match(migration, /shift_swap_requests_target_active_shift_unique/);
assert.match(migration, /ENABLE ROW LEVEL SECURITY/);
assert.match(routes, /\/api\/me\/shift-swaps/);
assert.match(routes, /FOR UPDATE/);
assert.match(routes, /Each employee must own the selected shift/);
assert.match(routes, /Only future scheduled shifts can be swapped/);
assert.match(routes, /resulting schedules would overlap/);
assert.match(routes, /pending_target/);
assert.match(routes, /pending_approval/);
assert.match(routes, /target_declined/);
assert.match(routes, /roster\.shift_swap\.requested/);
assert.match(routes, /roster\.shift_swap\.target_accepted/);
assert.match(routes, /roster\.shift_swap\.target_declined/);
assert.match(routes, /\/api\/me\/shift-swaps\/:swapId\/cancel/);
assert.match(routes, /Only the requester may cancel/);
assert.match(routes, /roster\.shift_swap\.cancelled/);
assert.match(routes, /\/api\/me\/shift-swaps\/:swapId/);
assert.match(routes, /shift_swap_history/);
assert.match(approvalMigration, /approver_employee_id/);
assert.match(approvalMigration, /BEGIN;/);
assert.match(approvalMigration, /COMMIT;/);
assert.match(approvalMigration, /approval_source/);
assert.match(approvalMigration, /approved_at/);
assert.match(approvalMigration, /rejected_at/);
assert.match(approvalMigration, /'approved','rejected'/);
assert.match(approvalMigration, /shift_swap_requests_approver_tenant_fk/);
assert.match(approvalMigration, /roster\.swap\.approve/);
assert.match(registry, /roster\.swap\.view_scoped/);
assert.match(routes, /resolveApprovalChain/);
assert.match(routes, /excludedEmployeeIds/);
assert.match(routes, /\/api\/hr\/shift-swaps/);
assert.match(routes, /roster\.swap\.manage/);
assert.match(routes, /expectedVersion/);
assert.match(routes, /approval_conflict/);
assert.match(routes, /notification\.shift_swap_approval_required/);
assert.match(routes, /notification\.shift_swap_approved/);
assert.match(routes, /notification\.shift_swap_rejected/);
assert.match(routes, /status='pending_approval'/);
console.log('Shift-swap lifecycle and approval routing contracts passed: 34');
