import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const migration = await readFile('src/db/migrations/20260728_add_shift_swap_requests.sql', 'utf8');
const routes = await readFile('src/server/roster/shift-swap-routes.ts', 'utf8');
assert.match(migration, /CREATE TABLE IF NOT EXISTS shift_swap_requests/);
assert.match(migration, /shift_swap_requests_requester_active_shift_unique/);
assert.match(migration, /shift_swap_requests_target_active_shift_unique/);
assert.match(migration, /ENABLE ROW LEVEL SECURITY/);
assert.match(routes, /\/api\/me\/shift-swaps/);
assert.match(routes, /FOR UPDATE/);
assert.match(routes, /Each employee must own the selected shift/);
assert.match(routes, /Only future scheduled shifts can be swapped/);
assert.match(routes, /resulting schedules would overlap/);
assert.match(routes, /pending_target/);
assert.match(routes, /pending_approval/);
assert.match(routes, /target_declined/);
assert.match(routes, /roster\.shift_swap\.requested/);
assert.match(routes, /roster\.shift_swap\.target_accepted/);
assert.match(routes, /roster\.shift_swap\.target_declined/);
console.log('Shift-swap lifecycle contracts passed: 14');
