import {createRequire} from 'node:module';
import './router-env';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import {getMigrationPool} from './migration-pool';
import { assertDatabaseMutationSafety, assertHttpMutationSafety } from './mutation-safety';
import { getDbPool, getHrQueue } from '../src/lib/hr-background';
const base=assertHttpMutationSafety(process.env.SUPPORT_TEST_BASE_URL||'http://localhost:3001','Support browser');
assertDatabaseMutationSafety(process.env.DATABASE_URL,'Support browser');
const pool=getMigrationPool();
const tenants:string[]=[];const password=crypto.randomBytes(20).toString('base64url');const tag=crypto.randomUUID();
type Person={id:string;tenantId:string;email:string;cookie:string};
async function call(u:Person|null,path:string,body?:unknown,method='POST',origin=base) {
 const r=await fetch(base+path,{method:body===undefined?'GET':method,headers:{...(u?{Cookie:u.cookie}:{}),Origin:origin,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 assert.match(r.headers.get('content-type') || '', /^application\/json\b/, `${path} must return API JSON, not the SPA document`);
 return {status:r.status,body:await r.json()};
}
async function ok(u:Person,path:string,body?:unknown,method='POST') {const r=await call(u,path,body,method);assert(r.status<300,`${path}: ${r.status} ${JSON.stringify(r.body)}`);return r.body;}
async function person(tenantId:string,name:string,permissions:string[],scope='company',manager?:Person):Promise<Person> {
 const email=`${name}-${tag}@example.invalid`;
 const row=(await pool.query(`INSERT INTO employees(tenant_id,email,full_name,password_hash,role,manager_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[tenantId,email,'Support test '+name,await bcrypt.hash(password,10),name==='admin'?'hr_admin':name==='manager'?'manager':'employee',manager?.id||null])).rows[0];
 const role=(await pool.query(`INSERT INTO tenant_roles(tenant_id,name) VALUES($1,$2) RETURNING id`,[tenantId,name])).rows[0];
 for(const permission of permissions)await pool.query('INSERT INTO tenant_role_permissions(tenant_id,role_id,permission_key) VALUES($1,$2,$3)',[tenantId,role.id,permission]);
 await pool.query('INSERT INTO employee_role_assignments(tenant_id,employee_id,role_id,scope_type) VALUES($1,$2,$3,$4)',[tenantId,row.id,role.id,scope]);
 const r=await fetch(base+'/api/auth/login',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:JSON.stringify({email,password})});assert.equal(r.status,200,'Fixture login');const signedIn=(await r.json()).user;assert.equal(signedIn.tenantId,tenantId,'Fixture cookie must belong to the intended tenant');assert.equal(signedIn.id,row.id,'Fixture cookie must belong to the intended employee');
 return {id:row.id,tenantId,email,cookie:r.headers.get('set-cookie')!.split(';')[0]};
}
const {chromium}=createRequire(import.meta.url)(process.env.BROWSER_PLAYWRIGHT_MODULE||'C:/Users/10/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'});
try {
 const tenant=(await pool.query('INSERT INTO tenants(slug,company_name) VALUES($1,$2) RETURNING id',['support-browser-'+tag,'Support browser fixture'])).rows[0].id;tenants.push(tenant);
 const other=(await pool.query('INSERT INTO tenants(slug,company_name) VALUES($1,$2) RETURNING id',['support-foreign-'+tag,'Foreign support fixture'])).rows[0].id;tenants.push(other);
 const manager=await person(tenant,'manager',['support.view','support.manage','assets.view']);const emp=await person(tenant,'employee',[]);const foreign=await person(other,'foreign',[]);
 async function pageFor(u:Person,width=1440,ar=false,preset='emerald',light=false,xl=false){const c=await browser.newContext({viewport:{width,height:width<500?844:1000},reducedMotion:width===1440?'no-preference':'reduce'});await c.addCookies([{name:u.cookie.split('=')[0],value:u.cookie.substring(u.cookie.indexOf('=')+1),url:base}]);await c.addInitScript(({ar,preset,light,xl})=>{localStorage.setItem('stanza.preferences.v1',JSON.stringify({tutorialsAutoStart:false,lanyardEnabled:false,backgroundPreset:preset,customTheme:{accent:'#bf52e5'},interfaceScale:xl?1.15:1,fontScale:xl?1.2:1}));localStorage.setItem('horizon-language',ar?'ar':'en');localStorage.setItem('horizon-theme',light?'light':'dark');localStorage.setItem('stanza-demo-notice-seen','true');},{ar,preset,light,xl});const p=await c.newPage();p.setDefaultTimeout(15000);await p.goto(base);await p.locator('[data-tutorial-target="geo-clock"]').waitFor();await p.keyboard.press('Control+k');await p.getByPlaceholder(/Search commands or ask Stanza|ابحث عن أمر أو اسأل Stanza/).fill('support');await p.getByRole('option').filter({hasText:ar?'الدعم التقني والمعدات':'IT & equipment support'}).first().click();await p.getByRole('heading',{name:ar?'الدعم التقني والمعدات':'IT & equipment support',exact:true}).waitFor();return p;}
 async function capture(p:any,name:string){await p.screenshot({path:process.env.TEMP+'/stanza-support-'+name+'.png',fullPage:true});}
 const p=await pageFor(manager);await p.getByRole('button',{name:'Company support queue',exact:true}).click();await p.getByText(/No requests here yet|No tickets/).waitFor();await capture(p,'empty-before');
 const asset=(await pool.query("INSERT INTO assets(tenant_id,asset_tag,name,category,status) VALUES($1,'SUP-001','Fixture laptop','laptop','assigned') RETURNING id",[tenant])).rows[0].id;await pool.query('INSERT INTO asset_assignments(tenant_id,asset_id,employee_id) VALUES($1,$2,$3)',[tenant,asset,emp.id]);
 const ticket=(await ok(emp,'/api/support',{assetId:asset,issueType:'equipment_issue',summary:'Laptop screen needs repair',description:'Fictional screen repair request',urgency:'high'})).ticket;
 await ok(emp,'/api/support/'+ticket.id+'/comments',{note:'Requester follow-up fixture',visibility:'requester'});await ok(manager,'/api/support/'+ticket.id+'/comments',{note:'Private diagnosis fixture',visibility:'internal'});
 await pool.query("UPDATE support_tickets SET assigned_to=NULL,created_at=now()-interval '8 days' WHERE id=$1",[ticket.id]);
 const progress=(await ok(emp,'/api/support',{issueType:'it_help',summary:'VPN connectivity issue',description:'Fictional VPN support request',urgency:'normal'})).ticket;await ok(manager,'/api/support/'+progress.id+'/update',{status:'in_progress',assignedTo:manager.id,note:'Checking network'});
 const resolved=(await ok(emp,'/api/support',{issueType:'it_help',summary:'Printer setup completed',description:'Fictional printer setup request',urgency:'normal'})).ticket;await ok(manager,'/api/support/'+resolved.id+'/update',{status:'resolved',note:'Printer configured'});
 await p.getByRole('button',{name:'Refresh',exact:true}).click();await p.getByText('Laptop screen needs repair',{exact:true}).waitFor();await capture(p,'queue-before');
 {
 await p.keyboard.press('Control+k');await p.getByPlaceholder('Search commands or ask Stanza…').fill('which open IT tickets are older than 3 days?');await p.locator('[data-entity-status=resolved]').waitFor();assert.match(await p.locator('[data-entity-status=resolved]').innerText(),/Laptop screen needs repair/);await p.keyboard.press('Escape');
 await p.locator('.support-ticket-row').filter({hasText:'Opened 8d'}).waitFor();await capture(p,'queue-desktop');await p.locator('.support-more-filters summary').click();await p.getByRole('combobox',{name:'Ticket age',exact:true}).selectOption('7');await p.getByText('Showing 1 of 1 requests',{exact:true}).waitFor();assert.equal(await p.locator('.support-ticket-row').count(),1);await p.getByRole('button',{name:'Clear filters',exact:true}).click();
 await p.getByRole('combobox',{name:/Assignment filter/}).selectOption('mine');await p.getByRole('button',{name:'Remove filter: Assignment: Assigned to me',exact:true}).waitFor();await p.getByText('Showing 2 of 2 requests',{exact:true}).waitFor();assert.equal(await p.locator('.support-ticket-row').count(),2);await capture(p,'assigned-to-me');await p.getByRole('button',{name:'Clear filters',exact:true}).click();
 await p.getByLabel('Search summary',{exact:true}).fill('Impossible fixture match');await p.getByText('No tickets match these filters.',{exact:true}).waitFor();await p.getByRole('button',{name:'Clear filters',exact:true}).click();await p.locator('.support-ticket-row').filter({hasText:'Laptop screen needs repair'}).waitFor();
 const requests:string[]=[];const record=(r:any)=>{if(new URL(r.url()).pathname.startsWith('/api/'))requests.push(new URL(r.url()).pathname);};p.on('request',record);
 const row=p.getByRole('button',{name:'Open ticket: Laptop screen needs repair',exact:true});const beforeHover=await row.boundingBox();await row.hover();await p.waitForTimeout(200);assert.deepEqual(await row.boundingBox(),beforeHover,'Hover must not move ticket rows');await p.keyboard.press('Tab');await row.focus();assert(await row.evaluate((e:HTMLElement)=>e.matches(':focus-visible')));assert.match(await row.evaluate((e:HTMLElement)=>(e.getAttribute('aria-describedby')||'').split(' ').map(id=>document.getElementById(id)?.textContent||'').join(' ')),/Open.*Unassigned.*8d/);await p.keyboard.press('Enter');let dialog=p.getByRole('dialog',{name:'Laptop screen needs repair',exact:true});await dialog.getByText('Private diagnosis fixture',{exact:true}).waitFor();await p.waitForTimeout(500);p.off('request',record);assert.deepEqual(requests,['/api/support/'+ticket.id],'Ticket selection fetches only its detail');assert.equal(await row.getAttribute('aria-pressed'),'true');
 await dialog.getByRole('heading',{name:'Equipment context',exact:true}).waitFor();await dialog.getByText('Requester follow-up fixture',{exact:true}).waitFor();await capture(p,'detail-desktop');await dialog.getByRole('button',{name:'Show equipment tickets',exact:true}).click();await p.getByText('Showing 1 of 1 requests',{exact:true}).waitFor();await p.getByRole('button',{name:'Remove filter: Equipment: Fixture laptop',exact:true}).waitFor();await p.getByRole('button',{name:'Clear filters',exact:true}).click();await row.click();dialog=p.getByRole('dialog');await dialog.getByRole('button',{name:'Show requester’s tickets',exact:true}).click();await p.getByText('Showing 3 of 3 requests',{exact:true}).waitFor();await p.getByRole('button',{name:'Remove filter: Requester: Support test employee',exact:true}).waitFor();await p.getByRole('button',{name:'Clear filters',exact:true}).click();await row.click();dialog=p.getByRole('dialog');
 await dialog.locator('.support-update summary').click();await dialog.getByRole('combobox',{name:/Assigned handler/}).selectOption(manager.id);await dialog.getByRole('button',{name:'Save update',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.equal((await ok(manager,'/api/support/'+ticket.id)).ticket.assigned_to,manager.id);
 await row.click();dialog=p.getByRole('dialog');await dialog.getByRole('textbox',{name:'Reply to requester',exact:true}).fill('Draft retained across modes');await dialog.getByRole('button',{name:'Internal note',exact:true}).click();assert.equal(await dialog.getByRole('textbox',{name:'Internal note',exact:true}).inputValue(),'Draft retained across modes');assert.equal(await dialog.getByRole('button',{name:'Internal note',exact:true}).getAttribute('aria-pressed'),'true');await dialog.getByText(/Only authorized support handlers/).waitFor();await capture(p,'internal-composer');await dialog.getByRole('button',{name:'Reply to requester',exact:true}).click();assert.equal(await dialog.getByRole('textbox',{name:'Reply to requester',exact:true}).inputValue(),'Draft retained across modes');await dialog.getByRole('button',{name:'Internal note',exact:true}).click();await dialog.getByRole('button',{name:'Save internal note',exact:true}).click();await dialog.getByText('Draft retained across modes',{exact:true}).waitFor();
 await dialog.getByRole('button',{name:'Reply to requester',exact:true}).click();await dialog.getByRole('textbox',{name:'Reply to requester',exact:true}).fill('Public reply browser fixture');let releaseReply!:()=>void;const heldReply=new Promise<void>(r=>releaseReply=r);await p.route('**/api/support/'+ticket.id+'/comments',async(route:any)=>{await heldReply;await route.continue();},{times:1});await dialog.getByRole('button',{name:'Send reply',exact:true}).click();await p.waitForFunction(()=>document.querySelector<HTMLTextAreaElement>('.support-reply textarea')?.disabled);assert(await dialog.getByRole('button',{name:'Internal note',exact:true}).isDisabled());assert(await dialog.getByRole('button',{name:'Send reply',exact:true}).isDisabled());releaseReply();await dialog.getByText('Public reply browser fixture',{exact:true}).waitFor();await dialog.locator('.support-history summary').click();await dialog.getByText(/Assignment updated/).waitFor();await dialog.getByText('Created · Open',{exact:true}).waitFor();await capture(p,'conversation-history');await dialog.getByRole('button',{name:'Close',exact:true}).click();
 const requester=await pageFor(emp,390,true,'amethyst',true,true);assert.equal(await requester.getByRole('button',{name:'قائمة دعم الشركة',exact:true}).count(),0);assert.equal((await call(emp,'/api/support?queue=true')).status,403);assert.equal((await call(foreign,'/api/support/'+ticket.id)).status,404);assert.equal((await call(emp,'/api/support/'+ticket.id+'/comments',{note:'Forbidden internal',visibility:'internal'})).status,403);
 await requester.getByRole('button',{name:'فتح الطلب: Laptop screen needs repair',exact:true}).click();const own=requester.getByRole('dialog');await own.getByText('Public reply browser fixture',{exact:true}).waitFor();assert.equal(await own.getByText('Private diagnosis fixture',{exact:true}).count(),0);assert.equal(await own.getByText('Draft retained across modes',{exact:true}).count(),0);assert.equal(await own.getByRole('button',{name:'ملاحظة داخلية',exact:true}).count(),0);assert.equal(await own.getAttribute('dir'),'rtl');assert.equal(await own.evaluate((e:HTMLElement)=>e.scrollWidth<=e.clientWidth+1),true);await capture(requester,'requester-arabic-xl');await own.getByRole('button',{name:'إغلاق',exact:true}).click();
 await p.getByRole('button',{name:'Open ticket: VPN connectivity issue',exact:true}).click();dialog=p.getByRole('dialog');assert.equal(await dialog.locator('.support-asset-context').count(),0);await dialog.locator('.support-update summary').click();await dialog.getByRole('combobox',{name:/^Status/}).selectOption('resolved');const resolution=dialog.getByRole('textbox',{name:'Resolution note (required)',exact:true});assert.equal(await resolution.getAttribute('required'),'');await resolution.fill('VPN repaired by browser fixture');await dialog.getByRole('button',{name:'Resolve ticket',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.equal((await ok(manager,'/api/support/'+progress.id)).ticket.status,'resolved');await p.getByRole('button',{name:'Open ticket: VPN connectivity issue',exact:true}).click();dialog=p.getByRole('dialog');await dialog.getByRole('heading',{name:'Resolution',exact:true}).waitFor();await dialog.locator('.support-update summary').click();await dialog.getByRole('combobox',{name:/^Status/}).selectOption('in_progress');await dialog.getByRole('button',{name:'Save update',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.equal((await ok(manager,'/api/support/'+progress.id)).ticket.status,'in_progress');
 await pool.query("INSERT INTO support_tickets(tenant_id,requester_id,issue_type,summary,description,urgency) SELECT $1,$2,'it_help','Queue page fixture '||g,'Fictional pagination fixture','normal' FROM generate_series(1,53) g",[tenant,emp.id]);await p.getByRole('button',{name:'Refresh',exact:true}).click();await p.getByText('Showing 50 of 56 requests',{exact:true}).waitFor();await p.getByRole('button',{name:'Load more requests',exact:true}).click();await p.getByText('Showing 56 of 56 requests',{exact:true}).waitFor();assert.equal(new Set(await p.locator('.support-ticket-row').evaluateAll((rows:HTMLElement[])=>rows.map(r=>r.getAttribute('aria-label')))).size,56);
 await pool.query("INSERT INTO support_ticket_events(tenant_id,ticket_id,actor_id,status,note,kind) SELECT $1,$2,$3,'open','History fixture '||g,'status' FROM generate_series(1,53) g",[tenant,ticket.id,manager.id]);await row.click();dialog=p.getByRole('dialog');await dialog.getByRole('button',{name:'Load more conversation / history',exact:true}).click();await dialog.locator('.support-history summary').click();await dialog.getByText('History fixture 53',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Load more conversation / history',exact:true}).waitFor({state:'hidden'});assert.equal(await dialog.locator('.support-history li').count(),56);assert.equal(await dialog.locator('.support-message').count(),4);await capture(p,'paginated-history');await dialog.getByRole('button',{name:'Close',exact:true}).click();
 // Existing Add to Workspace behavior, isolated in this fixture's browser storage.
 const key='stanza.composer.v1:'+encodeURIComponent(manager.tenantId)+':'+encodeURIComponent(manager.id);await p.evaluate(key=>localStorage.setItem(key,JSON.stringify({version:1,activeId:'active',surface:'auto',workspaces:[{id:'active',name:'Active fixture',widgets:[]},{id:'alternate',name:'Alternate fixture',widgets:[]}]})),key);await p.reload();await p.locator('[data-tutorial-target="stanza-launcher"]').waitFor();await p.keyboard.press('Control+k');await p.getByPlaceholder('Search commands or ask Stanza…').fill('support');await p.getByRole('option').filter({hasText:'IT & equipment support'}).first().click();
 for(const destination of ['active','alternate']){await p.getByRole('button',{name:'Add to Workspace',exact:true}).click();const add=p.getByRole('dialog',{name:'Choose a saved workspace',exact:true});assert.equal(await add.getByLabel('Workspace',{exact:true}).inputValue(),'active');await add.getByLabel('Workspace',{exact:true}).selectOption(destination);await add.getByRole('button',{name:'Add widget',exact:true}).click();const saved=await p.evaluate(key=>JSON.parse(localStorage.getItem(key)!),key);assert.equal(saved.activeId,'active');assert.equal(saved.workspaces.find((w:any)=>w.id===destination).widgets[0].widgetId,'support');}
 for(const config of [{width:390,ar:false,preset:'emerald',light:false},{width:820,ar:false,preset:'amethyst',light:false},{width:1440,ar:false,preset:'custom',light:false},{width:390,ar:true,preset:'amethyst',light:true}]){const q=await pageFor(manager,config.width,config.ar,config.preset,config.light,true);await q.getByRole('button',{name:config.ar?'قائمة دعم الشركة':'Company support queue',exact:true}).click();await q.getByLabel(config.ar?'بحث في الملخص':'Search summary',{exact:true}).fill('Laptop screen needs repair');await q.getByRole('button',{name:(config.ar?'فتح الطلب: ':'Open ticket: ')+'Laptop screen needs repair',exact:true}).waitFor();assert.equal(await q.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await q.locator('.support-ticket-row').first().scrollIntoViewIfNeeded();await capture(q,'queue-'+config.width+'-'+config.preset+(config.light?'-light':''));await q.getByRole('button',{name:(config.ar?'فتح الطلب: ':'Open ticket: ')+'Laptop screen needs repair',exact:true}).click();const d=q.getByRole('dialog');assert.equal(await d.evaluate((e:HTMLElement)=>e.scrollWidth<=e.clientWidth+1),true);await d.getByRole('button',{name:config.ar?'ملاحظة داخلية':'Internal note',exact:true}).focus();await q.keyboard.press('Enter');await d.getByRole('textbox',{name:config.ar?'ملاحظة داخلية':'Internal note',exact:true}).waitFor();await capture(q,'detail-'+config.width+'-'+config.preset+(config.light?'-light':''));await d.getByRole('button',{name:config.ar?'إغلاق':'Close',exact:true}).click();}
 let idleRequests=0;const idle=(r:any)=>{if(new URL(r.url()).pathname.startsWith('/api/support'))idleRequests++;};p.on('request',idle);await p.waitForTimeout(35000);p.off('request',idle);assert.equal(idleRequests,0,'Support idle does not poll');
 console.log('PASS all 15 Support states, real assignment/replies/internal privacy/resolution/reopen, queue+history pagination, restricted/foreign denial, active/alternate Workspace destinations, 390/tablet/desktop Arabic/theme/XL/reduced-motion keyboard matrix and 35-second quiet idle');
}
} catch(error){for(const c of browser.contexts())for(const p of c.pages())await p.screenshot({path:process.env.TEMP+'/stanza-support-failure-'+browser.contexts().indexOf(c)+'.png',fullPage:true}).catch(()=>{});throw error;}
finally{await browser.close();const queue=getHrQueue();for(const job of await queue.getJobs(['wait','delayed','completed','failed'],0,-1))if(tenants.includes(job.data?.tenantId))await job.remove();await queue.close();for(const t of tenants){await pool.query('DELETE FROM router_operational_metrics WHERE tenant_id=$1',[t]);await pool.query('DELETE FROM support_tickets WHERE tenant_id=$1',[t]);await pool.query('DELETE FROM asset_assignments WHERE tenant_id=$1',[t]);await pool.query('DELETE FROM assets WHERE tenant_id=$1',[t]);await pool.query('DELETE FROM tenants WHERE id=$1',[t]);}await pool.end();await getDbPool()?.end();}
