import type { HelpAction, TutorialContext } from './tutorial-types';

export type HelpLocale = 'en' | 'ar';
export type HelpGroup = 'getting_started' | 'workspaces' | 'account_app';
export type LocalisedText = { en: string; ar: string };
export type HelpSection = { heading: LocalisedText; body: LocalisedText };
export type HelpArticle = {
  id: string;
  group: HelpGroup;
  moduleId?: string;
  tutorialId?: string;
  title: LocalisedText;
  summary: LocalisedText;
  keywords: readonly string[];
  sections: readonly HelpSection[];
  eligible?: (context: TutorialContext) => boolean;
  action?: { label: LocalisedText; value: HelpAction };
};

const text = (en: string, ar: string): LocalisedText => ({ en, ar });
const section = (headingEn: string, headingAr: string, bodyEn: string, bodyAr: string): HelpSection => ({
  heading: text(headingEn, headingAr),
  body: text(bodyEn, bodyAr),
});

function workspaceArticle(input: {
  id: string;
  moduleId: string;
  tutorialId: string;
  title: LocalisedText;
  summary: LocalisedText;
  who: LocalisedText;
  features: LocalisedText;
  workflow: LocalisedText;
  notes: LocalisedText;
  keywords: readonly string[];
}): HelpArticle {
  return {
    id: input.id,
    group: 'workspaces',
    moduleId: input.moduleId,
    tutorialId: input.tutorialId,
    title: input.title,
    summary: input.summary,
    keywords: input.keywords,
    sections: [
      section('What this section does', 'ما الذي يقدمه هذا القسم', input.summary.en, input.summary.ar),
      section('Who can use it', 'من يمكنه استخدامه', input.who.en, input.who.ar),
      section('Main features', 'الميزات الرئيسية', input.features.en, input.features.ar),
      section('Common workflow', 'سير العمل المعتاد', input.workflow.en, input.workflow.ar),
      section('Important notes', 'ملاحظات مهمة', input.notes.en, input.notes.ar),
    ],
  };
}

const gettingStarted: readonly HelpArticle[] = [
  {
    id: 'welcome', group: 'getting_started', tutorialId: 'welcome', title: text('Welcome to Stanza', 'مرحباً بك في Stanza'),
    summary: text('Learn how Stanza organises workforce workspaces around your access.', 'تعرّف إلى طريقة تنظيم Stanza لمساحات عمل الموارد البشرية وفق صلاحياتك.'),
    keywords: ['welcome', 'start', 'overview', 'بدء', 'نظرة عامة'],
    sections: [
      section('What Stanza shows', 'ما الذي تعرضه Stanza', 'The launcher contains only modules available to your account. Inside each module, the server still validates every read and action against tenant, ownership, permission, and scope rules.', 'يعرض المشغل الوحدات المتاحة لحسابك فقط، بينما يتحقق الخادم من كل قراءة وإجراء وفق الشركة والملكية والصلاحية والنطاق.'),
      section('Start safely', 'ابدأ بأمان', 'Use the launcher to choose a workspace, Quick Actions for frequent commands, and Settings for personal display and app preferences. Guided tours explain controls without submitting or changing records.', 'استخدم المشغل لاختيار مساحة عمل، والإجراءات السريعة للأوامر المتكررة، والإعدادات لتفضيلات العرض والتطبيق. تشرح الجولات العناصر دون إرسال أو تغيير سجلات.'),
    ],
  },
  {
    id: 'navigation', group: 'getting_started', tutorialId: 'welcome', title: text('Navigation', 'التنقل'),
    summary: text('Move through authorised modules with the launcher, compact rail, mobile shortcuts, or command palette.', 'تنقّل بين الوحدات المصرح بها عبر المشغل أو الشريط المختصر أو اختصارات الهاتف أو لوحة الأوامر.'),
    keywords: ['launcher', 'rail', 'command palette', 'mobile', 'مشغل', 'تنقل'],
    sections: [section('Choosing a module', 'اختيار وحدة', 'The active item remains highlighted. Recent and frequent sections reflect local usage; they do not grant access. On mobile, configured shortcuts and the add menu keep navigation touch-friendly.', 'يبقى العنصر النشط مميزاً. تعكس الأقسام الأخيرة والمتكررة الاستخدام المحلي ولا تمنح صلاحيات. على الهاتف توفر الاختصارات وقائمة الإضافة تنقلاً مناسباً للمس.')],
  },
  {
    id: 'quick-actions', group: 'getting_started', tutorialId: 'welcome', title: text('Quick Actions', 'الإجراءات السريعة'),
    summary: text('Pin permitted commands for faster access without changing their authority.', 'ثبّت الأوامر المسموح بها للوصول السريع دون تغيير صلاحياتها.'),
    keywords: ['quick actions', 'pin', 'shortcut', 'إجراءات سريعة', 'اختصار'],
    sections: [section('How they work', 'طريقة العمل', 'A Quick Action opens an existing workflow. It never bypasses confirmation, scope checks, or backend authorisation. Settings lets you add all available actions or reset to the recommended set.', 'يفتح الإجراء السريع سير عمل موجوداً ولا يتجاوز التأكيد أو فحص النطاق أو تفويض الخادم. تتيح الإعدادات إضافة الإجراءات المتاحة أو استعادة المجموعة الموصى بها.')],
  },
  {
    id: 'themes-settings', group: 'getting_started', tutorialId: 'settings', title: text('Themes & Settings', 'السمات والإعدادات'),
    summary: text('Adjust appearance, interface size, navigation, shortcuts, language, and app preferences.', 'اضبط المظهر وحجم الواجهة والتنقل والاختصارات واللغة وتفضيلات التطبيق.'),
    keywords: ['theme', 'settings', 'language', 'size', 'سمة', 'إعدادات'],
    sections: [section('Personal preferences', 'التفضيلات الشخصية', 'Preferences are saved for this browser profile. Theme presets preserve semantic focus, selected, disabled, and destructive states in light and dark mode.', 'تُحفظ التفضيلات لملف المتصفح الحالي، وتحافظ السمات على حالات التركيز والتحديد والتعطيل والإجراءات الخطرة في الوضعين الفاتح والداكن.')],
  },
];

const workspaces: readonly HelpArticle[] = [
  workspaceArticle({ id: 'geo-operations', moduleId: 'geofence', tutorialId: 'geo-operations', title: text('Geo Operations', 'العمليات الجغرافية'), summary: text('Record attendance against authorised company locations and manage break requests.', 'سجّل الحضور مقابل مواقع الشركة المصرح بها وأدر طلبات الاستراحة.'), who: text('Employees use their own attendance controls. Reviewers see only break requests inside their authority.', 'يستخدم الموظفون عناصر حضورهم، ويرى المراجعون طلبات الاستراحة الواقعة ضمن صلاحيتهم فقط.'), features: text('Location readiness, geofence verification, clock in/out, break status, approval queues, and location context.', 'جاهزية الموقع والتحقق من النطاق وتسجيل الدخول والخروج وحالة الاستراحة وقوائم الموافقات وسياق الموقع.'), workflow: text('Check readiness, choose Clock In, grant location only when requested, then read the geofence result. Submit breaks separately and follow their status.', 'تحقق من الجاهزية ثم اختر تسجيل الدخول وامنح الموقع عند الطلب واقرأ نتيجة النطاق. أرسل الاستراحات بصورة مستقلة وتابع حالتها.'), notes: text('Latitude and longitude are sent only for the attendance action. An outside-geofence result is not the same as an open-shift conflict.', 'يُرسل خط العرض والطول لإجراء الحضور فقط. نتيجة خارج النطاق تختلف عن تعارض وجود مناوبة مفتوحة.'), keywords: ['attendance', 'clock in', 'break', 'geofence', 'حضور', 'استراحة', 'نطاق'] }),
  workspaceArticle({ id: 'weekly-roster', moduleId: 'roster', tutorialId: 'roster', title: text('Weekly Roster', 'الجدول الأسبوعي'), summary: text('View schedules and bring swaps, approvals, leave, and optional weekly Goals into one roster workspace.', 'اعرض الجداول واجمع التبديلات والموافقات والإجازات والأهداف الأسبوعية الاختيارية في مساحة واحدة.'), who: text('Employees see their own schedule and requests. Supervisors, custom scoped roles, and delegated approvers see only employees covered by current authority.', 'يرى الموظفون جداولهم وطلباتهم، بينما يرى المشرفون والأدوار المخصصة والمفوّضون الموظفين المشمولين بصلاحيتهم الحالية فقط.'), features: text('Week and range controls, responsive schedule views, My Swaps, approval queues, leave requests, approved-leave warnings, and Goals / Tasks.', 'عناصر تنقل ونطاق زمني وعروض متجاوبة والتبديلات والموافقات وطلبات الإجازة وتحذيرات الإجازة المعتمدة والأهداف والمهام.'), workflow: text('Choose a week and employee when authorised. Review or edit the schedule, use My Swaps for exchanges, Leave for absence requests, and Goals for short operational tasks. Supervisors can assign tasks; employees can start and complete their own.', 'اختر الأسبوع والموظف عند امتلاك الصلاحية. راجع أو عدّل الجدول واستخدم التبديلات والإجازة والأهداف للمهام القصيرة. يستطيع المشرف تعيينها ويستطيع الموظف بدء أهدافه وإكمالها.'), notes: text('Roster goals belong to one Monday-based week. Incomplete earlier goals appear in a small overdue section; they never crowd individual shift cells. Backend overlap and scope validation remains authoritative.', 'تنتمي أهداف الجدول إلى أسبوع يبدأ الاثنين. تظهر الأهداف السابقة غير المكتملة في قسم متأخر صغير ولا تزاحم خلايا المناوبات. يبقى تحقق الخادم من التداخل والنطاق هو المرجع.'), keywords: ['roster', 'schedule', 'swap', 'leave', 'goals', 'جدول', 'تبديل', 'إجازة', 'أهداف'] }),
  workspaceArticle({ id: 'leave', moduleId: 'roster', tutorialId: 'roster', title: text('Leave', 'الإجازات'), summary: text('Request leave, track decisions, and review requests routed into your scope.', 'اطلب الإجازة وتابع القرارات وراجع الطلبات الموجهة إلى نطاقك.'), who: text('Employees manage their own requests. Configured approvers act only on routed requests in scope.', 'يدير الموظفون طلباتهم، ويتصرف الموافقون المكوّنون في الطلبات الموجهة ضمن النطاق فقط.'), features: text('Request history, balances where available, cancellation, approval queues, conflict indicators, and schedule links.', 'سجل الطلبات والأرصدة عند توفرها والإلغاء وقوائم الموافقة ومؤشرات التعارض وروابط الجدول.'), workflow: text('Select dates and type, submit once, then follow the pending decision. Approvers review context before approving or rejecting.', 'حدد التواريخ والنوع ثم أرسل مرة واحدة وتابع القرار. يراجع الموافق السياق قبل القبول أو الرفض.'), notes: text('Leave is not a grievance. Concurrent decisions use expected state and the server returns a conflict if another reviewer acted first.', 'الإجازة ليست شكوى. تستخدم القرارات المتزامنة الحالة المتوقعة ويعيد الخادم تعارضاً إذا تصرف مراجع آخر أولاً.'), keywords: ['leave', 'absence', 'approval', 'إجازة', 'غياب'] }),
  workspaceArticle({ id: 'locations', moduleId: 'locations', tutorialId: 'locations', title: text('Locations', 'المواقع'), summary: text('Maintain company workplaces and geofences used by attendance.', 'أدر مواقع عمل الشركة ونطاقات الحضور الجغرافية.'), who: text('Readers see safe location details; configured location managers can create, edit, archive, and restore within authority.', 'يرى القراء تفاصيل الموقع الآمنة، ويمكن لمديري المواقع المصرح لهم الإنشاء والتعديل والأرشفة والاستعادة.'), features: text('Primary and active status, map coordinates, radius, type, usage checks, and archive protection.', 'الحالة الأساسية والنشطة والإحداثيات ونصف القطر والنوع وفحوص الاستخدام وحماية الأرشفة.'), workflow: text('Review active sites, edit the geofence carefully, and confirm dependent usage before archiving.', 'راجع المواقع النشطة وعدّل النطاق بعناية وتأكد من الاستخدامات التابعة قبل الأرشفة.'), notes: text('Coordinates are sensitive operational data. The server minimises exposure and all mutations remain tenant scoped.', 'الإحداثيات بيانات تشغيلية حساسة. يقلل الخادم كشفها وتبقى جميع التعديلات ضمن نطاق الشركة.'), keywords: ['locations', 'geofence', 'map', 'مواقع', 'خريطة'] }),
  workspaceArticle({ id: 'expenses', moduleId: 'expenses', tutorialId: 'expenses', title: text('Expenses', 'المصروفات'), summary: text('Submit reimbursement claims and route them through scoped review and reimbursement.', 'أرسل مطالبات التعويض ووجّهها للمراجعة والسداد ضمن النطاق.'), who: text('Employees manage their own claims. Approvers and reimbursers act only where assigned authority permits.', 'يدير الموظفون مطالباتهم، ويتصرف الموافقون والمسددون حيث تسمح صلاحيتهم فقط.'), features: text('Receipt extraction, editable fields, evidence, approval status, cancellation, and reimbursement tracking.', 'استخراج الإيصال والحقول القابلة للتعديل والأدلة وحالة الموافقة والإلغاء وتتبع السداد.'), workflow: text('Upload a supported receipt if useful, review extracted values, submit, and follow status. Extraction never submits the claim automatically.', 'ارفع إيصالاً مدعوماً وراجع القيم المستخرجة ثم أرسل وتابع الحالة. لا يرسل الاستخراج المطالبة تلقائياً.'), notes: text('Treat extracted values as suggestions. File validation, tenant scope, and decision authority are enforced server side.', 'تعامل مع القيم المستخرجة كاقتراحات. يفرض الخادم تحقق الملف ونطاق الشركة وصلاحية القرار.'), keywords: ['expense', 'receipt', 'reimbursement', 'مصروف', 'إيصال'] }),
  workspaceArticle({ id: 'hiring', moduleId: 'hiring', tutorialId: 'hiring', title: text('Hiring', 'التوظيف'), summary: text('Track applicants through stages, notes, reviews, and accountable handoffs.', 'تابع المتقدمين عبر المراحل والملاحظات والمراجعات والتسليمات المسؤولة.'), who: text('Hiring permissions and employee scope determine which candidates and actions are visible.', 'تحدد صلاحيات التوظيف ونطاق الموظفين المتقدمين والإجراءات الظاهرة.'), features: text('Candidate pipeline, filters, notes with visibility, document extraction, stage history, review attention, and handoffs.', 'مسار المتقدمين والفلاتر والملاحظات ذات مستويات الظهور واستخراج المستندات وسجل المراحل والتنبيهات والتسليمات.'), workflow: text('Open a candidate, review safe details, add an appropriate note, advance only through allowed stages, and hand off to an eligible active reviewer.', 'افتح المتقدم وراجع التفاصيل وأضف ملاحظة مناسبة وانقل عبر المراحل المسموحة وسلم إلى مراجع نشط ومؤهل.'), notes: text('HR-only notes stay restricted. Reviewer eligibility is checked again inside each handoff transaction.', 'تبقى ملاحظات الموارد البشرية مقيدة، ويعاد فحص أهلية المراجع داخل معاملة التسليم.'), keywords: ['hiring', 'candidate', 'handoff', 'توظيف', 'متقدم'] }),
  workspaceArticle({ id: 'organisation', moduleId: 'organisation', tutorialId: 'organisation', title: text('Organisation', 'المنظمة'), summary: text('Manage people placement, departments, teams, titles, scoped roles, and delegations.', 'أدر توزيع الأفراد والأقسام والفرق والمسميات والأدوار المحددة النطاق والتفويضات.'), who: text('Everyone with organisation view sees only authorised structure. Mutation controls follow distinct scoped permissions.', 'يرى أصحاب صلاحية العرض الهيكل المصرح به فقط، وتتبع التعديلات صلاحيات منفصلة ومحددة النطاق.'), features: text('People placement, reporting lines, memberships, hierarchy, role discovery, role assignments, and temporary delegations.', 'توزيع الأفراد وخطوط التقارير والعضويات والهيكل واكتشاف الأدوار وتعيينها والتفويض المؤقت.'), workflow: text('Find the person or structure item, open its focused dialog, review the current values, and confirm one bounded change.', 'ابحث عن الشخص أو عنصر الهيكل وافتح نافذته وراجع القيم الحالية وأكد تغييراً محدداً.'), notes: text('Titles never grant permissions. Cycles, cross-tenant references, inactive people, privilege escalation, and expired delegations are rejected by the server.', 'لا تمنح المسميات صلاحيات. يرفض الخادم الدورات والمراجع العابرة للشركات والأشخاص غير النشطين وتصعيد الصلاحيات والتفويضات المنتهية.'), keywords: ['organisation', 'team', 'department', 'role', 'منظمة', 'فريق', 'قسم'] }),
  workspaceArticle({ id: 'employees', moduleId: 'liveEmployees', tutorialId: 'employees', title: text('Employees', 'الموظفون'), summary: text('Review live attendance presence and safe employee context within your scope.', 'راجع حضور الموظفين المباشر وسياقهم الآمن ضمن نطاقك.'), who: text('Only accounts with live-attendance authority receive scoped records.', 'تستقبل الحسابات ذات صلاحية الحضور المباشر السجلات الواقعة ضمن النطاق فقط.'), features: text('Active shift state, safe identity labels, filters, refresh, and role-appropriate follow-up links.', 'حالة المناوبة النشطة وتسميات الهوية الآمنة والفلاتر والتحديث وروابط المتابعة المناسبة.'), workflow: text('Filter the visible list, inspect current status, and use only the actions exposed for your authority.', 'رشح القائمة الظاهرة وافحص الحالة واستخدم الإجراءات التي تظهر لصلاحيتك فقط.'), notes: text('This is not continuous employee surveillance and does not expose raw location coordinates.', 'هذه ليست مراقبة مستمرة للموظف ولا تعرض إحداثيات الموقع الخام.'), keywords: ['employees', 'live', 'attendance', 'موظفون', 'حضور'] }),
  workspaceArticle({ id: 'company-feed', moduleId: 'feed', tutorialId: 'company-feed', title: text('Company Feed', 'موجز الشركة'), summary: text('Read company announcements and, when authorised, create accessible rich-text posts and personal drafts.', 'اقرأ إعلانات الشركة وأنشئ عند التصريح منشورات نصية منسقة ومسودات شخصية.'), who: text('Tenant readers see published posts. Publishers receive editor, draft, audience, and status controls.', 'يرى قراء الشركة المنشورات المنشورة، ويحصل الناشرون على المحرر والمسودات والجمهور والحالة.'), features: text('Headings, lists, links, quotes, images, audiences, draft recovery, and publication status.', 'العناوين والقوائم والروابط والاقتباسات والصور والجمهور واستعادة المسودة وحالة النشر.'), workflow: text('Write or restore a draft, review the audience and image state, then publish once. Retry remains available after safe failures.', 'اكتب أو استعد مسودة وراجع الجمهور وحالة الصورة ثم انشر مرة واحدة. تبقى إعادة المحاولة متاحة بعد الأخطاء الآمنة.'), notes: text('Rich content is validated and rendered through the supported Lexical format. Author email and unsafe HTML are not exposed to ordinary readers.', 'يُتحقق من المحتوى ويُعرض عبر تنسيق Lexical المدعوم، ولا يظهر بريد الكاتب أو HTML غير الآمن للقراء العاديين.'), keywords: ['feed', 'announcement', 'editor', 'draft', 'موجز', 'إعلان', 'مسودة'] }),
  workspaceArticle({ id: 'assets', moduleId: 'assets', tutorialId: 'assets', title: text('Assets & Equipment', 'الأصول والمعدات'), summary: text('Track equipment, assignments, returns, software, evidence, and QR labels.', 'تتبع المعدات والتخصيصات والإرجاع والبرامج والأدلة وملصقات QR.'), who: text('Employees see their assigned equipment. Asset permissions control inventory and assignment actions by scope.', 'يرى الموظفون معداتهم، وتتحكم صلاحيات الأصول في المخزون والتخصيص حسب النطاق.'), features: text('Inventory, assignment history, condition reports, returns, licenses, extraction, and revocable QR labels.', 'المخزون وسجل التخصيص وتقارير الحالة والإرجاع والتراخيص والاستخراج وملصقات QR القابلة للإلغاء.'), workflow: text('Find an asset, review current status, then use the focused assign, return, report, or label action.', 'ابحث عن الأصل وراجع حالته ثم استخدم إجراء التخصيص أو الإرجاع أو التقرير أو الملصق.'), notes: text('Evidence is validated and stored securely. Removing an assignment preserves history and never deletes the employee.', 'يُتحقق من الأدلة وتُخزن بأمان. إنهاء التخصيص يحفظ السجل ولا يحذف الموظف.'), keywords: ['asset', 'equipment', 'license', 'QR', 'أصل', 'معدات'] }),
  workspaceArticle({ id: 'performance', moduleId: 'performance', tutorialId: 'performance', title: text('Performance', 'الأداء'), summary: text('Manage review cycles, long-term goals, feedback, reports, and recognition.', 'أدر دورات المراجعة والأهداف طويلة المدى والملاحظات والتقارير والتقدير.'), who: text('Employees see assigned or owned records. Reviewers and administrators receive only permission-appropriate controls.', 'يرى الموظفون السجلات المعينة أو المملوكة، ويحصل المراجعون والإداريون على عناصر مناسبة لصلاحياتهم.'), features: text('Review templates, assignments, 360 feedback, OKRs, reports, and Employee of the Month recognition.', 'قوالب المراجعة والتعيينات وتقييم 360 والأهداف والنتائج والتقارير وتقدير موظف الشهر.'), workflow: text('Open the active cycle or assignment, complete required responses, and submit only when ready. Administrators configure cycles separately.', 'افتح الدورة أو المهمة النشطة وأكمل الردود المطلوبة ثم أرسل عند الجاهزية. يكوّن الإداريون الدورات بصورة منفصلة.'), notes: text('Performance goals are long-horizon objectives. Roster Goals are separate short weekly operational tasks and do not replace OKRs.', 'أهداف الأداء طويلة المدى، بينما أهداف الجدول مهام تشغيلية أسبوعية منفصلة ولا تستبدل الأهداف والنتائج.'), keywords: ['performance', 'review', 'feedback', 'OKR', 'أداء', 'تقييم'] }),
  workspaceArticle({ id: 'audit-trail', moduleId: 'audit', tutorialId: 'audit-trail', title: text('Audit Trail', 'سجل التدقيق'), summary: text('Search read-only accountability events with minimised, safe metadata.', 'ابحث في أحداث المساءلة للقراءة فقط ببيانات وصفية آمنة ومحدودة.'), who: text('Only explicit audit viewers can access tenant events.', 'يمكن فقط لأصحاب صلاحية التدقيق الصريحة الوصول إلى أحداث الشركة.'), features: text('Date, module, action, actor, severity, search, pagination, and safe event detail.', 'التاريخ والوحدة والإجراء والمنفذ والخطورة والبحث والصفحات وتفاصيل الحدث الآمنة.'), workflow: text('Filter narrowly, inspect the event summary, and use identifiers to correlate an authorised operational review.', 'استخدم فلاتر محددة وافحص الملخص واستعمل المعرفات لربط مراجعة تشغيلية مصرح بها.'), notes: text('Secrets, coordinates, free-text reasons, and full sensitive payloads are deliberately excluded.', 'تُستبعد الأسرار والإحداثيات والأسباب النصية والحمولات الحساسة الكاملة عمداً.'), keywords: ['audit', 'history', 'event', 'تدقيق', 'سجل'] }),
  workspaceArticle({ id: 'session-center', moduleId: 'sessionCenter', tutorialId: 'session-center', title: text('Session Center', 'مركز الجلسات'), summary: text('Review and revoke active tenant sessions when explicitly authorised.', 'راجع جلسات الشركة النشطة وألغها عند وجود تصريح صريح.'), who: text('Everyone can manage their own sessions in Profile. Session Center requires sessions.manage.', 'يمكن للجميع إدارة جلساتهم من الملف الشخصي، ويتطلب مركز الجلسات صلاحية إدارة الجلسات.'), features: text('Safe device labels, masked networks, last activity, expiry, status, revoke one, and revoke all for an employee.', 'تسميات الأجهزة والشبكات المقنعة وآخر نشاط والانتهاء والحالة وإلغاء جلسة أو جميع جلسات موظف.'), workflow: text('Confirm the employee and device, then revoke. The affected session fails on its next authenticated request.', 'تأكد من الموظف والجهاز ثم ألغِ الجلسة، فتفشل في طلبها الموثق التالي.'), notes: text('Raw tokens, cookies, hashes, and full IP addresses are never returned. Your current session is protected from remote self-revocation.', 'لا تُعاد الرموز أو الكوكيز أو التجزئات أو عناوين IP الكاملة، وتحمي جلسة المستخدم الحالية من الإلغاء الذاتي البعيد.'), keywords: ['session', 'device', 'revoke', 'جلسة', 'جهاز'] }),
  workspaceArticle({ id: 'profile', moduleId: 'profile', tutorialId: 'profile', title: text('Profile', 'الملف الشخصي'), summary: text('Review your identity, employment context, badge, account security, and active sessions.', 'راجع هويتك وسياق العمل والشارة وأمان الحساب والجلسات النشطة.'), who: text('This is a self-service workspace. Administrative data is not exposed here.', 'هذه مساحة خدمة ذاتية ولا تعرض بيانات الإدارة فيها.'), features: text('Profile photo, employment details, digital badge, passkeys, sessions, payroll links, and personal requests.', 'الصورة والتفاصيل الوظيفية والشارة الرقمية ومفاتيح المرور والجلسات وروابط الرواتب والطلبات الشخصية.'), workflow: text('Review the section you need and use its confirmation dialog for changes. Session and passkey actions use the normal secure account path.', 'راجع القسم المطلوب واستخدم نافذة التأكيد للتغييرات. تتبع إجراءات الجلسات ومفاتيح المرور مسار الحساب الآمن المعتاد.'), notes: text('Job titles do not determine permissions. Role and scoped assignment changes belong in Organisation.', 'لا تحدد المسميات الصلاحيات، وتدار تغييرات الأدوار والتعيينات المحددة النطاق في المنظمة.'), keywords: ['profile', 'badge', 'passkey', 'ملف', 'شارة'] }),
  workspaceArticle({ id: 'resignations', moduleId: 'resignations', tutorialId: 'resignations', title: text('Resignations', 'الاستقالات'), summary: text('Submit, review, withdraw, and process resignation requests through a bounded workflow.', 'أرسل طلبات الاستقالة وراجعها واسحبها وعالجها ضمن سير عمل محدد.'), who: text('Employees manage their own request. Review and processing permissions expose scoped actions.', 'يدير الموظفون طلباتهم، وتعرض صلاحيات المراجعة والمعالجة إجراءات ضمن النطاق.'), features: text('Requested final date, type, status, review, withdrawal, processing, and offboarding checks.', 'تاريخ المغادرة والنوع والحالة والمراجعة والسحب والمعالجة وفحوص إنهاء الخدمة.'), workflow: text('Submit one clear request, follow its status, and withdraw only while allowed. Reviewers decide; processors complete approved offboarding.', 'أرسل طلباً واضحاً وتابع حالته واسحبه عند السماح. يتخذ المراجع القرار ويكمل المعالج إنهاء الخدمة المعتمد.'), notes: text('Outstanding assets remain visible to authorised offboarding staff and are not silently discarded.', 'تبقى الأصول المستحقة ظاهرة لموظفي إنهاء الخدمة المصرح لهم ولا تُتجاهل.'), keywords: ['resignation', 'offboarding', 'استقالة', 'مغادرة'] }),
  workspaceArticle({ id: 'grievances', moduleId: 'grievances', tutorialId: 'grievances', title: text('Grievances', 'التظلمات'), summary: text('Submit and follow workplace concerns as durable private cases.', 'قدم مشكلات العمل وتابعها كقضايا خاصة محفوظة.'), who: text('Reporters see their own cases. Handlers see only authorized scopes, with additional authority required for confidential cases.', 'يرى مقدم الشكوى قضاياه فقط. يرى المعالج القضايا ضمن نطاقه المصرح به، وتتطلب القضايا السرية تصريحاً إضافياً.'), features: text('Case numbers, department routing, attachments, assignment, employee responses, private notes, and an activity timeline.', 'أرقام القضايا وتوجيه الأقسام والمرفقات والإسناد وردود الموظف والملاحظات الخاصة والخط الزمني.'), workflow: text('Choose a destination and confidentiality level. Handlers triage, assign, respond, resolve, and close. Reopening preserves earlier resolutions.', 'اختر القسم ومستوى السرية. يفرز المعالج القضية ويسندها ويرد عليها ويحلها ثم يغلقها. تحافظ إعادة الفتح على الحلول السابقة.'), notes: text('Internal notes never appear in the reporter view. Preparing a response email creates a private draft for review; it does not send automatically.', 'لا تظهر الملاحظات الداخلية لمقدم الشكوى. ينشئ إعداد بريد للرد مسودة خاصة للمراجعة ولا يرسلها تلقائياً.'), keywords: ['grievance', 'case', 'concern', 'confidential', 'تظلم', 'شكوى'] }),
  workspaceArticle({ id: 'payroll', moduleId: 'payroll', tutorialId: 'payroll', title: text('Payroll', 'الرواتب'), summary: text('Review personal payroll or run, approve, pay, and export records within explicit authority.', 'راجع راتبك أو نفّذ واعتمد وادفع وصدّر السجلات ضمن صلاحية صريحة.'), who: text('Employees see their own authorised records. Payroll, compensation, and loan permissions are separate high-sensitivity boundaries.', 'يرى الموظفون سجلاتهم المصرح بها، وتبقى صلاحيات الرواتب والتعويض والقروض حدوداً حساسة منفصلة.'), features: text('Pay periods, run generation, approval, paid status, PDF export, compensation profiles, loans, and deductions.', 'فترات الرواتب والتوليد والاعتماد وحالة الدفع وتصدير PDF وملفات التعويض والقروض والاستقطاعات.'), workflow: text('Select the period, review generated records and skipped employees, then advance one valid status transition at a time.', 'حدد الفترة وراجع السجلات والموظفين المتجاوزين ثم انقل حالة صحيحة واحدة في كل مرة.'), notes: text('Financial actions are transactional and audited. A visible button never replaces backend permission and tenant checks.', 'الإجراءات المالية معاملية ومدققة، ولا يستبدل الزر الظاهر فحص الصلاحية والشركة في الخادم.'), keywords: ['payroll', 'salary', 'loan', 'رواتب', 'قرض'] }),
];

const accountApp: readonly HelpArticle[] = [
  {
    id: 'interactive-lanyard-performance',
    group: 'account_app',
    tutorialId: 'interactive-lanyard',
    title: text('Interactive Lanyard & Performance', 'بطاقة التعريف التفاعلية والأداء'),
    summary: text('Choose whether the optional 3D employee badge appears on your dashboard.', 'اختر ما إذا كانت بطاقة الموظف ثلاثية الأبعاد الاختيارية تظهر في لوحة التحكم.'),
    keywords: ['lanyard', 'badge', 'performance', 'GPU', 'CPU', 'بطاقة', 'أداء'],
    eligible: (context) => context.lanyardAvailable === true,
    sections: [
      section('What it is', 'ما هي', 'The interactive lanyard is an optional 3D employee badge attached to the Stanza launcher.', 'بطاقة التعريف التفاعلية هي بطاقة موظف ثلاثية الأبعاد اختيارية متصلة بمشغل Stanza.'),
      section('Resource usage', 'استخدام الموارد', 'Disabling the lanyard may reduce GPU or CPU usage on some devices and browsers.', 'قد يقلل تعطيل البطاقة من استخدام وحدة الرسوميات أو المعالج في بعض الأجهزة والمتصفحات.'),
      section('Where to change it', 'مكان تغيير الإعداد', 'Open Settings, expand Interface, and use the Lanyard card switch.', 'افتح الإعدادات ووسّع قسم الواجهة ثم استخدم مفتاح بطاقة التعريف.'),
      section('Stanza functionality', 'وظائف Stanza', 'Turning it off changes only the visual effect. Attendance, navigation, and every Stanza workflow continue to work normally.', 'يغيّر إيقافها التأثير المرئي فقط، وتستمر الحضور والتنقل وجميع وظائف Stanza بصورة طبيعية.'),
      section('Turn it back on', 'إعادة التشغيل', 'Return to the same switch at any time to re-enable the lanyard.', 'عد إلى المفتاح نفسه في أي وقت لإعادة تشغيل بطاقة التعريف.'),
    ],
    action: {
      label: text('Show lanyard setting', 'إظهار إعداد بطاقة التعريف'),
      value: { type: 'open-settings', section: 'personalization', target: 'lanyard' },
    },
  },
  { id: 'passkeys', group: 'account_app', tutorialId: 'settings', title: text('Passkeys', 'مفاتيح المرور'), summary: text('Register device-backed sign-in credentials without exposing private key material.', 'سجّل بيانات دخول مدعومة بالجهاز دون كشف مادة المفتاح الخاص.'), keywords: ['passkey', 'security', 'مفتاح مرور'], sections: [section('Using passkeys', 'استخدام مفاتيح المرور', 'Open Settings or Profile, register on a trusted device, and name it clearly. Authentication remains bound to the normal secure session cookie.', 'افتح الإعدادات أو الملف الشخصي وسجّل على جهاز موثوق وسمّه بوضوح. يبقى الدخول مرتبطاً بكوكي الجلسة الآمنة المعتادة.')] },
  { id: 'notifications', group: 'account_app', tutorialId: 'settings', title: text('Notifications', 'الإشعارات'), summary: text('Choose personal notification channels without changing workflow authority.', 'اختر قنوات الإشعار الشخصية دون تغيير صلاحية سير العمل.'), keywords: ['notification', 'email', 'push', 'إشعار'], sections: [section('Preferences', 'التفضيلات', 'Settings controls available email and push categories. Turning a notification off does not remove the underlying task or approval responsibility.', 'تتحكم الإعدادات في فئات البريد والدفع، ولا يؤدي إيقاف الإشعار إلى إزالة المهمة أو مسؤولية الموافقة.')] },
  { id: 'install-stanza', group: 'account_app', tutorialId: 'settings', title: text('Install / Remove Stanza', 'تثبيت / إزالة Stanza'), summary: text('Use browser-supported installation for a standalone app window and home-screen access.', 'استخدم التثبيت المدعوم من المتصفح لنافذة مستقلة ووصول من الشاشة الرئيسية.'), keywords: ['install', 'PWA', 'home screen', 'تثبيت'], sections: [section('Installation', 'التثبيت', 'Use App Readiness for platform-specific steps. Android and desktop use the browser install action when available; iPhone and iPad use Safari Add to Home Screen. Removal is performed through the operating system or browser app controls.', 'استخدم جاهزية التطبيق للخطوات المناسبة. يستخدم Android وسطح المكتب إجراء التثبيت عند توفره، ويستخدم iPhone وiPad إضافة إلى الشاشة الرئيسية في Safari. تتم الإزالة من النظام أو المتصفح.')] },
  { id: 'offline-readiness', group: 'account_app', tutorialId: 'settings', title: text('Offline / App Readiness', 'عدم الاتصال / جاهزية التطبيق'), summary: text('Understand installation, connectivity, and what remains available when the network is unavailable.', 'افهم التثبيت والاتصال وما يبقى متاحاً عند انقطاع الشبكة.'), keywords: ['offline', 'readiness', 'network', 'عدم اتصال'], sections: [section('Offline boundaries', 'حدود عدم الاتصال', 'The shell may remain available from the PWA cache, but secure data mutations require the server. Stanza disables unsafe actions rather than pretending an offline change was saved.', 'قد يبقى هيكل التطبيق متاحاً من ذاكرة PWA، لكن تعديلات البيانات الآمنة تتطلب الخادم. تعطل Stanza الإجراءات غير الآمنة بدلاً من الادعاء بحفظ تغيير دون اتصال.')] },
  { id: 'themes', group: 'account_app', tutorialId: 'settings', title: text('Themes', 'السمات'), summary: text('Select a semantic colour preset and light or dark mode.', 'اختر سمة ألوان دلالية ووضعاً فاتحاً أو داكناً.'), keywords: ['theme', 'dark', 'light', 'سمة', 'داكن'], sections: [section('Contrast and motion', 'التباين والحركة', 'Every preset shares the same interaction tokens for hover, selected, focus, disabled, and destructive states. Reduced-motion preferences keep feedback immediate without removing meaning.', 'تشترك السمات في رموز تفاعل موحدة لحالات التحويم والتحديد والتركيز والتعطيل والخطر. تحافظ الحركة المخفضة على المعنى دون حركة زائدة.')] },
  { id: 'language', group: 'account_app', tutorialId: 'settings', title: text('Language', 'اللغة'), summary: text('Switch between English and Arabic with full RTL layout support.', 'بدّل بين الإنجليزية والعربية مع دعم كامل لاتجاه RTL.'), keywords: ['language', 'Arabic', 'RTL', 'لغة', 'عربي'], sections: [section('Direction', 'الاتجاه', 'Changing language updates text direction and labels. Dates, IDs, email addresses, and other directional data remain readable with local direction isolation.', 'يحدث تغيير اللغة اتجاه النص والتسميات، وتبقى التواريخ والمعرفات والبريد وغيرها مقروءة بعزل اتجاهها عند الحاجة.')] },
];

export const HELP_ARTICLES: readonly HelpArticle[] = [
  { id:'communications', group:'workspaces', moduleId:'communications', tutorialId:'communications', title:text('Communications','Communications'), summary:text('Company email and meetings.','Company email and meetings.'), keywords:['email','meeting','template'], sections:[section('Compose and schedule','Compose and schedule','Save private drafts, use approved templates and schedule internal meetings. Sent means provider acceptance, not confirmed delivery.','Save private drafts, use approved templates and schedule internal meetings.')] },
  { id:'workspace-composer', group:'workspaces', moduleId:'composer', tutorialId:'workspace-composer', title:text('Workspace Composer','منشئ مساحات العمل'), summary:text('Save personal layouts without replacing the original modules.','احفظ تخطيطات شخصية دون استبدال الأقسام الأصلية.'), keywords:['widgets','layout','composer'], sections:[section('Customize your screen','تخصيص شاشتك','Create a workspace, add authorized widgets, then Customize to move or resize. Keyboard controls are available. Layouts are saved for this user and company in this browser; they do not synchronize to other devices.','أنشئ مساحة وأضف اللوحات ثم خصص مواضعها وأحجامها. تتوفر أدوات لوحة المفاتيح. تُحفظ التخطيطات للمستخدم والشركة في هذا المتصفح فقط.')] },...gettingStarted, ...workspaces, ...accountApp];

const ids = new Set(HELP_ARTICLES.map((article) => article.id));
if (ids.size !== HELP_ARTICLES.length) throw new Error('Duplicate Help article identifiers.');

export function getEligibleHelpArticles(
  context: Pick<TutorialContext, 'availableModules'> & Partial<Omit<TutorialContext, 'availableModules'>>,
) {
  const eligibilityContext: TutorialContext = {
    permissions: context.permissions || [],
    availableModules: context.availableModules,
    isMobile: context.isMobile === true,
    lanyardAvailable: context.lanyardAvailable,
    lanyardEnabled: context.lanyardEnabled,
  };
  return HELP_ARTICLES.filter((article) => (
    (!article.moduleId || context.availableModules.includes(article.moduleId))
    && (!article.eligible || article.eligible(eligibilityContext))
  ));
}

export function searchHelpArticles(articles: readonly HelpArticle[], query: string, locale: HelpLocale) {
  const search = query.trim().toLocaleLowerCase(locale === 'ar' ? 'ar' : 'en');
  if (!search) return [...articles];
  return articles.filter((article) => [article.title[locale], article.summary[locale], ...article.keywords]
    .join(' ')
    .toLocaleLowerCase(locale === 'ar' ? 'ar' : 'en')
    .includes(search));
}

export function getHelpArticle(id: string) {
  return HELP_ARTICLES.find((article) => article.id === id) || null;
}
