import { useCallback, useEffect, useState } from 'react';
import { apiFetch, apiUrl } from '../../lib/api';
import { useLanguage } from '../../lib/LanguageContext';

type Mode = 'required' | 'optional' | 'disabled';
type BreakPolicy = { id?: string; name: string; duration_minutes: number; maximum_uses: number | null; requires_approval: boolean; paid: boolean; active: boolean };
type Policy = { attendanceLocationMode: Mode; allowUnfiledBreaks: boolean; allowCustomBreaks: boolean; canManage: boolean; breakPolicies: BreakPolicy[] };
const input = 'min-h-11 min-w-0 rounded-lg border border-[var(--stanza-border-subtle)] bg-[var(--stanza-input-bg)] px-3 py-2 text-sm text-[color:var(--stanza-text-primary)]';
const button = 'stanza-secondary-action min-h-11 rounded-lg border border-[var(--stanza-border-subtle)] px-3 py-2 text-sm font-bold disabled:opacity-50';
async function api(path: string, body?: unknown, method = 'POST') {
  const res=await apiFetch(apiUrl(path),body===undefined?{cache:'no-store'}:{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  const data=await res.json(); if(!res.ok) throw new Error(data.error || 'Request failed.'); return data;
}
export function AttendanceWorkspace({ employeeId, hasShift, canRequest, canTeam, offline, onPolicy, onBreakState }: {
  employeeId:string; hasShift:boolean; canRequest:boolean; canTeam:boolean; offline:boolean; onPolicy:(mode:Mode)=>void; onBreakState:(active:boolean)=>void;
}) {
  const {isRtl}=useLanguage(); const text=(en:string,ar:string)=>isRtl?ar:en;
  const statusText=(v:string)=>({pending:text('Pending','معلقة'),approved:text('Approved','معتمدة'),rejected:text('Rejected','مرفوضة'),cancelled:text('Cancelled','ملغاة'),verified:text('Verified','معتمد'),outside:text('Outside','خارج النطاق'),unavailable:text('Unavailable','غير متاح'),disabled:text('Disabled','معطل')}[v]||v);
  const [policy,setPolicy]=useState<Policy|null>(null),[draft,setDraft]=useState<Policy|null>(null);
  const [breaks,setBreaks]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[team,setTeam]=useState(false);
  const [requestedStart,setRequestedStart]=useState('');
  const [selection,setSelection]=useState(''),[duration,setDuration]=useState(15),[reason,setReason]=useState('');
  const [reviewNotes,setReviewNotes]=useState<Record<string,string>>({});
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[now,setNow]=useState(Date.now());
  const [history,setHistory]=useState<any[]|null>(null),[hasMore,setHasMore]=useState(false),[page,setPage]=useState(0),[location,setLocation]=useState('');
  const [from,setFrom]=useState(new Date(Date.now()-30*86400000).toISOString().slice(0,10)),[to,setTo]=useState(new Date().toISOString().slice(0,10));
  const [employeeFilter,setEmployeeFilter]=useState(''),[state,setState]=useState(''),[exceptions,setExceptions]=useState(false);
  const load=useCallback(async()=>{
    try { const [p,b]=await Promise.all([api('/api/attendance/policy'),api('/api/attendance/breaks?team='+canTeam)]);
      setPolicy(p);onPolicy(p.attendanceLocationMode);setBreaks(b.breaks);setRequests(b.requests);setNow(Date.now());
    } catch(e) {setError((e as Error).message);}
  },[canTeam,onPolicy]);
  useEffect(()=>{void load();},[load,hasShift]);
  const own=breaks.filter(b=>b.employee_id===employeeId),active=own.find(b=>!b.ended_at),unresolved=own.filter(b=>b.ended_at&&b.exception_status==='unresolved');
  useEffect(()=>{onBreakState(Boolean(active));},[active?.id,onBreakState]);
  useEffect(()=>{
    if(!active)return;
    let timer:ReturnType<typeof setInterval>|undefined;
    const sync=()=>{if(timer)clearInterval(timer);if(!document.hidden){setNow(Date.now());timer=setInterval(()=>setNow(Date.now()),30000);}};
    document.addEventListener('visibilitychange',sync);sync();return()=>{if(timer)clearInterval(timer);document.removeEventListener('visibilitychange',sync);};
  },[active?.id]);
  const run=async(task:()=>Promise<unknown>, invalidateHistory=true)=>{setBusy(true);setError('');setNotice('');try{await task();await load();if(invalidateHistory)setHistory(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const elapsed=(b:any)=>Math.max(0,Math.floor(((b.ended_at?new Date(b.ended_at).getTime():now)-new Date(b.started_at).getTime())/60000));
  const selected=policy?.breakPolicies.find(p=>p.id===selection);
  const updateEntry=(index:number,change:Partial<BreakPolicy>)=>setDraft(d=>d?{...d,breakPolicies:d.breakPolicies.map((p,i)=>i===index?{...p,...change}:p)}:d);
  const loadHistory=(nextPage=0)=>run(async()=>{const q=new URLSearchParams({from,to,state,location,employee:employeeFilter,page:String(nextPage),exceptions:String(exceptions)});const result=await api('/api/attendance/history?'+q);setHistory(result.logs);setHasMore(result.hasMore);setPage(nextPage);},false);
  return <section className="relative z-10 mt-4 w-full space-y-4 text-start" dir={isRtl?'rtl':'ltr'}>
    {error&&<p role="alert" className="rounded-lg border border-red-500/30 p-3 text-sm">{error}</p>}
    {notice&&<p role="status" className="text-sm">{notice}</p>}
    <div className={`rounded-xl border p-4 ${unresolved.length?'border-amber-500/60':'border-[var(--stanza-border-subtle)]'}`}>
      <div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold">{text('BREAKS','الاستراحات')}</h3><button className={button} disabled={busy||offline} onClick={()=>void load()}>{text('Refresh','تحديث')}</button></div>
      <div className="my-3 flex gap-2"><button className={button} aria-pressed={!team} onClick={()=>setTeam(false)}>{text('My break','استراحتي')}</button>{canTeam&&<button className={button} aria-pressed={team} onClick={()=>setTeam(true)}>{text('Team queue','استراحات الفريق')}</button>}</div>
      {!team ? <>
        <p className="mb-3 text-sm font-bold" role="status">{active?text('On break','في استراحة'):hasShift?text('Clocked in','تم تسجيل الحضور'):text('Clocked out','تم تسجيل الانصراف')}{active&&` · ${elapsed(active)} ${text('min elapsed','دقيقة منقضية')}${active.planned_minutes?` · ${Math.max(0,active.planned_minutes-elapsed(active))} ${text('min remaining','دقيقة متبقية')}`:''}`}</p>
        <div data-tutorial-target="geo-break-request" className="flex flex-wrap items-end gap-2">
          <label className="flex min-w-0 flex-col gap-1 text-xs">{text('Break type','نوع الاستراحة')}<select className={input} value={selection} onChange={e=>{setSelection(e.target.value);const p=policy?.breakPolicies.find(p=>p.id===e.target.value);if(p)setDuration(p.duration_minutes);}}><option value="">{policy?.allowCustomBreaks?text('Custom','مخصصة'):text('Select a policy','اختر سياسة')}</option>{policy?.breakPolicies.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name} — {p.duration_minutes} {text('min','دقيقة')}</option>)}</select></label>
          {selected&&<p className="text-xs">{selected.maximum_uses&&`${selected.maximum_uses} ${text('per shift','لكل وردية')} · `}{selected.requires_approval?text('Approval required','تتطلب موافقة'):text('No approval required','لا تتطلب موافقة')} · {selected.paid?text('Paid','مدفوعة'):text('Unpaid','غير مدفوعة')}</p>}
          {hasShift&&<button className={button} disabled={busy||offline||(!active&&((!selection&&!policy?.allowCustomBreaks)||selected?.requires_approval||!policy?.allowUnfiledBreaks))} onClick={()=>void run(()=>api(active?'/api/attendance/breaks/resume':'/api/attendance/breaks/start',active?{}:{breakPolicyId:selection||undefined}))}>{active?text('Resume work','استئناف العمل'):text('Pause / Start break','إيقاف مؤقت / بدء استراحة')}</button>}
        </div>
        {unresolved.map(b=><div key={b.id} className="mt-3 rounded-lg border border-amber-500/30 p-3"><p className="text-sm">{text('You paused without a break request. Add a reason to resolve this reminder.','توقفت دون طلب استراحة. أضف سبباً لإغلاق هذا التنبيه.')} ({elapsed(b)} {text('min','دقيقة')})</p><form className="mt-2 flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();const reason=String(new FormData(e.currentTarget).get('reason')||'');void run(()=>api(`/api/attendance/breaks/${b.id}/resolve`,{reason}));}}><input name="reason" required maxLength={500} aria-label={text('Reason for unfiled break','سبب الاستراحة غير المسجلة')} className={input}/><button className={button} disabled={busy||offline}>{text('Add reason','إضافة السبب')}</button></form></div>)}
        {canRequest&&<form className="mt-4 flex flex-wrap items-end gap-2" onSubmit={e=>{e.preventDefault();void run(async()=>{await api('/api/break-requests',{durationMinutes:duration,reason,requestedStartTime:requestedStart?new Date(requestedStart).toISOString():null,breakPolicyId:selection||undefined});setReason('');setNotice(text('Break request filed.','تم إرسال طلب الاستراحة.'));});}}>
          <label className="flex min-w-0 flex-col gap-1 text-xs">{text('Planned start (optional)','موعد البدء (اختياري)')}<input type="datetime-local" className={input} value={requestedStart} onChange={e=>setRequestedStart(e.target.value)}/></label>
          <label className="flex flex-col gap-1 text-xs">{text('Minutes','الدقائق')}<input className={input} type="number" min={5} max={180} required value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label>
          <label className="flex flex-1 flex-col gap-1 text-xs">{text('Reason (optional)','السبب (اختياري)')}<input className={input} value={reason} maxLength={500} onChange={e=>setReason(e.target.value)}/></label>
          <button data-geo-interaction="break" className={button.replace('stanza-secondary-action','stanza-primary-action')+' stanza-theme-primary stanza-geo-break-primary'} disabled={busy||offline}><span className="stanza-geo-action-content inline-flex">{text('Request break','طلب استراحة')}</span></button>
        </form>}
      </>:<p data-tutorial-target="geo-break-approvals" className="text-xs">{text('Pending, approved, active, completed and unresolved breaks within your authority.','الطلبات المعلقة والمعتمدة والاستراحات النشطة والمكتملة وغير المحسومة ضمن صلاحياتك.')}</p>}
      <div className="mt-3 grid gap-2 md:grid-cols-2">
        {requests.filter(r=>team||r.employee_id===employeeId).map(r=><article key={r.id} className="rounded-lg border border-[var(--stanza-border-subtle)] p-3 text-sm"><p className="font-bold">{team&&r.employee_name+' · '}{r.duration_minutes} {text('min','دقيقة')} · {r.attendance_break_id?(r.ended_at?text('Completed','مكتملة'):text('Active','نشطة')):statusText(r.status)}</p>{r.reason&&<p>{r.reason}</p>}{r.review_note&&<p>{r.review_note}</p>}
          {r.employee_id===employeeId&&r.status==='pending'&&<button className={button} disabled={busy||offline} onClick={()=>void run(()=>api(`/api/break-requests/${r.id}/cancel`,{},'PATCH'))}>{text('Cancel request','إلغاء الطلب')}</button>}
          {r.employee_id===employeeId&&r.status==='approved'&&!r.attendance_break_id&&hasShift&&!active&&<button className={button} disabled={busy||offline} onClick={()=>void run(()=>api('/api/attendance/breaks/start',{requestedBreakId:r.id,breakPolicyId:r.break_policy_id||undefined}))}>{text('Start approved break','بدء الاستراحة المعتمدة')}</button>}
          {team&&r.canReview&&r.status==='pending'&&<div className="mt-2 flex flex-wrap gap-2"><input className={input} maxLength={500} aria-label={text('Review note (optional)','ملاحظة المراجعة (اختيارية)')} value={reviewNotes[r.id]||''} onChange={e=>setReviewNotes({...reviewNotes,[r.id]:e.target.value})}/>{(['approved','rejected'] as const).map(status=><button key={status} className={button} disabled={busy||offline} onClick={()=>void run(()=>api(`/api/break-requests/${r.id}/review`,{status,reviewNote:reviewNotes[r.id]||null},'PATCH'))}>{status==='approved'?text('Approve','موافقة'):text('Reject','رفض')}</button>)}</div>}
        </article>)}
        {breaks.filter(b=>(team||b.employee_id===employeeId)&&!b.requested_break_id).map(b=><article key={b.id} className="rounded-lg border border-[var(--stanza-border-subtle)] p-3 text-sm"><p className="font-bold">{team&&b.employee_name+' · '}{b.policy_name||text('Custom break','استراحة مخصصة')} · {b.ended_at?text('Completed','مكتملة'):text('Active','نشطة')} · {elapsed(b)} {text('min','دقيقة')}</p>{b.exception_status!=='none'&&<p>{b.exception_status==='unresolved'?text('Unfiled — needs reason','غير مسجلة — تتطلب سبباً'):text('Reason recorded','تم تسجيل السبب')}</p>}{b.reason&&<p>{b.reason}</p>}</article>)}
      </div>
    </div>
    <details className="rounded-xl border border-[var(--stanza-border-subtle)] p-4"><summary className="cursor-pointer font-bold">{text('Attendance history','سجل الحضور')}</summary><p className="mt-2 text-xs">{text('Daily totals use the shift start date (UTC). Unpaid breaks are deducted; paid breaks retain attendance credit.','تستخدم الإجماليات تاريخ بدء الوردية بالتوقيت العالمي. تُخصم الاستراحات غير المدفوعة وتحتفظ المدفوعة برصيد الحضور.')}</p>
      <form className="my-3 flex flex-wrap items-end gap-2" onSubmit={e=>{e.preventDefault();void loadHistory();}}><label className="text-xs">{text('From','من')}<input type="date" className={input+' block'} value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs">{text('To','إلى')}<input type="date" className={input+' block'} value={to} onChange={e=>setTo(e.target.value)}/></label><label className="text-xs">{text('State','الحالة')}<select className={input+' block'} value={state} onChange={e=>setState(e.target.value)}><option value="">{text('All','الكل')}</option><option value="working">{text('Working','يعمل')}</option><option value="on_break">{text('On break','في استراحة')}</option><option value="completed">{text('Completed','مكتملة')}</option></select></label><label className="text-xs">{text('Location','الموقع')}<select className={input+' block'} value={location} onChange={e=>setLocation(e.target.value)}>{['','verified','outside','unavailable','disabled'].map(v=><option key={v} value={v}>{v?statusText(v):text('All','الكل')}</option>)}</select></label><label className="text-xs">{text('Employee name','اسم الموظف')}<input className={input+' block'} value={employeeFilter} onChange={e=>setEmployeeFilter(e.target.value)}/></label><label className="text-xs"><input type="checkbox" checked={exceptions} onChange={e=>setExceptions(e.target.checked)}/> {text('Exceptions only','الاستثناءات فقط')}</label><button className={button} disabled={busy||offline}>{text('Show history','عرض السجل')}</button></form>
      {history&&<><div className="mt-3 overflow-x-auto" tabIndex={0} role="region" aria-label={text('Attendance history','سجل الحضور')}><table className="w-full min-w-[720px] text-sm"><thead><tr>{[text('Date / employee','التاريخ / الموظف'),text('First in','أول حضور'),text('Last out','آخر انصراف'),text('Worked','عمل'),text('Breaks','استراحات'),text('Location','الموقع'),text('State / reason','الحالة / السبب')].map(h=><th key={h} className="p-2 text-start">{h}</th>)}</tr></thead><tbody>{history.map(l=><tr key={l.employee_id+l.date} className="border-t border-[var(--stanza-border-subtle)]"><td className="p-2">{l.date}<br/>{l.employee_name}</td><td>{new Date(l.clock_in_time).toLocaleTimeString()}</td><td>{l.clock_out_time?new Date(l.clock_out_time).toLocaleTimeString():'—'}</td><td>{Math.floor(l.worked_seconds/60)} min</td><td>{Math.floor(l.break_seconds/60)} min</td><td>{l.location_status.split(', ').map(statusText).join(', ')}</td><td>{l.state==='completed'?text('Completed','مكتملة'):l.state==='on_break'?text('On break','في استراحة'):text('Working','يعمل')}{l.exception&&' · '+text('Unresolved break','استراحة غير محسومة')}{l.reason&&<p>{l.reason}</p>}</td></tr>)}</tbody></table></div>{!history.length&&<p>{text('No attendance in this range.','لا توجد سجلات في هذه الفترة.')}</p>}<div className="mt-3 flex gap-2"><button className={button} disabled={busy||page===0} onClick={()=>void loadHistory(page-1)}>{text('Previous','السابق')}</button><span>{page+1}</span><button className={button} disabled={busy||!hasMore} onClick={()=>void loadHistory(page+1)}>{text('Next','التالي')}</button></div></>}
    </details>
    {policy?.canManage&&<details className="rounded-xl border border-[var(--stanza-border-subtle)] p-4" onToggle={e=>{if(e.currentTarget.open&&!draft)setDraft(structuredClone(policy));}}><summary className="cursor-pointer font-bold">{text('Company attendance policy','سياسة حضور الشركة')}</summary>{draft&&<form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();void run(async()=>{await api('/api/attendance/policy',draft,'PUT');setDraft(await api('/api/attendance/policy'));setNotice(text('Attendance policy saved.','تم حفظ سياسة الحضور.'));});}}>
      <label className="block text-sm">{text('Location policy','سياسة الموقع')}<select className={input+' ms-2'} value={draft.attendanceLocationMode} onChange={e=>setDraft({...draft,attendanceLocationMode:e.target.value as Mode})}><option value="required">{text('Geofence required','السياج الجغرافي مطلوب')}</option><option value="optional">{text('Location optional','الموقع اختياري')}</option><option value="disabled">{text('Location disabled','الموقع معطل')}</option></select></label>
      <p className="text-xs">{text('Optional records available location but allows missing or outside locations. Disabled never requests or stores coordinates. Required always enforces the geofence.','الاختياري يسجل الموقع المتاح ويسمح بالحضور بدونه أو خارجه. المعطل لا يطلب أو يحفظ الإحداثيات. المطلوب يفرض السياج دائماً.')}</p>
      <label className="block text-sm"><input type="checkbox" checked={draft.allowUnfiledBreaks} onChange={e=>setDraft({...draft,allowUnfiledBreaks:e.target.checked})}/> {text('Allow unfiled breaks with a persisted exception','السماح باستراحة دون طلب مع تسجيل استثناء')}</label>
      <label className="block text-sm"><input type="checkbox" checked={draft.allowCustomBreaks} onChange={e=>setDraft({...draft,allowCustomBreaks:e.target.checked})}/> {text('Allow custom breaks','السماح بالاستراحات المخصصة')}</label>
      {draft.breakPolicies.map((p,i)=><fieldset key={p.id||i} className="flex flex-wrap items-end gap-2 rounded-lg border border-[var(--stanza-border-subtle)] p-3"><legend>{text('Break entry','نوع الاستراحة')} {i+1}</legend><label className="text-xs">{text('Name','الاسم')}<input className={input+' block'} required maxLength={100} value={p.name} onChange={e=>updateEntry(i,{name:e.target.value})}/></label><label className="text-xs">{text('Minutes','الدقائق')}<input className={input+' block w-24'} type="number" min={5} max={180} required value={p.duration_minutes} onChange={e=>updateEntry(i,{duration_minutes:Number(e.target.value)})}/></label><label className="text-xs">{text('Max / shift (blank: unlimited)','الحد لكل وردية (فارغ: بلا حد)')}<input className={input+' block w-24'} type="number" min={1} max={20} value={p.maximum_uses??''} onChange={e=>updateEntry(i,{maximum_uses:e.target.value?Number(e.target.value):null})}/></label>{(['requires_approval','paid','active'] as const).map(k=><label key={k} className="text-xs"><input type="checkbox" checked={p[k]} onChange={e=>updateEntry(i,{[k]:e.target.checked})}/> {k==='requires_approval'?text('Approval required','تتطلب موافقة'):k==='paid'?text('Paid','مدفوعة'):text('Active','نشطة')}</label>)}</fieldset>)}
      <button type="button" className={button} disabled={draft.breakPolicies.length>=30} onClick={()=>setDraft({...draft,breakPolicies:[...draft.breakPolicies,{name:'',duration_minutes:15,maximum_uses:null,requires_approval:false,paid:false,active:true}]})}>{text('Add break entry','إضافة نوع استراحة')}</button> <button className={button} disabled={busy||offline}>{text('Save policy','حفظ السياسة')}</button>
    </form>}</details>}
  </section>;
}
