import {useEffect,useRef,useState} from 'react';
import type {AuthUser} from '../../auth/auth-contract';
import {apiFetch} from '../../lib/api';
import {useLanguage} from '../../lib/LanguageContext';
import {assetActions,assetDate,assetLabel,ASSET_CONDITIONS} from '../../lib/asset-presentation';
import {ComposerDialog} from '../workspace-composer/ComposerDialog';
import {StanzaIcon} from '../ui/StanzaIcon';
import {AssetQrLabelPanel} from './AssetQrLabelPanel';
import type {AssetFormRecord} from './AssetFormDialog';
type Asset=AssetFormRecord&{status:string;assignedEmployee?:string;assignedEmployeeId?:string;assignedAt?:string;expectedReturnAt?:string;warrantyExpiresAt?:string;createdAt?:string;assignments:any[];conditionReports:any[]};
async function request(path:string,body?:unknown){const r=await apiFetch(path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||d.message||'Asset request failed.');return d;}
export function AssetDetail({id,user,revision,onClose,onEdit,onChanged}:{id:string;user:AuthUser;revision:number;onClose:()=>void;onEdit:(asset:Asset)=>void;onChanged:()=>void}){
 const {isRtl,t}=useLanguage(),text=(en:string,ar:string)=>isRtl?ar:en;
 const [asset,setAsset]=useState<Asset|null>(null),[error,setError]=useState(''),[mode,setMode]=useState(''),[busy,setBusy]=useState(false);
 const [people,setPeople]=useState<any[]>([]),[personSearch,setPersonSearch]=useState(''),[employee,setEmployee]=useState(''),[expectedReturn,setExpectedReturn]=useState(''),[condition,setCondition]=useState('good'),[note,setNote]=useState('');
 const [qrOpen,setQrOpen]=useState(false),[support,setSupport]=useState<any>(null),[ticket,setTicket]=useState<any>(null),[holder,setHolder]=useState<any>(null);
 const root=useRef<HTMLElement>(null);
 useEffect(()=>{root.current?.focus({preventScroll:true});if(window.matchMedia('(max-width:1100px)').matches)root.current?.scrollIntoView({block:'start'});},[]);
 const permissions=user.permissions||[],canDirectory=permissions.includes('organisation.view'),canSupport=permissions.includes('support.view')||permissions.includes('support.manage');
 useEffect(()=>{let live=true;setError('');request('/api/hr/assets/'+id).then(d=>{if(live)setAsset(d.asset);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[id,revision]);
 useEffect(()=>{setAsset(null);setMode('');setSupport(null);setTicket(null);setHolder(null);},[id]);
 const lookup=async()=>{setBusy(true);try{const d=await request('/api/hr/organisation/people?pageSize=20&search='+encodeURIComponent(personSearch));setPeople(d.people.filter((p:any)=>p.isActive&&p.employmentStatus==='active'));setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!asset)return;setBusy(true);setError('');try{
 const path=mode==='assign'?'assign':mode==='return'?'return':mode==='condition'?'report-condition':mode;
 const body=mode==='assign'?{employeeId:employee,expectedReturnAt:expectedReturn||null}:mode==='return'||mode==='condition'?{condition,notes:note}:{};
 await request('/api/hr/assets/'+id+'/'+path,body);setMode('');setHolder(null);setEmployee('');setNote('');onChanged();
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const openMode=(value:string)=>{setCondition(asset?.condition||'good');setNote('');setEmployee('');setPeople([]);setExpectedReturn('');setMode(value);};
 return <section ref={root} tabIndex={-1} className="assets-detail" aria-label={text('Asset detail','تفاصيل الأصل')} dir={isRtl?'rtl':'ltr'}>
 <header className="assets-heading"><h3>{asset?.name||text('Asset detail','تفاصيل الأصل')}</h3><button className="assets-control" type="button" onClick={onClose} aria-label={text('Close asset detail','إغلاق تفاصيل الأصل')}><StanzaIcon name="close"/></button></header>
 {error&&<p role="alert">{error}</p>}{!asset&&!error&&<p role="status">{text('Loading asset…','جار تحميل الأصل…')}</p>}
 {asset&&(()=>{const actions=assetActions(asset.status,permissions);return <>
 <p><bdi className="assets-identifier" dir="ltr">{asset.assetTag}</bdi> · {assetLabel(asset.category,isRtl)}</p>
 <dl className="assets-facts"><div><dt>{t('assets.status')}</dt><dd>{assetLabel(asset.status,isRtl)}</dd></div><div><dt>{t('assets.condition')}</dt><dd>{assetLabel(asset.condition,isRtl)}</dd></div>
 <div><dt>{t('assets.assignedTo')}</dt><dd>{asset.assignedEmployee||t('assets.unassigned')}</dd></div>{asset.assignedAt&&<div><dt>{t('assets.assignedDate')}</dt><dd>{assetDate(asset.assignedAt,isRtl)}</dd></div>}{asset.expectedReturnAt&&<div><dt>{t('assets.expectedReturn')}</dt><dd>{assetDate(asset.expectedReturnAt,isRtl)}</dd></div>}</dl>
 {canDirectory&&asset.assignedEmployeeId&&<button className="assets-control assets-navigation" onClick={async()=>{setBusy(true);try{const d=await request('/api/hr/organisation/people?pageSize=20&search='+encodeURIComponent(asset.assignedEmployee||''));setHolder(d.people.find((p:any)=>p.id===asset.assignedEmployeeId)||null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}} disabled={busy}>{text('View holder context','عرض معلومات حامل العهدة')}<StanzaIcon name="forward"/></button>}
 {canDirectory&&holder&&<p className="assets-secondary">{[holder.fullName,holder.department,holder.team,holder.jobTitle||holder.legacyJobTitle].filter(Boolean).join(' · ')}</p>}
 <div className="assets-actions">{actions.assign&&<button className="assets-control assets-primary" onClick={()=>openMode('assign')}>{text('Assign asset','إسناد الأصل')}</button>}{actions.return&&<button className="assets-control" onClick={()=>openMode('return')}>{text('Return / unassign','إرجاع / إلغاء الإسناد')}</button>}{actions.edit&&<button className="assets-control" onClick={()=>onEdit(asset)}>{t('assets.editAsset')}</button>}</div>
 <details className="assets-section"><summary>{text('Identifiers and operational details','المعرفات والتفاصيل التشغيلية')}</summary><dl className="assets-facts">{[['assets.manufacturer',asset.manufacturer],['assets.modelNumber',asset.model],['assets.serialNumber',asset.serialNumber],['assets.warranty',assetDate(asset.warrantyExpiresAt,isRtl)]].map(([key,value])=><div key={key}><dt>{t(key as never)}</dt><dd><bdi>{value||'—'}</bdi></dd></div>)}</dl>{asset.notes&&<p className="assets-note">{asset.notes}</p>}</details>
 <details className="assets-section" onToggle={async e=>{if(!e.currentTarget.open||support||!canSupport)return;try{setSupport(await request('/api/support?queue=true&assetId='+id));}catch(e){setError((e as Error).message);}}}><summary>{text('Support activity','نشاط الدعم')}</summary>
 {!canSupport?<p>{text('Support permission required to view related tickets.','يلزم إذن الدعم لعرض الطلبات المرتبطة.')}</p>:support?<><p>{support.total} {text('related tickets','طلب مرتبط')}{support.nextCursor&&' · '+text('Showing the first page','عرض الصفحة الأولى')}</p>{support.tickets.length?<ul className="assets-history">{support.tickets.map((s:any)=><li key={s.id}><button className="assets-control assets-navigation" onClick={async()=>{try{setTicket((await request('/api/support/'+s.id)).ticket);}catch(e){setError((e as Error).message);}}}>{s.summary}<StanzaIcon name="forward"/></button><span>{assetLabel(s.status,isRtl)} · {assetDate(s.created_at,isRtl)}</span></li>)}</ul>:<p>{text('No Support issues for this asset.','لا توجد طلبات دعم لهذا الأصل.')}</p>}</>:<p role="status">{text('Loading related tickets…','جار تحميل طلبات الدعم…')}</p>}
 {canSupport&&ticket&&<article className="assets-section"><h4>{ticket.summary}</h4><p>{assetLabel(ticket.status,isRtl)}</p><p className="assets-note">{ticket.description}</p>{ticket.resolution&&<p>{text('Resolution','الحل')}: {ticket.resolution}</p>}</article>}</details>
 <details className="assets-section" onToggle={e=>setQrOpen(e.currentTarget.open)}><summary>{text('QR / identification','رمز QR / التعريف')}</summary><p className="assets-secondary">{text('Verifies this company asset. It does not assign equipment or grant access.','للتحقق من أصل الشركة. لا يسند المعدات ولا يمنح صلاحية دخول.')}</p>{qrOpen&&<AssetQrLabelPanel assetId={id} canManage={permissions.includes('assets.manage')&&permissions.includes('qr.asset_label.manage')}/>}</details>
 <details className="assets-section"><summary>{text('Assignment and condition history','سجل الإسناد والحالة الفنية')}</summary><p className="assets-secondary">{text('Created','تم الإنشاء')}: {assetDate(asset.createdAt,isRtl)}</p>
 {!asset.assignments.length&&!asset.conditionReports.length&&<p>{text('No assignment or condition reports recorded.','لم يُسجل إسناد أو بلاغ حالة فنية.')}</p>}
 <ol className="assets-history">{asset.assignments.map(a=><li key={a.id}><strong>{a.employeeName}</strong><span>{text('Assigned','أُسند')}: {assetDate(a.assignedAt,isRtl)} · {assetLabel(a.status,isRtl)}</span>{a.returnedAt&&<span>{text('Returned','أُرجع')}: {assetDate(a.returnedAt,isRtl)} · {assetLabel(a.returnCondition,isRtl)}</span>}{a.returnNotes&&<p className="assets-note">{a.returnNotes}</p>}</li>)}</ol>
 <ol className="assets-history">{asset.conditionReports.map(r=><li key={r.id}><strong>{assetLabel(r.condition,isRtl)}</strong><span>{r.reportedBy||'—'} · {assetDate(r.createdAt,isRtl)}</span>{r.notes&&<p className="assets-note">{r.notes}</p>}{r.evidenceUrl&&<a className="assets-control" href={r.evidenceUrl} target="_blank" rel="noreferrer">{text('View private evidence','عرض الإثبات الخاص')}</a>}</li>)}</ol></details>
 {(actions.condition||actions.final)&&<details className="assets-section"><summary>{text('Lifecycle actions','إجراءات دورة الحياة')}</summary><div className="assets-actions">{actions.condition&&<button className="assets-control" onClick={()=>openMode('condition')}>{text('Report condition','تسجيل الحالة الفنية')}</button>}{actions.final&&<><button className="assets-control" onClick={()=>openMode('mark-lost')}>{t('assets.markLost')}</button><button className="assets-control" onClick={()=>openMode('retire')}>{t('assets.retire')}</button></>}</div></details>}
 </>;})()}
 {mode&&asset&&<ComposerDialog title={mode==='assign'?text('Assign asset','إسناد الأصل'):mode==='return'?text('Return / unassign','إرجاع / إلغاء الإسناد'):mode==='condition'?text('Report condition','تسجيل الحالة الفنية'):mode==='retire'?t('assets.retire'):t('assets.markLost')} onClose={()=>{if(!busy)setMode('');}}><form className="assets-dialog" onSubmit={submit}>
 <p><strong>{asset.name}</strong> · <bdi dir="ltr">{asset.assetTag}</bdi></p>
 <p>{mode==='assign'?text('Assign this asset to the selected employee.','إسناد هذا الأصل للموظف المحدد.'):mode==='return'?text('Return this asset from ','إرجاع هذا الأصل من ')+(asset.assignedEmployee||'—')+text(' to unassigned inventory.',' إلى المخزون غير المسند.'):mode==='condition'?text('Current condition: ','الحالة الفنية الحالية: ')+assetLabel(asset.condition,isRtl):t(mode==='retire'?'assets.confirmRetire':'assets.confirmLost')}</p>
 {mode==='assign'&&(canDirectory?<><label>{text('Find employee','البحث عن موظف')}<input className="stanza-form-control" value={personSearch} onChange={e=>setPersonSearch(e.target.value)} disabled={busy}/></label><button className="assets-control" type="button" disabled={busy} onClick={()=>void lookup()}>{text('Search employees','البحث عن الموظفين')}</button><label>{text('Employee','الموظف')}<select className="stanza-form-control" value={employee} onChange={e=>setEmployee(e.target.value)} required disabled={busy}><option value="">{text('Choose employee…','اختر موظفاً…')}</option>{people.map(p=><option key={p.id} value={p.id}>{p.fullName}{p.department?' · '+p.department:''}</option>)}</select></label><label>{t('assets.expectedReturn')}<input className="stanza-form-control" type="date" value={expectedReturn} onChange={e=>setExpectedReturn(e.target.value)} disabled={busy}/></label>{employee&&<p>{asset.name} → {people.find(p=>p.id===employee)?.fullName}</p>}</>:<p>{text('Directory permission is required to choose an employee here.','يلزم إذن دليل الموظفين لاختيار موظف هنا.')}</p>)}
 {(mode==='return'||mode==='condition')&&<><label>{t('assets.condition')}<select className="stanza-form-control" value={condition} onChange={e=>setCondition(e.target.value)} disabled={busy}>{ASSET_CONDITIONS.map(c=><option key={c} value={c}>{assetLabel(c,isRtl)}</option>)}</select></label><label>{t('assets.notes')}<textarea className="stanza-form-control" maxLength={4000} value={note} onChange={e=>setNote(e.target.value)} disabled={busy}/></label></>}
 {error&&<p role="alert">{error}</p>}<button className="assets-control assets-primary" type="submit" disabled={busy||(mode==='assign'&&!employee)}>{busy?text('Saving…','جار الحفظ…'):text('Confirm','تأكيد')}</button>
 </form></ComposerDialog>}
 </section>;
}
